### ISSUE TITLE
[BUDI-6807] Link card title in Cards block not working

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#10150]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.4.31
  * App Version: 2.4.31

**Describe the bug**
The card title link in a cards block does not navigate to a different screen. Same path works in the Link component.

**To Reproduce**

1. Add a second screen with route `/hello`
2. On the homescreen, add a Link component with URL: `/hello`
3. Then add a Cards block. Tick *Link card title*, and enter the same *Link screen*: `/hello`
4. See that the Link component will navigate, but the Card title link will not.  

**Expected behavior**
Link card title should work.

**Screenshots**

![bug.gif](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/7ff48381-1290-4250-9085-0931f0454a72/4f21664c-d2b2-4ceb-9e80-34fe6ec19402)

**App Export**

[Side panel card block-export-1680096715388.tar.gz](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/eda05a8b-6270-40c9-8bad-f1190da17377/72a650db-ffac-42c8-b3e8-23eb7b1b70a3)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-6807](https://linear.app/budibase/issue/BUDI-6807/link-card-title-in-cards-block-not-working)</sub>

**Comment by melohagan** [comment]
So I am able to get this to work - there's just a inconsistency here that may not be obvious to a user.

I.e. if you use the path: `/hello` in a Cards block, it automatically assumes to add the ID at the end.

If you use the path `/hello/:id` in a Cards block, it also automatically assumes to replace the ID and the link works.

If you manually reference the Repeater block ID, then it breaks, i.e. `/hello/{{ New Cards block.Employees._id }}`.
Because the Ejected Card now has the following binding: `/hello/{{ Repeater.Employees._id }}/{{ Repeater.Employees._id }}` it appends the Repeater block ID already!

**Comment by aptkingston** [comment]
Yea I can see the confusion here - the cards block is a weird one in that it can use the bindings that it provides. Normally you wouldn't be able to see `New Cards block` bindings when configuring it's own settings (as the data provider and repeater haven't been rendered yet, they exist inside the cards block) but you can do it because you need to be able to reference them to fill in things like card titles. Since the link URL is also a "nested" setting and can use these bindings, it makes more sense to build out the full URL referencing the ID field like you did.

The best solution is probably just update the cards block so that it will only append an ID param if you pick a URL that contains a URL param. Otherwise, like if you build the full URL itself, it won't touch it. Then it should work for both cases.
