### ISSUE TITLE
[BUDI-6853] Options fields cannot have an empty value even if they are not required with MariaDB

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#10271]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 2.5.0
  - App Version: 2.5.0

**Describe the bug**
When trying to save a row in the backend portal a 400 error occurs when trying to save a row with a null options field, even if that field is not required

**To Reproduce**
1. Create a new app with a MySQL datasource
2. Create a new option column with a couple of values to select and also add a couple of text columns
3. Create a new row and leave the options field blank, this might work or you might get a 400 error
4. If the row saves try editing the row
5. The 400 error will appear

**Expected behavior**
The options row is saved with no value.

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/231421090-3db8324d-8851-4a22-af6e-76eb0e750110.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser MS Edge
 - Version 112.0.1722.39

**Additional context**
This can also effect automations

<sub>[BUDI-6853](https://linear.app/budibase/issue/BUDI-6853/options-fields-cannot-have-an-empty-value-even-if-they-are-not)</sub>

**Comment by michal-81** [comment]
I have similar issue. All pages (screens) with boolean values are broken. 
If I try to edit and save any page where I use checkboxes I get errors like this: 

![boolean_error_Budibase](https://user-images.githubusercontent.com/114871390/231554785-1950720f-f4cd-4bfe-96e5-8b599114e164.png)
and in the console 400 Bad Request with validation errors

![Bad_request_400](https://user-images.githubusercontent.com/114871390/231556156-e5ebfe4f-ce29-4800-9beb-e2b20b8eff42.png)

The only way to get rid of these errors is to manually set the values for boolean fields in Save Row action 
(even if they were not changed by the user) but of course is not viable solution. 
I didn't make any changes to my app so the problem must be caused by some recent Budibase update (I update my docker images once a week on Friday and noticed the problem this week)
