### ISSUE TITLE
The "refresh data provider" action should allow refreshing all data providers on this page.

### ISSUE THREAD

**Issue by deifemu** [Budibase/budibase#10428]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> docker compose
  - Budibase Version: <version> 2.5.2

**Describe the bug**
I have 2 dataproviders with a table each. 
If I press a button on the lower table i want to add a row to the upper table and refresh it.
I have to put my lower dp int the upper dp so I can refresh the upper dp from the button on the lower table.
But now, the the pagination buttons for the upper table are below the lower table.

The "refresh data provider" action should allow refreshing all data providers on this page. Not just the providers up the tree.
Then I could put both dataproviders on the top level and have the pagination in the right place. 
This would also help when working with sidepanels. Putting the sidepanel inside the dp for the table makes the structure more complicated. 

**To Reproduce**
Create the page according to description / screenshot

**Expected behavior**
Have the pagination buttons after each table and be able to update the upper dataprovider from the lower table.

**Screenshots**
![budyBug](https://user-images.githubusercontent.com/81991548/234789548-20c8a233-9e6b-4db4-8b28-0cce059cfe76.png)

**Desktop (please complete the following information):**
-   OS: Linux 6.x
-   Browser: firefox
-  Version 112.0.1

**Comment by melohagan** [comment]
Hey @deifemu 

I agree that the side panels can make some data provider nesting aspects like this a bit trickier. In the coming months we hope to take another look at how we pull data into screens and see if we can make data more globally accessible within the screen.

In that case, it would resolve the issue you're seeing here. 

For the time being I'm going to close this issue as it's more of a feature request (which is in the pipeline) rather than an issue given how the Data provider nesting works today.
