### ISSUE TITLE
Barcode/QR Scanner as Filter 

### ISSUE THREAD

**Issue by GeisGit** [Budibase/budibase#10842]
Hi, i would like to use the pulled data from QR Scanner as Filter for Data Provider.

Anyone facing the same Problem?

**Comment by feurer98** [comment]
I think you could save the data from the QR code into a state and use the state as a filter.
This should be the fastest way.

But I haven't tried it myself.

**Comment by GeisGit** [comment]
Hi, thanks for your replay. How can i get the QR Code into state?

**Comment by feurer98** [comment]
okey must correct me.
I thought Budibase also had the option to perform an action when changing data.

But it can still be solved easily.
See the screenshot of the test.

One remark: if the QR code is scanned, the filter is already applied in the background.
Confirmation is still required. In my opinion, this is a bug, since a confirmation is asked for.
Or am I understanding this wrong? [shogunpurple](https://github.com/shogunpurple)
See video below.

![budi](https://github.com/Budibase/budibase/assets/45851500/da7929a1-a88c-464a-847b-ef5f9cad1903)



https://github.com/Budibase/budibase/assets/45851500/514c49c5-55e4-400c-9efb-84288913d2dd

**Comment by ConorWebb96** [comment]
Hey all, 

I actually added the ability to use the on-change, its a bit late but I'm only stumbling onto this issue now. You can view the pr made [here](https://github.com/Budibase/budibase/pull/12029). I believe it has been merged in and you can now use the suggestion provided by @feurer98.
