### ISSUE TITLE
cron automation triggers when not scheduled

### ISSUE THREAD

**Issue by andyburgessmd** [Budibase/budibase#10862]
**Checklist**
- I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: mistraldata

**Describe the bug**
I have an automation that uses the cron trigger with a value of '30 15 * * FRI' i.e. 15:30 every Friday - to send an email to users. Over the last week I have also received the email twice on Thursday 8th June at 13:15 & Sunday 11th June at 13:19.
The automation history shows it running at those times but there is trigger set at that time (see screenshots).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a automation and add a cron based trigger
2. Set an action that can be monitored
3. Wait and see if it fires at a non-scheduled time

**Expected behavior**

**Screenshots**
![history](https://github.com/Budibase/budibase/assets/110813989/cfb9b86c-72da-4155-b935-97fa38541d42)
![trigger](https://github.com/Budibase/budibase/assets/110813989/175c7993-c3c6-4da1-8190-ef1c51378d09)

**Comment by Rory-Powell** [comment]
Hi @andyburgessmd. We migrated to a new production environment at exactly that time on sunday, it seems by our new infrastructure coming online your cron automation was ran right away rather than at the next interval as it had likely been queued at the time of the previous infrastructure coming offline. Apologies that this has affected you in this way. You may have also been impacted by some duplicates at the desired interval until Wednesday this week as a result of related infrastructural error. All problems have now been addressed and you shouldn't see duplicates going forward. I'm going to close this one for now, but if you do notices any more duplicates / incorrect timings please let us know.
