### ISSUE TITLE
Copying and pasting a stack of components with bindings cause runtime bindings to be copied

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#1100]
**Describe the bug**
As with title - create a repeater, add a paragraph to it, bind something to it then copy it and the runtime binding will be displayed in the binding input/drawer rather than the readable binding - this also breaks the binding as it tries to run the `readableToRuntimeBinding` on the runtime binding.

**To Reproduce**
1. Create repeater + paragraph
2. Add binding to paragraph (say to current user - doesn't matter what)
3. Copy and paste somewhere else (on another screen for example)
4. look at binding and see it is now a UUID.

**Expected behavior**
Should still have the readable binding.

**Comment by aptkingston** [comment]
This is pretty hard to fix. If you were copying a component tree with bindings which also includes the datasource that is bound, then we could compare the new tree (with ID's replaced) with the old tree, and update any bindings to use the new component ID's. If you were just copying some component with bindings and not including the datasource that is used, then whenever you paste the component there's no guarantee that an equivalent datasource will exist in this new location, so we'd have to just remove the bindings.

Invalid bindings used to appear as `Invalid binding` if they were invalid which at least prevented a horrible looking UUID, but with handlebars I think it's harder now to know whether a binding is valid or not - at least that's what I've gathered from when we talked about that before.

I don't think we can really properly solve the issue of bindings breaking when copying component trees, but it would be good to at least try and put back in a placeholder value for invalid bindings rather than the UUID.

**Comment by mike12345567** [comment]
I think its pretty much impossible for us to detect it and replace with `Invalid binding` as we can't really know whether we are looking at a function or not, my plan had been to simply remove all bindings from the component tree which is being copied as there isn't much other way to do it - determining if it is valid or not is very difficult to do right now.

**Comment by shogunpurple** [comment]
I think we will have to just strip them as you say - it's going to be very hard to perform a true copy and paste with the current setup. You could possibly only allow cutting components with bindings, and omit the copy option entirely.

**Comment by aptkingston** [comment]
Yea in that case I think it's fine to remove them. That'll involve deeply recursing through the component tree props and removing all instances of `{{.*}}` I guess - just strip all handlebars expressions. I remember we mentioned before that we'd have to enforce some specific syntax inside handlebars so that we could tell with certainty which words were bindings and which weren't. And even with that I'm sure it would be complicated.

@shogunpurple I think cut will have the same issue, because if you move a binding outside of the parent context provider component then that binding won't be valid either. But we need to allow people to cut and paste because that's used for drag and drop, so we'll just have to keep the potential invalid bindings when pasting after cutting.
