### ISSUE TITLE
[BUDI-7239] Cannot filter by relationship on new SQL datasource

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11089]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker single image
  * Budibase Version: **2\.6.1** (Introduced, fine on 2.5.9)

**Describe the bug**
If you create a *new* SQL datasource after updating to 2.6+ then you can no longer filter by a relationship field in a Table block.

**To Reproduce**

1. Update to 2.6+
2. Create a new MySQL datasource
3. Within a data table, define a new One->Many relationship
4. Go to Design and add a Table block to a screen for the 'One' table
5. `Define filters`.
6. See that there are no relationship fields to pick!

**Expected behavior**
As a user, I should be able to filter my SQL tables by relationship in the Design section.

**Screenshots**
Employees with one->many relationship to salaries:

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/9697e09d-2aa9-4eb8-8add-515a2763f681/ac1e21fc-3660-49ba-be6d-4dea1df6b856)

Table block filter - where are the salaries fields?

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/56380c15-2bf0-4f46-9859-fe45a5e4c259/9458eb93-4de3-4a73-8628-b86039c85cc9)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7239](https://linear.app/budibase/issue/BUDI-7239/cannot-filter-by-relationship-on-new-sql-datasource)</sub>

**Comment by aptkingston** [comment]
Had a look into this. Good news is that it's fixed (and permanently fixed) by refreshing your page. This only happens immediately after defining a new relationship. Leaving your app or refreshing your page will fix this. The problem is just that after defining a relationship, we do not immediately update the table schema state, which is used by the filter setting.

I'll downgrade this as it's nowhere near as bad as it first seemed thankfully.

**Comment by melohagan** [comment]
Brilliant @aptkingston Thanks very much for taking a look - glad to hear it. Explains why it hadn't been flagged up to this point. Have a great weekend!
