### ISSUE TITLE
[BUDI-7248] CTRL + Z reverts actions outside the focused component

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#11084]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.7.14
  - App Version: 2.7.14

**Describe the bug**
Using CTRL + Z, for example, in a paragraph while writing reverts actions outside the paragraph field.

**To Reproduce**
1. Add a component where u can write in it
2. move the component, for example, in a container
3. Open and write in the component
4. Press CTRL + Z, moves the component back to it's position before the container

**Expected behavior**
Reverts just the actions done inside the open component

<sub>[BUDI-7248](https://linear.app/budibase/issue/BUDI-7248/ctrl-z-reverts-actions-outside-the-focused-component)</sub>

**Comment by aptkingston** [comment]
Hey @kasgithub8. Ctrl+Z maintains as long a history as possible (which is a good thing) but that means that it can revert any change. If we only reverted actions for the selected component it would severely limit it's usefulness, because as soon as you did something like delete a component (which would select a new one) you'd never be able to undo that.

I think there's probably a separately issue here for just disabling our undo/redo functionality while editing bindings, and let the browser default ctrl+z behaviour take over.

**Comment by kasgithub8** [comment]
@aptkingston thanks for the response. 
I understand.
I have another quick question tho, is it normal that I can't scroll in, for example, a embed component?
![image](https://github.com/Budibase/budibase/assets/95284278/90f3c5cb-6833-44f3-a4c6-be972e2b5650)
Im pretty sure that there used to be a scrollbar.
