### ISSUE TITLE
Changing the password of a user renders the account useless

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#1142]
**Describe the bug**
Changing the password of the first (admin) user renders the account useless, meaning, it can not login at all, neither with the old password, nor with the new one.

**To Reproduce**
1. Create a new app, enter account details for the first admin user
2. Preview your app and login with this account. You are able to login
3. In the builder, enter the Users table and edit and change the password of this user
4. Preview the app again, in the browser, and try to login with the same account
5. Unable to login: dev console shows password incorrect, for both the passwords 
6. The above behaviour can also be reproduced for other users, for any role

**Expected behavior**
Changing the password should just allow a user to login with the new password

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 0.7.8

**Additional context**

**Comment by imknight** [comment]
yup having same problem, once you update any user password through the user backend UI, the user will be no longer be able to login from frontend.

**Comment by RichardGrant-93** [comment]
There are a ton of issues here in the codebase but in reference of this specific issue:

After investigating \budibase\packages\server\src\api\controllers\auth.js
it appears that ~line 32 `await bcrypt.compare(password, dbUser.password)` is returning false.

This is appearing to be caused by ~line 95 \budibase\packages\server\src\api\controllers\row.js
ctx.request.body is overwritten by local row variable. This will continue on into `usersController.update(ctx)` and again hash.

**Comment by shogunpurple** [comment]
Thanks for investigating this one @RichardGrant-93, we appreciate it. Will get it resolved as soon as possible over the next few days. 

> there are a ton of issues here in the codebase

We are currently in beta, and the platform is under heavy development. It would be great to hear a bit more about these specific issues and hear how you would do things differently. Feel free to open an issue or discussion about them and we can discuss further.
