### ISSUE TITLE
No QR/Barcode scanner for relationship field with QR/Barcode display column

### ISSUE THREAD

**Issue by tbham** [Budibase/budibase#11426]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.8.30

**Describe the bug**
The relationship field ignores display column type of QR/Barcode, presenting an option picker with a list of QR codes as strings, instead of a QR scanner.

**To Reproduce**
Steps to reproduce the behavior (refer tables below):
1. Add data source (SQL DB)
2. Update column type for QR code column in table 1
3. Define relationship between table 1 and table 2
4. Create form block based on table 2
5. Confirm result: Relationship field linking to table 1 is an option picker, and cannot be configured to be a QR code reader

**Table 1**
|Field|Type|Note|
|---|---|---|
|table1_ID|int|Primary Key|
|QR_code|QR/Barcode|Display column|
|misc_detail|str|etc.|

**Table 2**
|Field|Type|Note|
|---|---|---|
|table2_ID|int|Primary Key|
|table1_ID|int|Foreign Key|
|misc_detail|str|etc.|

**Expected behavior**
Where the display column of a foreign table is set to QR/Barcode, the relationship picker field should be a QR/Barcode scanner, instead of an options picker with QR codes as strings. The QR/Barcode scanner should raise an invalid input warning if the QR code scanned does not match with the foreign column data.

**Screenshots**
QR/Barcode column as display column (table 1) 
![image](https://github.com/Budibase/budibase/assets/3260638/910289d8-fdf2-4c44-8f40-cb3ac004f745)

Form for table 2, with foreign key relationship (inventory). Instead of a QR scanner, there is an option picker.
![image](https://github.com/Budibase/budibase/assets/3260638/9f922414-61a6-458a-86a0-603f0ff76fde)

  
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 115.0.3

**Additional context**
Consider a use case: material inventory.

1. User wants to pick material from inventory
2. Open application and navigate to "pick" form
3. Select inventory item (relationship field)
4. Manually complete other required details
5. Submit form

The "pick" form at step 2 is representative of table 2 (above), the inventory item at step 3 is representative of table 1 and the foreign key in table 2. Say there are 500 items in inventory, or 10,000, it's not feasible to scroll through an option picker list. This limits the utility of the scanner.

**Comment by tbham** [comment]
An indirect solution could be to allow adding Barcode/QR scanners that are not tied to a field, and instead allow actions on change (i.e. reading a code). The scanner could then trigger an action based on the decoded value.

At present there is no option to define an action on change for a Barcode/QR scanner:

![image](https://github.com/Budibase/budibase/assets/3260638/6fbf7a74-9460-4058-bc33-5d763c35bab5)

A number field, in comparison:

![image](https://github.com/Budibase/budibase/assets/3260638/adc9e906-f705-42d9-b010-6dda36d985f6)

**Comment by aptkingston** [comment]
Hey @tbham. The relationship picker always needs to be a picker because we need to ensure you're always choosing existing data. If we had a QR scanner as a relationship picker, you could scan arbitrary codes that don't necessarily exist, meaning you'd be creating a relationship to data that doesn't exist.

You could always achieve this manually if you wanted - but it's a little complex. The steps would be:
- Put in a QR scanner component in your form instead of a relationship picker
- On your submit button, add a "fetch rows" action before your "save row" action
- In the "fetch row" action, search your table for a row that has the QR code you scanned
- If the row does not exist, you can stop here via a "continue if / stop if" action
- If the row exists, proceed to a "save row" action, where you can reference the previously fetched row and use that row's `_id` as the value for the relationship field in the row you're saving

This would let you achieve what I think you're after - scan a code and create a relationship to a row that matches that QR code.

But yes as stated above - this isn't a bug in the sense that we deliberately will always use a picker component to pick relationships.

**Comment by aptkingston** [comment]
> An indirect solution could be to allow adding Barcode/QR scanners that are not tied to a field, and instead allow actions on change (i.e. reading a code). The scanner could then trigger an action based on the decoded value.

You can do this today - you can use any arbitrary value for your field name. It doesn't need to match any field in your table. You can then run "on change" actions as you see fit, or use it for any other purpose (like my example above).

**Comment by tbham** [comment]
> * In the "fetch row" action, search your table for a row that has the QR code you scanned

Appreciate the response and guidance @aptkingston. I can't seem to get it working. The QR scanner returns the decoded content, but the `fetch row` action can't do anything with it. It accepts only an integer row id for the table lookup - but I don't have this until I find the decoded QR content in the table and get the row id. Maybe there's more that I'm missing, but anyway, I'll close the issue if it's intended behaviour.

Thanks
