### ISSUE TITLE
[BUDI-7465] Conditional UI validation restoring field value

### ISSUE THREAD

**Issue by jmtudela** [Budibase/budibase#11708]
**Checklist**

* [X] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: docker compose
  * Budibase Version: 2.9.38
  * App Version: 2.9.38

**Describe the bug**
If conditional UI is used to make a validation of a field A based on the value of a field B, when you empty field A and then change value of field B the value of the field A is restored.

**To Reproduce**
See attached gif and app export.

**Expected behavior**
Field A should remain empty.

**Screenshots**

![](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/a5741954-2d81-4c4e-a234-ac75740715c0/79158bba-1575-43d6-ad6c-8de2523f8594?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9hNTc0MTk1NC0yZDgxLTRjNGUtYTIzNC1hYzc1NzQwNzE1YzAvNzkxNThiYmEtMTU3NS00M2Q2LWFkNmMtOGRlMjUyM2Y4NTk0IiwiaWF0IjoxNjk0MTAzMjI4LCJleHAiOjE2OTQxODk2Mjh9.uUeq-Jsehb1x0JS1O_CfGxDBRn_8-fgguVPf0VVK4BE)

**App Export**
[app_example.gz](https://github.com/Budibase/budibase/files/12547726/app_example.gz)

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser Brave
* Version v1.57.62 Chromium 116.0.5845.180

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7465](https://linear.app/budibase/issue/BUDI-7465/conditional-ui-validation-restoring-field-value)</sub>

**Comment by shogunpurple** [comment]
This is happening because the value in the first field is invalid and therefore we do not save it (the empty state). We cannot save error states like this or we would be saving invalid states. If you were to change the first field to something valid, this wouldn't happen.

Could you explain a little bit more about what you are trying to do here and we may be able to suggest a solution or workaround?

**Comment by aptkingston** [comment]
We mean could you explain a little more about your use case, so we could try to give you an alternative solution. The only reason this is happening is because you have configured the validation so that field A is required, and you're setting it to an invalid state in your example here, then moving on and changing field B which causes your conditions to run, and in turn causes field A to remount because you changed something about it.

If you set field A to any valid value, then you'll notice that this behaviour of resetting the field to it's previous value doesn't happen.

As explained, it because conditionals are remounting the field when apply new validation rules, which causes the field to re-render itself, pulling it's value from form state again. This will be the last valid value, which is not the invalid empty state.

Your options are:
- Allow field A to be empty, if you want to allow this
- Accept that invalid values will be discarded when you change something about a field using conditions
- Add an "on change" action to field B to reset field A to some other value when it is changed. e.g. you could just clear the field every time B is changed
- Use 2 fields, with different validation rules, and use conditions so that only one of them is shown at a time, based on the value of field B

**Comment by jmtudela** [comment]
Sorry, but I don't get the point. The idea is to require Field A only if Option 1 is selected on Field B. I attach two more examples to be more clear.

Example 1:
![example1](https://github.com/Budibase/budibase/assets/144333676/015405a2-4656-4ce9-87d3-0cf5278b3ff1)
[example1.gz](https://github.com/Budibase/budibase/files/12588135/example1.gz)
In this example you can clear Field A, modify another field (required message appears but don't reset Field A), and then change Field B what resets Field A.

Example 2:
![example2](https://github.com/Budibase/budibase/assets/144333676/0e822499-4efe-4028-9388-6a3325f1870c)
[example2.gz](https://github.com/Budibase/budibase/files/12588187/example2.gz)
In this example Field A must be empty if Field B = Option 1, this does not resets Field A. If conditionals are remounting the field when apply new validation rules, why in this example doesn't do it?
