### ISSUE TITLE
[BUDI-7464] Remove the option to conditionally update default value

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#11700]
**Describe the feature request**
A user ran into some difficulty when trying to conditionally `Update setting`: **Default value**.

From what I can tell, updating the default value with conditional UI will never be useful because it is not reactive. Any initial default value conditions could be set within the default value binding itself.

<sub>[BUDI-7464](https://linear.app/budibase/issue/BUDI-7464/remove-the-option-to-conditionally-update-default-value)</sub>

**Screenshots**
![Screenshot 2023-09-07 at 09 54 31](https://github.com/Budibase/budibase/assets/101575380/99632c01-5668-4f5f-b1dc-61862c6bcfd6)

**Comment by aptkingston** [comment]
While this is the case now, I would hold off on any changes to the code regarding this because the upcoming changes regarding global bindings will likely affect how default values work - they were one of the primary issues with the previous skeleton loaders feature. I imagine we will eventually make this reactive again.
