### ISSUE TITLE
[BUDI-7478] Expose state store via client library SDK

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#11746]
Currently there is no awareness of what actions attached to an `on change` or `on click` event when creating custom components. Amend the client library's SDK to expose these elements so they can be pulled into custom plugins and mutated within them.

**Conditions of Satisfaction (COS)**

* Expose additional stores and allow them to be used within custom plugins.

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7478](https://linear.app/budibase/issue/BUDI-7478/allow-users-to-manually-mutate-actions-for-custom-components)</sub>

**Comment by aptkingston** [comment]
Update the title to explain that this issue was specifically just concerning being able to programatically update state from within a custom component, without the use of an action setting.

So all we need to do is add the `stateStore` into the client SDK so that custom components can manipulate it as they see fit.
