### ISSUE TITLE
1:N Relationship allows N:N

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1178]
**Describe the bug**
If I create a 1:N relationship, then modify the relationships on the "N" side, I can make it N:N

**To Reproduce**
1. Create 1:N relationship column. I have used Clients (1) : Projects (N)
2. Create 2 clients and 2 Projects. 
3. Assign 1 project to each client
3. Edit one of the clients, so that it now has another project 
RESULT: The project now belongs to both clients

(Also there is  UI error when initially loading the record)

**Expected behavior**
If I assign the project o another client, it should get removed from the existing client

**Screenshots**
https://www.loom.com/share/a59d30e004b74dfcb87c93d3d710f9b6

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Chrome
 - Version: `develop`

**Comment by aptkingston** [comment]
See on the back of this - we actually create the relationship the wrong way round.

If you create a 1:N relationship from a "Reps" table to a "Sales" table - e.g. each rep has multiple sales, each sale belongs to a single rep, then we actually use a select component in the reps table to pick a single sale, and a multiselect in the sales table to pick multiple reps. 

That's the wrong way round isn't it?

**Comment by shogunpurple** [comment]
@aptkingston I thought this concept was a little confusing when I first used this feature - it's actually a many to one. It does make more logical sense for the current table to be the "1" in the 1:N when you set up the relationship. In fact I'll switch them round now - it will make life easier for users

**Comment by mjashanks** [comment]
Could we display a little helper text at the bottom, once you have selected the related table?

e.g. `1 Rep will be related to many Sales`

**Comment by mjashanks** [comment]
Not pushing for this right now, I just had to get it out of my head. But I think we could be more descriptive about this, and allow for 1:N or N:1 or N:N ... all at once, by doing the following.

![image](https://user-images.githubusercontent.com/3524181/109169708-02b30680-7778-11eb-851c-0d3763078f5d.png)

I.e. you can check one or both of the boxes

**Comment by shogunpurple** [comment]
@mjashanks that's really nice. I like that a lot

**Comment by joebudi** [comment]
This looks nice Mike. I would have these listed in one column - reps and sales are small titles compared to others.

**Comment by tobehn** [comment]
Nice UI/UX nobody will get confused by N's, 1' or :'s this way. 
Also i agree with @joebudi - makes it even easier to get it within seconds.

**Comment by arladmin** [comment]
@shogunpurple @joebudi Hi all.
I seem to be still experiencing this issue in the latest release.

I designed a simple app:
Tables-  Books, Pages
Connection- 1 Book with many Pages

_Books:_
![image](https://user-images.githubusercontent.com/64059154/110072225-75893680-7da3-11eb-8369-910500c0ccaa.png)

_Pages:_
![image](https://user-images.githubusercontent.com/64059154/110072198-6a360b00-7da3-11eb-8012-8c1c090dcff2.png)

Now, when editing a Book row, i can only add 1 page!
![image](https://user-images.githubusercontent.com/64059154/110072138-55597780-7da3-11eb-8663-1ea158203b34.png)

And while editing a Page row, i can add multiple books
![image](https://user-images.githubusercontent.com/64059154/110072089-3fe44d80-7da3-11eb-8330-3fb42d5abe81.png)

Kindly clarify whether this is a persistent bug or is supposed to be by design.

Thanks.

**Comment by mike12345567** [comment]
Hi @arladmin - this did seem like it was the wrong way around, thanks for bringing it to our attention! I've pushed a fix to flip it which will be out in our next patch release!
