### ISSUE TITLE
Form Component not working.

### ISSUE THREAD

**Issue by shaikhashraf709** [Budibase/budibase#1205]
In design section "form" componet is not showing up anything

well i am editing the issue.
This issue occurs when We work on existing project .
when new project is created there are no issues. the form component works fine

**To Reproduce**
Just go to design section and click on "form"

![form bug](https://user-images.githubusercontent.com/78905650/109261939-b1158500-7826-11eb-805c-ea058762aeb7.png)

Platform:
Os: windows 7
Budibse : 0.8.3
Browser : Chrome Version 88.0.something

**Comment by arladmin** [comment]
Facing the same issue 

Win 10

**Comment by shaikhashraf709** [comment]
> Facing the same issue
> 
> Win 10

Just creating new project. this issue occurs only when you are trying to use the new form feature in existing project.
Also now it looks like i'll have to  build my project from beginning.

**Comment by arladmin** [comment]
> > Facing the same issue
> > Win 10
> 
> Just creating new project. this issue occurs only when you are trying to use the new form feature in existing project.
> Also now it looks like i'll have to build my project from beginning.

That's not the case with me. I was already wary of this aspect, hence, using a fresh project in the new builder. The issue exists even then.

**Comment by shogunpurple** [comment]
@arladmin @shaikhashraf709 Was just able to recreate this on a Win10 VM.

The problem here is that every app has a certain version of the budibase standard component library shipped with it. Old apps will not have access to new components, due to them using the old version of the standard library. We will resolve this and make the upgrade path much smoother very soon, but for now the best workaround is to export your old application using the export app feature, and to import it to another app. This will create a new app with the latest component library.

If that works, I will close this one in favour of https://github.com/Budibase/budibase/issues/1222, in which we will provide a much simpler upgrade path for old budibase apps.
