### ISSUE TITLE
[BUDI-7624] "Add filter" button closes filter drawer when editing a relationship field in a form block

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#12065]
If I try to edit one of the fields in a table block in side panel, when I click on "filtering" I see the following errors appear in console.  At that point if I click on "add filter" the panel disappears:

<img width="953" alt="image" src="https://github.com/Budibase/budibase/assets/82715690/649a1c4e-5ca0-4c6d-a6ac-b38cf032ebd9">

<sub>[BUDI-7624](https://linear.app/budibase/issue/BUDI-7624/add-filter-button-closes-filter-drawer-when-editing-a-relationship)</sub>

**Comment by aptkingston** [comment]
Those console errors can just be ignored - they don't affect the functioning of the product in any way. So the issue is just that pressing "add filter" closes the drawer? Could you confirm if this happens with all fields or just one in particular? It would also be helpful if you could please follow the template in future.

**Comment by aptkingston** [comment]
Just adding context for when someone picks this up - the issue is that the `FilterEditor` and `RelationshipFilterEditor` do not proxy the `drawerShow` and `drawerHide` events.

**Comment by melohagan** [comment]
This has been fixed: https://github.com/Budibase/budibase/issues/12621
