### ISSUE TITLE
Grid Detail URL doesn't work for external data sources

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1220]
![image.png](https://images.zenhubusercontent.com/5fd773ddf3d67d4ceebe466b/82bdd9f6-f671-4f90-9afc-a968caafff1e)

If you bind an **external** data source to a grid, the detail URL does not work properly because an `_id` field is expected.

We need to change the detail URL field to be bindable to be bindable to any value in context.

**Comment by aptkingston** [comment]
This deliberately wasn't updated because the grid component itself does a hardcoded replacement of `:id` with a row's `_id` property - so it assumes that both the URL has an `:id` param and that all rows have an `_id` property (i.e. are a couch doc). We'd need to make a fair few changes to the grid I think to let it handle external sources. I was under the impression we might replace it with something else (perhaps a spectrum table component) around the same time we look at the datasource refactor.

**Comment by shogunpurple** [comment]
Thanks for the insight @aptkingston that makes total sense. Let's keep it open for now until we decide what to do on that front!
