### ISSUE TITLE
Standard Components Upgrade Path

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1222]
As a user, I want to be able to smoothly upgrade my budibase standard components library on my old apps so that I can get access to all the latest features.

Right now, users need to export their old apps and import them into a new one to get the latest standard components. This is a bit cumbersome. We should provide a smooth upgrade path, and let users manually upgrade their apps to certain versions of the component library from the builder.

Example of the issue this creates: https://github.com/Budibase/budibase/issues/1205

**Comment by aptkingston** [comment]
Yep absolutely. We'll need to let people upgrade to the latest version, at the risk of some of their app components breaking and needing to be reimplemented, which we could highlight. For bigger breaking changes it's harder, for example if we change bindings or where some top level component property is stored then the whole app will likely break, or if we make major backend changes too.

Issues like #1205 will at least go away whenever we implement the single stack since everything is versioned together, but we still would need to provide a way to update whenever they choose - rather than being forced to update as users are now due to the builder and self hosted installs being versioned independently.
