### ISSUE TITLE
data source field select bug

### ISSUE THREAD

**Issue by SOVLOOKUP** [Budibase/budibase#1229]
**Describe the bug**
when using two datasource(from different tables) in one chart, items in the columnName selectors are the same

**To Reproduce**
#1167 

**Screenshots**
![image](https://user-images.githubusercontent.com/53158137/109451554-a35f3a00-7a88-11eb-8e89-45f52c2305fb.png)
![image](https://user-images.githubusercontent.com/53158137/109451576-aeb26580-7a88-11eb-877a-b9366e259764.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser chrome
 - Version 98246ad

**Comment by aptkingston** [comment]
Hi @SOVLOOKUP. I thought you might encounter this issue when I saw your PR. The reason for this problem is that you have 2 settings of type `datasource` in your component. Your settings that are type `field` (which renders a `FieldSelect` component) uses `getDatasourceForProvider` to determine what the schema for your components datasource should be. That function finds the first setting of type `datasource`, `table` or `schema` and uses that. This is deliberate, because we don't have any components that have multiple datasources at the moment, and it simplifies the process. The solution to this is that we would need to change the definition for our components in `manifest.json` so that they specify which setting should be used for bindable properties, and then every setting of type `field` would need to specify which `datasource` setting they relate to.

Changing the definition structure is a breaking change, and I'm not sure if this is a change we want to make at the moment. Is there any way the component could be refactored to only use one datasource or is that not possible?
