### ISSUE TITLE
File System - MinIO Migration

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1274]
Right now all static files during local dev are stored on disk. When running in the single stack, static files for apps should be stored and updated in MinIO instead. 

**Conditions:**
- Remove references to the `~/.budibase` directory
- Update most if not all calls to `fs` to be writes to MinIO using the S3 SDK. Bear in mind that users should be able to configure their budibase installation to point at an s3 bucket - so worth testing that the code still works when configured for S3 instead of MinIO

**Comment by mike12345567** [comment]
On this issue we'll need to have a think about templates going forward, I have partially migrated them right now, but for the time being I have removed everything to do with local templates. The concept of a local template doesn't make as much sense anymore since it should be running in a docker instance, although it could be useful when doing development. For this reason we may need to re-think exactly how local templates would come back into the system in future.
