### ISSUE TITLE
Datasource Refactor

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1278]
When creating UI in the budibase builder, I want to be able to use a Data wrapper component that is used to connect to data sources.

**Conditions**
- A single "Data Provider" (nomenclature up for debate) component becomes the sole entry point for fetching data from tables, external data sources and more.
- Grid, Repeater etc are no longer bindable directly to data sources. You wrap them in a data provider and bind their data to the provider
- Consolidate all data fetching logic into the Data Provider component

@aptkingston would be good to discuss this one a bit further with you and we can add some more detail to it. I know you have thought about this for quite some time

**Comment by aptkingston** [comment]
Sure thing. Quick summary of my thoughts (in addition to what's above):
- The component has settings for the actual data source (table, view, or query), search, filter, sort, limit and page size (can be client side paged for now if desired, until server side pagination is a thing).
- The component provides (via svelte context) the data, functions to control pagination, and the state of pagination.
- Button actions will be created to programmatically refresh the data source (for example searching) and for controlling pagination (for example next page, previous page). We could also add an opinionated pagination control component if we want.
- Data bindings can be used to display other state information, for example `Page 1 of 5` or `24 results found`.
- We'll need to slightly rework some of the component definitions. The `dataProvider` flag will become redundant, and rather than hardcode the schema for data bindings provided by this new component, I think it would be good to allow specifying in definitions the schemas that components provide via context. In this case, that would probably be `dataLength`, `currentPage` and `numPages`. These schemas would then be used by the data binding code to allow users to bind to these specific fields.

Also happy to discuss this properly if that would help tie down the spec 👍

**Comment by shogunpurple** [comment]
Really like the idea of tying server pagination into this too, although I think the scope of that could be huge with external data sources. We would need to define for each integration how to paginate - (OFFSET etc for SQL, or cursor limits in mongo for example.) Maybe best to keep this pagination on the client side for now until we sort that out.

All of your points above sound totally sensible, and will add a ton of value IMO. Just on this one:
```
rather than hardcode the schema for data bindings provided by this new component, I think it would be good to allow specifying in definitions the schemas that components provide via context. In this case, that would probably be dataLength, currentPage and numPages. These schemas would then be used by the data binding code to allow users to bind to these specific fields.
```
What do you mean by "allow specifying in definitions the schemas that components provide via context"? Does this mean adding some values into the manifest to say what will be available in bindings for that particular component?

**Comment by mike12345567** [comment]
I do think if we can support pagination on the server is someway for internal tables as part of this it would be amazing, simply because getting server pagination into the system for our main CouchDB instance needs to be done.

It could also be that for external data sources we need to define how pagination works as part of the integration itself then have the data source component only expose the pagination feature if the source itself actually supports pagination via the standardised, defined method.

Initially we could just get all external data source pagination to false (maybe implement it on some SQL ones if we have time) and then the pagination feature of the data source would only be available for internal tables initially.

I think partially implementing server-side in this method will mean we'll have a good idea of what we need to really spec out in the data source schemas for it to be possible across all integrations easily (as I do agree it will be complicated, the method used for a SQL table will be completely different to say that of Dynamo)

**Comment by aptkingston** [comment]
> Really like the idea of tying server pagination into this too, although I think the scope of that could be huge with external data sources. We would need to define for each integration how to paginate - (OFFSET etc for SQL, or cursor limits in mongo for example.) Maybe best to keep this pagination on the client side for now until we sort that out.
> 
> All of your points above sound totally sensible, and will add a ton of value IMO. Just on this one:
> 
> ```
> rather than hardcode the schema for data bindings provided by this new component, I think it would be good to allow specifying in definitions the schemas that components provide via context. In this case, that would probably be dataLength, currentPage and numPages. These schemas would then be used by the data binding code to allow users to bind to these specific fields.
> ```
> 
> What do you mean by "allow specifying in definitions the schemas that components provide via context"? Does this mean adding some values into the manifest to say what will be available in bindings for that particular component?

Yep, basically that in the standard components `manifest.json`, the definition of a component can define what it will provide via context in the client app - and therefore what properties are available inside this component as data bindings. Initially this might only be this new data component, but we could easily use the same thing for something like forms. Forms could provide `formValid` or `numErrors` for example, and people could bind to them. I think using the component definition for this is perfect, as it means when generating data bindings we can add other rich information from the components themselves, as well as the normal data schema bindings that we currently provide.

**Comment by shogunpurple** [comment]
Yep, I think anything that we can define in the manifest we should, as it should make life easier when it comes to upgrade paths, for example.

In my mind these are the tasks that **this** issue should pertain to:
- Build the data provider component and get it working with a simple setup
- Replace the current repeater/grid (any `dataProvider` basically) functionality with the new data provider 

This way, we should be able to make all the changes we need to the client lib/context and add functionality on top.

As for:
- pagination
- settings for search/filter/sort

I'm concerned that the scope of this is potentially massive as it stands, so it would be good to define it in a series of steps that we can tackle as separate tasks. What do you think about splitting this up a little?

**Comment by aptkingston** [comment]
I agree we can leave pagination - it's definitely a significant task by itself.

For the other settings though, I don't actually think they're too bad. Searching will only be available for internal tables for now, using the function you've already written for the search component. I envisage it looking pretty much identical to what the current filtering settings look like on a repeater, but this is the only setting that could potentially end up being a bit more work when it comes to it's implementation.

Filtering is already implemented for the repeater and it's done in memory so works for any source easily, so this is basically free. Sorting and limiting the result count are just quality of life features which are also in memory and would be super quick to implement, so I think we could easily bundle those inside this too.

Your steps above there are correct - I think the first step of building the component just also includes implementing these few settings. I'm happy to leave search for now, especially if we'll likely be refactoring it anyway with the single stack capabilities. I think the in memory settings are really easy to implement though and would the component much more useful.

**Comment by shogunpurple** [comment]
Thanks for the clarity - I think that makes total sense.

Let's go with the in memory implementation of these settings in the new `DataProvider`, and encapsulate them in such a way that allows us to provide server side implementations of them in future.

I think that we are probably at the point where we can start writing some code for this now and get feedback from the rest of the team about the UX once we have an MVP.
