### ISSUE TITLE
Missing "Calculate" and "Group By" in Data Views

### ISSUE THREAD

**Issue by purebordem** [Budibase/budibase#13108]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud version 2.20.8, all apps including newly created ones

**Describe the bug**
The "Calculate" and "Group By" options for a Data View, per instructions [here](https://docs.budibase.com/docs/progress-donut-chart), are missing from the tool bar 

**Screenshots**
![image](https://github.com/Budibase/budibase/assets/13024100/0d6fa3cc-5a9d-4897-a750-93eeb9b97c51)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave & Edge

**Comment by melohagan** [comment]
Hey @purebordem 

Thanks for raising this - I have now hidden that particular docs page.

Calculate and Group By options were removed some time ago. This is because we're currently upgrading our internal DB, and this functionality had to be removed in the interim. 
In future this functionality will return and more!

Sorry for the inconvenience.
