### ISSUE TITLE
End User Authentication and Permissions - Worker Service

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1316]
### Architecture

The user management stack relies heavily on the **worker service**. It will be responsible for all the API endpoints for:

- Auth
- Admin Panel

### User Database

The user database is the core of the User Management Stack. It will contain everything pertaining to global level settings and authentication.

- Users will have a unique ID that is common across all apps
- User credentials for each app
- SMTP credentials for the installation
- OAuth Information for the installation
- User permissions (Admin, Builder etc)

### Authentication
The worker service will be responsible for all authentication. This involves checking the user database to ensure that the hashed password matches the one being sent over the wire.

**Comment by shogunpurple** [comment]
@mike12345567 and I chatted about an initial approach to this. Here's what we are planning:

### Prereqs
- All users can "build" at this time. We will add user building permissions later
- 

### Setup Envoy and Dev
Add rules to envoy to proxy requests to `/api/admin` to the worker service. This allows us to keep things simple on the client. 
- Since no envoy in dev, set up a proxy between the app server and the worker service to allow communication for the `/api/admin` endpoint.

### Create Global User Path Alongside Current User Creation Logic
- Alongside the current user creation logic, add another path that creates global users in the user database.
- Allow authentication for these users from the UI through the worker service (passportJS)
- Once done remove the old user logic in the app server

**Comment by mike12345567** [comment]
Just to expand on @shogunpurple comment above with some other thoughts on our planning:

There are a few main areas that need tackled as part of this which are discussed below.

### Global user database
- [ ] Currently users will be created through the same path as we have today, a user can be created through the user table interface in an app, however the API will be updated to create the user globally - this includes retrieving users globally, this will be removed/replaced with the admin interface which is global across all apps when we are ready to do so.
- [ ] The global user creation and authentication will all be handled by the worker service through a new global user API.
- [ ] Data about the user that pertains to an application level will be stored in database specific to the app rather than part of the global user object. When a global user is being retrieved/the list of users in an app is being retrieved for a specific app information will be enriched onto the global user list to create the apps full user info.

### Authentication
- [ ] Swapping over our current hand-rolled authentication to use something pre-built, likely [Passport](http://www.passportjs.org/).
- [ ] Updating our management of cookies so that there is a single cookie used to authenticate with all apps and the builder - this simply links to the global user.
- [ ] Initially as @shogunpurple mentioned all users will be builders with complete access, with the goal of updating this to a list of apps that a user can access, for end usage and builder usage at a global level (stored in the global user database).

### Infrastructure
- [ ] As @shogunpurple mentioned global/auth requests will be directly passed to the worker service by Envoy in production, in development however we will have to build a proxy middleware which sends the global requests through to a locally running worker service.
- [ ] Currently the App ID is quite hard to manage as it can be stored in a lot of different places. As part of this work it will be removed from the authentication and will be purely passed around as a header on requests. This will involve a refactor of the client, builder and server to make sure they all expect to put/find the app ID in the same, single place.
