### ISSUE TITLE
Stacked list component's URL does not automatically prefix local links with with `#`

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1358]
**Describe the bug**
Stacked list component's URL does not automatically prefix local links with with `#`. We should check this for any other components that use a URL.

reported here: https://github.com/Budibase/budibase/discussions/615#discussioncomment-569033

**To Reproduce**
1. Add a stacked list, and put a screen's URL in
2. Test your app
URL is broken because there is no hash

**Expected behavior**
System should put a hash in for us, just like the Link component

**Comment by aptkingston** [comment]
I think this is actually only an issue with the `StackedList` component, because it doesn't use the `linkable` action from the SDK which links are supposed to use (it automatically handles the hash routing, and ensures links work with `svelte-spa-router` which is the routing lib for client apps). I think all other other components that use URL's already handle this correctly, so this just looks like one that was missed. You shouldn't ever need to worry about putting `#`'s in URLs.

**Comment by shogunpurple** [comment]
This one has since been resolved with `linkable`
