### ISSUE TITLE
Automation trigger.id shortcut doesn't output anything

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#13588]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.24.0
  - App Version: 2.24.0

**Describe the bug**
The trigger.id shortcut doesn't output anything you instead have to use the longer binding; `trigger.rows._id`.

**To Reproduce**
1. Create any automations
2. Trying and reference `trigger.id`
3. See error, no value is present.

**Expected behavior**
Should output the trigger.rows._id value.

**Comment by aptkingston** [comment]
I can't actually repro this now which is really weird because I know we had this issue. It must have been something else about our chain... I'll try some more examples and see if I can break it.
- Create row trigger with a simple log of `{{ trigger.id }}` works as expected
- Update row trigger with a simple log of `{{ trigger.id }}` works as expected

**Comment by aptkingston** [comment]
Also just tested this in our actual app again and it does work too. We must have been wrong about this one - I think it works as expected. Something else must have been breaking our automation and we wrongly thought it was this binding.
