### ISSUE TITLE
Make _id available immediately after Save Action

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1387]
When dealing with a new row, we do not have an `_id` parameter available in bindings - because it does not exist yet. 2 different users have wanted this to be available. One wanted to use the `_id` to link to another record. Another wanted to immediately load the "Row Detail" screen for the record.

After the Save Action has been run, the `_id` is technically available to the client - but is not getting set on the underlying object.

I have created a commit that **i think** will work, but cannot test as I cannot get my dev environment to build. https://github.com/Budibase/budibase/commit/186596a5c8528e0ca63806afdff586c4218087dc

This mutates the context - which I think is the simplest way. This will make the `_id` available to subsequent actions - e.g. `Navigate To /customer/{{ Form.Fields._id }}`

**Comment by aptkingston** [comment]
I can see the use case, but it's technically quite hard to do this. We'd need to refactor the whole idea of actions to be the same as automations, with defined outputs.

That commit won't work unfortunately because it's directly mutating the observable value of a svelte store. Even if we did actually update the real context, it wouldn't appear in bindings as an option unless we refactor that in line with what I was saying above, like making actions have defined outputs which are considered when creating data bindings.

**Comment by mjashanks** [comment]
Cool yea - I wasn't expecting it to appear in available bindings - but thought it would be a quick fix to allow people to manually type `._id` in the bindings. 

We could always give the underlying object an `_id = ""` for new records - so it gets listed, but I can see why its a bit hacky. No worries if we want to close this.
