### ISSUE TITLE
MySQL working weird in budibase

### ISSUE THREAD

**Issue by mad4me** [Budibase/budibase#13871]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

- Self
  - Method: docker-compose 
  - Budibase Version: 2.27.6

**Describe the bug**
In addition to #13804 -> As well as not being possible to delete foreign key rows from the budibase User Interface, the foreign keys in general work poorly. 

In my app, I made a new MySQL Table `Eventos` through the User Interface of budibase, created the structure using Adminer, and set up the foreign keys from different tables.  Then, using the budibase UI, I defined the relationships to manage the data from other tables a bit better, but when I decided to add data through the built-in relationship columns, the IDs were always null. When I decided to insert the ID's manually, the built-in columns weren't showing data. I fetched the tables at every step I made, constantly checking Adminer.

**To Reproduce**
Steps to reproduce the behavior (In my app):
- Try to add a new row in the Events table with a foreign key in any way

**Screenshots**

- Image 1: Stuck in trying to delete a row with a 500 error

![image](https://github.com/Budibase/budibase/assets/54853465/0bf5eb5e-9da3-4b6a-acfb-e8aa0abd8751)
  
- Images 2: Foreign keys empty

![image](https://github.com/Budibase/budibase/assets/54853465/c27d8e63-94dc-4834-83e6-c74e5e497e9d)
![image](https://github.com/Budibase/budibase/assets/54853465/d3bb602f-7386-47f0-a97c-9aab2e76a26f)
![image](https://github.com/Budibase/budibase/assets/54853465/65528724-28c5-4801-b654-f2fdd21404df)

  
**App Export**
[Viaturas-export-1717690266840.tar.gz](https://github.com/user-attachments/files/15652369/Viaturas-export-1717690266840.tar.gz)

**Desktop**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 125.0.6422.142

**Comment by Reftek85** [comment]
I second this issue,
I am trying to implement a Budibase software with a mysql back-end,
I wasted a couple hours trying to make relationship works between tables and could not figure why it was not working, I resorted to manually create relationships through automation and still the automation would always return a NULL value for my foreing keys columns,

I had multiple problems always related to null values with the ID primary key that are foreign keys,
Automation could not work since values of ids were always NULL
I had to remove all the foreign keys from mysql tables for budibase to work with its relationship system which is non-sense.

https://github.com/Budibase/budibase/discussions/13623

**Comment by mikesealey** [comment]
Hi Reftek85<br><br>We're looking into this for you. Thank you for including your app-export. Please could you email your schema to support@budibase.com<br><br>Mike

**Comment by mad4me** [comment]
I already found a way to fix (by manualy creating a relationship column in the budibase ui in the table itself) it so for me its working, and i dont have the schema of the database that wasnt working.

**Comment by ConorWebb96** [comment]
Closing this as resolved. Glad that you figured out how to resolve this.
