### ISSUE TITLE
When ejecting the form block and interacting with fields, the column layout options are presented but do nothing

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#14015]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
BB Cloud

**Describe the bug**
I ejected my form. I then tried positioning two fields in the same row by clicking the column icon, but it did nothing. 

![CleanShot 2024-06-25 at 09 41 56@2x](https://github.com/Budibase/budibase/assets/49767913/655d5667-3c8e-4118-80b2-562e440c6cbe)

**Comment by aptkingston** [comment]
I'll push a fix for this. The bug is that those options should not be appearing at all - they only work in the form block. You'll notice that the setting isn't in the normal settings panel on the right, and it shouldn't be in the bar either. We just obviously don't check for the `hidden` manifest property that we use to hide it normally.

But ultimately I'm afraid you won't be able to use those layout options if you eject - they are for the form block only.

What made you need to eject?

**Comment by joebudi** [comment]
So, my immediate need to eject was to add information under the field label - this is often my need to eject. 
I also wanted additional customization.
 
![CleanShot 2024-06-26 at 08 46 30@2x](https://github.com/Budibase/budibase/assets/49767913/800c528d-95fe-4068-9637-a1db7379b70c)
