### ISSUE TITLE
Followed k8 directions -> appId could not be found crash

### ISSUE THREAD

**Issue by mateothegreat** [Budibase/budibase#14014]
**Checklist**

* \[ x\] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

* Self
  * Method: k8s
  * Budibase Version: 2.29.1
  * App Version: 2.29.1

**Describe the bug**

1. went to documentation at [https://docs.budibase.com/docs/kubernetes-k8s](https://docs.budibase.com/docs/kubernetes-k8s)
2. ran `helm install --create-namespace --namespace budibase budibase budibase/budibase`
3. pulled logs from app-service container and got:

```json
{"level":"ERROR","timestamp":"2024-06-25T08:11:04.843Z","service":"@budibase/server","err":{"type":"InternalServerError","message":"AppId could not be found","stack":"InternalServerError: AppId could not be found\n at Object.throw (/app/node_modules/koa/lib/context.js:97:11)\n at requiresMigration (/app/dist/index.js:249089:18)\n at serveApp (/app/dist/index.js:249099:36)\n at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57\n at serveApp (/app/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at /app/node_modules/@koa/router/lib/router.js:368:16\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at allowedMethods (/app/node_modules/@koa/router/lib/router.js:429:12)\n at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57\n at allowedMethods (/app/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at /app/node_modules/@koa/router/lib/router.js:368:16\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at allowedMethods (/app/node_modules/@koa/router/lib/router.js:429:12)\n at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57\n at allowedMethods (/app/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:26:21)\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at /app/node_modules/@koa/router/lib/router.js:368:16\n at dispatch (/app/node_modules/koa-compose/index.js:42:32)\n at allowedMethods (/app/node_modules/@koa/router/lib/router.js:429:12)\n at /app/node_modules/dd-trace/packages/datadog-instrumentations/src/koa.js:88:57","status":500,"statusCode":500,"expose":false},"pid":30,"tenantId":"default","correlationId":"e0eb55c1-4ed9-418b-af64-a2101b7d987c","msg":"Got 400 response code"}
```

This is a fresh install.
Thanks!

**Comment by samwho** [comment]
Hey @mateothegreat, apologies for the delay in getting around to this. I just ran the following on my home cluster:

```
helm install --create-namespace --namespace budibase-test budibase budibase/budibase -f ~/budibase-values-test.yml
```

With the values file containing the following because my home cluster doesn't have a default storage class (I know, I really need to fix that):

```yaml
couchdb:
  persistentVolume:
    storageClass: "nfs-client"

services:
  objectStore:
    storageClass: "nfs-client"
  redis:
    storageClass: "nfs-client"
```

And everything comes up okay without crashing:

![CleanShot 2024-07-19 at 16 13 06@2x](https://github.com/user-attachments/assets/c3d1eaa7-f791-4369-82ae-d51565f30838)

I'm then able to port forward (no ingress by default) to the proxy pod and see the expected admin account creation screen:

![CleanShot 2024-07-19 at 16 17 39@2x](https://github.com/user-attachments/assets/4e1dcd41-9086-4d72-b313-df35cdd8bc89)

I made sure to run `helm repo update budibase` before trying this, so this is the latest available Helm chart.

Are you able to provide any more details about your setup and what you did that might help us narrow down the problem? 🙏
