### ISSUE TITLE
Unable to use Conditions to Update Settings >> Details on Multi Step Form Block

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14288]
**Checklist**
- `[Y]` I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
Observed on Self (Docker single image) and Cloud (2.29.26) miketest1.budibase.app

**Describe the bug**
_Bug raised on behalf of customer_
Unable to use conditions to update settings on Multi Step Form Block - "Error updating component prop".

**To Reproduce**
1. Add a Multi Step Form Block
2. Add a Condition to update setting `Details`
3. Make a change to fields shown or title or description - UI changes, error appears message appears.

**Expected behavior**
Should be able to configure settings with "Update Setting > Details" settings

**Screenshots**
JAM https://jam.dev/c/ea1d4e87-7487-47f7-b017-290415a16741
  
**App Export**
[Geis MultiStep Form BLock-export-1722423403250.tar.gz](https://github.com/user-attachments/files/16440280/Geis.MultiStep.Form.BLock-export-1722423403250.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (arm64)

**Additional context**

**Comment by aptkingston** [comment]
Just chipping in to say that I think it's a lot more likely we remove conditional UI for monster settings like "Details" in the multi-step form block rather than make this to work... Rendering that entire section inside the drawer looks terrible. If this customer does need conditional multi-step form block field settings then I think having multiple form blocks which are shown/hidden using conditional UI is probably the way to go.
But I'll take a look in case there's an easy fix anyway.

**Comment by shogunpurple** [comment]
@aptkingston did you get a chance to look at this? Might be better us removing it as you say for new applications and keeping legacy support around

**Comment by aptkingston** [comment]
Just a heads up that when this fix is shipped, this customer will have to delete their condition and recreate it in order to benefit from the fix.
