### ISSUE TITLE
Cannot bind to calculated view of type "Count"

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1433]
**Describe the bug**
Budibase crashes when we try to set a repeater's datasource to a calculated view, which is a "Count". Works ok with "Statistics "

**To Reproduce**
1. Create a view > calculate > count
2. Add a repeater
3. Set datasource to your view
4. Exception thrown - budibase freezes & data does not show

**Additional context**
```
dataBinding.js:240 Uncaught (in promise) TypeError: Cannot create property 'name' on string 'string'
    at dataBinding.js:240
    at Array.forEach (<anonymous>)
    at SC (dataBinding.js:238)
    at dataBinding.js:118
    at Array.forEach (<anonymous>)
    at EC (dataBinding.js:103)
    at vC (dataBinding.js:16)
    at Object.e.$$.update (PropertyControl.svelte:27)
    at Qe (index.mjs:1482)
    at new M6 (PropertyControl.svelte:72)
```

**Comment by aptkingston** [comment]
Looks like whenever you do a `Count` calculation it returns a weird schema that's different to normal. Usually schemas are a map of field name to a field schema object, e.g.
```js
{
  name: {
    type: "string"
  }
}
```
But whenever a count view is used the schema becomes this for some reason.
```js
{
  name: "string"
}
```
This actually throws an error in the backend UI in the `next` branch too, because the `Table` component also uses the schema. I'll fix this so it handles either, but I also think that with the implementation of server side searching and the new formula field type, views are slowly becoming redundant.
