### ISSUE TITLE
Budibase app does not follow Javascript code when run in preview or published. Works in test window.

### ISSUE THREAD

**Issue by VMan228** [Budibase/budibase#14609]
**Hosting**

- Self
  - Method: Docker-compose
  - Budibase Version: 2.32.6
  - App Version: 2.32.6

**Describe the bug**
Javascript IF statement or switch returns items seemingly at random when setting a state.

**To Reproduce**
Create a form. Choose Options Picker. Set options to custom with numeric values.
Add an "On Change" event to  Update State with the following JS code:

`if( $("Form.Fields.IssueRequest") == 2){
	return ['https://wiki.voigtie.com/en/NOC/LNYCGateAccess']
} else if( $("Form.Fields.IssueRequest") == 3) {
	return ['Gate Hold Open']
  }
else if($("Form.Fields.IssueRequest") == 4) {
  return ['N/A']
}`

**Expected behavior**
IssueRequest State returns correct web URL or correct string rather.

**Screensh
<img width="687" alt="Screenshot 2024-09-19 at 11 23 51 AM" src="https://github.com/user-attachments/assets/9e2273eb-f3ac-4a1a-80d8-d95b6122ce34">
ots**

  

**Desktop (please complete the following information):**
 - OS: Mac or Windows
 - Browser chrome and safari

**Comment by aptkingston** [comment]
Hi @VMan228. This is happening because you're using the wrong binding in that expression. When using an "on change" action, the field binding (`Form.Fields.IssueRequest` in your case) references the value *before* the change. There is a binding called `Field Value` which contains the new value.

We cover that in the docs [here](https://docs.budibase.com/docs/calculate-field-value-on-save) if you want to read more. But basically just update your JS to use the `Field Value` binding and this will work as expected.
