### ISSUE TITLE
Updating user via public api broken in new versions

### ISSUE THREAD

**Issue by marzzzello** [Budibase/budibase#14638]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 2.32.7

**Describe the bug**
Can't update roles via public API anymore

**To Reproduce**
1. Update to latest version
2. `curl -sX PUT https://bb.domain.tld/api/public/v1/users/USERID -H 'x-budibase-api-key: APIKEY' --data '{"roles": {"APPID":"BASIC"}}'`
3. Receive error: `{"message":"Unable to save user - Cannot set role of account holder","status":400}`

**Expected behavior**
I expect that the user roles are updated as requested

**Additional context**
In previous versions of Budibase no error appeared. I think the breaking change was introduced with https://github.com/Budibase/budibase/pull/14470

**Comment by ConorWebb96** [comment]
Hey @marzzzello,

These are enterprise-only API [endpoints](https://docs.budibase.com/reference/roleassign). This restriction was mainly introduced to avoid using the public API to work around our paid user groups feature. When you invite a user, you can assign them to user groups so they already have default access.

If you are an enterprise customer encountering this issue, please email support@budibase.com, and we will investigate further.

I'm going to close this as I don't believe this to be a bug.

**Comment by aptkingston** [comment]
This particular endpoint is just the user update endpoint which is available to everyone. The error here is because the owner of the Budibase installation is always an admin, and this can't be changed. We made sure to enforce this in the change you linked @marzzzello.

Basically there is no point in attempting to set app roles for the owner because they can always do everything, so app roles are meaningless for them. You'll only get this error when attempting to update the owner of your account (who indicated in the UI now too). App roles only apply to non-admins, so using this endpoint with non-admin users should be fine.

**Comment by marzzzello** [comment]
@aptkingston ah yes. I tested with multiple users and this was the reply for an admin user.
I also tried it with a non admin user and then no error appears.
But the role is not set. I do the same request for a non admin user and I get as response that no roles are set:

`
curl -sX GET https://bb.domain.tld/api/public/v1/users/us_USER_ID_NO_ADMIN -H 'x-budibase-api-key: BB_API_KEY' --data '{"roles": {"APP_ID": "BASIC"}}' | jq
`
```json 
{
  "data": {
    "_id": "us_USER_ID_NO_ADMIN",
    "email": "removed",
    "status": "active",
    "firstName": "removed ",
    "lastName": "removed",
    "forceResetPassword": false,
    "roles": {}
  }
}
```

Then I tried to use `/roles/assign` endpoint instead but there another issue occurred: https://github.com/Budibase/budibase/issues/14643
