### ISSUE TITLE
When referencing another field as the default value, it doesn't get the value and instead outputs as empty.

### ISSUE THREAD

**Issue by ConorWebb96** [Budibase/budibase#14658]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.32.8
  - App Version: 2.32.8

**Describe the bug**
Default values don't output a value when referencing other field values within. Currently, these values are blank when used.

**To Reproduce**
1. Use the sample data
2. Set a default value for the last name column using the first name column
3. Add a new row
4. See no value is present for last name on row creation.

**Expected behavior**
I should be able to reference other column values in the default value area whenever they have data present.

**Screenshots**
<img width="679" alt="Screenshot 2024-09-30 at 10 02 51" src="https://github.com/user-attachments/assets/603ed8af-70ec-4733-aa00-889af4cc0437">
<img width="370" alt="Screenshot 2024-09-30 at 10 03 15" src="https://github.com/user-attachments/assets/9be4641e-d246-4efa-9cde-7b10f8276299">

**Comment by aptkingston** [comment]
This is unreleased so just removing the production tag. And just to add that I believe the bug here is that we shouldn't offer bindings for other columns at all. It doesn't make sense for default values to be able to be based on other column values as it could cause cyclical dependencies, so we should remove these bindings.

**Comment by aptkingston** [comment]
Yea that's what came to my mind too. But the possibility of that at all means we can't allow it can we? Unless we go down the route of only hiding bindings from columns which we can't allow (e.g. those with defaults and formula columns). But that would then need communicated to the user and docs to explain what's going on. We would also then need to prevent adding default values to any columns currently used in other default binding expressions. I just think it's a bit complicated and I'm not sure if the value it provides is worth it.

I think the cleaner solution is just don't allow it in general.

Do you think there's an easier way to solve this that still allows us to offer this feature?

**Comment by samwho** [comment]
I don't have strong feelings either way, just from a technical standpoint we can certainly offer _some_ bindings, and the fact that Conor thought it was a bug makes me think we _should_.

If a user sets a field to be a default field later on, with a formula for the value, then anywhere else they're trying to use that field in a default formula binding will stop working. This will be confusing, agreed.

It sounds like a judgment call. We should ask the founders.

**Comment by aptkingston** [comment]
> the fact that Conor thought it was a bug makes me think we should

To be honest I think this was only the case because the bindings are currently shown. I'm not sure if this would be an expected feature if the bindings weren't there in the first place... But to be fair - since you can do this in formula columns, perhaps users would indeed expect to be able to do the same with default values.

> It sounds like a judgment call. We should ask the founders.

Agreed 👍

**Comment by shogunpurple** [comment]
@samwho @aptkingston I feel like the usefulness of default values is reduced (and the need to have expressions at all) if you can't reference other columns, it enables the use case of providing a better fallback value if something isn't populated for a new row, rather than just a static value.

My vote would be to hide the bindings from those with defaults/formulas, and we can add something to the docs about it

**Comment by aptkingston** [comment]
I'll have to rethink my PR (https://github.com/Budibase/budibase/pull/14635) then, since in that I added a default value setting for options fields and used a dropdown as the component to pick the default value (since that's better UX for an options type), and it also simplifies validating that default value is in the options list.

If we allow bindings that reference other fields it will be impossible until runtime to validate that the default value for an options column is actually included in the options. Maybe we'll just have to make this conditional on the field type? I hadn't added default values for multi-select types yet but the same thing applies there too.

**Comment by mjashanks** [comment]
Agree that this would be very nice to have, but we decided early on to not allow this due to the potential of circular references. I'm happy to **not** allow referencing other fields.

If its easy and low-risk to achieve, great, go for it.

**Comment by shogunpurple** [comment]
> I'll have to rethink my PR (#14635) then, since in that I added a default value setting for options fields and used a dropdown as the component to pick the default value (since that's better UX for an options type), and it also simplifies validating that default value is in the options list.
> 
> If we allow bindings that reference other fields it will be impossible until runtime to validate that the default value for an options column is actually included in the options. Maybe we'll just have to make this conditional on the field type? I hadn't added default values for multi-select types yet but the same thing applies there too.

Cheers for context - that's a good point, probably ok to have it conditional on field type as they don't all follow the same rules. It's not the end of the world to ship without it, but as long as it's something we can address later on as a v2
