### ISSUE TITLE
Update Setting conditions not working as expected on Buttons and Text

### ISSUE THREAD

**Issue by mikesealey** [Budibase/budibase#14809]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:docker compose
  - Budibase Version: 2.32.1
- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**

**To Reproduce**
1. data provider set to a table with rows
2. add a form and text field
3. set the data provider's filters to match a field in the table
4. Add a headline component or button
5. give the headline a condition >> Update setting (Text) to 'That' if Data Provider rows length equals 0
6. give the button a condition >> Update Setting (Disabled) to True if Data Provider rows length equals 0
7. Preview or publish, and interact with the form field in such a way that the data provide rows equals 0
8. 

**Expected behavior**
Update Setting should take affect and (in these instances) change the text and button-settings

**Screenshots**
https://jam.dev/c/70270b0a-d73a-49dc-9363-8069d6b3a911
  
**App Export**
[Venu Oct 16th-export-1729099324744.tar.gz](https://github.com/user-attachments/files/17400316/Venu.Oct.16th-export-1729099324744.tar.gz)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrme
 - Version 130.0.6723.58 (Official Build) (arm64)

**Additional context**
Bug filed by CSE as a result of customer support enquiry

**Comment by aptkingston** [comment]
Hey @mikesealey. The issue here is that the condition is using the wrong value type.

For example, let's assume there are 0 rows.
- The true value in context for `Data Provider.Rows Length` is integer 0.
- The result of the Handlebars expression `{{ Data Provider.Rows Length }}` is string `0` *not* integer 0. This is because all Handlebars expressions return strings unless you use the `literal` helper.
- You are comparing to a value type of `number` with value `0`, which is integer 0.
- Therefore the expression is comparing string 0 with integer 0, and this does not match.

The fix is change `number` to `binding`, which will compare string 0 against string 0 and work as expected.

This is another reason why JS is superior to HBS, because there is no forced string coercion.

Handlebars expressions always return strings unless you use the literal helper.

**Comment by aptkingston** [comment]
I do realise this is far from ideal and is hard to spot. This is just one of the reasons I strongly dislike Handlebars. But technically there is no bug here.
