### ISSUE TITLE
Cannot see external datasource schema in binding drawer (next)

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1483]
**Describe the bug**
The fields from my external datasource are not available in the Binding drawer. Using `next` branch

**Steps**
1. Create external datasource and query (I used a rest API)
2. Create new screen with `Data Provider` linked to my query
3. Add a component inside data provider
4. Open binding drawer

These are the fields that I see: (not my schema)

![ds](https://user-images.githubusercontent.com/3524181/117955403-eb63ce00-b30f-11eb-8439-6270fc1a0a47.png)

**Comment by aptkingston** [comment]
The reason here is that you need to use a `Repeater` if you want to access the data in each individual row. The provider always assumes multiple rows, and doesn't make the data inside each row available. If you want to do something like display the name of each row, you'll need to add a repeater, and then put your component inside the repeater. 

I think this might be one of the cases where it's confusing because you're only expecting a single row back. 

One way to make this slightly easier is that we could maybe expose the actual data of the first row, so that if you only want or expect a single result you don't need to use a `Repeater` for one row, which feels strange. I'm open to suggestions here, it's one of those problems that will be hard to get right I think.

**Comment by mjashanks** [comment]
Of course :)

It is a little strange, but may just be something that needs to be learned. I don't think I'll make that mistake again. Maybe `Repeater` is not the right name anymore. 

I think the main thing will be around documentation. We will need to make it very clear, in a few different ways.
