### ISSUE TITLE
Invite user - incorrect link in email

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1528]
I have setup my Budibase to be on port 10001.

The links in the invite email all reference port 10000.

**Comment by mike12345567** [comment]
This is sort of an issue, the links sent out in the email are driven by the `platformUrl` which is in the `Organization > Platform` settings.

I'll change it so that the default URL it sends out has the right port in it, but for example if you want to host budibase behind a reverse proxy of say `app.mycoolapp.com` theres not much way for the platform to realise thats the URL you're going to use.
