### ISSUE TITLE
Search filter - null values excluded from bool filters

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#1581]
Related to https://github.com/Budibase/budibase/issues/1580 - this issue would be redundant if we decided that a required bool makes no sense and bools are always true or false.

**To Reproduce**
1. Create a bool column
2. Add a new record, don't touch the checkbox - bool field is therefor `null`
3. In design, add a filter to your dataprovider

There is no way to include `null` in a filter.

**Comment by aptkingston** [comment]
Finally thought of a way to fix this!

Indexing `null` as `false` is impossible, because when indexing we only have access to the document, but not the schema, so we can't tell if a field is supposed to be `boolean` or not, and we also don't know what fields we might be missing.

So I figured it would be possible by inverting the filter expressions to always work on `true` properties instead. The following transformations will solve the problem:
- Transform `equals false` to `not equals true`
- Transform `not equals false` to `equals true`

These two rules ensure that `null` values are always assumed to be false, because any fields set to `true` are obviously not `null` any more. This basically considers boolean logic to always be concerned with `true` and `not true` rather than `true`, `false` and `null`.

I can't apply this transformation in the filter editor because it will screw up the UI and be confusing, so instead I've implemented it in the data provider, when the luncene query is being built to be sent to the server. This keeps the UI consistent and transparently solves this issue.

Here's a screenshot with this patch, showing a table filtered with a boolean field equal to false:
![image](https://user-images.githubusercontent.com/9075550/121385366-f460b300-c940-11eb-828f-48c323c7f6da.png)

And here's the table of data, showing rows with both `false` and `undefined` in the field:
![image](https://user-images.githubusercontent.com/9075550/121385471-0b9fa080-c941-11eb-9d98-384de26f7b70.png)

I'll PR this change and copy over this description there.
