### ISSUE TITLE
Unable to remove text input validation when using the search component

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1653]
**Describe the bug**
I am using a text input as a search component. When I add text and search, it would fine, but when I remove the text and continue on with my work, there's a validation error 'Required' that hangs around.

**Expected behavior**
There should be an X / close icon to remove the validation error. 

![Screenshot 2021-06-07 at 15 13 07](https://user-images.githubusercontent.com/49767913/121032104-df4e1d80-c7a2-11eb-939d-26197ec7f1ca.png)

**Comment by shogunpurple** [comment]
Nice find @joebudi - so I had a look at your CRM app that this happens on. It's because your form is bound to the `Leads` schema, meaning that the `name` field (the primary display column) is required. You would only really bind to the `Leads` schema if you were creating or updating a lead.

In the case of a search experience like you have there, you should use the `Custom` schema, and bind your input to the data provider. 

I've fixed your app and it's now working as expected, however I've discovered another bug in that the list of data sources gets cut off when it gets long.

![Screenshot 2021-06-09 at 12 49 03](https://user-images.githubusercontent.com/11256663/121349230-2c57fe00-c921-11eb-8f72-c0810ccd7a0c.png)

Think we are starting to get into modal territory here. Thoughts?

**Comment by joebudi** [comment]
A fixed height, scrollable dropdown might be an option?
