### ISSUE TITLE
Unable to duplicate a data provider

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#1661]
**Describe the bug**
Within the design section, I am unable to duplicate the data provider component

**Comment by aptkingston** [comment]
What happens when you try? I can't reproduce this I'm afraid - seems to work fine even when duplicating a complicated tree of components.

**Comment by joebudi** [comment]
Nothing happens. I also find it hard to delete screens - what's your experience with this?

**Comment by aptkingston** [comment]
Is there an error? Is it only in a certain app or can you never duplicate them? Do the other components duplicate fine? Sorry for all the questions, just I need something to go off because I can't reproduce it and I don't want to leave issues lying open.

Saw the issue for deleting screens. It only jumps if you're trying to delete a screen that is not the selected screen, and that's below the current screen. I've never seen it myself, probably because I think I always select the screen before deleting it. But I can see that it's annoying when it happens. Should be an easy fix though.

**Comment by joebudi** [comment]
![Screenshot 2021-06-14 at 11 57 49](https://user-images.githubusercontent.com/49767913/121881883-be884980-cd07-11eb-915d-6cd11794c9b5.png)
it happens on all apps, and specifically happens when a data provider has a large table in it.

**Comment by aptkingston** [comment]
Got it fixed. It was nothing to do with data providers actually, it was caused by the table settings in this specific app. The problem happened when you tried to paste a component that has a null value anyhere in it's definition, because of the way the recursive function `removeBindings` worked.

**Comment by joebudi** [comment]
Awesome work @aptkingston . Great find!
