### ISSUE TITLE
Client library upgrade path - ability to update to latest version

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#1693]
Currently we do not have a method to upgrade the client library that is stored in MinIO for an app. This is problematic as from time to time we do update the client library and with updates it will bring new features and upgrades.

Realistically this path needs to make the user aware that there are risks (e.g. it might not have exactly the same API) and some components may break etc - check somewhere to see if this is the case. Also should probably print out the current version and the new version.

This will also need a backend API which is able to do this.

**Comment by shogunpurple** [comment]
Yeah, this is definitely required since you need to export/import to do it now. I think that we need to avoid a breaking app at all costs - as in, the app crashes and becomes unrecoverable. I think it's ok if some of the components might need updating, but not if you get "the white screen of death".

A few suggestions to mitigate:
- Be able to roll the client lib version for an app back from the portal screen, so you can access the app again
- Have much more sophisticated error handling in the app preview so we can catch errors lower in the stack, and maybe even identify which components are broken

**Comment by aptkingston** [comment]
Got a few ideas around how to hopefully improve error handling. Nearly all of the time when the apps break though it's actually not throwing an error, but just doesn't have some required resource or has no routes (the most recent one) so can't render anything. Some intelligent stuff there around doing some basic sanity checks and displaying some messages to the user about possible solutions would definitely be a big upgrade, as well as some more error wrappers to catch any errors thrown by individual components.

**Comment by kevmodrome** [comment]
I think we talked about this at some point, but this is probably the quickest way to handle errors: https://www.npmjs.com/package/@crownframework/svelte-error-boundary and hook it up to something like sentry
