### ISSUE TITLE
Space Before and After Text Not Saving Data

### ISSUE THREAD

**Issue by arpit314ad** [Budibase/budibase#1820]
**Describe the bug**
Space before and after the text, the data will not save, gives an Error msg: "An error has occurred"

**To Reproduce**
1. Go to 'Form Create in Budibase'
2. Click on 'Preview Button'
3. Scroll down to 'Add space before the text and try to save the data'
4. See error  msg: "An error has occurred"

**Expected behavior**
![IMG_20210621_114553865](https://user-images.githubusercontent.com/86228170/123234187-5bad6400-d4f8-11eb-925c-c5c8d2aec854.jpg)

**Screenshots**
added the screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version [91.0.4472.114]

**Additional context**
NA

**Comment by aptkingston** [comment]
Hi @arpit314ad. I don't think this error has anything to do with spaces before or after text, as I have just tested that and it works fine. Could you open developer tools, and provide more information on what the error is? There may be some information in the console, and some information in the network tab as a response from that request that fails.

Can I see the actions for your button? That may be where the issue is.
