### ISSUE TITLE
Renaming an App

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#1876]
### Discussed in https://github.com/Budibase/budibase/discussions/1868

<div type='discussions-op-text'>

<sup>Originally posted by **edc1970** June 29, 2021</sup>
Is there a way to rename an app? </div>

**Comment by Mitch-Budibase** [comment]
Seeing an issue against this one.

In general there is no validation against App names (can use any character/special character/number).

More specifically, it is possible to have an app name with a bunch of spaces
-This can be achieved via creating an app with empty spaces as the name
-Or via updating the app name and replacing the current name with spaces

Another thing to note is that you click the name to enter and edit the app - you cannot do this when the app just has spaces for the name.

I've attached a screenshot here to show an app with spaces for the name.
![Screenshot 2021-08-02 at 17.38.16.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/d6dcd43f-c0b7-4632-ab45-39ab82d497f1)

Setting this back to in progress

**Comment by mslourens** [comment]
this issue is not related to this feature, because, as you said, it can be achieved by creating an app with spaces alone. I propose to close this issue and create a bug with these findings. 
Please specify (in that bug report) what the validation of an app name should look like:
- are special characters allowed? If so, which ones? Or all?
- are numbers as app name allowed (I would say so, there is no harm in using a number as name)
- should we strip the name of leading and trailing spaces?

**Comment by shogunpurple** [comment]
App names should strip leading/trailing spaces, as well as be alphanumeric and only allow spaces/underscores. I've added this functionality here in this PR:
https://github.com/Budibase/budibase/pull/2379
