### ISSUE TITLE
Some components break after app import

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#1928]
v0.9.70

Hey All. After app export->import some existing/previous design properties imported incorrectly:

- **Buttons:** font-weight, padding, text align. It also unable to override/fix it by custom CSS - Using custom CSS for fixing, it starts showing okay in builder until page refreshed or app opened in new tab. 

- **Headliners:** font size, weight, margins - after import, text looks bigger but thinner. **h1** becomes **h2**. Just checked in Chrome Inspector **the same headliner** in existing vs imported app:
  
Existing: h1 in css:
  `  font-size: 1.5em; `_(as 21px)_
`   margin-block-start: 0.83em;` 
   `  margin-block-end: 0.83em;` 
    ` margin-inline-start: 0px;` 
   `  margin-inline-end: 0px;` 
    ` font-weight: bold; `_(as 700)_

After export-Import: h1 section became h2 section in css:
   `  font-size: 22px;` 
   `  font-weight: 600;` 
   `  margin-block-start: 0.67em;` 
   `  margin-block-end: 0.67em;` 
   `  margin-inline-start: 0px;` 
    ` margin-inline-end: 0px;` 
  `   font-weight: bold;` 

p.s. I use Inter font-family across my app and all my headers were customized (font size, weight changed) in old builder with beautiful design section.

- **Link component:** two **new** properties come in css after app import: `display: inline-block; `and `text-align: left;` (they are absent in existing app links). It breaks design or elements position in containers.

Not related to v0.9.70:

- **Animations/Transitions:** Existing ones that I had on some containers just disappeared. Now App looks more static and kind of boring/dead without it.

- **Chart font (legend)** is displaying completely differently in Chrome Windows and Chrome Mac (more ugly on mac, like not the same font as on Chrome windows). Mb because it is missing on macs, then Google fonts would help I guess..

- **Date Range component:** also noticed a versions ago: the date/time picker font always looks like times new roman. Checked it in inspector: not font-family specified for it. Moreover, when app is starting opening (page contents loading) there is the same font (like times) everywhere which then switching to font I use (inter) in less than a half second when page loading completed. It is more noticeable on slow computers.

Hope my little observations will help to investigate.

Thanks

**Comment by joebudi** [comment]
Hey @sergey-dme 

Thank you for reaching out. As I said before, please feel free to[ book a slot in my calendar.](https://calendly.com/budibase/) I would love to chat more about your intentions and needs.


Button - I tried to recreate your persistence issue, but failed. It worked for me. Could you provide more info or a video?
Headliners - The headlines now use Source Sans Pro, and for good reason. Source Sans Pro is used across all components now. This makes it easier to build components that look great across all apps with Budibase. It also makes it easier to do things like [theming](https://github.com/Budibase/budibase/pull/1918). The new headline does have different props, but you can override these with css.

Links - [A fix is coming](https://github.com/Budibase/budibase/pull/1918/commits/963f6fa3fd9502daa9d96610862ef1de250051ec)
Chart font - [A fix is coming](https://github.com/Budibase/budibase/pull/1918/commits/40e31907dac305f816762fdc491bfd710f94d1c8)
Date range component -  [A fix is coming](https://github.com/Budibase/budibase/pull/1918/commits/1b094b43ef2ca9bd36b1e830838a82f8d53594c9)

I must give you credit for noticing these small inconsistencies. 

Please book in for a call. It will allow me to understand your requirements a lot better.

Joe

**Comment by aptkingston** [comment]
Hi @sergey-dme. As Joe mentioned, there are already fixes in place for the actual bugs here - the chart font color and date range component font family. Well spotted. As for the other components, I'm going to go through them and explain the changes.

### Buttons
**Customised buttons from old apps will still be customised.**
Buttons were changed be be much better looking and provide useful variants out of the box. The default style therefore looks different to the old default, but any custom styles will still be applied. If you had customised buttons in your old app they should still look the same. I have just tested it myself, and using custom CSS works perfectly to change the style of a button to whatever you want. Here is a very ugly button I made with a couple of lines of CSS.
![image](https://user-images.githubusercontent.com/9075550/124564218-be77f700-de38-11eb-881e-8486649e347c.png)

### Headlines
**Customised headlines from old apps will still be customised.**
You are describing the default styles, which are how the component looks whenever no styles have been customised. You are correct that the new default is very slightly larger (1px) and very slightly thinner (700 to 600). If in your existing app you had specified either font-weight or size in the old design section then they will still be applied and it will look the same. The reason that the default styles looks a tiny bit different is because we're updating component to allow easy theming of entire apps. You can easily change the weight, color or size of headlines using the settings without needing to use custom CSS.

### Links
These style propertiesa should really not break anything. `text-align: left` is the default, and if you had changed it in the old design section then it will still be applied. You can also customise alignment in links using the settings, which again defaults to left. `display: inline-block` is a very safe default style and again, would not break the position of a component. When inside a flex container, display `inline-block` is no different from `block`. Having said this, `display: inline-block` is not needed in the link component so I will remove it anyway. Perhaps if you have a container which is not `display: flex` then `inline-block` on a link will position it beside another component rather than below it? In which case that behaviour will not happen after I remove the style.

**Comment by sergey-dme** [comment]
@joebudi @aptkingston Thanks for the quick responses and detailed explanation. 

I will be posting some screens (existing app vs imported) today for buttons (I also will try to override css again) and links when its position breaks after app import.
 
Joe I booked a slot in your calendar for today. Looking forward to having conversation with you.

**Comment by sergey-dme** [comment]
The following screen demonstrated the main noticeable changes after export->import app

![Ex_vs_Imported](https://user-images.githubusercontent.com/53024832/124600187-21848080-de6f-11eb-9049-2712d696a03b.png)

**Button** existing properties fixed by CSS override. That's Okay now. The button text is on the place now with ex. size/weight.

**Comment by aptkingston** [comment]
Thanks for that @sergey-dme. A few of those issues there look like consequences of the new container settings, such as gap or alignment. Try removing gap if it is set on your containers, and try using vertical align "Middle" for some of those places where things aren't aligned properly. In general, I think play around with the container settings and it should be easy to fix those couple of alignment issues.

**Comment by sergey-dme** [comment]
@aptkingston I fixed most of them by CSS override. But decided to work in existing app for a while, Then I will import it and fix by CSS issues appeared. Could you please help me with this: How to add CSS properties using Custom CSS for HOVER? Tried almost everything, but can't figure it out, for example, I'd like to change txt color on Link when mouse over it.

**Comment by joebudi** [comment]
:hover is not currently possible sadly. We will provide theming in the upcoming releases.

**Comment by sergey-dme** [comment]
> :hover is not currently possible sadly. We will provide theming in the upcoming releases.

@joebudi That sounds interesting. Looking forward to releasing new functionality. But please retain/keep current hover and other user-customized properties on objects/components created in previous budibase versions. And please retain ability to us Custom CSS 🙏

Joe thanks a lot for your time, I really enjoyed the conversation we had. My apologies that it took more time than scheduled because of my ideas/requests:)

**Comment by joebudi** [comment]
> > :hover is not currently possible sadly. We will provide theming in the upcoming releases.
> 
> @joebudi That sounds interesting. Looking forward to releasing new functionality. 
> But please retain/keep current hover and other user-customized properties on objects/components created in previous budibase versions. And please retain ability to use Custom CSS 🙏
> 
> Joe thanks a lot for your time, I really enjoyed the conversation we had. My apologies that it took more time than scheduled because of my ideas/requests:)

It was my please @sergey-dme

**Comment by sergey-dme** [comment]
Is there a way to restore transition fx (fly, scale, etc..) for a container using Custom CSS in imported app?

**Comment by joebudi** [comment]
@sergey-dme no. These were removed as they generally provide more problems than solutions.
