### ISSUE TITLE
Unable to add External Postgres DB on DigitalOcean

### ISSUE THREAD

**Issue by sunasra** [Budibase/budibase#1967]
**Describe the bug**
I am trying to connect external Postgres DB hosted on Digital Ocean. It throws below error

Self signed certificate in certificate chain

**To Reproduce**
1. Go to Data -> Sources
2. Click on Add name - select postgress
3. Add connection detail
4. Save datasource and Fetch tables

**Screenshots**
<img width="1078" alt="Screenshot 2021-07-10 at 3 13 44 PM" src="https://user-images.githubusercontent.com/993152/125158971-06c54b00-e192-11eb-9189-af9db98beb8b.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Additional context**
Budibase Version -  0.9.73

**Comment by spokebase** [comment]
I have the same problem.

**Comment by shogunpurple** [comment]
Does turning off the "SSL" toggle work?

**Comment by spokebase** [comment]
No, if I turn it off I get the following error: no pg_hba.conf for host "..."

I had the same problem when I set up forest admin. At the end I had to add a few variables to the .env file to make it work. But this time it does not.

**Comment by chrisshaw** [comment]
I have the same setup. This is a **managed** Digital Ocean PostgreSQL DB Cluster. I can potentially shed some additional light from my research.

I believe it's essentially this issue: https://www.digitalocean.com/community/questions/can-t-connect-via-nodejs-error-self-signed-certificate-in-certificate-chain

I forget where I read this by now, but I think something about how Node.js and node-postgres (`pg`) automatically sets `sslmode`. This seems to be the same issue. https://github.com/brianc/node-postgres/issues/2558

I _assume_ DO is using self-signed certs for its managed DBs. Digital Ocean's documentation says it requires the mode to be `require`. I think this becomes an issue here: https://github.com/Budibase/budibase/blob/master/packages/server/src/integrations/postgres.ts#L125. Because it will reject the self-signed certificate.

The internet will tell you to set this to `false`, which seems awfully backwards. Rather, the answer should be to allow us to set the mode and use the DO-provided ca-certificate after toggling on SSL. I think there may still be issues with `pg` on this front, but I'd have to dig further.

**Comment by shogunpurple** [comment]
Thanks a lot for this detail @chrisshaw. There has been a few issues in the past specifically with DO managed databases. It seems like we need to provide a more custom SSL configuration for the postgres connector. That line you highlighted there was a bit of a catch all so people could get their connectors working, but we should provide the ability to even upload a certificate in the UI and have it stored against the connector.

As you say i'm not sure if that will even solve it given the `pg` issues, but we will dig into it.

Thanks again!

**Comment by chrisshaw** [comment]
No problem! On a bit more research, I do think that node-progress issue gives the answer, because DO allows you to up the security mode. So just being able to add a CA certificate and setting `{ ca: ... }` should suffice (:crossed_fingers:)

**Comment by spokebase** [comment]
@chrisshaw exactly - I had the same problem on Heroku.

**Comment by shogunpurple** [comment]
Honestly this is great @chrisshaw you've saved us a ton of time - we will account for this and let you guys know the status. Thanks a lot for your patience!

**Comment by james-freec** [comment]
I have the same issue, any one help?

**Comment by aiskingstud** [comment]
Thanks to the advice I found buried here in the issues, I was able to get my development app (on my local machine) to query the remote postgres database on the Digital Ocean servers. But when I deployed the code to the production environment, I got the dreaded SSL chain error.

But ... the code below worked.


```
const { Pool } = require('pg')
const fs = require('fs') // to read the cert file

// load environment variables in file .env for local development
require('dotenv').config();

const pool = new Pool({

  /* DATABASE_URL comes either from the .env local configuration file, where it is a copy-paste of the connection string found in the managed database dashboard on digitalocean's servers, or from the app environment variable that I bound in DO's app settings. I bound it to ${<databasename>.DATABASE_URL} */

  /* Must strip the query string off connectionString. DO supplies connectionString on managed postgres databases with a query string ?sslmode=require appended. Kind people on this forum pointed out that the query string must be removed. */

  connectionString: process.env.DATABASE_URL.substring(0, process.env.DATABASE_URL.indexOf('?')),

  /*
  CACERT is an environment variable I bound in the app settings on DO's servers. I bound it to ${<databasename>.CA_CERT}. I also set a LOCALCACERT variable in .env to point at the local certificate file. 
  */

  ssl: {
    rejectUnauthorized: true,
    ca: process.env.CACERT ? process.env.CACERT : fs.readFileSync(process.env.LOCALCACERT).toString()
  }
})
```
