### ISSUE TITLE
Forms: Dropdown Dynamic Options

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2094]
When I am configuring a dropdown component, I want to be able to load the options of the dropdown dynamically - using either JS, or the result from an external data source so that I can show or hide options based on other pieces of data in context.

**COS**
- An "Options" setting on dropdown components, which will bring out a binding panel allowing the options to be loaded with JS or an external data source.
- If external data source is chosen, there should be a transformer option available also to map the data
- The data source or script must return values in an array with a format like so:

`[{ label: "Apple", value: 123 }]`

**Comment by mjashanks** [comment]
This might be a separate issue, but wanted to flag this: https://github.com/Budibase/budibase/discussions/2082#discussioncomment-1082463

Is autocomplete on a relationship picker. Would likely be useful for other options pickers as well.

**Comment by aptkingston** [comment]
Updating the scope of this slightly since we aren't implementing JS in August. I'm thinking we can have a setting to pick the source of the options, which will include tables, external data sources and queries. Similar to how charts work, we can then also have settings to pick what the columns are for the option "label" and "value".

We should really also just let people define them statically, so I think an initial setting to choose what way you want to define the options is important.

**Comment by mjashanks** [comment]
If we could hook it into a Data Provider, that would give all those options - maybe that was your intention. It would be slightly annoying to have every Select nested in a Data Provider though. Unless the select could in some way inherit a Data provider, so that all its settings were automatically in-built.

**Comment by aptkingston** [comment]
The settings for the columns to pick would need to be on the select itself, so there's only one extra setting needed which is the "data" setting currently on data providers. But there are other advantages to using providers, in that they can search and filter tables too - because without that we would be unable to filter options down on internal tables. So I think you're right, that data providers are the way to go.

I agree it might be annoying to have every select in a provider, but it's only for those selects which need to dynamically load options. All of our current selects which get values from the schema don't need one, and if you were using a select to control UI state or something and had manually defined options then you wouldn't need them either. Pretty much all selects for entering data into external sources will need it though.
