### ISSUE TITLE
Can't create two relationship columns to the same table

### ISSUE THREAD

**Issue by cradford** [Budibase/budibase#2106]
I have a table listing the 'unit of measure' that a product is inventoried in. Example entries would be 'Each' or 'Bottle' or 'Gram'.

I need a second table to define conversion factors between related units of measure. An example might be 'FromUnit: Dozen, ToUnit: Each, Factor: 12' which would indicate that a 'Dozen' would convert to 12 'Each' units.

When I try to create the table I start with the 'FromUnit' column and set it to be a one to many 'Relationship' column referencing the 'UnitsOfMeasure' table and the column is created. When I try to create the 'ToUnit' column as a one to many relationship to the 'UnitsOfMeasure' table the process fails to create the column.

Is there a proper way to do this in Budibase?

**Comment by mike12345567** [comment]
Just had a look at this issue, I believe it has been resolved at some point, I've created the scenario you were referencing here:

![image](https://user-images.githubusercontent.com/4407001/133765280-4f07aaad-024f-4e97-a02c-77de02aea534.png)

One thing to check is whether or not your `column name in other table` is different for each relationship you create, this must be unique for each one (due to the bidirectional nature of Budibase relationships).
![image](https://user-images.githubusercontent.com/4407001/133765417-e4cbe78f-a5b1-479a-8fcd-4e15df29e707.png)
