### ISSUE TITLE
[Feature request] Watch for changes in standard-components library

### ISSUE THREAD

**Issue by mslourens** [Budibase/budibase#2111]
This is a feature request for developers: since Vite 2.2.0 you can watch for file changes, so whenever you change something to the standard-components library, it gets build automatically.

**Comment by shogunpurple** [comment]
@mslourens Myself and the team are unable to recreate this. The standard components reload as normal for me because everything is symlinked together in the monorepo and managed by lerna. 

Try running a `yarn bootstrap` before a `yarn dev` to create the symlinks.

**Comment by mslourens** [comment]
I don't use Lerna to start the services, I start them separately with Webstorm in order to debug them. Is that still possible if you run them using Lerna?

**Comment by Rory-Powell** [comment]
another option @mslourens is to use `yarn dev:noserver`. that'll let you have hot reloading on everything but
- worker
- server
which you have to start separately in your case using webstorm

**Comment by aptkingston** [comment]
Hey @mslourens. The `standard-components` package is a bit confusing at the moment. The `client` package already bundles `standard-components` inside itself, and this is all that's needed. `standard-components` never needs to be ran by itself. If you start the `client` rollup bundler (through webstorm, you don't need lerna other than to do the symlinking initially) then that will already bundle `standard-components`. Just make sure to do a top level `yarn bootstrap` to let lerna create the symlinks, and then you can run all the packages standalone if you want (just not `standard-components`, because like I said it never gets bundled by itself).

**Comment by mslourens** [comment]
Thanks @Rory-Powell, that's the one I was looking for. I'll close this PR, since it's not really needed for my purpose.

**Comment by mslourens** [comment]
@aptkingston thanks for the explanation, I was wondering how it all fits together, but I get the picture now.
