### ISSUE TITLE
update to 9.82 killed all of my tables 

### ISSUE THREAD

**Issue by AndrewJRamay** [Budibase/budibase#2133]
@shogunpurple @mike12345567  when refreshing my tables hoping the date not saving problem and the key row problem was fixed in the update I got this error. 
![image](https://user-images.githubusercontent.com/80058238/127177865-9418f088-655e-4412-9829-e9917a569e04.png)

 I have never had a table called FINISHED_ no idea where this is coming from. if I create a table called FINISHED_  to try and mitigate the error I get this error. 

![image](https://user-images.githubusercontent.com/80058238/127178037-07330550-1f23-4c2d-b5e8-0b2ef557531e.png)

![image](https://user-images.githubusercontent.com/80058238/127178256-9a9f6e0b-26ae-4745-baa7-5ea9503bf5f5.png)

please help this update has gone backwards with my functionality.

**Comment by mike12345567** [comment]
Hi @AndrewJRamay - sorry about this, although I'm a little confused, do you know what release you were on before? We haven't actually updated anything in this area in a while, we are planning a soft release for today with a bunch of fixes and new features, but the releases that went out today weren't actually updates, the system just released because some changes were made to the README and so on.

**Comment by AndrewJRamay** [comment]
I did figure it out, one of my guys put a # in a data table label finished_#2_deisel. the fault is 100% on my side sorry for the false alarm.
