### ISSUE TITLE
auto columns not populated / deleted rows reappearing / and more

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2139]
### Discussed in https://github.com/Budibase/budibase/discussions/2132

<div type='discussions-op-text'>

<sup>Originally posted by **projestra** July 27, 2021</sup>
Dear all,

when I came across budibase a couple of days ago I was excited by the whole concept. Brilliant - many thanks! 

I've installed budibase as instructed in die manuals via the CLI on an old iMac running Ubuntu 20.04.1. All components from node.js to docker where installed in their most current version. So far so good ... up and running smoothly.

Actually everything woks fine for as long as I work from a single user (which in my case is the budibase admin user). As soon as data rows are added from a second user account, database behaviour becomes very strange (to be on the safe side, I even ditched the whole install incl. containers and volumes, of course but the behaviour stays the same). 

As this is best illustrated with a series of screenshots, I have attached a PDF illustrating the system behaviour. I don't have the faintest idea what may be going on here and would greatly appreciate some insight.

Many thanks in advance and kind regards,
Christian
[The Problem.pdf](https://github.com/Budibase/budibase/files/6885942/The.Problem.pdf)
</div>

**Comment by mslourens** [comment]
I investigated the issue. As far as I can see the Created By is empty, because the new user is not known in the database of the app. When you first create an app, then you create a new user, and finally you open the created app with the new user and add a new row with a 'Created By' field, the system will try to find the user to create a link between the user and the created row. It will not find this new user, because it only has a reference document to the user who originally created the app. 

In order to fix this issue we need to add a reference to the new user (`ro_ta_users_us_<ID>`) in the app this user is working on. We could do this when creating a new user for all apps, or we could check if the user is known by the app when the app is opened, and if not, create the reference to the user table.

**Comment by Mitch-Budibase** [comment]
I have followed the steps within the produced problem.pdf (linked above).

I am seeing an issue still.

Table created and populated by one user - Created By & Updated By columns populated accordingly.
I sign in as another user(admin user) and add a row to the table - Created By & Updated By columns are **NOT** populated correctly.
I sign in as another user (basic user) and add a row to the table - Created By & Updated By columns are **NOT** populated correctly.

![Screenshot 2021-08-18 at 15.46.34.png](https://images.zenhubusercontent.com/60fed9d54a973614368dfdfe/abc22c57-f499-4003-b512-b6228cada44e)
