### ISSUE TITLE
Research Spike - Live App Preview performance

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#226]
The live app preview completely re-renders when you: 
- Choose a component or screen
- Update a components props
- really any interaction in the builder UI

We need to prevent this. It's a bad user experience and is very jarring. 

This issue pertains to a research spike, which is essentially just looking into ways that it could be improved and hopefully finding some low-hanging fruit. Once investigated, comment findings under this issue for discussion.

**Comment by kevmodrome** [comment]
I've been looking a bit at this today and I think there are a number of options. From what I can gather the preview-pane is pretty much the "real" application with a style to show which component is selected.

@shogunpurple has suggested switching to using `<svelte:component>` instead of using an iframe. I think should be doable but I'm again a bit unsure about what is actually going on when the application is "built". A nominal glance seem to indicate currently it manually renders the svelte components and attaches them to different nodes (or parents in the case of child components). Are there any specific architectural reasons that makes this a necessity?

The benefits of using Svelte would be that we can take advantage of the built-in optimisations as well as get some easy wins like dynamically loading each page rather than load everything at once, etc.

Looking for some low-hanging fruit that we can quickly adopt.

**Comment by shogunpurple** [comment]
@kevmodrome I think initially it made sense to render everything client side as budibase was to be framework agnostic, where you could write a small wrapper around the vanilla JS in the client lib for different frameworks. 

This is no longer the case - we are leaning into svelte and will probably configure apps at compile time, saving us the need to do any kind of runtime config. This would be a pretty sizeable chunk of work to do, so any low hanging fruit that we can tackle for now would be great before we start thinking about that step.
