### ISSUE TITLE
Select relationships in data provider filters

### ISSUE THREAD

**Issue by kevmodrome** [Budibase/budibase#2316]
**Describe the feature request**
As a user it would be a much greater experience if you could filter on relationships somehow. I'm finding myself running into this when building different things. It's particularly nice to have in apps where an admin assigns tasks/jobs/etc. to other users. Ideally you just want to list those rows that do not have an "owner" if that makes sense.

I tried a workaround where I added a formula field that checks the length of the relationship but that doesn't work either (probably for the same reason it's not possible to filter on relationships?).

**Comment by mjashanks** [comment]
I'd just like to note that this is different from: https://github.com/Budibase/budibase/issues/2876

This, I believe, is a lot simpler. 

In the example `One Project has Many Tasks`, I want to be able to
- Set up a `Data provider` for `Tasks`
- Filter the dataprovider to only show Tasks that belong to the project that is selected in a options/relationship picker. 

I feel like we can already do this on the backend, however, it is not possible to apply this filter on the frontend. Relationships are not selectable in filters.

**Comment by gvlx** [comment]
Hi, this is similar to #3344.

**Comment by yeoldegrove** [comment]
Are "formulas" also covered by this issue or would this be easier to implement already?

**Comment by mjashanks** [comment]
Just writing a note here as I had an idea that I don't want to forget.

Filtering by relationships on internal tables is a problem because relationships exist as a separate document in CouchDB. The reason that it is done this way is so that we can support Many-To-Many relationships - every relationship internally is a many-to-many underneath.

It seems that we could simplify filtering (though it still might be a big change), by changing 1-N relationships to be stored as a field in the child document.... i.e. `MyParentTable_id : "row_1234abcd"`. This structure would make 1-N filtering trivial (I think).

I believe that this would cover the majority of uses. We could decide not to support filtering on many-to-many for internal tables (or deprecate many-to-many for internal tables entirely).

Another benefit of this is that it's an easy-to-explain limitation of internal tables, making it easier to describe when it's a good time to choose SQL.

**Comment by mike12345567** [comment]
Hi @mjashanks sorry I didn't see this until now, had a discussion with @shogunpurple about this early this evening, this is an approach we considered before ever building the relationship system, but there are a few troubling issues with it. While it would definitely solve the filterability of internal relationships, it could open up some serious problems we'd have to solve.

1. The first and biggest reason that it could be problematic is that it is not the recommended path for creating relationships/references between documents in Couch. The consistency problem in part with managing conflicts in Couch makes this very difficult, since we can't perform a partial document update it would be very easy for us to get into issues caused by non-atomic updates. We sort of have this problem today in that the relationship documents aren't necessarily updated atomically, but the worst case scenario today is the relationships could get a little bit out of sync if too many parallel requests were received, whereas with a full document update we could end up in a data loss scenario, such as an old revision being written, or the users request simply failing and them needing to re-fill in the form. We would also have an issue with the revision history for all inter-related docs becoming very lengthy, updating a document in one table could cause many simultaneous document updates in other tables, meaning that a single row write could generate a significant number of revisions to be created - this is noted to be very problematic for replication performance. This also could have major implications down the line for backup and undo systems, more revisions will always make this more difficult.

2. The bi-directional nature of relationships today, versus what they would become. This is a big issue to do with how relationships are implemented today, for us to continue to support the bi-directional nature of relationships, while also writing the related rows into each other we'd need to build out a relatively smart system to recognise that only relationship fields have been updated. There's a risk here for a loop to form where one row is updated, causing another row to update, causing the original row to update, and then going back around in a loop. There are definitely solutions to this issue, but we'd need to be aware of the risk here.

3. Many to many relationships would be nearly impossible, as the building a through table wouldn't really be a through table - only the through documents would actually contain the contents of both tables. I'm not really sure this a solvable problem, coupled with the bi-directional nature of Budibase relationships, we'd probably have to completely remove many to many relationships from internal tables to be able to support this - however we'd need to double up relationship systems for a while to allow deprecating it, which again could be a source for issues.

4. The migration path could be very complicated, not only would we be removing the concept of many to many relationships, we'd be fundamentally changing how relationships work in Budibase, for 1:N, N:1. Planning out the migration would take a fair amount of thought, again a solvable problem, but not a simple one.

5. Lastly, I think its worth noting that even without the bi-directional issue the solving of consistency across relationships will be quite difficult as this method would introduce a risk of data inconsistency to relationships. In the past when we first implemented relationships we had issues with consistency, but the worst case was only ever losing reference of what was related to what. If rows contain the full relationship data we now have an issue where the data itself can be inconsistent. I'll not get too deep into this, but I think there are a lot of problems we'd need to think about here, as there is a significant chance of data loss depending on how users build forms around relationships.

At this point sorry for the wall of text, tried to keep it as brief as possible, I think there is a more limited scope solution here, which I've discussed with Marty, the idea of formulas being calculated on row input, rather than row output, meaning that consistency only has to be solved for the formula fields (which specifically state the data they require) and could be added as a setting for formulas meaning no need for migrations or deprecation. It wouldn't be a perfect solution but could allow for basic relationship filtering scenarios, as well as simply allowing formula filtering - it would just cut down the scope significantly although issue 1 would still apply - but it would be a lot more heavily scoped at least.

**Comment by mjashanks** [comment]
Thanks @mike12345567 - incredible explanation :)

One issue to be aware of with formulas on input - it would prevent the creation of Formulas based on the current date, e.g. "2 Weeks from now", or `Age` (based on DoB).

But that is probably an acceptable tradeoff, as it can be accomplished in `Design`. Filtering on formulas would be incredible.

One thing to keep in mind as well - grouping by formulas & relationships in a view (future version of views).

Great work.

**Comment by mike12345567** [comment]
No problem, glad it made sense!

I think for formulas it comes down to adding an option, with a tool tip to denote which type should be used for what. I think it'd be something like a static formula vs a dynamic formula, static formulas only get their value once (or when relationship updated) vs dynamic updating everytime they're used (with the negative of not being searchable/usable in views).

With views, the static/input processed formula would automatically work with them as you'd expect from a property within the doc, there would just be the issue of making the UI aware of the static formula columns.

**Comment by gvlx** [comment]
Hi all,

A quick question: using an external relational database like Postgres runs into the same issues?

**Comment by mike12345567** [comment]
Hi @gvlx - no in the case of SQL based databases in the next release we will support filtering on related values - you can see the progress on this as part of PR: https://github.com/Budibase/budibase/pull/4073

**Comment by rpavlik** [comment]
So strange that this is closed as wontfix when there is this workaround that could presumably be done internally just as well as I can do it manually: https://github.com/Budibase/budibase/discussions/5661

Is the only benefit of a relationship in the built-in database, then, constraining the possible values?

**Comment by shogunpurple** [comment]
Hi @rpavlik - the static formula workaround is a temporary measure, and we plan to address this with a larger project in the coming months to make life easier when working with relations in budibase. But yes - constraining the values (and allowing you to edit the relationships between the records in apps) are the main benefits.

**Comment by mike12345567** [comment]
@rpavlik - also worth noting that the workaround is not a proper fix for the problem, for us to do it internally we would have to take some very major performance hits to the internal DB and it would limit some functionality severely to offer it in a consistent fashion. When a user configures a static formula they can extract the specific field they want, something that is unknown to Budibase internally - therefore a user configured static formula can be quite a bit more efficient.

**Comment by SidPayton** [comment]
Hi @mike12345567 , just wanted to ask about the status on this topic as I still don't see this solved. It would really help me build with Budibase. Is this feature anywhere near release?

**Comment by mike12345567** [comment]
Hi @SidPayton at the moment this isn't on the roadmap - there isn't much more information I can provide on this other than that right now!

**Comment by SidPayton** [comment]
Hi @mike12345567, thanks for the swift update. 
Looking forward to the major update to your DB. I found a workaround in the meantime with which I can live. 

Loving Budibase by the way. Great job. There are still a few kinks to work out to make a totally smooth platform to work with but so far it really helps me to get an MVP fast. Thanks
