### ISSUE TITLE
force numpad on input type="number" on mobile webbrowsers

### ISSUE THREAD

**Issue by tobehn** [Budibase/budibase#2414]
**Describe the feature request**
As a user i want to directly be passed to the numpad on mobile browsers in case a form field is defined as number.

https://stackoverflow.com/questions/3372380/how-to-force-keyboard-with-numbers-in-mobile-website-in-android

**Comment by kevmodrome** [comment]
I think this is a reasonable feature request. I'm unsure if we want to force this on users automatically. Are there situations where this not something we want?

We also need to keep in mind that it should work on both iOS and Android.

**Comment by tobehn** [comment]
i cannot see a situation either where you want to access letters while being i a form field of type number.

So if possible budibase should directly prompt to the numpad.

**Comment by kevmodrome** [comment]
You're probably right, just want to make sure it makes sense in all cases, including edge cases.

**Comment by aptkingston** [comment]
@tobehn this is already the case for anything other than Safari on iOS. In future it would be helpful if you could specify if the issue is iOS / Safari specific. In this case Safari does not respect `type="number"` like all other browsers do, but we can force it by using `inputmode="decimal"`, which is something we can add.

**Comment by tobehn** [comment]
I am on iOS Firefox (will specify in future, sure). It's probably an iOS (14.6) issue.
