### ISSUE TITLE
URL parameter is not what I expect, when using SQL

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2417]
Copied from this comment: https://github.com/Budibase/budibase/discussions/2043#discussioncomment-1205027

I have a `Customers` table, in postgres, and corresponding `/customers` and `/customers/:id` screens.

The `View` link on my customer table reads `/customers/{{ customers Table.customers._id }}`. However, at runtime, this translates to `/customers/%5B10%5D`. So, the `{{ URL.id }}` parameter decodes as `[10]` (the id of the record is `10`).

This is inconsistent with internal tables, which do not wrap the id in brackets `[ ]`.

If I manually browse to `/customers/10` the page works just fine, so there doesn't seem to be a purpose for this.

There is a very sensible workaround, it's just confusing.

**Comment by aptkingston** [comment]
This is by design. Since there's no guarantee that external SQL tables have an `_id` field (which we depend on), we enrich them with one automatically for rows in external tables. This field is an array because SQL rows may have composite keys, so the only way to uniquely identify them is to generate this `_id` field using all the attributes of the composite key. In the case where there is just a single primary key then there's just one entry. We need to do this in order to be able to unique identify the row when we want to update it.

What the key is shouldn't matter though, because the API should be able to retrieve the correct row using this ID. Was it not retrieving the row correctly when clicking the link and using that generated ID?

**Comment by mjashanks** [comment]
It was retrieving it ok.

However, when tried to add a Note (child record) inline, it wouldn't work - I assume because it was trying to set the foreign key to `[10]` (see below).

The workaround is to use the id from the repeater, rather than the URL - so not an issue really. It just makes the usage of `{{ URL.id }}` inconsistent.

![image](https://user-images.githubusercontent.com/3524181/130065482-e79c39fc-0968-499f-bb39-caad7786a69d.png)

**Comment by aptkingston** [comment]
Ah fair enough. I can't image it would be hard to update it so that any schema columns for foreign keys just extract the value inside the generated `_id` array if present, which would make that work. I can see people are bound to trip up on that. At the same time if people don't have an `_id` column in their table they may also be confused as to why they're setting a foreign key to a column that doesn't exist.

I also have no idea what would happen there if the primary key actuallty was a composite key, because that would require totally different SQL to be generated if you wanted to reference it as a foreign key.

**Comment by sergey-dme** [comment]
Hey  @mjashanks just as idea - use Handlebars:
`{{ remove ( remove ( decodeURI  "%5B10%5D" ) "[" ) "]" }}` => 10
your example: `/customers/{{ remove ( remove ( decodeURI  customers Table.customers._id ) "[" ) "]" }} `
I use couchDB and unable to check if this will work for you

**Comment by MarkOSullivan94** [comment]
Big thanks to @sergey-dme for the snippet, helped me with a similar scenario 🎉

**Comment by AndrewJRamay** [comment]
I still can not get this to work I have no idea why. I have tried all of the above suggestions. @MarkOSullivan94 are you using MySQL or the built-in DB?

**Comment by MarkOSullivan94** [comment]
@AndrewJRamay I'm using a Postgres DB.

What is your URL parameter showing and what are you expecting @AndrewJRamay?

**Comment by AndrewJRamay** [comment]
@MarkOSullivan94 I am using Maria DB
