### ISSUE TITLE
Detail screen pulls all rows in SQL table, in builder preview

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2434]
When i use a SQL (postgres) table to create a detail screen, the Data Provider pulls all rows in the table. This only happens in the builder preview, not when running the app.

![image](https://user-images.githubusercontent.com/3524181/130422292-bbabed9e-1f2c-4270-98e8-d4b02ba8d92f.png)

Filter is set correctly:

![image](https://user-images.githubusercontent.com/3524181/130422351-9d44451f-f045-44cc-8d43-6d8223787749.png)

I can set `Limit = 1` to solve this. However, since it's not set by default, it will cause someone pain if they have a lot of rows in their table.

**Comment by aptkingston** [comment]
This is because the URL doesn't exist when inside the builder preview, so it's not applying the filter. It shouldn't pull back all rows though, it should use the default of 50 (unless you've increased it or cleared it) so I don't think it will cause a performance problem, but the preview will look messed up. I imagine it will show 50 details pages if you've combined this with a repeater, and that might cause some slowdown to be fair when rendering that. I always set a limit of 1 for a details page and would just recommend doing that.

If we wanted to address this properly then the best way I can think of would be adding a builder screen setting for "preview URL", so whenever you're editing a screen in the builder you can set what the URL is. That would let you fill in whatever type of URL you wanted and see how the screen reacts. Could also maybe just be a setting to configure any URL parameters, if they exist, rather than free typing the URL.

**Comment by mjashanks** [comment]
Great thanks! Default limit to 1 sounds sensible to me.

**Comment by aptkingston** [comment]
Ah I've just found in the code that if it's not an internal table it doesn't set the limit to 1 for details autoscreens! That's probably a leftover relic from before "plus" datasources were a thing. I'll remove that so that it always sets 1 as the default for autoscreens for external tables too.
