### ISSUE TITLE
Form.Fields.Attachment always returns nothing

### ISSUE THREAD

**Issue by sergey-dme** [Budibase/budibase#2481]
Hey all, 

When binding of attachment is using it always returns nothing when a file selected to upload or deleted. 

So, it's unable to use the `Form.Fields.Attachment` as a condition. Component binding doesn't recognize if there's a file is selected and ready to upload or attached file to be deleted. 

This issue I faced long time ago. Now it became more vital, as I'd like to use conditions, for example: on the edit row screen -- I want to keep Save button disabled until at least one of the form fields updated (just comparing repeater values vs form fileds values) and this doesn't work for attachments. Or to show other components if user selected file to upload.

**Comment by aptkingston** [comment]
Hey @sergey-dme. I've had a look at this and there's a bug that means if you bind to `Form.Fields.Attachment` it will always be undefined. Normally if you bind to an attachment it will return the URL of the first file, so I'm going to fix this so that the form does the same behaviour. This means you should be able to compare them against the repeater. Thanks for reporting 👍

**Comment by sergey-dme** [comment]
Hey @aptkingston Thank you very much for looking at this and for the PR!
