### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by lipan1024** [Budibase/budibase#2487]
**Describe the bug**
I deployed budibase with docker compose,,but I forgot my administrator account, password and email. What should I do?

**To Reproduce**
docker-compose --env-file hosting.properties up -d

I don't know where the account password is kept. I thought it was CouchDB, but it wasn't.

**Comment by mslourens** [comment]
This is not really the place for these kind of questions, it's better to ask them in the Discussions section of the Github repo, since it's not a bug. 
To answer your question: you could try removing the admin user from your global couchDb database:

1. Login couchDb with 'budibase' as username and password
2. Navigate to the database called `global-db`
3. Remove the document starting with `us-`
4. Navigate to http://localhost:10000/builder/admin and create a new user.

**Comment by shogunpurple** [comment]
Thanks @mslourens! 

Just to add to that - if you set up with the budibase CLI, your database credentials can be found in your `.env` file in the directory that you installed budibase. They are under the `COUCH_DB_USERNAME` and `COUCH_DB_PASSWORD` variables.

**Comment by lipan1024** [comment]
Thanks @shogunpurple @mslourens !
We will try to use budibase as a productivity tool, and I'm looking forward to it.
