### ISSUE TITLE
Tenant names are case sensitive

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#2570]
**Describe the bug**
Tenant names are case sensitive on the organisation tenant selection screen. This means that entering an existing tenant name with different casing leads to budibase asking you to bootstrap a completely new tenant.

**To Reproduce**
- Go to organisation tenant selection screen
- enter an existing tenant name with different casing
- You will be asked to create a completely new tenant.

**Expected behavior**
You should be taken to the relevant tenant.

**Screenshots**
<img width="338" alt="Screenshot 2021-09-09 at 11 22 37" src="https://user-images.githubusercontent.com/11256663/132669193-8958512b-13ff-41c7-8d22-534f8fbfd1d1.png">

**Comment by aptkingston** [comment]
If I use a capital letter, or space, or non standard character, I actually get an error when I try to proceed:
```
Name: 'asd asd_global-db'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.
```
So I think we need to heavily sanitise this. Displaying it sanitised to the user doens't matter much, because whenever they come to enter it again, if we run the same sanitisation over it then we shoud end up with the same original string.

Does this same thing need to be applied in the account portal when entering a domain name? I'm assuming the domain name is what becomes the tenant ID?

**Comment by Rory-Powell** [comment]
This was looked at just before the release, there's some regex in there now
```js
static TENANT_REGEX = new RegExp(/^[a-z0-9-_]+$/)
```
and a warning message
```
Domain Invalid. Must only contain lower case letters, numbers and the characters '-' or '_'
```

I went with these rules to match the structure of a uuid, should we ever need to support uuids for tenant ids instead of strings
