### ISSUE TITLE
Data Validation rules cause field to require a value (when a non null validation is not selected) 

### ISSUE THREAD

**Issue by KernOil** [Budibase/budibase#2580]
Hi Team, 
I have noticed that when I apply some custom data validation rules I can no longer leave that field blank when submitting the form. 
the data validation is not for the box not to be null so it should work with an empty box. 

to Recreate my current setup ( maybe the same with other setups)
use MySQL DB 
have one too many relationships between tables.
have a date field that is auto captured when a form is submitted. 
put data validation on the data fields saying the date can not be before the form was submitted.  
you can now not submit the form with null values in these boxes.

I started a discussion here #2564
here is a video 

https://user-images.githubusercontent.com/80058238/132722140-42368061-dd73-48a6-9d0d-a033c5287fa1.mp4

**Comment by aptkingston** [comment]
Hey @KernOil. You're correct - using a "minimum" constraint does currently also imply "required". To me that made sense logically, but since that behaviour differs from the "maximum" contraint (which does not imply "required") and there is a separate "required" constraint which you can add if you want to, I will update this so that "minimum" accepts empty values.

**Comment by aptkingston** [comment]
This will be merged soon and included in our next release 👍

**Comment by KernOil** [comment]
@aptkingston Thank you very much!
