### ISSUE TITLE
Filter only applies final condition

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2585]
I am trying to create a filter with 2 x "Not Equal" conditions. Only the final filter is applied:

![image](https://user-images.githubusercontent.com/3524181/132753858-89b46a3b-f884-4d12-9509-66a81a5d4681.png)

It doesn't matter how many conditions I add - only the final one is applied. Same issue for "Equals"

**Comment by aptkingston** [comment]
This is because of the structure that we use for the search payload - it's an object and therefore will only be able to store one type of condition for each column. I thought this was alright, because you'd never search for `name = bob` and `name = bill`, that wouldn't make sense. But for not equals it's a more valid thing to do. We'll have to refactor things a fair bit to support this.

**Comment by magickaito** [comment]
This should be resolved. Thanks!
