### ISSUE TITLE
Support Projections in MongoDB connector

### ISSUE THREAD

**Issue by wehde92** [Budibase/budibase#2590]
Hi,

The mongo db connector doesn't allow you to pull out specific data using projections. 

`{},{"data.node" : 1 }`

Is one example that it returns an error with the syntax issue being the comma:

![image](https://user-images.githubusercontent.com/8854624/132922088-250e9824-c9fb-44ad-aa95-c45bc13d8e6d.png)

Is there a better way to this?

My json collection an array of 

`
{
  "_id": 1234
  "data": [
    {
      "mem": 1234,
      "disk": 1234,
      "type": "node",
      "uptime": 1234,
      "level": "",
      "status": "online",
      "maxmem": 1234,
      "cpu": 1234,
      "node": "abcd",
      "maxcpu": 1234,
      "maxdisk": 1234,
      "id": "node/s2nc"
    }
]
}
`

Thanks

**Comment by shogunpurple** [comment]
Hi @wehde92 - unfortunately it is not possible to pass a second argument to `find` or any other mongoDB method with our mongoDB connector to perform projections.

Over the next few weeks, we will be working on JavaScript "transformers" that will allow you to run some JS code over your response, and map it into the format you need. This would solve your problem.

I do however think that we should support projections in our mongoDB connector, so that you don't always have to map the data client side. I'm going to change the title of this issue to reflect that, and we will look to solve it over the coming weeks.

**Comment by wehde92** [comment]
Sounds Good. I appreciate the fast response. For now we will just pull data from a separate collection that is structured for the frontend view. Keep up the great work!
