### ISSUE TITLE
 budi hosting --start Watchtower port error

### ISSUE THREAD

**Issue by bdevroey** [Budibase/budibase#2615]
Following the guide by default on Ubunt 20.04 https://docs.budibase.com/self-hosting/budibase-cli-setup

Gives the lower error.

./budi hosting --init
? This will create multiple files in current directory, should continue? (Y/n) Y
root@h2949204:~# budi hosting --start
Starting services, this may take a moment - first time this may take a few minutes to download images.
The WATCHTOWER_PORT variable is not set. Defaulting to a blank string.
The Compose file './docker-compose.yaml' is invalid because:
services.watchtower-service.ports contains an invalid type, it should be a number, or an object
Error - Failed to start - logs written to file: docker-error.log

**Comment by burnoutberni** [comment]
Make sure that your `docker-compose.yaml` contains a `WATCHTOWER_PORT` environment variable (your file should look something like [this](https://github.com/Budibase/budibase/blob/master/hosting/hosting.properties#L20)). Then either run `budi hosting --start` again or edit your local `.env` file to add the variable there as well.

**Comment by bdevroey** [comment]
Thanks :) that worked!

**Comment by jdawg2112** [comment]
My docker-compose.yaml file includes: 

watchtower-service:
image: containrrr/watchtower
ports:
    - "${WATCHTOWER_PORT}:8080"

But I still get the error when I run ./budi hosting --start

Budibase Erro
The WATCHTOWER_PORT variable is not set. Defaulting to a blank string. The Compose file './docker-compose.yaml' is invaled because: serves.watchtower-service.porsts contains and invalte type, it should be a number or and object.


Any ideas on what the issue is??

Thanks

**Comment by jdawg2112** [comment]
enyoy.yaml has watchtower port_value set to 8080 also.
