### ISSUE TITLE
The screen slot in the layout editor gets deleted with its parent section

### ISSUE THREAD

**Issue by dominikjannis** [Budibase/budibase#2652]
Stumbled upon this today. If you nest the screen slot of a layout inside of a section, upon deletion of this section the screen slot gets deleted with it. Since the screen slot itself is not deletable, and i did not find a way to add it back in, i think this is a bug.

To reproduce:
1. Create new Layout
2. Create a new Section
3. Nest the Screen slot inside of it
4. Delete the Section

**Expected behavior**
The Section getting removed and the screen slot being brought back to full width.

Best,
Dominik

**Comment by mslourens** [comment]
I don't think removing the parent section but not the child screen slot is the right way, because we always remove the children if the parent gets removed. It would be better, in my honest opinion, to add the screen slot to the components list (at the top of the preview), so the user can add a new one, of the existing one gets deleted. We just have to make sure only one screenslot is allowed per layout.
