### ISSUE TITLE
Close button on theming is confusing

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2785]
**Describe the bug**
When I was changing the theme of my app, I was hesitant to click close because I was not sure if my changes would be saved.

Maybe a button that says 'Save' or 'Apply theme changes' or 'Update theme'

![Screenshot 2021-09-29 at 10 58 04](https://user-images.githubusercontent.com/49767913/135247306-2cdfdf1e-bb1a-4573-ae52-c4d092bbeeb2.png)

**Comment by aptkingston** [comment]
The only reason it isn't called save is because it saves automatically when you make a change, and normally this is evident by the fact that you can see your app changing in the background. I'm happy to change it to "Save" or "Done" if you think that close is confusing though. Although as long as this change wouldn't mislead people into thinking they can make changes and then abandon them by clicking outside the modal to cancel.

**Comment by joebudi** [comment]
'View changes' is prob best then.

**Comment by aptkingston** [comment]
I've pushed this to develop 👍
