### ISSUE TITLE
Action buttons

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#2856]
**Describe the feature request**
Problem: I am constantly adding/editing two types of buttons:
1. View detail button
2. Create new row button

It would be great if there were button presets - View detail button, New row button - that were already hooked-up with the correct navigation/modal etc. This would stop me from having to search for the ID (in re to the view detail button).

**Comment by aptkingston** [comment]
I'm not sure that this would actually save time, because even if we made a "View detail button" component, it would need to take in the URL of the details page as a setting - which is the same amount of settings as a normal button takes in order to become a "View detail button". The only thing we could save filling in is the actual button text, but even then people are probably going to want to be able to change the text.

I don't think we can make a component that knows what URL it should link to automatically in order to be a details button or a new row button. 

Both of those are just normal buttons with one action - just a "navigate to" action with a URL. What part of that process has the most friction do you think? Maybe we can make that easier somehow.

**Comment by joebudi** [comment]
Part with most friction: 
Clicking the binding button, searching for the id (often required scrolling and reading), then clicking it and saving.
Do you not think this process could be better? I am not saying remove the button component, just add presets.

My thought was, and it might not be possible:
Create 'new row' button - no need to open the actions panel, just select your table and done.
View detail button - once again, select the table rather than the process above. Done.

**Comment by joebudi** [comment]
The more I think about it the more this type of feature will be obsolete in the future.

The source of the problem for me was invalid bindings when copying components.
