### ISSUE TITLE
Apply a filter based on fields of a relationship

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#2876]
Not to be confused with https://github.com/Budibase/budibase/issues/2316.

This is the ability to filter on fields **within** a relationship. 

So for example, say I have the structure ```One Project Has Many Tasks```.

I want to 
- Setup a data provider, for all tasks
- Only show **tasks** that belong to project where `Project.Status = "Open"`

**Comment by mike12345567** [comment]
The ability to do this for our internal tables could be very difficult, as the lucene search system is unaware of the nature of our relationships, we would have to do all the non-relationship filtering and then filter in memory afterwards against whatever rows where returned. The real difficulty with this is that if there is only a filter for relationships then we would need to pull the entire table out and filter it down that way as there would be no base search result to work from - this issue is the one that makes it incredibly difficult as if you have a table with 1 million rows in it, there just isn't a particularly efficient way to only filter on relationship values.

We could implement something like this however for SQL only, as relationship filtering would be easy to implement and would be very efficient, as its based on a real relational database.

**Comment by mjashanks** [comment]
:+1: for sure. I was mainly logging this as I think we have been chatting about this before, but was logged as something different - in #2316 . I actually think it's totally fine if this turns out to be not feasible with our internal tables (the answer is to reach for SQL).
