### ISSUE TITLE
Options Picker validation issues

### ISSUE THREAD

**Issue by Rory-Powell** [Budibase/budibase#2981]
**Describe the bug**
Seeing some inconsistency around the validation performed on the options picker specifically when using sources other than schema. 

**To Reproduce**

- Create an options field
- Don't specify schema options
- Change the `Options Source` to `Custom`
- Add custom options
- Select a custom option
- See output validation message
![Screenshot 2021-10-12 at 16 01 44](https://user-images.githubusercontent.com/8755148/136982195-16491256-12b2-463f-b589-a6d193ecb59f.png)
- Change the `Options Source` to a `Data Provider`
- Select a data provider option
- See output validation message
![Screenshot 2021-10-12 at 16 02 02](https://user-images.githubusercontent.com/8755148/136982299-49e014ac-109d-462f-840d-41389a3e1c68.png)
- Add some schema options
![Screenshot 2021-10-12 at 16 12 22](https://user-images.githubusercontent.com/8755148/136982637-971bc073-546b-47da-84f4-f41d124b498b.png)
- Change the `Options Source` to `Schema`
- Only now can a value be chosen
![Screenshot 2021-10-12 at 16 01 29](https://user-images.githubusercontent.com/8755148/136982809-08634a63-f35d-450b-a834-e4da8fe09463.png)
- Visit the `Configure Validation` panel
- Notice that no schema validation rules are shown
![Screenshot 2021-10-12 at 16 14 33](https://user-images.githubusercontent.com/8755148/136983006-c8d48b61-c7ad-4946-ac7d-32e32421eb95.png)
- Add a validation rule to match a custom option
![Screenshot 2021-10-12 at 16 15 42](https://user-images.githubusercontent.com/8755148/136983181-6e9ba371-63a6-4ef7-844a-f9346e2e9bac.png)
- Switch back to `Custom` for `Options Source`
- Select the matching option
- Validation does not take effect
![Screenshot 2021-10-12 at 16 16 46](https://user-images.githubusercontent.com/8755148/136983371-9c863e2c-c6a0-4107-b412-6a2f5fcbef32.png)
- Switch back to `Schema` for `Options Source`
- Select an option
- Validation takes effect
![Screenshot 2021-10-12 at 16 17 38](https://user-images.githubusercontent.com/8755148/136983517-089d67f2-8491-4862-8b22-fcb1e1014acf.png)

It appears that validation rules only work correctly when the `schema` source is chosen

**Expected behavior**
- Validation should be performed correctly according to the options source chosen

**Screenshots**
- See above

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Chrome
- Version: 94.0.4606.61

**Additional context**
Verified on budibase production cloud

**Comment by aptkingston** [comment]
The problem here is that you're defining an options column with no options - therefore no value is valid. The datasource or custom options aren't really designed to be used for inserting data into internal tables because we have server side validation of valid options. They're more for filtering data, or could be used for running queries / automations. So personally I wouldn't class this as a bug, since the validation is working as intended.

I think there's a separate task here which you've looked at, which is allowing a picker component to be used on a text field. That's a much better solution in my opinion for inserting values loaded from an external datasource or an API into internal tables. You'd make a text column, then load options into a picker and insert them. That flow makes more sense to me, because you don't know your options ahead of time, unlike with an internal options column where you do define your options ahead of time.

So in my opinion this isn't a bug because internal tables are designed to only allow a set number of values, and the frontend custom validation can't override the server side validation there, but I like the sound of your PR to let pickers be used for text fields.
