### ISSUE TITLE
Full Bindings in Relationships

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#3151]
When I'm using bindings with relationships in the budibase builder, I want to have access to the full relationship object so that I can use the ID for links, datasource queries and more.

**COS**
- Revert the frontend changes to parse out the displayName of the relationship by default, and return the object
- Update UI components that depend on the displayName parsing

**Comment by gvlx** [comment]
Hi, trying to understand this issue.

I can access the full relationship object by including a new data provider inside the main one, using the relationship as the source.

This allows me to use repeaters or tables to show all the details of the related data.

**Comment by aptkingston** [comment]
Hi @gvlx. You're correct, that's exactly how to do it at the moment if you want to pull relationship data.

This issue concerns whenever you use a relationship binding in something like a text field. Currently, if you use a binding like `{{ Current user.Dogs}}` (where `Dogs` is a relationship field) - then we automatically just convert that binding into some readable text, by pulling out all the "display column" values and joining them. For example, if that field contained a relationship to multiple dogs and the primary display column of the dog table was their name, then we would display the text `Rover, Barney, ...` etc. This is useful because it allows relationships to display readable text.

What we actually store in those columns is an object with the `_id` of the relationship and the `primaryDisplay` value. Sometimes it would be useful to be able to access the stored `_id` directly, without having to nest another data provider. This change removes the previous behaviour of making readable text, and instead allows the real array of objects to be used. When combining this with JavaScript bindings, we can now let users do more advanced things by using the objects directly.

The current method of using data providers to get relationship data will not be changed, and is still the correct way to do things for most use cases. This feature just lets you use relationship `_id` columns a bit easier, without having to use another data provider - in case you just want to do something simple like create a link to related record's detail page.

**Comment by gvlx** [comment]
OK. I understand now.
Thank you for your explanation.

**Comment by gvlx** [comment]
You should probably check if this approach would still work or, in fact, would not be needed anymore after your change.

See ➡️  https://github.com/Budibase/budibase/discussions/3365#discussioncomment-1636793
