### ISSUE TITLE
Sort by relationship does not work

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3182]
If we sort by relationship, either in a data provider or in the `Data` section, the sort order is random. The expectation is that it sorts by the display name.

I think that this will likely be impossible for internal tables (?). If so, we should disable sorting by relationship.

Having said that, maybe allowing it to sort by the relationship `_id` is slightly better than nothing at all - this will allow us to group rows together that have the same relationship, even if not sorted by the display name.

**Comment by mike12345567** [comment]
Hi @tluyben - I think we would need to implement a more complex sort system as a separate feature, for now we will disable it as this is the quickest option to protect against problems arising.

Right now our sort is implemented at the database level so that it plays nicely with pagination, I believe how a JS/complex sort would be implemented is client-side; this is problematic for any sort of paginated data however so I think we'd need to put a bit more thought around this.
