### ISSUE TITLE
Not able to edit row `does not exist` error 

### ISSUE THREAD

**Issue by antimatter96** [Budibase/budibase#3196]
**Describe the bug**
Trying to use PostgreSQL v13.4, getting an error while editing a row

**To Reproduce**
1. Create new app
2. Create postgres schema
```sql
CREATE TABLE IF NOT EXISTS public.persons
(
    "Name" "char" NOT NULL,
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    address text COLLATE pg_catalog."default",
    CONSTRAINT persons_pkey PRIMARY KEY (id)
)
```
3. Connect budibase to db
4. Create a person
5. Try to edit created person

**Expected behavior**
Row should be saved

**Screenshots**
eg uuid : `d03276c5-511f-4fb3-bca2-961d82e152fd`
error : `%5B'd03276c5-511f-4fb3-bca2-961d82e152fd'%5D does not exist`

<img width="450" alt="Screenshot 2021-10-29 at 7 49 26 PM" src="https://user-images.githubusercontent.com/12068176/139727714-81da8e60-35d1-4a05-aba6-34ad62b504e4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.4
 - Browser Chrome
 - Version 94
 - App version : 0.9.173
 - PostgreSQL v13.4

**Additional context**

**Comment by gunar** [comment]
I'm getting the same error with `DELETE`

**Comment by gunar** [comment]
I've looked at the code but couldn't find any leads. The only common thing between these errors seems to be that the data source is a postgres server. At one point I even got an `%5B''%5D does not exist` which obviously means an id is missing.


I can't use Budibase as is. This seems to be a pretty big issue with a simple fix. Do we think we could take a look at it?

**Comment by mike12345567** [comment]
Hi @gunar - I've tried to recreate this issue but haven't had much success, i've tried the steps described in the main issue and wasn't able to reproduce. I was wondering if you could provide a few things:

1. What version of Budibase are you currently using?
2. Could you provide a table schema that doesn't work for you?
3. Could you let me know what your datasource configuration looks like? Without the host/user/password properties.

**Comment by gunar** [comment]
@mike12345567 Thanks for looking into this.

1. I'm running the cloud hosted version of Budibase 1.0.47
2. Even the simplest of tables won't work — I can CRU but not D.
    ```
    postgres=> \d test
                                Table "public.test"
     Column |  Type   | Collation | Nullable |             Default
    --------+---------+-----------+----------+----------------------------------
     id     | integer |           | not null | nextval('test_id_seq'::regclass)
     name   | text    |           |          |
    Indexes:
        "test_pkey" PRIMARY KEY, btree (id)
    ```
3. Data source configuration:
    
![image](https://user-images.githubusercontent.com/7684574/152012304-1d2316c3-93c6-4d27-94d7-2a9a76ebba2a.png)

**Comment by mike12345567** [comment]
Hi @gunar thanks for getting back to me, I've still been unable to replicate your issues, I'm wondering if you can tell me how you have been trying to delete rows?

I've tried this locally (against my development environment) and against old and new apps in the Cloud, I created a new Postgres database and setup a table as such:

```
                            Table "public.test"
 Column |  Type   | Collation | Nullable |             Default              
--------+---------+-----------+----------+----------------------------------
 id     | integer |           | not null | nextval('test_id_seq'::regclass)
 name   | text    |           |          | 
Indexes:
    "test_pkey" PRIMARY KEY, btree (id)
```

Which I believe is identical to the one you've been testing with, but still I haven't been able to recreate the issues you've been having.

Also just to check, what version of Postgres are you running? Perhaps it is an issue with an older version that we haven't encountered before?

**Comment by mike12345567** [comment]
Hi @gunar - Budibase generates an ID for all SQL records for it to work by, we use the `[id]` syntax so that we can support composite keys as well, that is expected behaviour and Budibase will handle it.

I will have to continue to try replicate this, I've been testing against Postgres 14 so perhaps it is specifically an issue with Postgres 13.

Just to check, in the table you referenced above the ID type was `integer` - just to make sure I have an identical setup to yours can you confirm this DDL defines a table like yours? Just making sure the sequence is a relatively standard one and thats not the issue.

```
CREATE SEQUENCE test_id_seq;
CREATE TABLE test (
    id integer NOT NULL DEFAULT nextval('test_id_seq'),
    name text,
    PRIMARY KEY(id)
);
ALTER SEQUENCE test_id_seq
OWNED BY test.id;
```

**Comment by gunar** [comment]
Hey @mike12345567, I've just dropped that table and created a new one from exactly your code. Same error when trying to delete a row.

![image](https://user-images.githubusercontent.com/7684574/152392793-5e35f23f-6a10-4e01-9dd8-d3a606c947d8.png)
![image](https://user-images.githubusercontent.com/7684574/152392841-287fb122-4000-49e4-9e1d-a2e754e1e982.png)
![image](https://user-images.githubusercontent.com/7684574/152392862-4ed783ea-bc6a-4837-aaed-79099b054119.png)

**Comment by mike12345567** [comment]
Hi @gunar - thanks for testing this, so that table works fine in all of the environments I've tested it within (Cloud, locally etc) using Postgres 14, so I assume it must be some incompatibility with Postgres 13/something specific about the version used in AWS RDS. 

I've given it a test again in the Cloud, with a fresh Postgres 13 install, with the same table and a new app (connected to database, fetched tables, generated screens and then previewed) and didn't experience the issue so it must be something to do with the Postgres version used in AWS RDS - I will have to look into this.

**Comment by gunar** [comment]
@mike12345567 - It's frustrating, isn't it? Having bugs we can't reproduce. Only things that come to mind is that perhaps AWS RDS doesn't allow Budibase certain operations? Or that it might not have certain extensions enabled? I find it very hard to be the case as certainly other people use Budibase + RDS. Let me know how else I can help, or if you want me to run other experiments.

**Comment by gunar** [comment]
@mike12345567 Hey Mike, what can we do to move this issue along? Happy to share access to my Budibase portal if that helps you debug it. This issue is high on my priority list.

**Comment by techninja1008** [comment]
I've been encountering the same issue when using Budibase cloud with postgres 12 installed from repositories on an Ubuntu server instance.

I've found that a viable workaround is making the handlebars template for the delete ID in the action Uri decode the ID rather than just putting it in straight.

Taking a brief look at source, [this line](https://github.com/Budibase/budibase/blob/516cadab9df334b7456ec619c4f97c8a3237fee7/packages/server/src/api/controllers/row/external.js#L79) initially appears suspect - it doesn't pass the row ID through `breakRowIdField`, like `bulkDestroy` does [here](https://github.com/Budibase/budibase/blob/516cadab9df334b7456ec619c4f97c8a3237fee7/packages/server/src/api/controllers/row/external.js#L91) and patch does [here](https://github.com/Budibase/budibase/blob/516cadab9df334b7456ec619c4f97c8a3237fee7/packages/server/src/api/controllers/row/external.js#L36).

Looking at `breakRowIdField`, it appears to do a URI decode [here](https://github.com/Budibase/budibase/blob/516cadab9df334b7456ec619c4f97c8a3237fee7/packages/server/src/integrations/utils.ts#L129), suggesting that this may actually be the cause of the issue.

**Comment by techninja1008** [comment]
@mike12345567 I'll see if I can create a basic reproduction case if possible later

**Comment by Gaafar** [comment]
Same here using MySql 8.0.25 on AWS RDS

@techninja1008's fix seems to work
payload: `{_id: "[31]", _rev: "rev"}` => works
payload: `{_id: "%5B31%5D", _rev: "rev"}` => does not exist, this is the default payload from auto generated delete button
