### ISSUE TITLE
Redundant javascript execution when rendering a page

### ISSUE THREAD

**Issue by cverdes** [Budibase/budibase#3205]
**Describe the bug**
I made a simple toy demo application to isolate a problem that I discovered while making a more complex application to test the new frontend javascript functionality.
This simple demo application, that you can find at the bottom of this issue, has one page with a row container with six buttons inside.
The fourth button `text` field has associated the following javascript code:

> console.log('Four')
> 
> return 'Four'

When the application is run, in the console of the browser it can be seen that the script is executed six times during the first render of the page.

**To Reproduce**
1. Import the application file attached at the end of this isuue
2. Run the application to render the Home page
3. Open the Chrome Console at the Developer tool

**Expected behavior**
It would be desirable, for performance issue, that the script associated with the button be executed only once for each time the page is rendered

**Screenshots**
On this screen it can be seen the application basic structure. One page with one row container with six buttons inside:
![Screenshot from 2021-10-31 10-43-20](https://user-images.githubusercontent.com/6440942/139587850-01cf6187-cc8c-408a-9490-b5475eec5276.png)

On this screen it can be seen the javascript associated to the `text` field of the `btnFour` button. It's the only piece of javascript code written within all the application:
![Screenshot from 2021-10-31 10-43-46](https://user-images.githubusercontent.com/6440942/139588011-ddd2effa-5aa7-4ce4-906d-53e160248a8d.png)

On this screen it can be seen how the javascript code associated to the fourth button is executed six times during the first rendering of the screen:
![Screenshot from 2021-10-31 10-42-42](https://user-images.githubusercontent.com/6440942/139587372-9317089c-0623-4d63-bad2-eac7408ca041.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.3 LTS
- Browser: Chrome
- Version: Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
This is the file generated when exporting the application. It could help to test the case:
📄 [test for redundant execution when rendering a page-export-1635688323354.txt](https://github.com/Budibase/budibase/files/7448972/test.for.redundant.execution.when.rendering.a.page-export-1635688323354.txt)

**Comment by aptkingston** [comment]
Hi @cverdes. This is just a side effect of how our apps work. Without getting too technical, we need to enrich any bindings (which includes running JS code) very frequently to ensure that we don't show any stale data. We already very aggressively minimize when these are executed, using a variety of techniques which you can check out in `Component.svelte` in the `client` package if you're interested. The initial page load is the worst offender, because we load a lot of data needed to the run the app which triggers multiple enrichments of bindings (and therefore multiple JS executions).

In the scope of things, running small JS snippets like that will not affect the performance of your app at all, even it was ran 600 times rather than 6. If you encounter an issue because of this behaviour then we can have a look at it, but we have already ensured that our apps perform very well by reducing the frequency of these executions as much as possible.

**Comment by cverdes** [comment]
I understand it @aptkingston. Thanks for your explanation.
I'll read `Component.svelte` to deep a little more.
Thanks for your answer. Have a very good day!
