### ISSUE TITLE
JavaScript content disappeared

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#3217]
When writing a condition and adding JS, then saving. everything worked. When I went back to edit the JS, there was no code to edit - it was absent for some reason but the JS Scripting label was still present.

**Comment by aptkingston** [comment]
Do you have a way to reproduce this? Are you sure you didn't save with HBS enabled instead of JS?

I've tried to reproduce but everything works as intended. Did this happen yesterday when you were having those 409 errors? It could have been that the request to save the JS code was a 409 conflict which would mean that the result wasn't saved. I really don't think there's a bug here, so I'm leaning towards it being one of the 409s.
