### ISSUE TITLE
The revert button once the error occur so the entire app get deleted

### ISSUE THREAD

**Issue by nnasoke** [Budibase/budibase#3277]
**Describe the bug**
At the app builder screen: I try to undo the previous action by clicking the 'Revert' button at the top-right corner of the app builder screen but it gives me an error and then my app gets deleted.

**To Reproduce**
1. Go to 'https://[my domain].budibase.app/builder/portal/apps'
2. Click the button 'Create App' and choose 'Start from scratch', naming the app as 'Test Crash'.
3. Follow the steps of creating a data source. Then, create a table naming 'table1', leave all tick-boxes as default.
4. Once the app has been created, click the 'Design' tab at the top-left corner.
5. Click on page '/table1/new/row' and make a selection at the 'Save' button located in the app's design screen.
6. Click on the toolbar 'Elements -> Icon' to add a new icon.
7. Undo the previous action by clicking the revert button at the top-right corner. Confirm 'Revert', then you will see error 'Error reverting changes: Unable to revert. [object Object]'.
8. Then go back to ''https://[my domain].budibase.app/builder/portal/apps', the 'Test Crash' is missing.

**Expected behavior**
The 'Revert' should be undoing the previous action. But the consequence of error causes the app to get deleted.

**Screenshots**
I have a video capture for the entire steps but no idea how to put it into the ticket. Please let me know if the reproduce steps just don't work somehow.

**Desktop (please complete the following information):**
 - OS: OSX Monterey
 - Browser: Chrome
 - Version: 95.0.4638.69 (Official Build) (x86_64)

**Additional context**
The issue happens to Budibase cloud.

**Comment by HyperCrowd** [comment]
I've identified a bit more details on this

#3278

**Comment by aptkingston** [comment]
Hi @nnasoke. Thanks for raising this - this is absolutely a valid bug. The "revert" functionality lets you revert your apps to the last published state. This is so that if you have an application that has been published an in use, but then you've made some changes to your app and haven't published those changes yet, then you can revert your app back to the latest published version.

The issue here is that there is no published version to revert to, because your app has not been published. This is absolutely an issue and we should not even show that button if the app has not yet been published.

We will get this fixed as a priority.

@HyperCrowd I will respond to your issue separately but it is not related to this.

**Comment by nnasoke** [comment]
Thank you Andrew @aptkingston . The response is so fast, appreciated that.
