### ISSUE TITLE
Enrich fails with on double-nested provider, on relationship 

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3596]
Table structure

`One Team has many Tasks`
`One Team has many Users ("members")`

I want to display all tasks for the current user's team.

Component structure
```
> Data Provider: Current User.Team
  > Repeater
    > Data Provider: Repeater.Team.Tasks
       > Table
```

Nothing shows in my table.

When I inspect the API request, `enrich` fails with `{"message":"missing","status":400}`

URL looks like: 
```
/api/ta_7592d9d0dd4d491695c080c45097a45e/ro_ta_7592d9d0dd4d491695c080c45097a45e_3d62929463ba40b082dc75faec998fe0/enrich
```

App export attached..

[Team Members-export-1638274211477.txt](https://github.com/Budibase/budibase/files/7625578/Team.Members-export-1638274211477.txt)
.

**Comment by mjashanks** [comment]
This also affects blocks, which otherwise would really simplify the structure to

```
> Repeater Block
   > Table Block
```

**Comment by aptkingston** [comment]
I've justed imported this app, assigned my user a team (so that there's some data to work with), and it actually worked straight away. I also did the same thing with blocks which worked too. I wonder if one of our hotfixes that went out yesterday fixed it?

![image](https://user-images.githubusercontent.com/9075550/144577007-cf7860d1-7160-4540-8c74-d481bd9f1de4.png)

**Comment by shogunpurple** [comment]
I think this was related to an issue with the `enrich` call that was resolved in: https://github.com/Budibase/budibase/pull/3558

I'm assuming you are using cloud @mjashanks - that fix should have went out with the release.

**Comment by mjashanks** [comment]
Yes - this works in cloud now. Thanks!
