### ISSUE TITLE
Automation, Query rows - filter does not handle dynamic dates via handlebars

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3598]
In `Query Rows`, if we define a filter against a date using handlebars we get a console error and cannot save the binding...

STEPS
1. Create table with a date column
2. Create an Automation
3. Add a `Query Rows` step
4. In `Define Filters`, do 
```MyDateColumn > More Than > Binding > {{date now "YYYY-MM-DD" "America/New_York" }}T00:00:00.000```
5. Save Filter

RESULT
Binding drawer does not close, and we get a console error:
```
Uncaught RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at index.550fdba7.js:201
    at Array.forEach (<anonymous>)
    at vU (index.550fdba7.js:201)
    at b (index.550fdba7.js:201)
    at Array.v.detail (index.550fdba7.js:201)
    at index.550fdba7.js:201
    at vendor.278a305c.js:1
    at Array.forEach (<anonymous>
```

I have verified that `{{date now "YYYY-MM-DD" "America/New_York" }}T00:00:00.000` parses correctly.

If we enter a static date, it works... e.g. `2021-01-01T00:00:00.000`

**Comment by aptkingston** [comment]
Had a look at this. It's actually not an easy fixl. The issue is that the "query rows" step, which has a filter field, attempts to build the lucene query and save the built query as part of the step. This doesn't work at all though, because any bindings need to be enriched before the lucene query can be built, as is the normal flow in the client library. We can't do this enrichment because we have bindings for things like the automation trigger and previous step outputs.

Currently any bindings anywhere in a filter in an automation will fail.

The only way I can see to solve this is to refactor any automation steps which take filters so that tney build the lucene query object only after they do enrichment, at the moment of execution. It looks like the automation section does save the filter "definition" as part of the step for some reason, but I can't see it being used anywhere... We basically need to only use this definition, do the enrichment, then build the query and execute it and don't both sending up any sort of built lucene query from the automation section.

**Comment by melohagan** [comment]
I've just run into this. 
The same is true of JavaScript bindings as well - I was just using filter 'CreatedAt' less than `return new Date()` as a test.

It's a bummer because I would have liked to use the new looping feature in automation to cleanup old rows everyday. Seems like that'd be a fairly common use case.

**Comment by melohagan** [comment]
This appears to have been fixed. Closing.
