### ISSUE TITLE
Date Filtering Improvements

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3612]
A few issues that I have encountered when adding a filter to a block.

1. Relationship columns are available for selection when choosing my filter columns. Nothing appears when I select that column. They should not be available for selection
2. Date filters are applied `MyDate Equals value`. It's rare that I would use a date filter like this. It's always `Less than`, `More than` or `Between`. Additionally, I selected the exact date - this didn't work either. I have a row with a date of `2021-12-01T12:00:00.000` and I selected `2021-12-01` in the filter. Filter works if I change the time component of the row to `00:00:00.000`.
3. Auto columns are available for selection. When we select them, the filter is added, but the component is disabled - so not usable.
4. `_id` and `_rev` are available, but don't appear when selected

**Comment by aptkingston** [comment]
For #1, #3 and #4 it's all the same thing. Filtering on some column types won't result in a component being rendered because they aren't searchable. The reason they're listed is because we resused an existing "settings type" to render the component that lists those fields. We will need to add a new setting type specifically for this component in order to hide those fields from the list. I understand the confusion because it looks like you can filter on them. This is worth doing to avoid the confusion.

For #2 I'm not sure how to solve this. It's definitely a limitation. Currently all searches are equals other than for text columns, which does a "starts with". One thing I could do, is make it so that at least it will select everything for that day. I can make it a range of time 00:00 to 23:59 on the selected day, so it will at least match any records on that day. We can't really do more than / less than without adding an additional component beside each date field. 

For advanced filtering I think the new dynamic filter component would be better, which we can build into a block now.

**Comment by twilson9034** [comment]
@mjashanks @aptkingston Trying to search a column that is of "Number" type renders no results.

I have one table that uses a text field for my "Asset name" and another that uses a number field, setup by accident that way. 
When using the search field it will not retrieve any data for the number column.

**Comment by aptkingston** [comment]
@twilson9034 thanks for reporting! I can see the issue and it's an easy fix 👍

**Comment by aptkingston** [comment]
This needs scoped - there's no action to be taken here at the moment. Adding the ability to do before/after filtering for dates inside blocks isn't a small task by any means.

Personally I would prefer to go down the route of just adding a setting for "use dynamic filter", so that instead of showing any search fields above the block, it will just show the dynamic filter button. Then you could configure any sort of filters.
