### ISSUE TITLE
Bug: unauthenticated page not saved until change applied

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#363]
Steps to reproduce:

- Create a new Budibase app
- try to run it straight away

{“message”:“ENOENT: no such file or directory, stat ‘.budibase/83faa5597ef84911bccde79c1975f00b/public/unauthenticated/index.html’“,”status”:404}

We should save the unauthenticated page to disk as soon as the app is created, rather than when a change is made to props.

**Comment by mjashanks** [comment]
I briefly looked into this before... 

The reason for this is because the app does not "build" when you create a new application... you just get the pages & screens JSON, but nothing in the public folder.. which is generated by the server.

Sounds easy to fix. the one snag that I hit, and just didn't have the time to take it further, was the CSS, generated from the design panel, in the builder.

This CSS is generated inside the builder front end and sent to the server. So, the server does not have access to this code.

The reason it is in the builder is because the CSS is also used by the builder preview.
