### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#365]
The color picker is awesome but it has a few issues.

The opacity bar is not an opacity bar.
When you pick a color, then use the opacity bar, then pick another color, the color doesn't change.

https://www.loom.com/share/e92f15f3f405458e96e02bcb69715d47

**Comment by Conor-Mack** [comment]
Yeah I see what you mean - though this was intentional.

Both of the sliders (hue and opacity) only change the colour of the element whenever a colour from the palette is selected after selecting a new hue or opacity.

In Budibase the onchange event triggered by the color change hits an endpoint in the server. When we fire that onchange as we drag it hits that endpoint repeatedly in a short amount of time which seems to make the server freak out and throw an error.

I agree though that we need it to make the change without having to re-select a colour in the palette. I'm thinking the middle way is to trigger the color change on drag end (mouse up event) or implement some sort of debounce.

@shogunpurple have you any thoughts on this?
