### ISSUE TITLE
Cannot use multi-select dropdown as filter

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3773]
Not sure if this is a bug or an enhancement!

However, mutti-select pickers don't really work as filter components. So, say I have:
- A BB table with a mutli-select column - `Tags`
- A component structure of
```
> Form (for filtering)
   > Multi-select: with values `feature`, `bug`, `data`, `design`
   > Data Provider: with filter of `Tags Contains Form.Multi Select`
       > Table
```
- a record, with tags `feature`, `data`

When I select `feature` from the filter, my record is included in the results (correct)
When I select `feature` and `data` from the picker, my record is **not** included in the result (incorrect)

Ideally, when filtering a multi-select field, we would want operators of
- `Has any of`
- `Has all of`
- `Has none of`
- `Has only` (only the selected values, no more, no less)

**Comment by aptkingston** [comment]
Yep that's just an enhancement then - we'd need to add those new operators exactly like you said. Not all of those might be possible though so we'd need to check what we can do. In fact I know right away that `Has any of` would be impossible, but I think the others could work. `Contains` is just a single value lookup like you discovered. The fact it's a multi select makes it feel like you should be able to filter on multiple though so I get why this might be expected behaviour.

**Comment by joebudi** [comment]
I'm just flagging this here. When using a block (card and table) it's not possible to use a multi-select as a filter. If we don't/can't offer this, we should consider providing some feedback to the user.

**Comment by geekrambo** [comment]
I'm looking for a way to show fields in a form through conditions of a multi-select drop-down. It would be nice to have a "Contains" condition along with Equals, Not Equals, Starts with, Like, Is empty, and Is not empty.
