### ISSUE TITLE
Budibase ETL Functionality

### ISSUE THREAD

**Issue by gvlx** [Budibase/budibase#3881]
**Describe the feature request**
Following https://github.com/Budibase/budibase/issues/2316#issuecomment-1001974166,  there should be a way to ease the transition from internal budibase storage to external databases (noSQL and SQL).

This also implies a migration helper from internal to external storage of assets.

**Comment by shogunpurple** [comment]
hi @gvlx - feliz ano novo!

This is actually something that we have discussed quite a bit internally, but haven't decided on a direction for it yet. Since internal table types could map to SQL types fairly effectively, this could be a really nice feature. 

We haven't any kind of timeline for this yet, but what I can tell you is that a migration path from internal databases to SQL is likely to be included in budibase in 2022. When you have a lot of relational data, it makes sense to use a relational database - and we want to make it easy for people to choose this when necessary.

We'll update this issue with further discussion as it occurs.
