### ISSUE TITLE
Update automation JS scripting data "label" to use array access rather than dot notation

### ISSUE THREAD

**Issue by nobodyshome** [Budibase/budibase#3926]
**Describe the bug**
JS Script block in automation tab won't work with steps due to invalid syntax. Objects can't begin with a number. "steps.1" / "steps.2" etc

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'automation' tab
2. Create a new automation using app action
3. Add a step which returns some data
4. Add a JS Script block after it
5. Add some code and try to return data from the step, eg: "steps.1.response[0]" <-- from a external data source

**Expected behaviour**
Return the first response in the first step

**Screenshots**
![chrome_Jt6oySYRlG](https://user-images.githubusercontent.com/4974214/148193571-a98adf94-7817-4b72-9cae-691260ccf6b1.png)
![chrome_oAGJ232Q6t](https://user-images.githubusercontent.com/4974214/148193584-197e5578-6b78-416c-a3da-109a3b40c117.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.110
 
 **Suggested fixes?**
 1. return the steps as an array? steps[0] / steps[1]
 2. have each step it's own object? step1 / step2

**Comment by mike12345567** [comment]
Hi @nobodyshome - currently it is actually stored as an array, the labels displayed here for the data available should be updated to use the `steps[0].property` syntax as that is the correct method of accessing the data. The reason it is labelled that way is due to Handlebars, when accessing arrays through Handlebars the syntax is `steps.1.property` as square brackets (`[]`) are used for other purposes than array access.
