### ISSUE TITLE
Add HTML element id

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3927]
### Discussed in https://github.com/Budibase/budibase/discussions/3910

<div type='discussions-op-text'>

<sup>Originally posted by **marco-santulli** January  3, 2022</sup>
Hi,

I notice there are often (Buttons, links in the top menu) no ids on html elements of BB.   This makes it not usable in case of RPA or other screen-scraping scenarios, can we add id's somehow?

M</div>

If this is an easy change, it might be worthwhile considering as it seems that it could make Budibase play nice with other enterprise platforms.

**Comment by aptkingston** [comment]
We don't use the actual `id` tag on elements because there can be multiple elements with the same ID (i.e. inside a repeater). We do however attach the component ID to the DOM via a custom `data-id` attribute. I'm not familiar with exactly what he's referencing, but it's very easy to identify our components in the DOM. All components are wrapped in a `div` with the `component` class and the `data-id` attribute mentioned before. There's also a `data-name` for the component name and other classes for internal use.

There aren't ID's for things built in to the layout like the navigation links, but if it would help certain enterprise tools if we added explicit ID's for certain predictable components of apps then it's not hard to add them in. We'd just need a bit more clarity on why they need ID's and where exactly do they need them.
