### ISSUE TITLE
Drag and Drop is not working in Budibase cloud

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#3986]
I am using Budibase cloud, Chrome on Ubuntu.

When I try to drag and drop **either** in the component tree or inside the design preview, nothing happens.

**Comment by aptkingston** [comment]
I've tested Firefox on Ubuntu, Chrome on Windows and Firefox on Windows with Budibase cloud and they all work alright. So it must be something to do with the latest version of Chrome on Ubuntu, unless there's something specific with your setup. I'm ruling out it being an app level bug since it works on all those platforms for me.

Does the drag animation happen - so like if you drag in the client app do you see the green drop candidate lines? Wondering at what stage it's breaking. If you try to drag and drop and watch the network tab in devtools does the save requets get sent? I would assume not, and that something is stopping the actual drag and drop action from working.

Genuinely might be worth a restart (either browser or computer) to check it isn't just some weird temporary mouse issue.

**Comment by mjashanks** [comment]
After full restart of my machine, this is still an issue. There is no indication that anything is happening, as though there is no listener at all.

https://user-images.githubusercontent.com/3524181/148786736-73fa9108-1fdf-4f65-9345-a27968ede91b.mp4

**Comment by aptkingston** [comment]
Do you have a different browser to try to see if it's only Chrome that's affected?

**Comment by mjashanks** [comment]
Works on firefox!
