### ISSUE TITLE
[BUDI-7801] Queries don't work with auto refresh capability

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4035]
If i use the Refresh Data Provider action, I am unable to select my Block, which acts as/contains a data provider.

![image](https://uploads.linear.app/7ecfa297-cc77-4fdf-9117-fa5afdb8f908/e8203c92-0757-4d22-91a3-dcf5e7614aed/e1b09c3b-b264-447f-84d5-3becf4f1f4f5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdlY2ZhMjk3LWNjNzctNGZkZi05MTE3LWZhNWFmZGI4ZjkwOC9lODIwM2M5Mi0wNzU3LTRkMjItOTFhMy1kY2Y1ZTc2MTRhZWQvZTFiMDljM2ItYjI2NC00NDdmLTg0ZDUtM2JlY2Y0ZjFmNGY1IiwiaWF0IjoxNzAxNDQ4MjMwLCJleHAiOjE3MDE1MzQ2MzB9.hCf9nHFviYIrCv50amah4shNzypYW-zylHkg8zG2iLM)

<sub>From [SyncLinear.com](https://synclinear.com) | [BUDI-7801](https://linear.app/budibase/issue/BUDI-7801/queries-dont-work-with-auto-refresh-capability)</sub>

**Comment by aptkingston** [comment]
You're right that they don't expose the refresh action, but can I check your use case? Table blocks and card blocks don't accept children so they can never be used with a manual refresh, so I'm guessing it's the repeater block.

With the repeater block though, that "Save Row" action should cause the block to automatically refresh (assuming you're saving an item in the repeater block). I just tested that and it works, which means there's no need to manually refresh the block.

I'm sure there's a valid use case here that I'm just not thinking about! It's possible to add it to the repeater block but it would take a little bit of work since blocks do things a bit different. Can definitely do it though.

**Comment by mjashanks** [comment]
Yes - it was a repeater block, and I was using `Execute Query` on a REST API. The button fired a `POST /api/....` (save), then I wanted to run a `GET /api/...` to refresh the source.

**Comment by aptkingston** [comment]
Ah ok cool - yea a REST datasource is about the only thing that doesn't work with automatic refreshing (since it doesn't have the concept of a common datasource ID that other sources do). We can look at adding the ability to refresh blocks then, which would solve this.

**Comment by sdsys-ch** [comment]
Not stale..

I think having the ability to refresh blocks is a common use case for many UI interactions that consume RESTful data.

It can be as simple as showing the user externally triggered events or upcoming calendar entries or as complex as showing time sensitive market values for a budibase managed portfolio with buy/sell buttons.

Any block with REST queries should have a refresh ability based on user action or cron-type functionality.

Unless there's another way to do this since the issue was opened that I haven't found yet.

Thanks!
