### ISSUE TITLE
Airtable Integration: v2

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4122]
When configuring the airtable integration, I want to be able to use it as a datasource plus, so that I can easily choose my tables without having to enter table ids.

**COS**
- Add buildSchema method to airtable integration and make it a datasource plus
- Pull the tables from the airtable base using airtables API
- Allow CRUD methods on rows and tables to be passed through to airtable

**Comment by PedroHase** [comment]
Hey, would this also mean that Budibase could resolve relations from Airtable in the future?

E.g. suppose I have a user table and a projects table where I reference users as project managers, I currently have to create multiple queries to resolve the relation or I have to specifically add lookup fields in Airtable (which unfortunately will become problematic when having one-to-many relations since Airtable will then just concatinate the values, as well as clutter Airtable), would the new integration help with that?

**Comment by shogunpurple** [comment]
Hi @PedroHase - this is a good suggestion, and something we will take into account when building out the spec for this over the next month or two. It would be nice to have this ability and make things relationship aware, but I'm not sure if that will potentially blow through airtable rate limits and potentially not work that well. We will have to experiment with this and understand the limits of the airtable API. Of course we would still be doing the multiple queries under the hood as you say, but its whether that's feasible or not given the API airtable provides.

Thanks!

**Comment by adamjdavies** [comment]
Any update on this?

**Comment by adamjdavies** [comment]
As mentioned in #8324, it would be great to have pagination included in the updated Airtable integration!
