### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by pcar-13** [Budibase/budibase#4151]
I started building yesterday and today when I tried to log back in, it is telling me I had invalid credentials; I tried resetting my password and when I did, it still won't let me log in, tells me I have invalid credentials

<img width="322" alt="Screen Shot 2022-01-22 at 9 40 52 AM" src="https://user-images.githubusercontent.com/72821771/150643068-c0bb1572-7e44-4cec-89d9-0b664a824442.png">

What is wrong with the site? is it the server or what?

**Comment by Rory-Powell** [comment]
Hey @pcar-13, we had an outage yesterday between ~12:30-13:00 GMT, would this correspond with when you were having login issues? I would recommend trying the password reset flow once more, and if you still experience an issue we can look further into this if you forward your email address to rory@budibase.com

**Comment by nick-walt** [comment]
Got the same thing just now trying to login after creating and verifying a new account. As the email is validated by the response from Budibase I tried to reset the password but got an "unable to reset password" error with no explanation. So, I'm recognised by the system but at the same time it doesn't recognise my credentials and because it is in an impossible state all other actions fail, like trying to reset the password.

This feels like the kind of impossible state that is often associated with Booleans and instead something like algebraic Union types can be used if Typescript is available. Union types would make it easy to make this impossible state impossible.

I guess this is why people are asking for Typescript in Svelte. Svelte would rock with Union types under the hood (so would any language). They could simplify the syntax even more than how it is exposed in Typescript, which is very verbose (when compared to a language like Elm or Haskell).

Function and type composition could be embraced in Svelte so much better than in JS or TS.

**Comment by aptkingston** [comment]
I did actually experience this myself with the proprod env, exactly as Nick described. Registered and verified a new account, but then was not allowed to log in. Tried to reset the password, which also fails, so basically totally locked out. I assumed it was just something to do with the env, but maybe there is something going on.

**Comment by Rory-Powell** [comment]
For users currently experiencing authentication problem please follow this issue
https://github.com/Budibase/budibase/issues/7081
