### ISSUE TITLE
REST Api UX - Default endpoint naming rarely makes sense

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4175]
When using the REST api connector, I always rename my endpoint, because it always looks like this...

![image](https://user-images.githubusercontent.com/3524181/150819370-33909f01-88c3-485f-94a1-4bdcd708fb37.png)

I.e. when using the full host, I always see an ellipsis - which blocks the actual endpoint name. Maybe we should always be using variables like `{{baseURL}}/api/path`, or maybe it would be better to default to `/api/path` ?

**Comment by Rory-Powell** [comment]
I like the path idea because it will work in all situations

**Comment by shogunpurple** [comment]
Yep, sounds good - let’s strip the host from the display in the nav items on the left to make it easier to read. The only issue is that since the host is overridable per query now, the paths could all be for different hosts. Are we ok with that? 

/api/something could appear twice, but point to 2 different APIs

**Comment by mjashanks** [comment]
I think 1 host + many paths is much more common than many hosts.

Just need the 80% case

**Comment by Rory-Powell** [comment]
>  /api/something could appear twice, but point to 2 different APIs

I'd be alright with this, because the user is still free to rename one if they want to distinguish. It's unlikely to happen during import because you wouldn't have an api definition from multiple hosts
