### ISSUE TITLE
Message "Cannot read property 'rows' of undefined" on saving edited Postgres record with relation

### ISSUE THREAD

**Issue by crudyrudy** [Budibase/budibase#4179]
I successfully linked a PostgreSQL database to my budibase app and discovered the following problem:

There are two tables (company and employee in my PostgreSQL database 1-to-many related)

When I edit a company record that has no related employee records everything works fine.

But as soon as I try to edit a company record that has a related employee record I get the following message after clicking save: 
"Cannot read property 'rows' of undefined" and the record shows up unchanged. But after a browser refresh the changed field value is shown correctly.

I am using V 1.0.46 
The behavior is the same on a local install of Budibase and Postgresql on my Mac (M1 Pro) and on a Digital Ocean Docker Droplet with a managed Postgresql instance attached to it.

Any idea?

**Comment by mike12345567** [comment]
Hi @crudyrudy - can you provide a bit more information so that I can try to diagnose this - 

1. Could you provide a limited example of the schema used to define the company and employee tables, including how you've related them (what the foreign key constraints are). For example here is a schema for one of our test cases below (People are related to tasks, one to many)
```sql
CREATE TABLE People (
    PersonID SERIAL PRIMARY KEY,
    LastName varchar(255),
    FirstName varchar(255),
    Address varchar(255),
    City varchar(255)
);
CREATE TABLE Tasks (
    TaskID SERIAL PRIMARY KEY,
    PersonID INT,
    Completed BOOLEAN,
    TaskName varchar(255),
    CONSTRAINT fkPersons
        FOREIGN KEY(PersonID)
            REFERENCES People(PersonID)
);
```
2. Just to check, have you configured Budibase to be aware of the relationship between your company and employee tables?

**Comment by crudyrudy** [comment]
Thank you so much for your detailed answer. Your example works for me. There was something wrong with mine.
