### ISSUE TITLE
REST Api - Handlebars binding does not work when query name is a URL

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4180]
My endpoint name has defaulted to `https://api.github.com/orgs/{{org}}/repos`

So, my binding looks like - `{{ Github Api Repeater.https://api.github.com/orgs/{{org}}/repos.description }}`

The binding does not work, it looks like: 

![image](https://user-images.githubusercontent.com/3524181/150865956-77bdd26e-44ef-496b-b78e-73eaecf8a694.png)

**Comment by mjashanks** [comment]
Just tried this again and discovered some additional conditions:

1. The path must have a binding in it - `{{ org }}` in my example
2. You need to use the Binding dropdown to apply it as the drawer will flag it as an error

![image](https://user-images.githubusercontent.com/3524181/150976011-6c81b9a4-016a-44c6-84f7-4ddcefa5a725.png)

My Exported app:

[ApiTest-export-1643113083876.txt](https://github.com/Budibase/budibase/files/7933501/ApiTest-export-1643113083876.txt)

**Comment by upccjesse** [comment]
I'm running into this issue as well.

My REST API data source is accessed within the Design section like `{{Repeater.<base-url>.id}}`, for example. This works fine on apps that are simply a list form, like a list of all employees, because that API call doesn't need any special bindings.

This fails to work when I need to look at individual records, because the REST URL changes to include a binding. For example, `<base-url>/{{employee_id}}`.

I wager the reason it's failing is because of the way the data is accessed within the page? If I want to assign the `employee_name` field of my record to a textbox, the binding for the text field looks like `{{ Repeater.<base-url>/{{employee_id}}.employee_name }}`. However, I get the error `Current Handlebars syntax is invalid, please check the guide [here](https://handlebarsjs.com/guide/) for more details.` and when I click save, the textbox value is not updated. I guess it's the "nested binding" that's causing the issue.

It's definitely caused by the binding, though. If I edit the data source to remove the binding and instead hardcode it to access a static employee record, then go back to design and re-bind one of the fields, the field shows up as expected.

**Comment by melohagan** [comment]
Hey @upccjesse
 
If you click the pencil icon beside the REST query name then you can give the query a sensible name:
 
![Screenshot 2022-08-19 at 16 28 44](https://user-images.githubusercontent.com/101575380/185653740-6ddd815c-e874-49d3-af56-2652d40460ef.png)

![Screenshot 2022-08-19 at 16 29 44](https://user-images.githubusercontent.com/101575380/185653928-e8666a3b-7238-4d70-a061-f0514601a95d.png)
