### ISSUE TITLE
Binding/State performance

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4241]
### Discussed in https://github.com/Budibase/budibase/discussions/4056

A good discussion here about the performance of the Update State Action. I profiled this to the best of my ability (not much!) in chrome. For me, there seems to be a huge performance hit for **any** javascript binding. It's not that noticeable (for me) when I have a few bindings on the page.

However, if I have multiple (>5) Update State actions, which run Javascript - I notice it. I assume it's because they are running consecutively.

Logging as a bug, though not quite sure that it should be!

**Comment by aptkingston** [comment]
I've had a look at this. The slowdown is nothing to do with javascript bindings, or directly to do with the update state action - it's the fact that an update state action causes the entire app to enrich data bindings again.

The "state" context is global and sits above everything. Whenever state changes, every single component in the app enriches all their settings with the new context (i.e. processes all the setting values with handlebars). This has always been slow, but we've tried to add improvements over time to speed it up.

Using multiple set state actions in a row causes a full enrichment of the entire app multiple times, and this is the slowdown that you see in some cases. It is directly proportional to the number of components, regardless of whether those components actually use data bindings or not. I can easily create lag in the order of more than a second by adding 1000 text components (without any bindings) and using a set state action.

I have some "experimental" improvements on a branch to try and address this. In large component trees this results in a 10X speed improvement (reducing the example above down to about 100ms). I think I can actually take this further by implementing a version of HBS enrichment that is custom for the client library. The impovements I've made so far focus entirely on trying to avoid HBS enrichment as much as possible. These improvements are:
- Split component settings into "static" settings (no bindings) and "dynamic" settings (with bindings) and only actually pass those dynamic settings into HBS enrichment
- Cache the HBS template functions created inside the string-templates package. The client library often runs the same string templates against different contexts, so by caching the template function we can avoid the overhead of recreating it every time

I'll continue to work away at this and see what else can be done. Random thought, but if we actually dropped HBS completely and used JS everywhere I could speed things up massively.

**Comment by aptkingston** [comment]
https://github.com/Budibase/budibase/pull/4312 addresses this as much as possible for time being.

On my PC I noted the following speed improvements:
- Update state on page with 1000 components: 950-1100ms to 100-200ms
- Bastiaan's app, updating the filters (4 state updates): 400-700ms per action to 100-200ms per action

So that's reducing the total duration of the 4 update state actions in this case from ~2 seconds to ~0.5 seconds, which I think is a decent improvement. It's not perfect and in extreme cases like this (multiple set state actions in a page with lots of components) I would still consider 500ms too slow, but it's good enough for now.

There are larger, more significant refactors that could speed things up even more but they would require substantial overhauling. I did a PoC of one idea which reduced the 1000 component test from 1000ms to 1ms for example.

Lets leave this open until my PR is merged and we can evaluate the same scenario again, to see if these changes are agreeable.
