### ISSUE TITLE
Client-side search "Like" operation should allow searching anywhere in a string

### ISSUE THREAD

**Issue by marco-santulli** [Budibase/budibase#4325]
Hi,

I have two budi UI tables. One is generated from a table, the other from a query.  They both have a "company name" column.  I have added a search form for both tables.  The search uses a filter on the data provider with "like binding" option. 

I have a postgres back-end for both.

for the one generated  directly from the table, the search is case insensitive (good) and I can type any word, so if the company is called "this is a cool company" and I type in COOL, it works.
for the one generated using the query, I must use the right cases and start from the first character of the field, I can't just use a word in the middle,

I am not sure if it is a bug or feature or I am doing something wrong :)

**Comment by mike12345567** [comment]
Hi @marco-santulli, this is due to the search used for queries being carried out client-side, while the search performed directly through the table can be performed with actual SQL statements. When you write a query Budibase can't modify it to include a `WHERE` statement or anything like that, so all the data is pulled back and then searched in the client. One way you can solve this is by adding a `WHERE` clause to your query which you can link up to the frontend using a binding, although this only works for quite static searches.

In this case though I think that the client-side implementation of searching should also be case insensitive as that is the standard functionality of most search systems, i'll look at getting it updated.

**Comment by marco-santulli** [comment]
Hi Mike,

yes I see what you mean, I thought it would be something like this.  I think ideally if one specified "like" instead of "equals", it should search case-insensitive, and also words anywhere in the target string, not just from the beginning.

M

**Comment by mike12345567** [comment]
Yes, I agree with the case-insensitive, the only issue with words anywhere in the target string is that our internal database doesn't actually support a true SQL `LIKE` search, we can only search from the start of the string, so for now until we have a solution to that we have to replicate the functionality of our internal DB.

**Comment by mike12345567** [comment]
Hi @marco-santulli - I've looked into this, currently the client side search seems to actually be case insensitive (at least in the version about to be released), for now I don't think we can solve the client-side searching anywhere in the string as we need it to match the functionality of the internal DB - I'll change this issue into a feature request for a way to enable this.
