### ISSUE TITLE
Global Datasources

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#4359]

**Comment by Jan-M** [comment]
I think this title is what I am currently trying to understand. How could I use Budibase in a selfhostes way on Kubernetes where Postgres is running in the same K8s clusters and credentials are provided via K8s secrets. Somehow I would love to have Postgres data sources populated so that the Budibase app developer does not have to fiddle with this.

Same could potentially be applied to REST APIs

did my first local run and what I have seen so far looks pretty neat.
