### ISSUE TITLE
Tables using scrolling, when not the intended use.

### ISSUE THREAD

**Issue by EpsilonCommunity** [Budibase/budibase#4484]
Hi, 

I'd like to be able to visual a whole table (however cluttered) without needed to scroll left/right.

This is doable with a normal HTML Table, why isn't there a scrollable checkbox/toggle?

**Comment by aptkingston** [comment]
You're referring to horizontal scrolling right? Not vertical scrolling? Since you can already control whether the table scrolls vertically or not.

To be honest I struggle to understand why you would want a table to compress down to any size (like what use is a column thats 5px wide - you wouldn't be able to see anything). Our columns are 150px which is already small, but enough that you can actuall ready the content.

However we're currently working on adding some improvements to tables - one of which is the ability to be able to control the width of columns. So if you have 100 columns and want to set them to 1px each then you can do that. That issue is written up here if you'd like to follow progress:
https://github.com/Budibase/budibase/issues/4200

It's due to go in this month.

**Comment by aptkingston** [comment]
You'll be happy to know that you'll be able to make your data much more compact in a couple of weeks after the February release - here's a sneek peak:

![image](https://user-images.githubusercontent.com/9075550/154678020-fbdc7e4c-e053-4920-9ffa-04acac4613a0.png)

**Comment by EpsilonCommunity** [comment]
**Thanks for the sneak peak**, but there's still unnecessary space.

Maybe make a toggle for "ultra compact" to set width to whichever is the minimum.

![thanksbut](https://user-images.githubusercontent.com/46479078/154683918-22195808-f512-4270-8e8f-03e41756399c.png)

**Comment by aptkingston** [comment]
My screenshot above is already using the minimum width without truncating the content. The spacing in there is just the padding around the cells, and in this case the column label is longer than the content, which is why there is space.

You can set any widths you want, so if you really want this you can do it:
![image](https://user-images.githubusercontent.com/9075550/154684698-54e827fe-0033-4c05-bdea-420fe4e5a925.png)

Here I have renamed my column headers so that they are shorter, making the data even more compact:
![image](https://user-images.githubusercontent.com/9075550/154684814-cdb98f4f-922d-4c04-b647-9880da756eba.png)

**Comment by aptkingston** [comment]
I've actually added a new `Compact` setting to address this, and make data even denser. It will reduce the padding around cells and also reduce the row height slightly, so you can fit more data on screen at once.

Here's an example:
![image](https://user-images.githubusercontent.com/9075550/154687262-3412208c-4fcd-4651-bd01-70dbbd701a94.png)

Would something like this solve your problem? You can still customise column widths as well, this is just an additional setting to make data more dense.

When talking about the column size, it will be a in a new drawer setting, where you can choose the order, label and widths of your columns:
![image](https://user-images.githubusercontent.com/9075550/154687499-919567d6-f661-4fa9-8afa-a2e96c21ef4a.png)

There will be extra features as well for cell formatting and colour etc.

For preventing scrolling, you can just delete the "row count" setting, or set it to something huge like 99999 as you say. An empty field is easier though:
![image](https://user-images.githubusercontent.com/9075550/154687839-321a80df-c21b-4722-b6fa-99db0e4d8f40.png)

**Comment by EpsilonCommunity** [comment]
Very useful information, thank you!

How does printing that out preview as, that would be my next challenge, currently the printability is awful, with sizing for an A4 paper having a "zoomed in" effect? (I'm at 100% zoom on the browser -- Nothing special added to the table/data.)

**Comment by shogunpurple** [comment]
Closing this one due to inactivity and updates made both in the new table compact setting and bug fixes around printing

**Comment by EpsilonCommunity** [comment]
> You'll certainly be able to fit more on your screen. Landscape would obviously be a better choice for table data too, depending on how many columns you have.
> 
> Here's my table with the new compact setting enabled: ![image](https://user-images.githubusercontent.com/9075550/154688860-c58fe000-a2e8-4b9b-8663-4148cc2b350b.png)

Could you confirm which settings you have for the table, as I cannot seem to reproduce this will my dataset?

**Comment by aptkingston** [comment]
That screenshot is just using the new "compact" setting on the table and nothing else, with the page rotated landscape.

**Comment by HeronCS** [comment]
How did you make it full page? @aptkingston

**Comment by aptkingston** [comment]
> How did you make it full page? @aptkingston

That's just up to your printer settings. You can set the margin to whatever you want. I used no margin in that screenshot which you can see on the right hand side.

**Comment by HeronCS** [comment]
Appreciate your help. However still unable to reproduce. Maybe it's the Applications setting for the page, as all the content is in the middle?
![image](https://user-images.githubusercontent.com/86607231/161804394-35c16622-720d-4b8a-ade0-ece778512072.png)

**Comment by HeronCS** [comment]
Additionally scale isn't able to be: Fit to Page Width
![image](https://user-images.githubusercontent.com/86607231/161805370-08bb2bea-6b3b-495d-b206-82207879dd02.png)

**Comment by aptkingston** [comment]
You could try making your layout full width:
![image](https://user-images.githubusercontent.com/9075550/161811706-2e57226e-35b0-41be-884b-2f72bf262274.png)
