### ISSUE TITLE
UX issues with new tag component

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#4504]
**Describe the bug**
When using the new tag component, I ran into two small issues:

1. I was unsure what the / meant - not sure if there is a better way to display this, or whether to display it all:
<img width="199" alt="CleanShot 2022-02-15 at 10 30 01@2x" src="https://user-images.githubusercontent.com/49767913/154043739-37fad9f3-cba3-4a52-a25c-15d175a85fbc.png">

2. When you add the delete icon, I'm not sure what to do after that. I get you there needs to be an action, but what action?

**Comment by joebudi** [comment]
P.s i don't think this a bug, but there was 'UX issue' label when creating the issue

**Comment by aptkingston** [comment]
The `/` is a bug - that shouldn't be in the bar at all.

When you add the delete icon, you get another setting:
![image](https://user-images.githubusercontent.com/9075550/154045999-509eb238-25c2-42ae-a18e-e9030937a691.png)

But the `/` thing is a bug - I'll remove that from the bar.

**Comment by joebudi** [comment]
Yes, but what do you do when you click define actions? I could not find a 'remove tag' option - therefore I was unsure how to delete the tag in the preview. I am probably being silly.

**Comment by aptkingston** [comment]
The tag will very likely be bound to some data - so you would update a row, or delete a row, and that in turn would cause the tag to disappear. It's the normal click actions available here, so you can do anything you could do on a normal button press.

**Comment by joebudi** [comment]
Ok, another silly question. Is there any point in the delete icon then?

**Comment by aptkingston** [comment]
Of course, yea. Otherwise you wouldn't be able to trigger any actions...

Think of things like:
- Listing relationships and displaying them in tags
- Listing multi select columns and displaying them in tags
- The EC app, where we use these heavily when iterating over JSON arrays

In all of these situations you would use the delete icon to allow quickly updating the row to remove a certain relationship or value. It's very useful.

If all the delete icon did was remove the tag, what use would that be? It would be purely visual and not update data. That is the only situation where the delete icon is pointless.

When you can trigger any button actions, it's very useful.

**Comment by joebudi** [comment]
Thanks for the response. I get you. It was more around communicating to the user than someone has been removed - user clicks X:
- update row
- remove component

**Comment by aptkingston** [comment]
I understand what you mean, but the update row action would take care of removing the tag automatically - since the reason the row will be displayed will be that it is bound to data.

### Quick example
I have a `Customer` table and they have a multi-select column of `Favourite ice-cream flavours`.
Joe has `Vanilla`, `Chocolate` and `Salted caramel` selected:
![image](https://user-images.githubusercontent.com/9075550/154051693-50baa05c-51e0-4b51-8c4d-19ae245d0c77.png)

I want to display the favourite flavours of all my users.
I use one repeater block to iterate over my `Customer` table, and another repeater block to iterate over the customers' favourite flavours:
![image](https://user-images.githubusercontent.com/9075550/154052278-bc633c69-2e54-4c68-8f5c-a7a02e749981.png)

I want to allow removing flavours, so I add a delete icon and set up an action to update the `Customer` row.
I add a `Save row` action to the "on click" setting of my delete icon:
![image](https://user-images.githubusercontent.com/9075550/154052717-fb0b0395-bfd0-4e68-9033-68f587f734a8.png)

I use a javascript binding to update the array of flavours, and remove the one I want to delete:
![image](https://user-images.githubusercontent.com/9075550/154052797-c577d885-52c2-48f3-858c-2894b416c112.png)

Now I can use my app and press the delete icon on a flavour:
![image](https://user-images.githubusercontent.com/9075550/154052871-45e7def2-e388-43f3-bdf6-6b6364e53657.png)

I can delete `Vanilla`, and it will automatically remove the tag:
![image](https://user-images.githubusercontent.com/9075550/154053002-280913fc-9fbc-4c52-85a1-896059c2e13d.png)

We rely on the automatic hot-reloading of data by the client library to refresh the data that was changed, and in turn update that tags that are displayed. 

I appreciate that this uses JS, and in general is probably more of an advanced feature. It's really powerful though and will definitely be used by power users in more complex apps.

**Comment by joebudi** [comment]
Cheers @aptkingston

**Comment by aptkingston** [comment]
I pulled the fix for the slash into master which has already been released to self-host I believe, and should be pushed to cloud soon.
