### ISSUE TITLE
Card block card width

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#4508]
When I add a wide image to the card block, it increases the width of the card and in the following use case, makes the card look awkward. I have no control over the width of the cards, just the card block so it makes it hard to customize without changing the width of the actual image.
<img width="970" alt="CleanShot 2022-02-15 at 12 57 00@2x" src="https://user-images.githubusercontent.com/49767913/154066765-cbba271c-f4c6-4e05-8a56-56a6af1afeaa.png">
.

**Comment by aptkingston** [comment]
Had a look into this. It's nothing to do with the image setting actually, it's just because the cards in the cards block are a CSS `grid` layout using `auto-fill`, with a min of 300px and a max of 1fr, meaning if the container is something like 800px wide, it will stretch the cards up to be 400px each.

We can remove `auto-fill` and go for `auto-fit` instead if you prefer. I think we maybe had a convo about this before. The tradeoff is just that your cards wouldn't line up nicely with the edge of the block, which makes the search controls and "add new" button look a bit weird, since they're further right than the content.

**Comment by joebudi** [comment]
Ah yes, I do recall. And I suppose we have to use 400px due to the horizontal view

**Comment by aptkingston** [comment]
Is there any action you would like taken here? We used to space cards rather than stretch them, but personally I find stretching much more pleasing to look at.

**Comment by shogunpurple** [comment]
Any action to be taken here? Can close if not

**Comment by aptkingston** [comment]
Was waiting for @joebudi to reply, but I'm still of the opinion that using `auto-fill` is the way to go, which is the current way. But if Joe feels strong we can swap to `auto-fit`.

**Comment by joebudi** [comment]
I don't think this is a major issue, but the last two times I've tried to create a card the auto-fill option has made the card look off (stretched). It's party due to the text clipping.

Also, should there minmax on the card column width? Maybe something like:
grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));

Not sure this is possible due to the horizontal aspect (but I feel these cards should be split :-))

**Comment by aptkingston** [comment]
Yep they do exactly that! The CSS is
```
repeat(auto-fill, minmax(min(300px, 100%), 1fr))
```
The additional `min` statement is there to ensure it shrinks to the screen width on narrow resolutions.

The text clipping will clip to the width of the cards. Here's them at the max possible width:
![image](https://user-images.githubusercontent.com/9075550/159258244-71750eaa-481a-4018-8273-0952031ff9ea.png)

In your screenshot what is the full text? It does look like it's cut off for some reason.

**Comment by aptkingston** [comment]
Ah it's just the default `word-break` not wanting to break in the middle of the word. You must have a long product ID there. I'll add `word-break: break-all` so that it will fill the width before inserting ellipses.
