### ISSUE TITLE
NavigationEditor can't refresh correctly

### ISSUE THREAD

**Issue by MaShiChen233** [Budibase/budibase#4597]
**Describe the bug**
The content of navigationeditor can't refresh correctly when I change the selectedComponent in (builder/app/[application]/design/layout/***)

**Additional context**
In my opinion, we can change "let links" to "$: links" to sovle this problem.
![image](https://user-images.githubusercontent.com/52853629/154899726-bf84c963-d16d-47c1-9a5a-285d2ee8b77d.png)
This code is located in packages/builder/src/components/design/PropertyControls/NavigationEditor/NavigationEditor.svelte

**Comment by aptkingston** [comment]
Hey @MaShiChen233. Whenever you change the selected component, the entire settings panel will remount. In `builder/src/components/design/PropertiesPaenl/PropertiesPanel.svelte` we key the entire settings section by the selected component ID:
```js
{#key componentInstance?._id}
```
So whenever you change component, the entire panel remounts and it works correctly. If we didn't remount then you would be correct - we would need a reactive statement there.

Currently everything works as expected though so I'm not sure what the bug is here. Whenever I change layouts the links update properly. Changing the selected layout should also cause the navigation editor drawer to hide itself - does this not happen for you?
