### ISSUE TITLE
Error appearing in the design screen

### ISSUE THREAD

**Issue by FlaminWrap** [Budibase/budibase#4690]
**Describe the bug**
When designing forms I get these error messages and the form component I am trying to update reverts to it's original state or a state with some changes applied. 

**To Reproduce**
I am unsure how to replicate it, but here is a guess.
1. Create a BB DB.
2. Create a bunch of columns.
3. Create the default views that contain the :id view and the /new/row view.
4. Start changing things on the form (e.g. change margins, paragraph contents, colours, labels, etc.).
5. The errors should start appearing.

**Expected behavior**
To be able to edit form components without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/97764630/155692239-6639308b-95f3-467d-8245-2a6bac5720eb.png)

**Additional context**
Doing the modifications again normally works.
BB Version: 1.0.73

**Comment by aptkingston** [comment]
Hey @FlaminWrap. These are just conflict errors, which means you're making changes too quickly and the builder isn't keeping up. This is either due to a slow server or a slow browser (or a combination of both). If you wait slightly longer between changes then this won't happen. Are you using the cloud version or self hosted?

**Comment by FlaminWrap** [comment]
Good to know. I think I was having internet issues at the time as they have disappeared now. The environment is self hosted.
