### ISSUE TITLE
Per record access controls

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#4789]
I would like to be able to assign access to 
1. Individual records
2. All child records of an individual record

e.g. consider the table structure
```
Clients has many Invoices
Clients has many Users
```

I would like my clients' users to be able to see their own record and all of their own invoices without giving them access to the entire invoices/clients table.

This has been asked for many times, and would greatly increase the uses for Budibase.

It would be **incredible** if we could apply this feature to both SQL and Budibase DB rows.

**Comment by CartCaved** [comment]
It would be similar to the Row Based Security model that can be used with Power BI, I guess.

**Comment by bachi76** [comment]
We really _need_ this, or many use cases are not do-able with Budibase.

**Comment by matteoveglia** [comment]
Yeah agreed, this is vital for my use-case where I want some users to be able to see some data and others not due to security restrictions on some content.
It seems a bit wild that the only way around this would be to create a new set of the same tables per-user.

I've also looked into just using a relational db like MySQL but then Budibase doesn't support the blob type and I need to have thumbnails per table row on one of my tables.
Kind of stuck here and will start looking at other platforms unfortunately

**Comment by ConorWebb96** [comment]
Going to close this out as I believe the new [user](https://docs.budibase.com/docs/users-1) column basically solves this.
