### ISSUE TITLE
Rethink Builder "Frontend"

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#48]
# Budibase Frontend Rethink

## Current Scenario in Brief 

You may not have to read this bit, don't get hung up on it.

Currently we have 3 concepts

1. Components that are imported from a component library. e.g. the "Budibase Material Design Library"
2. Components that the user creates (listed down the left of the builder). The user will create a component "Based on" a library component (i.e. from No.1 above).
3. Pages. The main point of a page is to point to an "Entry Component"... a component from No.2 which will be loaded when the app starts. All other components would be a child of this one.

## Proposed

We have the following concepts instead

1. Components that are imported from a component library. e.g. the "Budibase Material Design Library"
2. Pages. A page will point to a "Root Layout"- see No.3 below (naming up for grabs). A page is actually a an entire front end - i.e. a Single Page Application. In case you are wondering, the use case for having multiple pages is as follows
   - Initially we have 2 pages. "Main" and "Login". When you are not logged in, you will be served "Login", otherwise you will be server "Main". This simplifies the apps SPA that gets created as we dont have to have an "Are you logged in?" workflow in the "Main" SPA. 
   - A future use potential use case is the ability to serve different front-ends to different users. E.g. Consider a Football Pitch Booking App. You can server one app to the staff of the company that owns the pitches, and a different app to their customers, who want to book a pitch.
3. Root Layout. This...
   - defines what gets initially loaded into the index.html, when the app loads
   - controls all other "Screens" (see No.4 below) that are displayed
   - describes a basic layout of the app... e.g. a "Left Nav", and a footer, with a company name and copyright guff.
   - controls URL fragments - i.e. routing
4. Screens. At any one time, one screen is displayed in the app (loaded into the root layout). This is where you start adding components (from No.1), to create the various parts of your app. This is the lowest level of.

### Notable omission

We now no longer have the ability to create our own "components" from the builder (No.2 above, in the current solution).

This means that we are not able to create a reusable "Primary Button", which (for example) previously was simply a "Button" with the `class` property set to `btn btn-primary` 

When the user wants a primary button, they will have to create a new "Button", and add the class every time they need it.

This does not rule out implementing a feature like this in the future.

----

![UI Concepts](https://user-images.githubusercontent.com/3524181/71896977-1d2db900-314d-11ea-9a18-fbd2fbf833e5.jpg)

**Comment by joebudi** [comment]
I like it. 

Why do we not have the ability to create components anymore?

Would I be right in thinking the following is the hierarchy:
Root layout > Pages > Screens > Components

CRM App Example
Root layout = Left hand nav, grey background, fonts, colors,  grid system.
Pages = Login page, main page, 
Screens = deals, contacts, leads, customers
Components = table, button, record

**Comment by mjashanks** [comment]
You are correct, in everything execpt that the hierarchy would be Pages > Root Layout > Screens > Components

Why we cannot have comonents... underneath, "Screens" will become what "User Components" (No.2 old way) used to be.  Screens will be the lowest user defined concept... and a screen will not be allowed to contain another screen.... this simplifies screens.

Later, we can re-add this concept.

For now, it will mean that any style customisations (e.g. "All my primary buttons are read" must be done inside a css stylesheet, and linked). Not ideal, but acceptable for V1 IMO.

**Comment by mjashanks** [comment]
![image](https://user-images.githubusercontent.com/3524181/71835163-c9699400-30a8-11ea-9a44-830012cd1b2a.png)

@joebudi  maybe ou could come up with something better here...

Im trying to workou where the "Page Layout" goes. It really belongs to a Page... so in the pic above, ive sketched it as a "Layout" tab, when you select a page

**Comment by DigiJo** [comment]
Should pages not go above screens?

**Comment by mjashanks** [comment]
Logically, yes.... as that's the heirarchy order. However, screens will be used more, so thats why i put them there. Do you still think Pages should be on top ?

Here is another question...

Should screens be reusable between Pages? i.e. Should 2 different pages be able to use the same screen ?

If not, then maybe they should not live in the same nav. I.e. maybe we should have to select the page to see the screens? Pages = tabs along the top ?

**Comment by Conor-Mack** [comment]
1. Page Layout convention may confuse users
Instead of "Page Layout" would  "App / Root / Master Layout"  be a more appropriate naming convention for the "common always visible" part of the application. When a user thinks of a page, they probably think in terms of one standalone page like in a newspaper without realising the dynamic nature of web apps these days (I've got a non-technical user in mind here), whereas this element of Budibase is more global than that.

2. Using SPA as a convention may confuse non-tech users
I know you were going to go for page layout over SPA anyway but I thought I would note my thoughts on this. The naming convention of "SPA" may please technical users but may add unnecessary complexity for non-technical users. Everybody understands intuitively what an App is but not everybody may understand what an SPA is.

3. Page / App / Root Layout - Could this ever be changed dynamically?
My understanding is that a Page / Root Layout is a master screen of sorts that holds common components like nav and footer. Would there ever be a time when a user would want to hide this part of their application or maybe add some more items to it? (if for example it included a nav element that they wanted to change dynamically based on the active screen - maybe too complex for now but just a thought).

4. Can a user save reusable composite components of their own creation?
A thought that crossed my mind. The very basic building blocks of components become more useful whenever they are added together into a composite element that can be reused by a user. If this is the case then it leads me to my next point below.....

5. The Components category could be a very wide range
Its easy to understand the distinction between App Layout, Screen and Components, but its hard to make distinctions within the component category itself. Seems like components could range from the most basic building block of a Budibase application (which to me would be an element from a component library like an input, textfield etc.) but what about composite components which are built from multiple basic building blocks tied together with some sort of layout? ). Would it be intuitive for these to also be known as components or should they be called something else? I quite like the distinctions made on the component level (without the chemistry naming conventions) in Brad Frosts [Atomic Design Methodology](https://bradfrost.com/blog/post/atomic-web-design/) where he talks about atoms, molecules and organisms . Maybe a basic component could be known as an "element" and a composite component comprised of multiple elements and a possible layout could be known as a "component"?

6. Are Layouts also Components and how will they be implemented?
It seems like layouts could be given their own category within the app. I see that a root layout will have a layout defined which acts as a sort of "master screen" but what about layouts on the level of screens (maybe allowing the user to split up a screen into different sections) or components? (allowing a user to define a row or column layout for composite components).

**Comment by mjashanks** [comment]
> would "App / Root / Master Layout" be a more appropriate naming...

i do prefer that name. I thought maybe "Page Layout" ties it into "Page" (its parent) more... but yes

> Using SPA as a convention may confuse non-tech users..

i dont really like "SPA" - i prefer Page... but dont like Page that much either, for reasons that you stated in point 1 (about the dynamic nature of web apps)

>  Everybody understands intuitively what an App is
Agreed. But then, we are already using "Application" higher up... i.e. you can create a Budibase Application, which refers to the Backend and Frontend together :/

> Page / App / Root Layout - Could this ever be changed dynamically
Yes. In fact, the user wil always choose what layout they want (it will be a component from a library). Examples they could choose
- Left Nav / Top nav, etc - with optional properties for "Header" and "Footer"
- App drawer (hamburger menu)
- Empty (i.e.  just a <div>)

So, any type of component could be written for this - including one that changed depending on some application state. 

> Can a user save reusable composite components of their own creation?
The current (old) design allows exactly this. The proposed design removes this feature - in order to simplify the whole thing (see "Notable Omission" on the original post). This can be re-added in the future.

> The Components category could be a very wide range
Yes you're correct. A component could be an <input> , or it could be a Kanban board. In the propsed solution, these would both be written in normal code, as a comonent library, and used through the builder.

RE the user composing their own components using the builder... this was peviously possible, but this solution removes it. We can come up with a better solution in the future.

I have never heardof Atomic Design Methodology. That terminology sounds lovely! Will check that out.

I think this is something we revist in the future, if it raises its head as a priority.

> Are Layouts also Components?

Yes! I think they are components (from component libraries) that get labelled or tagged as "page layout" , thus allowing the builder to present a list of only layout components, when creating a new page layout.

Note that I said "Page Layout" components. As "Layout" components are ones that can be used inside screen to position other components.

**Comment by joebudi** [comment]
Layout thoughts:

Do we use CSS grid as a standard across the builder?

Does every component need a defined CSS grid area? This will lead to a lot of nested CSS grids.

Can the user edit the CSS grid properties?

**Comment by mjashanks** [comment]
> Do we use CSS grid as a standard across the builder?

Theres a deeper question here. Do we make "Layout" as standard across the builder. The current mechanism for creating a grid layout inside a component..
1. Add Parent Component
2. Add child component of "Grid"
3. Define grid columns and rows on your "Grid" component
3. Add child items items into Grid

To make "Layout" an in-build standard, the mechanism would be
1. Add Parent Component
2. Set Parent's "Layout Type" to "Grid" 
3. Define column and rows on the parent
4. Add child items to parent

Other "Layout Types" could be 
- "Block" (every item stacked on top of on another)
- "Inline" (every item in a row - with wrapping options)
- "None" - the component itself is responsible for layout its own children.

This will make a simpler builder, but a more complicated client library (which is fine ccos thats hidden)

> Does every component need a defined CSS grid area

No - if we handle the grid layout as standard, its really not much extra effort to also handle other types of alternative layout

> Can the user edit the CSS grid properties?

we should expose all options of a CSS grid, in nice, easy to use controls (eventually). As a first step all of them can be Inputs e.g. where we would type "auto auto 1fr 300px" (for a "Template Rows") property.

**Comment by mjashanks** [comment]
#19 Should also be covered by this
