### ISSUE TITLE
Screen properties in code are a bit mixed up

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#484]
working with screens, in the codebase is quite confusing, due to the JSON properties being a bit mixed up. Probably  a good ide to tackle this with #338 

Currently a screen looks a bit like this:
```
{
  name: "13caeead476d4770a1626a10a3066a2a",
  props: {
    _instanceName: "My Screen",
   _id: "13caeead476d4770a1626a10a3066a2a",
  ......
  }
}
```

A few things that are weird with this
1. The `name` property is the same as `props._id`
2. `props._instanceName` is the readble name fo the screen (feel like this should belong n the screen root

I feel like we should restructure this a bit...

```
{
  _id: "594d966dda5e4976a8bd5ed21cfe445a/",
  name: "My Screen",
  props: {
    _instanceName: "Container",
   _id: "13caeead476d4770a1626a10a3066a2a",
  ......
  }
}
```

I.e.
1. The screens name should live on the root of the screen - not belonging to it's root component
2. The screen should have its own id, seperate to the root components id
3. The root component's _instanceName should just be some default component name (and displayed anywhere)

**Comment by Conor-Mack** [comment]
I may be able to offer some insight into this.....

`props._instanceName` was introduced by one of my recent PRs for adding the ability for the user to name a screen or component from the settings view. I figured since a screen is a component then there would be no point in having a separate name property existing at the screen level. 

This allows us to set and edit names without having to introduce a different name property convention between components and screens.

Part of this was also setting the file name of screens to be the `_id` property. This keeps them unique and also means filenames aren't getting changed whenever the name gets changed.
