### ISSUE TITLE
Moustache - When using {{{ context ... }}} urls get encoded

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#491]

**Comment by mjashanks** [comment]
I have been having a look into this.

The issue that we were facing with this was, when we bind to a field that is a url .. `{{ context.url }}`  ... mustache produces something like `https:&#x2F;&#x2F;www.google.com&#x2F;` - an encoded url.

So, we want to disable escaping - which we can either do by;
- writing `{{{ context.url }}}` when we need to NOT escape
OR
- disabling it globally for mustach - so that it never gets escaped.

Never escaping is fine for us 99% of the time, as our svelte components will be sanitizing input for us anyway.... i.e. usually not a security risk (e.g. script injection)

The one instance where this is a problem, is with the `Embed` component. This component allows unsanitized HTML, and is a very useful components... e.g. for YouTube embeds, or Airtable etc etc.

The combination of unescaped binding expressions + the Embed component is s nasty security risk - allowing end users to inject scripts.


My feeling is that we should
- disable mustache escaping globally... so that `{{ context.url }} ` will produce an unescaped url
- document the use of `Embed` with a security warning
- Aim to lookout for any common use of the `Embed` component, and replace with a specialized component... e.g. an "Aritable" component... or a "Video" component

**Comment by shogunpurple** [comment]
Nice summary @mjashanks.

I don't think we want to include a security warning - that's scary for users and there are ways to prevent or at least drastically reduce the risk of an XSS vulnerability.

Ee can probably just use https://github.com/apostrophecms/sanitize-html to do sanitisation for us when using embed components - this should prevent any unsanitized HTML being stored on disk or in the DOM.

I agree that we should have specialised components where possible, but an embed is essential and we must include it.

**Comment by mjashanks** [comment]
I ended up having a look to see how mustach is sanitizing strings.... see [here](https://github.com/janl/mustache.js/blob/4b7908f5c9fec469a11cfaed2f2bed23c84e1c5c/mustache.js#L78)

it's just doing a simple replace of some characters.

I reduced the list of characters that we are escaping to `<` and `>` only. I believe this does what we need. If anyone needs these 2 characters, they can still use `{{{  }}}` .
