### ISSUE TITLE
Inputs should have a min-width

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#4973]
**Describe the bug**
I'm not sure this is a bug but I think it would be nice if inputs had a sensible min-width. This would ensure they 'wrap' on small devices.

![CleanShot 2022-03-21 at 11 00 00](https://user-images.githubusercontent.com/49767913/159248291-5821442f-e805-4e23-ba7d-5ae27b628e22.png)

**Comment by aptkingston** [comment]
If you enable wrapping in your container then they will wrap - they only shrink like this if wrapping is disabled. Even if they all had min widths here they still wouldn't actually work unless wrapping is enabled on the parent container, because they'll just overflow and be hidden.

Defaulting wrapping to be enabled is a different matter though, which would fix this but would need investigated in case it caused other issues.

**Comment by daawaan** [comment]
@joebudi you can use sections in this case found in layout -> sections. there's a three-column option where it will automatically wrap the items for you if the screen size is in mobile
