### ISSUE TITLE
Add new automation to send HTTP requests

### ISSUE THREAD

**Issue by alrik11es** [Budibase/budibase#4990]
**Describe the feature request**
Add new automation to send HTTP requests. I don't know if this is planned/talked or not but I think that it is an important feature. With this you can connect almost any service.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/249844/159327026-a16215e1-0a74-44f2-b1c4-c9704bf87a7e.png)

**Comment by mike12345567** [comment]
Hi @alrik11es - this can currently be done already, using the `External Data Connector` - this allows you to execute a datasource query.

You can setup a REST datasource and some REST queries that way, following our docs on the REST UI [here](https://docs.budibase.com/docs/rest).

We do it this way so that you have access to the full suite of features that our REST connector offers - we previously had a very simple HTTP automation step but it performed poorly as there were a lot of options that couldn't be set.

**Comment by alrik11es** [comment]
A little bit counter-intuitive. Docs need to explain this better. Anyways thanks for that fast response.
