### ISSUE TITLE
Grid System Container/Screen Config

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#501]
**Goals**

* A better way to lay out budibase applications and create custom layouts
* Get rid of the completely custom flex/grid properties, replacing them with an intuitive experience

Budibase users should be able to select layouts for their screens, either at screen creation or configurable at the screen level. For example:

* Sidebar layout
* 12 Column Layout

This would prevent the user needing to use so many CSS properties in the design panel, and allowing users to create beautiful layouts with very little CSS or coding knowledge.

**Features**

* A custom experience to build grids and layouts in the builder
* A modal/selector for screen layouts. Either at screen creation or in the settings panel
* Ability to change layouts on screens
* Needs to be responsive

https://spectrum.adobe.com/page/responsive-grid/

**Comment by mjashanks** [comment]
BUMP!

We have opted for a non-DnD, non-Canvas approach. This is because we feel like mobile/responsiveness will be easier in the future. I agree with this approach. 

However, laying things out is very awkward - and nowhere near as fast as retool and others. It's a frustrating experience right now - If I had no CSS experience, I would be lost.

**Comment by shogunpurple** [comment]
In my mind there are two ways to look at this, each of which are a separate body of work:

- Allow layouts to use "slots", provide some good layouts by default, then allow people to harness the full power of CSS to customise them and create new ones to their hearts content
- Make the **whole** layout system simpler. Think in terms of grids and columns, stripping back quite a few of our existing design properties

### Slots
This would provide ultimate flexibility and make budibase very powerful for creating totally custom layouts. The default layouts would be responsive and you could create "sub-screenslots" that allow you to put certain elements into them.

- A lot of engineering work required
- Total flexibility
- More likely the community will create them due to their complex nature?

### Simpler Layouts
This would involve implementing design properties on a screen or layout specifically for the layout of that screen.
OR
A _specific component_ for layout templates
OR
Add these properties to the "Container" component

Regardless of the option above, you may set a "rows" or "columns" property on the component, and that would then be shown in the builder preview. You can then add components to the layout, and override how many rows/columns that they span.

For example:
- I add a screen/container/layout template component
- I set "rows" prop to 3
- I set "columns" prop to 3
- I add some elements as children
- The elements know they are the child of a layout template, so will inherit props to override how many rows/columns they span
- Configure your layout as required

I think this options provides strong flexibility also, with less engineering effort and a more intuitive UX.

Thoughts?

**Comment by rr559** [comment]
- - [ *_[[@]()]()_**

**Comment by rr559** [comment]
- [ ] - 08y

**Comment by shogunpurple** [comment]
No
