### ISSUE TITLE
"Add Fake Data" Datasource Option 

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#5017]
As a user starting an app from scratch, I want to be able to add a fake table with some dummy data to my budibase internal DB, so that I can get using the platform as soon as possible.

Spec: https://docs.google.com/document/d/1oCV3m9dT3WZho45Tp-E_bRRbyVMzAZvjmmgky4JYwtg/edit#

**COS**
- When user clicks "Budibase DB" they will be presented with the option to use fake data
- If they select this option, create a fake table called "Example" filled with a portion of fake sales records from the sales CSV
- Run test against 3 options (Example, BBDB, External)
- Use images in the example data

**Events**
- Add an event `budibase:fake_data_selected` to track usage

**Designs**

Journey:

1. User creates a new app from scratch
2. We show the popover to select which data source they want to use
3. The user selects Budibase DB
4. We show the new step to allow the user to start with blank table or use example data
5. User select to use example data, we create a table called "Example" filled with a portion of fake sales records from the sales CSV, then take them into the design section

XD - New step - https://xd.adobe.com/view/9ffa3893-516a-4f5e-b9eb-fbd6debd1da5-caa9/

**Comment by daawaan** [comment]
@shogunpurple i think an integration with [Mockaroo](https://www.mockaroo.com/) would be great since they already have APIs for it and I'm always using it when populating my tables during development by importing from CSV. 

The only problem is it is being saved and persisted into the same database for production. Either a development database with the option to populate and persist fake data is always generated alongside the production database with a matching schema when developing the app, or fake data matching the schema of the current data provider is generated on the fly for every client during development instead of querying from the production database so long as the fake data switch is on.

Personally, I'd prefer the former option since you'll be able to actually test how the data changes during testing & development from multiple clients. The only problem is it might not sound good for the cloud hosted version since only a maximum of 1000 records are allowed for each app and there are always two separate databases for one schema. On the other hand, the latter doesn't require additional space but it is only good for designing and seeing how data is displayed, since the fake data is generated on the fly and changes aren't persisted and saved for every other client.
