### ISSUE TITLE
Issues with templates that include a public form

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#5103]
All templates that include a public form seem to be broken right now, in 3 separate ways

1. The table that is being inserted into has Basic write access. It should be Public. I assume that the template's table was public when saved
2. The public form's schema is set to the "Create" and the schema is set to the correct table. However, this causes an API cal to `/api/tables/<id>` which fails due to a permissions error. Changing the schema to `Custom` allows the `Save Row" to work however...
3. Right after the row has saves, a  call gets made to `/api/tables/<id>` even though there are no other actions in the sequence
4. If the form has an attachment (e.g. the Applicant Tracker), then initial uploading of the attachment just fails. It's just not possible.

**Comment by aptkingston** [comment]
I tried the applicant tracker template there, and it correctly has public write and basic read. Were you seeing basic access for both?

Copying and pasting message from discord:
technically i actually think basic read with public write is correct - you don't want any old public user being able to see all applicants (using applicant tracker as an example) 
but then yea i understand of course why that would cause the 403 when trying to fetch the schema
with both public read and write, any public user could read all applicants (eg get their emails and contact details) and then be able to even update them
i sometimes wonder if schemas should be under protection or not... i guess it is slightly sensitive info sometimes
updating the form schema to custom fixes the error from popping up since it doesnt need the schema, and theres no downside to that (for creating) other than its harder to maintain in the builder since the form fields arent linked to the available fields from the table

**Comment by aptkingston** [comment]
Just realised that tables that do need public read do not have it - e.g. the vacancies table for the job applicant tracker. Missed that initially.

**Comment by mjashanks** [comment]
Honestly, I think the way we do public forms is all wrong. I think it should be simply a form with a completely custom schema, that sends all of its data to an automation, which then writes to the tables.

**Comment by shogunpurple** [comment]
@mjashanks I like that idea - it effectively removes the concept of completely public read/write. We also don't account for public, tenant based read/write in the budibase API either so it wouldn't affect that.

> But.... building this flow is a bit of a pain.
This says to me that the flow there should just be automated. If you have a form with a (or even regular) schema, you should be able to create a new automation from the button action of the form, and check an option to have it read the schema of the form to create an app action automation with a`Create Row` step.. with all the values filled in. This is a common flow regardless, so it might be nice to introduce a feature to accommodate it

**Comment by mike12345567** [comment]
> @mjashanks I like that idea - it effectively removes the concept of completely public read/write. We also don't account for public, tenant based read/write in the budibase API either so it wouldn't affect that.
> 
> > But.... building this flow is a bit of a pain.
> 
> This says to me that the flow there should just be automated. If you have a form with a custom (or even regular) schema, you should be able to create a new automation from the button action of the form, and check an option to have it read the schema of the form to create an app action automation with a`Create Row` step.. with all the values filled in. This is a common flow regardless, so it might be nice to introduce a feature to accommodate it
> 
> Downsides though:
> 
> * Automations are async so your write might fail and you won't know in the UI
> * It's just something else to think about and a concept to teach
> * It's not what the user expects

The downsides here make it a bit difficult to actually recommend implementing it this way, but I do think we could have a synchronous automation execution - we already do this for previewing/testing the automation so theres no reason we couldn't do this for a real execution in a published app as well. I think it could be quite beneficial to support this, I could see us adding something to the button action modal to generate a public write automation and wire it up to the button, simplifying this flow significantly.
