### ISSUE TITLE
Filter Binding Issues

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5105]
**Describe the bug**
Value Filter type applies binding instead of taking literal value.  

**To Reproduce**
1. Create new app. New table with column expression.
2. Add two rows. One with value `{{ add 1 1 }}` and another `2`
3. Add default new screens for table
4. Define filter to '/expression' Data provider.
5. Add filter: | Expression | Equals | Value | {{ add 1 1 }}
6. Save
7. Only the `2` value is shown, instead of the `{{ add 1 1 }}` expression.

**Expected behavior**
Value should not interpret handle bars. So I should be able to filter on exact string match `{{ add 1 1 }}`

----

This next bug is specific to a new column on the User table. But hopefully the first bug fix will sort this as well. 
See this discussion for further reference: https://github.com/Budibase/budibase/discussions/5029

**Describe the bug**
When adding a new column 'tenant' to the user table, and attempting to filter a Data Provider with `{{ Current User.tenant }}` the filter is not applied until it is removed and re-added.

**To Reproduce**
1. Create new app. New table: **Tenants** with column Name.
2. Add two rows: A, B
3. Add a column to the default **Users** table: tenant (with value A)
4. Add default new screens for **Tenants**
5. Define filter to '/tenants' Data provider.
6. Add filter: | Name | Equals | Value | {{ Current User.tenant }}
7. Change the type to 'Binding'
8. Save. See that the Filter is not applied.
10. Remove the filter. Save.
11. Re-do steps 5 -> 8, but this set the type to 'Binding' before entering `{{ Current User.tenant }}`. 
12. The filter should now work.

**Expected behavior**
Shouldn't have to re-add the filter to use the Current user binding.

**Comment by aptkingston** [comment]
Issue 1 is correct but I do think it's extremely unlikely that a user would encounter it. You can escape HBS expressions by prefixing with a `\` (i.e. `\{{ add 1 1 }}`, but it will still be subject to our internal processing and come out as `{{ all (add 1 1) }}`. I think we should probably update our processing to fully ignore expressions prefixed by a `\`.

For issue 2, there isn't actually a bug here but it visually looks like there is. If you manually type a binding for a value and then swap the type to a binding, the binding is not actually valid. This is because behind the scenes, when you configure a data binding the saved value is not what is displayed in the field. For example, if you want a binding of `{{ Current User.name }}` then the real data binding that is saved is `{{ [user].[name] }}`. When data bindings are displayed, we convert them to and from these readable versions. So if a binding is created outside of an input that supports bindings, such as when "value" type is selected, the literal string is then sent up as a binding which is invalid.

That's a bit hard to explain but hopefully it makes sense. The reason an empty string is sent up is because the binding is invalid and not converted properly if it was created outside a component that supports them. What we could maybe do for 2 is run that conversion whenever the value type changes, so that in the very rare occurence that someone does this, it would probably still work.

**Comment by melohagan** [comment]
Ah that does make sense. I mentioned the first bug because I thought it would impact the second, but I agree it's a very unlikely scenario. 

For the second bug, I think it still would be a good idea to run the conversion when the type changes from Value -> Binding. 
It is an edge case, but when it does happen, it's not obvious that you need to remove the filter/binding and re-add. 

Another possibility could be to remove matches on "{{ % }}" when switching between the Value and Binding types. 
That way the user is forced to re-add the binding and generate the correct syntax.

So if you had **Value:**  *Hello, {{Current User.Name }}*, and then switch to **Binding** would give you just: *Hello,*

**Comment by aptkingston** [comment]
I'll give it a shot here because I think just manually running the conversion when swapping from value to binding could be a quick win.
