### ISSUE TITLE
[CLOUD] Cannot pass data to query through public API

### ISSUE THREAD

**Issue by PedroHase** [Budibase/budibase#5117]
**Describe the bug**
When trying to call a query through the public API that creates a new record in an external MySQL database, the passed parameters/data will not be passed along to the bindings (bindings do not get populated and fall back to their default values).

For my query setup, see the `Screenshots` section.

I am trying to call the API like this:

```bash
curl --request POST \
     --url https://budibase.app/api/public/v1/queries/<QUERY-ID> \
     --header 'Accept: application/json' \
     --header 'Content-Type: application/json' \
     --header 'x-budibase-api-key:<APIKEY>' \
     --header 'x-budibase-app-id: <APP-ID>' \
     --data '{"name":"testuser"}'
```

The API call is successful and the default values from the bindings are inserted, but the passed body (in this example `{"name": "testuser"}` is not used to populate the bindings for the SQL query.

**To Reproduce**
1. Create a new external MySQL data source
2. Create a new query that creates a new record
3. Add bindings to the query
4. Try to call the query from the public API with data for the bindings
5. See that bindings do not get populated with the passed data

**Expected behavior**
When calling a query through the public API, it should be able to pass parameters/ a json body to it that will populate the defined bindings.

**Screenshots**
Query settings & Bindings
![image](https://user-images.githubusercontent.com/73759210/160279955-fcee3f30-bde9-42b0-8db8-4399231accfc.png)

Fields
![image](https://user-images.githubusercontent.com/73759210/160279970-690955ef-51bf-426b-8a80-7470600a09db.png)

**Desktop (please complete the following information):**
 - Version: Budibase Cloud

**Additional context**
I also noticed that complex handlebar expressions as laid out [in the documentation](https://docs.budibase.com/docs/bindings#chaining-helpers) does not work and the raw string will be passed instead, e.g. I tried splitting `name` to extract first and last name through `{{ split (name " ") 0 }}` and `{{ split (name " ") 1 }}`, but both expressions were simply passed to the SQL query as strings causing the query to fail.

**Comment by mike12345567** [comment]
Hi @PedroHase - this is a flaw in the documentation, you need to put the parameters you want to pass into the query under the `parameters` key in your body. I'll update the docs to state this - sorry about that.

We do this as there are other props for some datasources (like REST, it supports pagination) which can be passed into the body and aren't used as parameters.

As for the handlebars expressions, not so long ago we made the decision to remove Handlebars advanced expressions from queries because they were causing a lot of problems for people as there is no real editor for handlebars at the minute. We decided that they weren't very beneficial in the situation, since if you were calling it from a screen/automation within Budibase you can transform your inputs, in the case of calling from the public API, you can transform the inputs with bash, JS, Java, Python, whatever language/framework you are using to call the API. There has been some discussion around implementing Javascript transformers for inputs on queries, but there really hasn't been many requests for changes in this area so we haven't added anything to the roadmap for it as of yet.

**Comment by PedroHase** [comment]
Thank you @mike12345567, much appreciated! I almost figured that would be the case :)

And thanks for the information on the handlebars in the queries! If this isn't already in the docs, I think it would be a good idea to point out that limitation.

**Comment by mike12345567** [comment]
Hi @PedroHase - closing this as the docs have been updated now.

Yes will need to add that to the docs as well, will sort that - thanks for the suggestion!
