### ISSUE TITLE
Specifying percentage as map height doesn't work

### ISSUE THREAD

**Issue by Topener** [Budibase/budibase#5128]
**Describe the bug**
There currently is no way to enter a non-absolute value as the map height

**To Reproduce**
1. Customize a map component
2. Set `100%` as the map height
3. Doesn't work, it resizes to 100px

**Expected behavior**
A screen-filling map experience

**Comment by aptkingston** [comment]
The height style does support relative heights (including `100%`) but if you have the map inside a small data provider, it will only fill the data provider! Because we can't set the height of a data provider, I would recommend using a fixed height like `100vh` if you want a full height map (or add a large container, and then use 100%).

**Comment by Topener** [comment]
Awesome, that explains it. I'll close this ticket for now
