### ISSUE TITLE
Dropdown in component props panel to bind values to other components

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#513]
#486

#### Dropdown In Component Prop Selection
In component props, you can then select to bind the value of a component to the value of another component using a dropdown. This dropdown will add values like {{ someComponent }} to the prop input when clicked. Mustache interpolated values should have different styling than regular text.

**Comment by mjashanks** [comment]
Note - we should consider how the builder behaves when we delete a component that is the target of binding

**Comment by mjashanks** [comment]
in the `components.json` (where we define components and their props), we shall add 2 new properties:

## Bindable

`"bindable" : "<propName>"`

This allows us to name a property which can be bound to - so that we know where to take the "value" from. We were considering the following
- A checkbox may have a "checked" property, whereas an input may have a "value" property. Or a table component may have a "SelectedRow" property, that we may want to pull info from
- In future, a component may need multiple "bindable" props... e.g. a Table may have "SelectedRow" and "SelectedCell". if we need this, then we can allow `"bindable" : ["SelectedRow", "SelectedCell"]` .... but this is not to be implemented now

## Context

`"context": "<model/view prop name>"`

This allows us to name a property which is used to select a view/model. Using this, we are then able to list out the fields belonging to the selected model.

Considerations
- We discussed simply detecting whether a component had a `model` property. However, some components have a model property, and dont provide context ... e.g. Table and Charts.
- We felt that explicitly naming the property catered for different naming ... "model", "view" - and for the possiblity of components having multiple datasources.... e.g. "Totals View", "Data Model"

## UI

We agreed that we would proceed on the basis of the mockups below

## Text binding - to apply to all props on the "Settings Panel", of type "string"

![Stories - 1-way binding of text component](https://user-images.githubusercontent.com/3524181/89026400-9165bf00-d320-11ea-9c7a-aac539a7d631.jpg)


## 2-way input Binding (where an input is able to set the value of something else)
![Stories - 2-way input binding](https://user-images.githubusercontent.com/3524181/89026309-62e7e400-d320-11ea-8d5d-537512c6217e.jpg)
