### ISSUE TITLE
Allow multi-select as a search column for table blocks

### ISSUE THREAD

**Issue by aidenmitchell** [Budibase/budibase#5144]
**Describe the feature request**
This was mentioned here: https://github.com/Budibase/budibase/pull/3249
> You can't currently search on attachments, multi-selects, relationships or formula fields.

Ideally, searching on multi-selects could be added, as it helps with tag-based organization.

**Comment by tailorck** [comment]
Is anyone else getting an issue where the search column drop down is not populated?
<img width="242" alt="image" src="https://user-images.githubusercontent.com/7613002/162985233-4342d171-65ef-453b-a41a-f4fff4582928.png">

**Comment by aptkingston** [comment]
> Is anyone else getting an issue where the search column drop down is not populated? <img alt="image" width="242" src="https://user-images.githubusercontent.com/7613002/162985233-4342d171-65ef-453b-a41a-f4fff4582928.png">

This is technically a bug, but you're using a custom query for your datasource so it means that we can't do any searching for you. I'll push a fix though that will list the "readable" schema here because we can do fake client-side searching on your data at least, even if you're using a custom query.

**Comment by shogunpurple** [comment]
Fixed in https://github.com/Budibase/budibase/pull/5369
