### ISSUE TITLE
Using the key `type` in a JSON field array breaks schema generation

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#5205]
**Describe the feature request**
Currently if you have a JSON column, you can only setup schema for the top level fields. It would be useful to be able to map additional fields to a nested path.

Use case: https://github.com/Budibase/budibase/discussions/5189

**Screenshots**
| Schema | Resulting fields |
| -------- | --------------- |
| ![Screenshot 2022-04-01 at 11 18 56](https://user-images.githubusercontent.com/101575380/161244819-ec37eedd-fbd5-453d-aadb-a730f98c8158.png) | ![Screenshot 2022-04-01 at 11 19 58](https://user-images.githubusercontent.com/101575380/161244957-3cb9a35b-1e1e-4824-b974-78af97bfe109.png) |

*I would like to see the **type** field in the resulting fields, or have a way to add a field mapping to it*

---
| Form | Options Picker |
| -------- | ------- |
| ![Screenshot 2022-04-01 at 11 22 40](https://user-images.githubusercontent.com/101575380/161245362-3f8ce17c-2814-4d57-a776-bf615fb02e6f.png) |  ![Screenshot 2022-04-01 at 11 26 41](https://user-images.githubusercontent.com/101575380/161245974-b21330ac-2bd8-4c0b-8c88-363ad15b4fff.png) |

*I would like to be able to select the **type** field in here*

**Comment by aptkingston** [comment]
I was puzzled by this because this does work. After debugging for a while I realised this is an edge case bug where using the key `type` breaks it, as we use `type` in the schema to mean the type data for each field, and this is used to determine the full schema.

If you use any other value than `type` it will be fine. e.g. I updated to `foo` and here it is working:
![image](https://user-images.githubusercontent.com/9075550/161250821-e9fa280b-82a0-4d7d-b851-30aae621e34e.png)

**Comment by melohagan** [comment]
Ah brilliant, cheers! I would still consider this a bug because 'type' is still a valid JSON object field:

```
let obj = {
	devices: [{
  	"type": "Laptop"
  }]
};
console.log(obj.devices[0].type); >> "Laptop"
```

Easy to work around of course.

**Comment by aptkingston** [comment]
Oh yea definitely a bug! Or well I think more of a limitation haha, but I'll see if i can get around it. The logic for all this stuff is already very complicated. At least it does still work in general!
