### ISSUE TITLE
custom MySQL query with order by issue

### ISSUE THREAD

**Issue by samg666** [Budibase/budibase#5395]
Hello,

I found a similiar issue as #5187 on custom SQL query. My query is something like `SELECT * FROM view_bills WHERE BillDesc LIKE '%{{Keywords}}%' ORDER BY {{OrderBy}}`, and the variable `OrderBy` is a dropdown list with options like `id DESC` or `name DESC`,  this query work just fine on v1.0.9x, but after upgraded to v1.0.1xx, as Budibase has changed the parameters handling, it will treat the variable as string then automatically added single quote, the query sent to MySQL was `SELECT * FROM view_bills WHERE BillDesc LIKE '%keyword%' ORDER BY 'id DESC'` while the expected correct query should be `SELECT * FROM view_bills WHERE BillDesc LIKE '%keyword%' ORDER BY id DESC`.  

@mike12345567 Could you please help to take a look on this?

**Comment by mike12345567** [comment]
Hi @ggs331 - the use of dynamic identifiers in queries through Budibase has been restricted for the time being, statements like `order by {{ sort }}` cannot be considered valid due to the security implications of them - we are currently discussing internally as to how we could support this, for now you'll need to change your query to something like:
```sql
select * from Persons 
order by 
  CASE WHEN {{ sort }}='id DESC' THEN firstname END DESC,
  CASE WHEN {{ sort }}='id ASC' THEN firstname END ASC
```
We realise this is somewhat non-ideal if you have a very very dynamic scenario, we are looking into ways that we can support this safely - but for now you'll need to use something like the above statement to utilise dynamic identifiers in SQL queries through Budibase.

**Comment by hawkinsjon** [comment]
@mike12345567 I'm curious, in a scenario like the one you guided above:

```
select * from view_bills
order by 
  CASE WHEN {{ sort }}='id DESC' THEN firstname END DESC,
  CASE WHEN {{ sort }}='id ASC' THEN firstname END ASC
```

What settings would one put on the datasource so budibase didn't attempt to apply its datasource, sort settings to the already sorted results? Or will the budibase datasource sorting component be irrelevant if a sort command is found in the query? 

In other words, I'm troubleshooting a similar issue myself and it would be helpful to know which sort (the SORT BY in the custom sql query) or the sort in the datasource component is used. Or maybe both?

**Comment by mike12345567** [comment]
Hi @hawkinsjon - the sort options within the data provider don't apply at the query level, Budibase does not know how to apply these to say SQL, a DynamoDB query, a REST request, so instead that sorting is carried out in the frontend end based on whatever data is returned in the response. For queries you need to write your sorting/pagination yourself and pass the required parameters to the query.

**Comment by hawkinsjon** [comment]
That's good to know, thanks Mike. 

Given I'm having all of my sorting and filtering of a given results set done at the query level, how can I deselect the sorting and limit options in the Budibase UI?

For example, in the screenshot above, how could I prevent this results set from being sorted by column `id` and order `ascending` if all of the sorting I need is already being done at the query level?

Maybe the BB UI does nothing if it sees a sort or sort order in the query? My guess is that's not accurate because I believe I see it still sorting results no matter what.

**Comment by hawkinsjon** [comment]
That's good to know, thanks @mike12345567 

This leaves me with just one question. What settings should I set to Budibase to so that it leave the already sorted results alone?  The problem I'm running into now is that my **sort column** and **sort order** settings in the Budibase UI are applying sorting to my already sorted results set.

Here's a more specific example. My data provider is running a query that ends like this:

<img width="695" alt="Screenshot 2023-03-14 at 5 59 06 PM" src="https://user-images.githubusercontent.com/3512179/225150411-2c7d9971-3626-47c8-afde-fa14cf1b4966.png">

The results from this query directly are perfect, exactly how I need them to be. The problem is that I am forced to select a **sort  column** and **sort  order** in the BB UI.

<img width="247" alt="Screenshot 2023-03-14 at 6 01 49 PM" src="https://user-images.githubusercontent.com/3512179/225151604-1855b792-b6f1-40d3-839f-b589a2e6094b.png">

When BB Data Provider component sorts on top of sort instructions that are carried out at the query level, the results get funky. Is there a way to essentially disabled the BB Data Provider component sort order, sort column, and limit settings?

**Comment by hawkinsjon** [comment]
@mike12345567 as a quick update I found this dummy column work around from @mjashanks and it works perfectly. If I can +1 or vote for a setting in these drop downs that allows the BB user to disable the front end sorting attempts, that would be outstanding!

https://github.com/Budibase/budibase/discussions/2947#discussioncomment-1458450

**Comment by mike12345567** [comment]
Hi @hawkinsjon - sorry for not responding earlier - that is a good workaround for now - I've raised this to the team that looks after data provider settings, there has been some discussion about this, adding an option to disable sorting is being looked into.

**Comment by hawkinsjon** [comment]
@mike12345567 no worries at all and thank you for your consideration and help. 

_FWIW Mike, I (as I'm sure many in the community) are very appreciative of your time when you have it to share but never feel so bold as to expect it. 

It's incredibly motivating watching the BB team build software with this energy, quality, opinionated no-code/low code design, everything...

You all should be proud of this rhythm you've developed over time. This level of software development reminds me of a small period of time when I was able to work with Pivotal Labs (NYC). You guys have it right now, don't loose it and know that when you do have time for a little support and chatting with the customer base, it's seen as a luxury by us, not an expectation._

**Comment by mike12345567** [comment]
@hawkinsjon - thank you so much for the kind words - I've passed them along to the rest of the team as well - you've made our day!
