### ISSUE TITLE
Frontend - Component Layout

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#54]
## Tone of this issue..
Just a note to start. This is all up for discussion, anything written below is a "general direction".

## Overview
Layout & Positioning are fundamental concepts that can be applied on every level of a web UI hierarchy.

We would like to make some layout & positioning properties applicable to all components in a stack, regardless of what those components define in their "props".

## Definitions (naming open to suggestions):
**Layout**
This defines how a parent component lays out its children (hence only applies to components whose `children === true || children === undefined`)

As an example, 

```
button  (parent)
-- icon (child)
-- text (child)
```

We could define this button as having a `grid` layout, with 2 columns.

**Positioning**
This refers to how a component is positioned _within its parent_ . This could include properties such as `padding` and `margin`

e.g. If the parent's layout is `grid`. We should be able to set `column start`, `column end`, `column span` etc.

## Layout Types

Something we need to think about, but `grid` should be the first, and our primary focus. We want to mirror CSS grid here.

Other options **could** be 
- `inline` (stack components in a row) (named `row` maybe ?).
- `block` (stack components in a column)

## Implementation
Below is a rough mockup... designed to give you a general idea. Please innovate, based on other styles!

![Builder Frontend - New frame](https://user-images.githubusercontent.com/3524181/72941280-78c08f00-3d68-11ea-91df-061a2bdeef14.jpg)

We don't have to worry too much about what properties are actually settable... this should be easy to change as we go along.

What's more important is how these layout definitions are applied at build-time and run-time.

### 1. Output in screens (JSON) file

currently a screen file looks something like:

```
{
  "name": "Edit Customer",
  "props": {
    "_component": "@budibase/standard-components/div",
    "_children": [ ...components ],
    "className": "some-class",
  }
}
```
I suggest that we add another "special" property to `props`, called `_layout`, which contains the layout **and** positioning definition (am open to having a `_positioning` also) ...

```
{
  "name": "Edit Customer",
  "props": {
    "_component": "@budibase/standard-components/div",
    "_children": [ ...components ],
    "_layout": {
        "type": "grid",
         "columns": ["1fr", "auto", "1fr"],
         "margin": ["10px", "10px", "10px", "10px"]
         ....etc
    },
    "className": "some-class",
  }
}
```

### 2. Applying to an app

These layout options ultimately represent static css.  So, we need to somehow apply styles to the nodes in the DOM. This is a bit out of my experience, so I am not going to make suggestion on how to do this - i know others have opinions :)

However, for some direction, the creation of components at runtime are done in `packages/client/src/createApp.js` ... in the `_initialiseChildren` method (this method is curried and used to create `hydrateChildren`, `insertChildren` and `appendChildren` ).

**It would be nice** if we could convert the `_layout` member to css at buildtime, so we are not calculating at runtime. "building" is done in `packages/builder/src/userInterface/pagesParsing/buildPropsHierarchy.js`

**Comment by pngwn** [comment]
This looks good.

**UI**

Regarding the UI, layouts and position are quite challenging because the layout definition is in the parent but the individual position of an element is defined in the child. This can cause problems for users because they have to hold the layout they defined in the parent in their mind while positioning the child. This could mean a lot of trial and error on their part or a great deal of context switching between the two components.

We could solve this by showing the user the grid they defined in the parent whenever they are in a child that is affected by it. Then we have the additional issue of showing both a grid wireframe and a bunch of controls/inputs at the same time, I'm not sure we have the screen real-estate for this.

One solution would be to combine both and simplify the position controls. Instead of a series of inputs that take a number value, we could provide an interactive UI that both displays the grid defined in the parent and allows the user to select the position of the current element within it. It could fit within the sidebar and I don't think it would take up much more space than the separate inputs (could also be collapsible/toggleable). It also wouldn't really require any knowledge of css-grid (although defining the grid layout in the parent would).

I drew an image to explain:

![position](https://user-images.githubusercontent.com/12937446/72974090-5fe6c680-3dc6-11ea-9825-a4d6e5318e89.png)

I imagine this like those widgets in google docs to define the rows/cols of a table. Could be click for start position + click again for end position or more of a click + drag.

**Implementation**

 I don't see any real need to separate layout and positioning internally, while they are semantically different from a users point of view, they are all just CSS definitions when it comes down to applying them. It will probably be simpler to treat them all the same at a lower level.

When it comes to applying styles to an application, the ideal scenario would be to turn them into static styles/stylesheets as there are more opportunities for optimisation there. Directly setting the element's cssText is fast, scoped and would definitely work with very little runtime. css-in-js seem overkill here since these are set-and-forget static styles, and cij solutions come with a hefty chunk of runtime to handle dynamically changing styles.

**Comment by mjashanks** [comment]
I like your grid selection idea (time permitting ?)

> I don't see any real need to separate layout and positioning internally

agreed. I actually think we should just call the member `_style` - as i have a feeling we will put more in here in future.

>  ...the ideal scenario would be to turn them into static styles/stylesheets..

makes sense to me

**Comment by pngwn** [comment]
[Quick PoC for the grid thing](https://svelte.dev/repl/3c1ad3f6e36f403e93d2b729e124ab04?version=3.17.3).

I don't think it would be too much work to implement.
