### ISSUE TITLE
SQL query for IN state with string is not working

### ISSUE THREAD

**Issue by Kanary159357** [Budibase/budibase#5411]
A change in the way SQL parameters work has made the SQL ... WHERE something IN {{ values }} impossible.

Discussed in https://github.com/Budibase/budibase/issues/4978
cc. https://github.com/Budibase/budibase/issues/3863

Hi, I'm using cloud version of budibase that is 1.0.110

It seems that budibase currently work on IN hotfixs, and there is problem when using IN with string value

```
select * from tableA
where method in {{array}}
```
and array is     
```Alex, Jin```

And then I have this error
```Query results empty. Please execute a query with results to create your schema.```

when I do a query with direct value

```
select * from tableA
where method in ('Alex', 'Jin')
```
It works well

Is there anything I miss?? Or is this budibase's error?

**Comment by mike12345567** [comment]
Hi @Kanary159357 - I believe this maybe due to whitespace in the binding, we split the binding into variables that can be injected into the SQL query, so `Alex, Jin` will split into `'Alex'` and `' Jin'` - if you could remove the whitespace from your query to confirm the issue that would be great.

I'll also update Budibase to trim whitespace on the variables as that's a better/less confusing default.
