### ISSUE TITLE
App preview failed to load due to violated Content Security Policy

### ISSUE THREAD

**Issue by archeopternix** [Budibase/budibase#5680]
**Hosting**
- Cloud
  - Tenant ID: kouri 

**Describe the bug**
Using Google Chrome: Version 100.0.4896.127 (Offizieller Build) (64-Bit).
Created a fresh project from the templates. When switching to the Design tab an error message on screen will be shown:

```
App preview failed to load
An unknown error occurred
```

Error within the JavaScript console:
Refused to load the script 'http://13.226.132.103:6080/php/urlblock.php?args=AAAAcgAAABAmG9Zp0dayZN7U~8NABCDMAAAAEK2FE5NW5l~XIgyo~OQFb58AAABCAAAAQmtOFOoTyPFmrO7g6dBwdwGxQ6caQ3HhA_VlJze9FFlS9kf2qHH2QLGg7z~ykwKT5EB~UlsmnPVIpwbU3XSYv1LCFg==&url=https://cdn.budi.live%2fapp_kouri_33fab9e910284d68a499e14796ebe20a%2fbudibase-client.js%3fv%3d1.0.110' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.budi.live https://js.intercomcdn.com https://widget.intercom.io". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**To Reproduce**
1. Created a fresh project from the templates (any template shows the same effect). 
2. App will be loaded - you are on the 'Data: tab
3. Click on the 'Design' tab
4. Menu, Icons on the header for adding 'Blocks', 'Layout' .. is shown
5. in the app preview section the error message will be shown (See error)

**Expected behavior**
My expectation is that the app preview is shown

**Desktop (please complete the following information):**
 - OS: Win 10 Enterprise
 - Browser Google Chrome: Version 100.0.4896.127 (Offizieller Build) (64-Bit).

**Additional context**
just started playing around with templates

**Comment by melohagan** [comment]
Seeing a similar issue for exporting table data: https://github.com/Budibase/budibase/discussions/5683

**Comment by shogunpurple** [comment]
Hi @archeopternix - our CSP is locked down to only allow client side calls to `https` domains for security. I have no idea what that ` http://13.226.132.103:6080/php/urlblock.php?....` URL is - it seems like this is being injected somehow into your client (possibly a corporate requirement or something). I did an IP lookup of that address and it's in Germany. 

We would have to whitelist that IP address directly for that to work - which we won't do in our production environment. Seems like this is an environmental issue with the network/environment where you are running budibase cloud, rather than a bug in the platform.

**Comment by archeopternix** [comment]
@shogunpurple - thank you very much. I will reach out to my IT Sec team
