### ISSUE TITLE
Workflows - contextual awareness

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#580]
There are some UI updates that are required in the workflows section of the builder in order for it to be more useful to our users.

- Users need to be able to use moustache syntax in their workflow steps, they should have a binding dropdown that allows them to bind to the value of a previous workflow step
- Removal of client side workflow steps
- Removal of workflow orchestrator from client library

**Comment by aptkingston** [comment]
Points 2 and 3 have been completed.

Point 1 will be handled when we've got our new automation system up and running, since that will then be able to define exactly what outputs are available to bind to from previous steps.

**Comment by aptkingston** [comment]
I'll detail here a few of the other UI changes as well since this issue originally was for UI:
- [ ] Mustache syntax for workflow block params
- [ ] Remove client side workflow steps
- [ ] Remove workflow orchestrator from client
- [ ] Align workflow block param inputs and make visually consistent
- [ ] Add proper binding of workflow state when editing workflows, so changes are visualised in real time and discarded when not saving workflows
- [ ] Add animations when adding and removing blocks for better UX
- [ ] Make workflow builder scrollable
- [ ] Add visual selection state when selecting a workflow block
- [ ] Remove deprecated "test" workflow tab, and instead add button to trigger workflow to the main "setup" tab when viewing workflow

**Comment by aptkingston** [comment]
A few more features as part of contextual awareness:

- [ ] Allow binding to block outputs using mustacche syntax
- [ ] Validate mustache bindings via block numbers and block definitions
- [ ] Use new block definition structure to render param input fields
- [ ] Allow combination of binding to block outputs via mustache and free typing for accessing deeper properties within block outputs whenever the outputs are generic objects or arrays

**Comment by mike12345567** [comment]
https://www.loom.com/share/8eea5a59bb314ee7871824368d12160b
And the email:
![image](https://user-images.githubusercontent.com/4407001/93620312-b518bd80-f9d1-11ea-9588-f91981ba6815.png)
