### ISSUE TITLE
Backslashes in App URL

### ISSUE THREAD

**Issue by Havock94** [Budibase/budibase#5831]
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 1.0.99

**Describe the bug**
Backslashes in App URL settings get ignored on save.

**To Reproduce**
1. From builder dashboard, open an App menu and select Edit
2. Type an URL with pattern `/app/with/path`
3. Click on save
4. Select Edit again, URL is now `/appwithpath` 

**Expected behavior**
Opening the app redirects me to `/app/with/path` if paths are allowed, or show an error on save if they're not allowed

**Screenshots**
While saving
![image](https://user-images.githubusercontent.com/7635248/167896323-dc25ce90-6aee-4b73-84e3-5cfd0769081a.png)

After saving
![image](https://user-images.githubusercontent.com/7635248/167896400-8dbc5b05-e3ea-49ac-ba53-ec893e0b17da.png)

**Comment by Havock94** [comment]
Just for completeness, I tried editing the URL to `/app/path` to make the app navigate to `/path` on load (I couldn't find any other ways to change the homepage URL)

**Comment by aptkingston** [comment]
Hey @Havock94. 2 things - firstly those are forward slashes rather than backslashes, not that it really matters. But secondly, we don't support slashes in the base app URL like you've noticed so we should sanitise them out before saving like we do with other invalid characters. Then at least it would be obvious that we don't support it.
