### ISSUE TITLE
Async Workflow Blocks

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#586]
It could be beneficial to move the workflow steps out of the server code and into somewhere we control.

We could store workflow definitions in a remote server that allows people to select them from their builder.

See budibase/packages/server/src/api/controllers/workflow/index.js.

**Comment by mike12345567** [comment]
Technical design
-----------------
After some discussion we have come to some conclusions as to how we will achieve async loading of automate actions that are not pre-builtin to the system.

The process by which the actions will be made available to the builder/production server is as follows:
1. A separate repo, likely called `budibase-automation` will be created, which will be a monorepo containing all of the actions as separate packages.
2. Each action will be a complete package in and of itself, they will be required to have a standardized entry point, a `automate` property in their `package.json` specifying the block definitions and a `README.md` describing their functionality and any useful information.
3. During a new release each package will be built into a full bundle and compressed into a tarball, the `automate` section of the `package.json` will be extracted and the `README.md` will be lifted out.
4. All of the `automate` properties will be combined into a large list of the automation options that are available, including the `README.md` which will be used in the builder to display information about the packages. This will be known as the `manifest.json`.
5. The manifest and the tarball'd packages will be uploaded to an S3, the manifest will always overwrite so that there is only a single one at the root of the bucket, the latest one and the packages will be written to a directory as such: `<${stepId}>/<${version}>` as extracted from the package definitions. This means that all previous packages will still be stored for future use if required.

After these steps are complete a builder application will be able to pull the manifest on load of the automate section of the app, allowing it to list packages which the user can retrieve. The user can then select a package which will be downloaded and installed to their builder. The definitions will be extracted from the manifest and inserted into the automate definitions - which the server will then use later on.

When the system is deployed to production we have two choices as to how we load the packages:
1. Installed at build time, when preparing the package for deployment to prod we pull down all packages from the bucket and include them in the build. This could increase the size of the docker image significantly (due to size of `node_modules` in each one).
2. Load the packages in an async manner similar to how it will work in the builder, however in this case we would be loading the actions as we need them. When a automation reaches a point that a loaded action is needed we would retrieve it and the flow would wait until the package has been loaded. This would be the easiest method but would likely cause us to run into some issues, pipelines which are fairly time dependent could be slowed down once every now and then while the package is being loaded.
3. Instead of installing at build time we could have an internal process to the prod server which periodically polls the `manifest.json` and downloads any packages which it does not currently have (running once immediately on startup in a prod environment).

@shogunpurple It'd be great to hear your thoughts on the section above, to some extent discussing this might be a little pre-mature optimization, while the second option would be the quickest to get implemented as we have to build it anyway for the builder I'm concerned that time constrained automation could have a problem with this, would like to hear your thoughts on it.

Package example
-------------------
Here is an example of the `package.json` that each action must have.
```
{
  "name": "@budibase/automate-send-email",
  "version": 1.0.0,
  "automate": {
      "stepId": "send-email",
      "description": "Send an email"
      "tagline": "Send a email from {{inputs.from}} to {{inputs.to}}",
      "type": "ACTION",
      "icon": "ri-mail-open-fill"
      "inputs": {
          "from": {
              "type": "string",
              "label": "Send from"
          },
          "to": {
              "type": "string",
              "label": "Send to"
          },
          "subject": {
              "type": "bigstring",
              "label": "Subject",
              "default": "Hello from {{context.company}}!"
          },
          "body": {
              "type": "string",
              "label": "Body"
          }
      }
      "outputs": {
          "result": {
              "type": "string",
              "label": "Email send result"
          }
      }
  }
  "dependencies": {
    "svelte": "^3.18.1"
  }
  "scripts": {
      "start": "node index.js"
  }
}
```

**Comment by shogunpurple** [comment]
@mike12345567 this all sounds great to me - this model is something we should probably use for most of our "multiples" in future.

As for this:
`When the system is deployed to production we have two choices as to how we load the packages:`

A variation of option 3 is a potential solution. The production servers should have **all** of the workflow blocks installed so that it can run any application workflow once deployed. 

We could possibly "auto-install" the bundles somewhere on release, either through an S3 trigger or just by manually uploading them somewhere (an EFS volume maybe?) that would provide persistent storage to the docker containers running in AWS. This way, we wouldn't have to bundle them with the docker image.

**Comment by mike12345567** [comment]
Yeah, mounting an EFS volume directly is probably a pretty good solution, my concern with that is that when we come to self hosting customers this method will be very hard to configure for them and its a fairly integral component of the system.

We could use some like FUSE with [this](https://github.com/s3fs-fuse/s3fs-fuse) - which would allow us to mount the S3 bucket directly to the docker container when it is running and it will cache modules as and when they are added to the bucket. Once issue with that approach is that each docker container will make its own copies of everything in the bucket, so if we had a lot of packages you'd end up paying a fair amount for EBS attached to them. Nice thing about a solution like that is its platform agnostic, as long as the S3 is public any system could connect to it and read the packages to their local system - just checked as well and it does work with [read only access to the bucket](https://github.com/s3fs-fuse/s3fs-fuse/issues/525).

**Comment by aptkingston** [comment]
Regardless of how we want to make them available to the production servers, I think it's wise to do as much work as possible at build time to minimise the time taken to download and use them both in the builder and in production.

I've got a monorepo up and running with some test automations, defined using the syntax which has already been pasted above. I quite like the idea of actually bundling the automations at build, and storing a lightweight minified version. I'd even say that we could bundle in all dependencies at this step and output a single file for each automation, which would make using them lightning quick. I realise storing dependencies will increase the size of each bundle, but the time gained from not having to install dependencies in the builder or production server will make acquiring and using automations extremely quick. We're also not planning to have hundreds of these initially and S3 storage isn't exactly expensive for a few hundred kB so I don't see a problem with bundling dependencies - I just see it as shifting more of the time effort to the build step.

I've set up my test repo with lerna, purely to speed up installing all dependencies at build time and take advantage of its depduping of packages.

Here's the flow I propose for working with this repo.

### Building automations
 - Use lerna to install and dedupe dependencies for all automations
 - Run node script to discover and prammatically bundle each automation (so far rollup didn't work very well, and parcel worked but isn't able to correctly import modules which both have an ESM and CommonJS entry point, so I'lll try webpack next).
- Automations should be built and exported as CommonJS modules
- Run node script to parse each package.json in the automations and build a manifest file indexing all automations

### Publishing automations
 - Run node script to push manifest and each bundle to a S3 bucket via the node AWS SDK
 - Configure a GitHub action with stored secrets to publish on each change to master

### Using automations
 - Fetch the current manifest
 - Fetch any required automations using the stub defined in the manifest - e.g. `https://production-url.com/send-email@1.0.5.bundle.js`
 - Since the automations will be exported as CommonJS modules, they can easily be `required` as needed
 - Managment of "installed" automations is super easy since each automation is a single file
 - Since there are no build or dependency installation steps when using automations, I'd expect this to be extremely snappy

### Future improvements
There's some easy optimisations which could also be added down the line when the number of automations grow - such as fetching the current manifest at build time and only building and publishing any automations whose versions have changed, but I see that as a bit of a premature optimisation at the moment.

Automations could also be tar'd and compressed, but again I don't see that being necessary until we have some massive automations where the reduction in transmission size is meaningful, because it also adds another layer of inconvenience to use them.

**Comment by shogunpurple** [comment]
Thanks for the detail @aptkingston - totally agree with this approach and the key points you mentioned around bundling workflows:
- Single bundle per workflow, including dependencies
- Managing monorepo with lerna for separate releases
- Installing automations by pulling the entire bundle down **including dependencies** to the users local builder. (I wouldn't worry about dependency duplication here either - since they are run on the server side, we don't care about bundle size)
- GH action to automate the build and deploy of the manifest and bundles to S3

The bundler we use doesn't really matter a whole lot, happy to use either webpack or rollup - both should have a fairly light configuration for a simple bundle like this. Also, do we need to programmatically bundle the workflows? Since they will be separate packages, could we just add NPM scripts to each package that will run before publish?
```
"prepublish": "npm run build:prod"
```

@mike12345567 FUSE looks like a nice solution as well actually - EBS isn't expensive either, however they can only be attached to one instance in one AZ, meaning the more we scale out our fargate cluster, the more that replication is going to cost. EFS volumes can be shared between thousands of instances IIRC.

Another thing worth mentioning about EFS is that its really just a cloud NFS file system - a fairly common file system interface. The server side code shouldn't care what the underlying technology is, as long as we mount it at a specific directory. That said, we would have to probably come up with some kind of docker-friendly, cloud agnostic way to run an NFS volume that could be mounted to the app servers, regardless of where they are run.

**Comment by aptkingston** [comment]
@shogunpurple re the programmatic bundling - my preference for doing this programmatically rather than as a standard npm script in each package is just really for consistency. We want to enforce certain opinions on how automations should be built since we need to guarantee compatibility and bundle them the same way. If we wanted to do it via normal npm scripts we'd need to add configuration to each repo which would allow unique configurations per automation which means we can potentially lose our consistency with packaging. I guess it's also duplication which might make it harder if we decide to update part of the bundling or publishing process.

Everything I'm saying there would be null and void though if there's just a way to reference configs above the root folder of each automation - then we could just keep a bundler config file somewhere in the top level repo and have each package's bundler process reference that. Would certainly be easier if this is possible as doing the bundling programmatically is slightly harder. I'll look into this!
