### ISSUE TITLE
[BUDI-7175] [ Builder / Core ] Container Setting "Stack on Mobile"

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#5901]
Having seen this in Wordpress, the Container element could have a Boolean setting "Stack on Mobile".
This is the equivalent of the Conditional UI rule to change the direction of the flex box from Row to Column, but since its such a common thing we do, it would be much easier to have that Boolean setting.

<sub>[BUDI-7175](https://linear.app/budibase/issue/BUDI-7175/[-builder-core-]-container-setting-stack-on-mobile)</sub>

**Comment by melohagan** [comment]
To add to this one, I wonder if Budibase should just do this automatically, because it looks fairly pretty bad if it doesn't.

<img width="1088" alt="Screenshot 2023-06-21 at 12 46 14" src="https://github.com/Budibase/budibase/assets/101575380/24a42131-5d3e-491a-b02c-13ae3b84f8e3">

<img width="647" alt="Screenshot 2023-06-21 at 12 47 19" src="https://github.com/Budibase/budibase/assets/101575380/360d4f78-3a0b-4505-b313-ee5fc3afacea">

**Comment by poirazis** [comment]
hey @melohagan i think you should be able to enable / disable as there maybe times you want to keep two columns on a mob screen.

**Comment by melohagan** [comment]
Hey @poirazis 

Closing this one because I realised you can simply check the **Wrap** checkbox of the container to adapt to a mobile screen:

![Screenshot 2023-07-10 at 10 32 23](https://github.com/Budibase/budibase/assets/101575380/f8f2e6b4-22dd-47d1-8a7c-6a827beb368c)
*Wrap setting is checked for the container*

**Result on mobile**
![Screenshot 2023-07-10 at 10 33 11](https://github.com/Budibase/budibase/assets/101575380/9dae4cd3-864c-407e-99d1-daf0d6dd35f8)
