### ISSUE TITLE
Allow form fields to be repeated with bindable names -- repeater block with array data and text inputs

### ISSUE THREAD

**Issue by Kanary159357** [Budibase/budibase#5944]
**Hosting**

I'm using Cloud version 1.0.110,

**Describe the bug**

I'm using String Array to repeat Text Field Form and there is a problem that the default value is always first item of array.

Repeating value of Label works well so it is not the problem of my logic....

My handlebar value is quite simple. 

```{{ New Repeater block.url.value }} ```

my value is 
```
{
  "url": [
    "naver.com",
    "google.com",
    "hihi"
  ]
}
```
(I'm using Budibase's json column)

<img width="849" alt="image" src="https://user-images.githubusercontent.com/69702813/168947030-bef3b255-9afc-4021-9846-4080f36ccdf7.png">

As shown above, I gave it to label and value each. Label works well but default value shows first value only.

I think It misbehave because repeater text field has same id.... Is there any way to acheive input field repeater?

**Comment by melohagan** [comment]
Good thinking, but how would I save it as a single form?

![Screenshot 2022-05-24 at 16 19 59](https://user-images.githubusercontent.com/101575380/170072137-a6adc58e-9fce-436f-b7c6-e2707fcf4f36.png)

**Comment by NicolasFabre81** [comment]
With this feature, would we be able to dynamically generate form fields, based on a data dictionnary table, and make this big form to  work as a normal one ?
This would allow us to manage bigger apps with bb, because atm it's difficult to work with large tables (> 30 fields)

See, I just made a little poc and my big form generated with its 185 fields (3 nested repeater blocks) ! 
But I think there is no way to have it working ...

<img width="371" alt="image" src="https://user-images.githubusercontent.com/28592069/207375642-527aecb3-7922-4444-88fb-11dcbac6260d.png">
@mielune

**Comment by NicolasFabre81** [comment]
> With this feature, would we be able to dynamically generate form fields, based on a data dictionnary table, and make this big form to work as a normal one ? This would allow us to manage bigger apps with bb, because atm it's difficult to work with large tables (> 30 fields)
> 
> See, I just made a little poc and my big form generated with its 185 fields (3 nested repeater blocks : pages/sections/fields) ! But I think there is no way to have it working ...
> 
> <img alt="image" width="371" src="https://user-images.githubusercontent.com/28592069/207375642-527aecb3-7922-4444-88fb-11dcbac6260d.png">
> 
> @mielune

This issue has been closed, does it mean that what I described above is now possible ?

**Comment by melohagan** [comment]
Hey @NicolasFabre81 

I don't believe so; the OP closed the issue. 

This work is related to this issue however: https://github.com/Budibase/budibase/issues/5658
