### ISSUE TITLE
" SyntaxError: Unexpected token I in JSON at position 0  ". Unable to register to cloud.

### ISSUE THREAD

**Issue by Sagr859** [Budibase/budibase#5950]
This is my first time with the application. So I am trying to sign up to it in order to try it out. But I cant even set up my account.
![Screenshot from 2022-05-18 15-25-43](https://user-images.githubusercontent.com/40241809/169012684-7c94451c-bafb-4d59-b4df-6a9961b6f448.png)
I don't even understand what's causing the issue.

**////////////////////////////////////////////////////////////////////////////
EDIT
//////////////////////////////////////////////////////////////////////////
 It worked in Mac and Windows, this issue is in Ubuntu (v20)**

**Comment by Rory-Powell** [comment]
Hi @Sagr859, sorry to see you are having issues. We've just deployed some additional monitoring around the signup process to diagnose this, would you be able to try again?

**Comment by mehrashiv** [comment]
Hello,
I am running the self hosted version and cannot login due to this error. Do we have any update on the same

**Comment by Rory-Powell** [comment]
Hello @mehrashiv. The error you're describing is being caused by malformed json coming back from a http request, likely as a result of a 500 / internal server error. Can you create a separate issue for your problem and please include the following details
- screenshot of chrome dev tools network tab showing the failing network request
- logs from bbapps and bbworker containers throughout the login process
