### ISSUE TITLE
Repeater copying value to last record

### ISSUE THREAD

**Issue by timmehrees** [Budibase/budibase#6016]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 1.0.110 
  - MySQL latest docker image
**Describe the bug**

I have a repeater, and when I edit any field in the repeater, the same field in the last record reflects the value I just entered in. If I press save on the last record, the new values are written to the database. 

Screenshots below. 

**Screenshots**

![Screen Shot 2022-05-22 at 14 02 47](https://user-images.githubusercontent.com/7864923/169677988-fda93bf5-842e-4697-b70c-a1fff01e9ae4.png)
![Screen Shot 2022-05-22 at 13 54 03](https://user-images.githubusercontent.com/7864923/169677989-b1865d3d-7079-42ed-aa91-58ede4d77162.png)
![Screen Shot 2022-05-22 at 13 54 34](https://user-images.githubusercontent.com/7864923/169677990-f1603351-c71e-4f67-b0f7-24d7a62aa9bf.png)

**Comment by aptkingston** [comment]
Hey @timmehrees. I'm afraid this isn't supported in Budibase - if you put a repeater inside a form and then put fields inside the repeater, your form will have multiple fields with the same name. Forms don't support this, which is why you're seeing this issue.

We can't really prevent usage fo the repeater inside forms as there may be other valid use cases, but we should probably document somewhere that this setup that you have created (fields inside repeaters) won't work.

**Comment by timmehrees** [comment]
Hi @aptkingston 

Shouldn't work, but it does... with slight issues :-)

Any suggestion on a more appropriate way of editing multiple records on the same screen? 

Thanks.

**Comment by aptkingston** [comment]
If you just put the form inside the repeater too, then everything should work properly! Then there's always one form form for each record, which should fix this problem.

**Comment by timmehrees** [comment]
Yep, that's sorted it!

I thought I'd tried that, but its likely I had something else wrong at the time!

Thanks for your help, muchly appreciated!
