### ISSUE TITLE
Modal content is taking time to load

### ISSUE THREAD

**Issue by crohit7** [Budibase/budibase#6066]
**Describe the bug**
Modal content is taking time to load as modal is opened and shown blank for few seconds (2-3 sec)

**To Reproduce**
1. Go to listing page'
2. Click on create new button
3. Modal is opened which having form
4. Modal is taking time to load content

**Expected behavior**
Content should be visible immediately when modal is opened

**Screenshots**
when modal is opened
![image](https://user-images.githubusercontent.com/37010744/170471546-0eacac43-b222-4766-9d5b-129f55894062.png)

after 2-3 secs
![image](https://user-images.githubusercontent.com/37010744/170471871-9db112c1-58ec-4cbf-970d-1796deaade70.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : chrome
 - Version : 101.0.4951.67

**Comment by Klience** [comment]
Confirm that modal takes too much time to load. Around 2-3 seconds indeed.

**Comment by crohit7** [comment]
Modal is getting opened immediately, but modal contents are getting loaded after 2-3 seconds.

**Comment by aptkingston** [comment]
Hey @crohit7. This isn't a bug - it just depends on how fast your connection is and how fast your browser is. When you open a screen modal like that, it's actually an iframe with another full instance of the app running in it. Most of the resources required will be cached by your browser, so the only delay in showing the modal is the initial rendering of the app and pulling down any data you have on your screen.

Is the issue here that you don't want to see the modal until all the data is loaded? Or that there is a delay at all?

**Comment by Klience** [comment]
Hi @aptkingston. I'm not the OP. Though I experienced the same issue. I couldn't understand why the modal's content was taking 2-3 seconds to load (while regular window loads contents instantly). I believe the issue that @crohit7 experienced was the same -- content takes considerably more time to load.

Like the modal is supposed (I believe) to be a quick way to see the contents of a row without opening another browser tab. Though looking through the rows using modals actually takes more time. Considering each row opened in modal takes 2-3 seconds to load.
