### ISSUE TITLE
How do I override the 15 second timeout on the API calls

### ISSUE THREAD

**Issue by CovantaDataManagement** [Budibase/budibase#6078]
**Hosting**

- Self
  - Request: https://covformsdev.covanta.com/api/v2/queries/query_datasource_41c02fc0b95c4cb7a6ed6ec109e9ee11_24b09016614142318f4d5d19a2bd5be3
  - {
    "p_entity": "EN_BABYL",
    "p_operation_date": "2022-05-02",
    "p_enddate": "2022-05-26"
}
upstream request timeout

Waiting (TTFB). The browser is waiting for the first byte of a response. TTFB stands for Time To First Byte. This timing includes 1 round trip of latency and the time the server took to prepare the response.

We are beyond 15 seconds for this one call and that is OK

**Comment by mike12345567** [comment]
Hi @CovantaDataManagement - in relatively recently versions of Budibase you can set the environment variable `QUERY_THREAD_TIMEOUT` on your server services to a number of milliseconds, so for 1 minute you would set:
```
QUERY_THREAD_TIMEOUT: 60000
```

In your docker compose file. This has been around for quite a while, since version 1.0.30ish I believe, so it should work for you!
