### ISSUE TITLE
Problem with editing Link

### ISSUE THREAD

**Issue by cyber-kivi** [Budibase/budibase#6100]
**Describe the bug**
If make View Link with blank screen - it work's uncorrect.

**To Reproduce**
1. Create blank screen
2. Create 3 screens like it is "Autogenerated screens" ( /example0; /example0/:id; /example0/new/row )
3. Put all elements like in case "Autogenerated screens" (Data provider > example Table > Link)
4. Put into Link /example0/{{ example0 Table.example._id }}
5. Make other elements like in "Autogenerated screens"
6. Test it
7. Put a row and click a Link
8. Row clicked is not a row you get

**Screenshots**
![image](https://user-images.githubusercontent.com/106427850/170821135-915aea72-450a-4dd8-99eb-816fb883677b.png)

click on secod row
![image](https://user-images.githubusercontent.com/106427850/170821179-2b382c47-6f73-400e-868b-835ca047f1f7.png)

get first row
![image](https://user-images.githubusercontent.com/106427850/170821193-ac061a6c-ec59-4c64-b46c-81166a2a016d.png)

**Comment by aptkingston** [comment]
Hey @cyber-kivi. The link binding you've entered is not valid, which is probably why your link doesn't work. Your binding should just be `/example0/{{ Table.example._id }}` (removing the second `example0` which was inside your HBS expression).

**Comment by cyber-kivi** [comment]
Thank you for quick answer
it was at first:
https://user-images.githubusercontent.com/106427850/170829406-1dfc1831-f179-4831-b36a-b9bb8415a839.mp4

then I change name table and Link now it's not working
https://user-images.githubusercontent.com/106427850/170829426-41944c6f-b8af-4045-99a7-28bae233c08e.mp4

**Comment by aptkingston** [comment]
@cyber-kivi in your first video your links are working fine - the URLs are different. The details screen must not be set up properly because it is not pulling down the correct row.

**Comment by aptkingston** [comment]
Also what data source are you using? Is it an internal table? If you are using a custom query your rows might not even have an `_id` property. Rather than type the binding manually, just select the ID binding when editing the link URL.

Here is a very quick example I just made that works perfectly:
![image](https://user-images.githubusercontent.com/9075550/170830285-7ba9e9db-225b-4f4a-970e-8b955ceebc0d.png)

Just make sure your details screen is properly using the URL parameter to fetch the row:
![image](https://user-images.githubusercontent.com/9075550/170830324-51805769-396f-4a6f-a3e0-f972948ddad5.png)

In future please use our discussions forum for support like this unless it's an actual bug :+1:

**Comment by cyber-kivi** [comment]
Thank you so much! Now it works correct.
Sorry for wrong label "bug" use.
