### ISSUE TITLE
Not able to display user name in contact person column. only email id is getting displayed there

### ISSUE THREAD

**Issue by crohit7** [Budibase/budibase#6129]
**Describe the bug**
I want to display user name instead of email id in contact person column

**To Reproduce**
1. configure a table with records
2. enable auto column created by
3. there only email id is displayed
4. i want user name there.

**Expected behavior**
there should be provision to display user name / email

**Screenshots**
![image](https://user-images.githubusercontent.com/37010744/171149650-4b120d7a-a019-41c2-a31d-972bc5b0e635.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 101.0.4951.67

**Comment by aderici** [comment]
Hi @crohit7, within the "Data" tab of your application you should see the "Users" table. Within that table can you try : 

* Creating a new column, name it as "fullname"
* Select "Use as table display column"
* Select column type as "Formula" and select "Static" as type
* Enter your formula as "{{ firstName }} {{ lastName }}" without the quotes and as a Handlebars type
* Save

Now you should start seeing firstname and lastname instead of email when viewing mentioned records

I believe this is not a bug but a feature

**Comment by crohit7** [comment]
@aderici thanks for the solution
going ahead what if I want username along with user profile photo.
![image](https://user-images.githubusercontent.com/37010744/174284496-61412adf-49d1-4811-b8ad-f376eb3b5785.png)
