### ISSUE TITLE
MinIO license terms no longer useful for budibase users. 

### ISSUE THREAD

**Issue by anborg** [Budibase/budibase#6188]
### Please move away from MinIO.

Please Note: Minio - has changed license terms. [No longer opensource or free.](https://min.io/pricing)

"Designed for developers who are building open source applications in compliance with the GNU AGPL v3 license and are able to support themselves. It is fully featured. If you distribute, host or create derivative works of the MinIO software over the network, the GNU AGPL v3 license requires that you also distribute the complete, corresponding source code of the combined work under the same GNU AGPL v3 license. This requirement applies whether or not you modified MinIO."

If you customize budibase and add a form; because bb uses minio, **you have to release your org bb-custom-code public! Whether or not you modified MinIO.**

Related: #5587

Consider migrating to some other s3 compatible or more generic so any obj storage could be swapped. AWS/GCP/other

Perhaps this could be an alternative? https://github.com/scality/cloudserver

**Comment by mjashanks** [comment]
Thanks for pointing this out. You've made a good point, which is of some concern.

I have looked in a number of places to understand the application of AGPLv3 and have not found anyone else that agrees that any software that simply **uses** an unmodified version of the software should also be made AGPL.

MinIO uses the phrase 

> This requirement applies whether or not you modified MinIO

This seems to directly contradict the AGPL preamble ([see here in MinIO's license](https://github.com/minio/minio/blob/fd02492cb788c4a9ca1f86d38d9c42126535ae2e/LICENSE#L42)): 

> The GNU Affero General Public License is designed specifically to ensure that, in such cases, the modified source code becomes available to the community

And, [even more specific](https://github.com/minio/minio/blob/fd02492cb788c4a9ca1f86d38d9c42126535ae2e/LICENSE#L223)

> A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or  distribution medium, is called an "aggregate" if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit.  Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

I believe that the Budibase stack is the "Aggregate" here, hence "does not cause this License to apply to the other parts of the aggregate".

Additional reading that further supports this interpretation
- [from the license creators](https://www.gnu.org/licenses/why-affero-gpl.html)
- [on StackOverflow](https://opensource.stackexchange.com/questions/6712/agplv3-covered-work-and-based-on-is-it-really-viral) - maybe not the most reputable, but certainly mirrors my understanding

I would flag something with you though. You said:

> If you customize budibase and add a form; because bb uses minio, you have to release your org bb-custom-code public! Whether or not you modified MinIO

Please note that Budibase is GPLv3 Licensed. If you modify the Budibase source code, you are required to make those changes public. We do offer a commercial license that allows you to avoid this restriction, at a charge.

Also note - any apps that you build with Budibase are not subject to this restriction. You may build closed-source apps with Budibase. The restriction only applies to the Budibase codebase itself.

Again. thanks for flagging this. I believe that MinIO's statement on their website is not inline with the AGPL license, and will have to follow this up.

We had previously talked about abstracting the filestorage component so that Budibase could use non-S3 APIs, e.g. Azure File Storage. This issue might push us to implement it sooner.

**Comment by anborg** [comment]
"We had previously talked about abstracting the filestorage component so that Budibase could use non-S3 APIs, e.g. Azure File Storage. "

Would be great to include all major cloud storage  gcs, aws, azure. 
And a noncloud option ... e.g filestore, if users want to use that locally.

**Comment by mielune** [comment]
Openstack Swift will be a good candidate too :)

**Comment by shogunpurple** [comment]
Since you can configure your datasource through environment variables in budibase and the new license doesn't affect the use of MinIO inside budibase, closing

**Comment by liongkj** [comment]
> Since you can configure your datasource through environment variables in budibase and the new license doesn't affect the use of MinIO inside budibase, closing

is there any discussion link or documents for this ?

> configure your datasource through environment variables
