### ISSUE TITLE
Record Detail View Linked Record Enhancements

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#619]
The Record Detail view needs some work to make it aware of linked records.

### Use Case
- User renders a list of records (say users)
- User clicks a record
- Route changes to /users/:id
- Record Detail view is rendered, showing all the data for that particular user record, including linked records

### Notes
- Columns should be showable/hidable from within the settings panel in the builder
- It should be easy to route to a record detail component from a list component (@mjashanks has some insight here)
- Record detail components should show a list of all their linked records, pretty printed in a list

**Comment by mjashanks** [comment]
A few thoughts on what i think WOULD BE NICE here -  I think there is a wider use around editing of records - and it includes the form component.

Please consider the below thoughts as a brain dump from me.

## Current Behaviour

- The `Record Detail` component is added to a screen - each screen has it's onw URL
- At runtime, `Record Detail` will check to see if there have been any path parameters supplied... like `/customer/:id`
- It will assume that the final parameter is the `_id` of the record, and will fetch that record
- That record will then become available to all components that are children of the `RecordDetail` - and therefor they may bind to that record

## Extra Requirements (IMO)

### 1. Form component should be context aware

Currently, the form component is standalone - you put it on the page, and it will fetch the record itself (based on the same behaviour as the `RecordDetail` component above). Additionally, if the last part of the url is `new` the form will assume that this is a new record, and behave accordingly

Form should be changed so that it is **also** able to use a record that is in context (i.e. when placed inside `RecordDetail`)

(keep reading for why)

### 2. Form component should allow it's "Submit" button to be hideable

keep reading...

### 3. Form component should allow removal and reording of fields

keey reading...


###Why all these form changes ?

We could then combine multiple forms, inside a record detail, to layout a form in anyway we please... with different sets of fields in different places.. and... **crucially** ... 

**the ability to put a table of children in between the end of a form and the form submit button**

This is one form, composed of a bunch of different forms. 

### 4. The `Record Detail` component should support the  `/something/new`, the same as Form does

So that we can have a combined Create / Edit record screen

**Comment by mjashanks** [comment]
It's late and I realise that what I said above is madness.

But there is something more elegant than I have described around the composability of forms that I think we need to solve fairly soon.

Should RecordDetail have a Submit button and be called form?...  then we have a "Fields" component?
