### ISSUE TITLE
pagination not working on tables which use queries or relationship data

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6226]
In my customer account section, There is a table which lets them view all of their jobs.

The table is populated using `Relationships` Data.

I have found that the table only displays the number of entries set in `scroll limit`. if there is more entries than the number set, they will not be displayed even if pagination is ticked.
I have found that I also have this issue if taking the data from a custom query.

I have tried using both the `Table Block` and `Table with Data Provider` same result with both.

**Comment by aptkingston** [comment]
We can't enable pagination for custom queries (since they're custom) - you'd need to write your queries with a limit and offset built in and manage that yourself, which is possible but reasonably complicated. Pagination only works for internal tables or SQL tables because we can control the query syntax.

Using relationships as a datasource also doesn't support pagination at the moment like you've noticed, but it might be possible for us to enable that by changing how we query related data. This would need investigation though.

For now, if you use a separate table and data provider then you can control how many rows are pulled back in the data provider (e.g. all of them), and control how many rows are visible in the table before scrolling, separately. This will just make the table scroll and contain all of your rows. The table block only has a single setting for this, which is why any rows after the `scroll limit` are just chopped off. If you use the separate components you'll be able to see all your data - it'll just be scrollable rather than paginated.

**Comment by PaulMcF1987** [comment]
@aptkingston Would using Budibase DB essentially offer more customisation as it is the internal DB?

If so... is it reliable? Can I access it via HeidiSQL or similar? How do I back up the database

**Comment by PaulMcF1987** [comment]
@aptkingston Would I be right in saying that when using the Budibase DB and setting a `view`, that I have the same issues as above when running my own query?

I have tried using the Budibase DB and cannot seem to make use of Pagination or even row selection

**Comment by melohagan** [comment]
Closing as there are a number of open feature requests relating to this.

**Comment by ashwani3011** [comment]
Hi @aptkingston,
Thank you for your response regarding the limitations of pagination with custom queries in Budibase. 

Could you please provide an example or a more detailed guide on how to implement pagination for custom queries? Specifically, I'm interested in understanding how to structure the SQL query to include limit and offset parameters, and how to manage these parameters within Budibase to enable pagination functionality.

Thanks

**Comment by melohagan** [comment]
Hey @ashwani3011 This answer may help you: https://github.com/Budibase/budibase/discussions/7313#discussioncomment-3430353
