### ISSUE TITLE
Container Height not respected in Design Mode

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#6300]
I have an outer Container , with Height set to 12px and 4 nested Containers again set to 12px.
It works OK in running the APP but in Design Preview it seems the Height property isn't enforced.
Please see below.

<img width="854" alt="Screenshot 2022-06-14 at 11 39 17 AM" src="https://user-images.githubusercontent.com/80512170/173534137-58c29037-151b-41be-8e35-9d320d27f6b4.png">

**Comment by aptkingston** [comment]
Hey @poirazis. It just visually looks wrong in the preview as you've noticed, because we show placeholders for empty containers in the preview. If we didn't show a placeholder in the preview it would be much harder to find and see your containers, since a lot of the time they would be 0px sized until you manually add styles.

We could try and hide the overflow at least, so that those placeholders wouldn't overflow the 12px parent container.

**Comment by poirazis** [comment]
Hey @aptkingston 
I think that placeholders should have a default size (height here) if none is set, but if set respect that value.
This would give a placeholder for empty / unset containers and also follow the dimensions given if they are set.

In my case, the child placeholders do have a set height of 12px so the expected behavior in preview should that the placeholder would respect it ?
