### ISSUE TITLE
Public page/form not working

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#6314]
### Discussed in https://github.com/Budibase/budibase/discussions/6296

<div type='discussions-op-text'>

<sup>Originally posted by **YTDcontrol** June 13, 2022</sup>
I'm working in a self hosted server in a docker container. I´m working on release 195. Followed instructions in documentation, but no matter i do always redirect to uth/login.
Aplication publushed.
Aplication no locked.
screens seted to public.

Answer #4280 nether works for me.

Regards.</div>

Experiencing the same issue. 
1. Create a new App with a **Public** screen
2. Publish app and copy URL
3. In an incognito window, go to the URL - you will be redirected to the login page.

**Comment by Shadowfita** [comment]
I'm going to link our previous discussion and suggest you manually enter the hash into the URL and see if it presents the public form instead of redirecting to login, as that was the issue I was describing.

#6260

**Comment by aptkingston** [comment]
I can reproduce this issue and can confirm it exists, but due to a couple of reasons I'm hesitant to make changes.

Scope of issue:
The issue is only that if a public user requests a URL they don't have access to, that they will get redirected to login rather than redirected to some public URL that they do have access to.
- If your app has `/admin` (admin) and `/public` (public) and you navigate to `/`, you will be redirected to the login page. It would be better if you were redirected to `/public`.
- If your app has `/public` (public) and you navigate to `example.budibase.app/app/my_app/public` you will be redirected to the login page instead of the public screen. This is the issue @Shadowfita is describing and is a separate issue, as this is just how hash based routing works - the correct URL would be `example.budibase.app/app/my_app#/public`.
- If your app has `/public` (public) and you navigate to `example.budibase.app/app/my_app#/public` it works as expected
- If your app has a public `/` route, then navigating to just `example.budibase.app/app/my_app` (without a hash) also works fine

The other reason I'm hesitant to make a change is that this has been signifcantly improved on the new design UI branch, and I don't want to cause more conflicts by changing the same code here. On that branch this issue has already been solved, and if a public user requests a URL that they don't have access to, they will be pushed automatically to a public screen that they do have access to (preferring home screens, a new concept as well).

**Comment by rajat-b** [comment]
Hi, I am a new BB user & after many hours of frustration, I can also confirm this issue.
Although, it is a big relief to know that it is a known bug & not something which is not possible to achieve.

In fact, even if we follow the [how to build a public form in minutes](https://budibase.com/blog/app-building/public-forms-how-to-build-them-in-minutes/) guide to the letter, it fails.


However, I have 2 queries:

1. Can you please tell when is the new design UI branch's public release tentatively expected?
2. In the meantime, I want to proceed ahead with any workaround without URL manipulation. Under that you mentioned:
> If your app has a public / route, then navigating to just `example.budibase.app/app/my_app` (without a hash) also works fine

  In my test app, I only have single screen `/home`, to which I have given public access. Still when I open `http://xyz.com:10000/app/my-app`, it redirects to the login page. Do I need to do something else? How can I set "public / route"?
  
 ---
Also, I do want to mention:

- I am using the docker installed BB, same as for original issue poster #6296 (in case docker install is causing any bug).
- If I use [Business Directory Template](https://budibase.com/directories/templates/business-directory/) on my self hosted version, it works perfectly out of the box i.e. `http://xyz.com:10000/app/business-directory-template` opens publicly without redirecting to login page. But any custom app fails to achieve so.

Thank you.
