### ISSUE TITLE
Filtering by relationship table columns

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#6371]
The relationship option between table sin Budibase, I would say plays an important part in the app structure etc.
A relationship would only be defined between 2 tables if there was a requirement

For that reason, I feel that it would be massively beneficial to be able to search by these columns

For example
If a company has 30 invoices to assign all from different suppliers, need to go into each suppliers /:id page and look through the table on their page (if one is set up) and then go to the next supplier and do the same until all suppliers have been handled.
Either that or scan through the Job table for each job, hut there could be hundereds or thousands to scan through

If there was the ability to filter by supplier (which is one of the relationship columns) that would save a massive amount of time in the above scenario as well as a multitude of other scenarios

**Comment by mike12345567** [comment]
Hi @PaulMcF1987 - this functionality is supported for SQL databases, but cannot be supported for internal tables. This is due to the fact that internal tables are backed CouchDB rather than a relational database, we can support basic relationships but our filtering mechanism is not capable of accessing multiple documents.

A small workaround for this, while not perfect, you can use static formulas to extract values from relationship columns and then filter on the formula column.

Issue #2316 discusses this in a lot more detail.

**Comment by PaulMcF1987** [comment]
@mike12345567 so should I assume that this is something that there is no intention of looking at improving at present?

It doesnt even really need to be the relationship column that is used for filtering...

If another column is created as a formula cell, and the name is pulled from the other table using `return $("column")[0]._name` this should display same name as the relationship column, and save it as a virtual column in the DB.

If there was a vay to make this column filterable that would sort the problem.

With previous software I have used.. Instead of creating a relationship between tables, we were able to link the tables via a Query... essentially there would be a `Text! column in the table... on the form I would add a drop down and the dropdown would be populated via a query... this then populated the table cell once the form was saved.

then in the customers page, I could use a further query to pull entries where the name in cell X matches the name of the customer etc.

The relationship, whilst potentially useful seems as though it holds back the potential of the app.

Is there a reason why this is used and the ability to run queries is restricted?

**Comment by mike12345567** [comment]
Hi @PaulMcF1987 - the ability to run queries is available for SQL based databases as well, we have to restrict a fair amount of things in the CouchDB based tables as they are supposed to be used for simple use cases, this is something that we are working on improving documentation around to make it obvious that for relation heavy datasets SQL based databases should be preferred.

As for the formula cell example you described, this is achievable using the static formula workaround I mentioned, if you create a new formula column and during creation set its type to "Static" as such:
![image](https://user-images.githubusercontent.com/4407001/177181716-571df9d5-0d21-40e6-a4c2-e04ffd7d867a.png)

Then you will be able to extract related data from relationship columns on the table, store it and then filter by it. In the background Budibase keeps the values in the two tables/rows in sync, it is duplicated data rather than a virtual computed column, but this is just due to the nature of CouchDB and our lucene index, there is no other way to achieve filtering than having the data within the document you want to filter.

**Comment by PaulMcF1987** [comment]
@mike12345567 The static formula only seems to be available if using CouchDB, I am using an external MYSQL DB.

I appreciate that the ability to run queries is available, however it is massively restricted which prevents me (and apparantly others) from being able to achieve the desired outcome.

As mentioned... if I could add a dropdown (option picker) to my form and populate it with an SQL query rather than using the relationships that then adds the value to the table as a text column, that would make a massive difference and essentially solve the unsolvable problem that I am coming up against

**Comment by PaulMcF1987** [comment]
@mike12345567 Can I also make sure we are talking about the same thing as I suddenly thought, there are quite a few different `filters` that can be discussed...
I am talking about the `dynamic filter` used to filter a populated table so that I can filter it down to show only data that I need.

so the table could have 100 entries, each with a different sub-contractor. As it stands the sub contractor is held in a different table and linked via relationship...

I know that via the back end, this can be filtered... however in the live app, using the dynamic filter, it doesnt seem to be achievable

**Comment by mike12345567** [comment]
Hi @PaulMcF1987 I've opened a separate issue that describes this problem: https://github.com/Budibase/budibase/issues/6550

**Comment by PaulMcF1987** [comment]
@mike12345567 when adding options to the dynamic filter, it allows me to select a relationship column as a filterable column, however when it comes to actually using the filter, the option is not diplayed.

**Comment by PaulMcF1987** [comment]
@mike12345567  I meant to add, I think there might actually be a ticket already open for this though...

`Defining Filters on the datasource` while it works, it doesnt work overly great... If, for example, I add 3 items to filter by

eg

    ColumnA Not Equals Value X
    ColumnA Not Equals Value Y
    ColumnA Not Equals Value Z

Which should show all values of ColumA except X,Y or Z, however, I have found that if more that one entry is defined in the filter, that at least one of the entries is ignored.

**Comment by mike12345567** [comment]
Ah, @PaulMcF1987 currently this isn't supported, this is a known issue, its quite a complex one to resolve however - there is a separate issue for this though - #2585.

**Comment by mike12345567** [comment]
Yes I'm not sure what the basis of that comment is, the issue has not been resolved by a maintainer.
