### ISSUE TITLE
Select elements around the app are not selecting the first option by default

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#641]
You have to switch options on the select before the change comes into effect.

This can be seen on the:
- User panel 
- Filters

**Comment by aptkingston** [comment]
This was happening with some of the workflow block configs too. The explanation is pretty simple - the value of the select is null, but there is no corresponding `option` with a value of `""`, so the select just renders the first option. This makes it look like a value is selected, but it actually isn't.

If there is more than 1 option then this can be fixed by choosing another option, then back to the one you want. If there is only one option then there's no way for a user to fix this.

The solution is to add a "placeholder" option with an empty value for any select which may not have a value. In cases where we can guarantee the select will always have a value then this isn't needed. Typically I add `<option value="">Choose an option</option>`. The other solution would be to correctly set the initial value to a real value, but personally I believe it's always better to have an empty option to solve this ambiguity. 

I'll update the selects in question here as I'm working on the backend page at the moment already.

**Comment by aptkingston** [comment]
Fixed in the `linked-records` branch - will keep this issue open until it's merged.
