### ISSUE TITLE
repeater checkbox checked unexpected row

### ISSUE THREAD

**Issue by ggs331** [Budibase/budibase#6489]
Hello,

I have a checkbox on repeater and I foud that no matter I check on any row, the last row will be also checked. I am running on v 1.0.206. I can replicate this issue on other app, below is the screen video for your information.

![checkbox issue](https://user-images.githubusercontent.com/29649651/176192864-421d759f-aad4-490c-affa-9933c8d48e21.gif)

**Comment by aptkingston** [comment]
Hey @ggs331. Do you have a form inside your repeater too? Or do you have the form outside the repeater? If you have the form outside the repeater then this won't work, as every checkbox field has the same name. To fix this, you need to put your form inside the repeater as well, so that each checkbox has it's own form, preventing any issue with every checkbox having the same name.

The correct structure would be:
> Repeater
>> Form
>>> Checkbox

**Comment by ggs331** [comment]
Thank you @aptkingstoa, the checkbox works normal after I added a Form inside the repeater.
