### ISSUE TITLE
Removal of all_<modelId> concept

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#655]
We have made a bit of a poor database design choice by creating a separate couchDB view for every single table in budibase.

The way to model this in NoSQL databases is to either abuse document IDs or to keep the number of views down as much as possible. More information on both approaches is below.

### Changing document IDs
Records would follow the format of `modelId:recordId`and we could use the `startKey` in couch to query on a specific modelId from the allDocs index. This would more than likely be the most efficient option.

### View for records
A completely separate view mapping modelIds to record Ids would also solve the problem. The definition would look something like this:

```
    all_records: {
      map: `function(doc) {
        if (doc.type === "record") {
          emit(doc.modelId, doc._id)
        }
      }`,
```

This way, to get all the records for a table we can query this view by the modelId key. 

### Conclusion
The document ID approach is better practice and would save a ton of disk space and view building. We could query for models without creating any new indexes at all.

The view for all records will save a lot of view building work as well, although not as big a help for disk space. It's also easier to implement compared to the document ID approach.

There's also the possibility of leaving this for now, and writing a migration to convert it over in future.

**Comment by mjashanks** [comment]
I think we should do it. Now's the time - a data migration will be scary.

**Comment by mike12345567** [comment]
Think this is a great idea, going live with a view per model seems like it might be asking for trouble, it means complex apps with many tables could cause major slow downs in DB writes and if we discover we need to migrate due to this its going to create a period of un-usability in client apps until we migrate and fix up the DB.

Changing document IDs is definitely something we can do as well, however its definitely a bigger job as its a fairly fundamental change to the entire system but I think it is absolutely necessary.

The migration would be an absolute nightmare and I think at the very least we should look at making sure our IDs are capable of being used in a view collation manner - getting rid of all non-essential views should be on the roadmap no matter what I think.

My vote goes for updating record, model, user and automation IDs and using `allDocs` to access them, but perhaps for the time being we would leave around the `by_type`, `by_username` etc views and only remove the model record views as this would be a major saving and allow us to migrate completely away from the views without having to actually change anything in DB in the future.

**Comment by mjashanks** [comment]
Yea, I say use `allDocs` for everything as well.

Do we need the `RecordId` to `ModelId` view - why would a `startKey` query on `allDocs` not suffice ?

**Comment by shogunpurple** [comment]
We don't need the extra views if we just start using document Ids for everything:

`model:<modelId>`
`record:<modelId>:<recordId>`

then `startKey=model` or `startKey=record:<modelId>` would let us query everything we need from allDocs.
