### ISSUE TITLE
Only show automation log filters relevant to the BB pricing plan you are on

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#6675]
When I'm viewing automation logs, I only want to have access to the time based filters that are relevant to me - for example 24h on free, 7days on premium etc, so that I can be sure that I am viewing the full history of my logs that my plan allows.

**COS**
- Remove all filters apart from 24h or less on free plan
- Show the other filters, but place a "premium" badge beside each in the filter options and disable them
- If you click the premium badge, you are taken to the account upgrade page

#### Original Context
I have a CRON trigger that shoots our an email automation every morning at 8am.
It was a success yesterday:
![CleanShot 2022-07-12 at 12 41 21](https://user-images.githubusercontent.com/49767913/178685484-e0686b47-758f-4eab-85d8-9a08b6f8fed7.png)

And it was a success today:
<img width="1386" alt="CleanShot 2022-07-13 at 09 17 50@2x" src="https://user-images.githubusercontent.com/49767913/178685557-de25c039-910b-421c-bca0-47d93a80998e.png">

But shouldn't the logs show both events? I can't see yesterday's automation event.

**Comment by shogunpurple** [comment]
This is because the automation history by default is 24h - your log line was over a day ago.

Converting this issue to an enhancement to only show the relevant filters based on the plan you are on

**Comment by deanhannigan** [comment]
Hey @joebudi, We could definitely add in the disabled option behaviour as a global change to the Select component but the clickable labels might prove tricky to pull off.

Instead, the upgrade messaging could be approached at the table level, e.g:

![automations_upgrade](https://user-images.githubusercontent.com/5913006/182175241-4e101bd6-c840-4053-bcdf-0987fbe51fe8.png)

Does that seem like a decent compromise?

**Comment by joebudi** [comment]
Would it be possible to have the labels (disabled option) if it wasn't clickable?

**Comment by AndyWhann** [comment]
@joebudi We don't store anything past 24 hours for free plan and showing the disabled options in the dropdown as suggested I.M.O looks like we are saying "We have your past 30 days, upgrade to get access" but we don't store it. 

Once you upgrade we only begin to start tracking past 24 hours.

**Comment by joebudi** [comment]
Maybe include a tooltip saying, "Once you upgrade, we will start tracking logs for up to X days."?

**Comment by aptkingston** [comment]
From a dev perspective, I'd prefer to avoid putting any sort of pro-specific logic inside components. We need to keep the components as generic as possible. We can show the options and disable them since that's generic, but a "pro" badge or tooltips inside the dropdown would be tricky to do in a clean way.

**Comment by shogunpurple** [comment]
Think the easiest solution here is:
- Andys point is right - showing the upgrade beside the filters is a little misleading as we don't actually have the data. I think we just hide the filters that the user does not have access to, or simply disable them
- Instead of messing with global components and introducing pro logic, show a tagline/banner saying you can store more history if you upgrade (Deans suggestion)

**Comment by joebudi** [comment]
The "pro" badge will become more important as we add more pro features. It's an important way to educate users about the additional functionality available on the premium tiers. It will need to be done eventually.
