### ISSUE TITLE
Usage Tracking Middleware

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#668]
Usage needs to be tracked on a user basis as they interact with budibase applications. This means that every request in the builder will update their quota depending on what they action are attempting to perform.

### Notes
- Use a Koa middleware that looks at HTTP methods and the path
- Perform conditional write for that against dynamo

For example, a POST to `/api/records` may increment their records quota by 1 if successful.

**Comment by mike12345567** [comment]
One thing that we didn't consider with this is that the conditional write is not capable of handling resetting the quota usage if a timestamp is passed.

The conditional expression is used for a pass fail type condition on the request, which is great for our use case of whether or not it has surpassed the level, we will always be able to keep a user below the limit of their usage level, but it cannot account for when the quota period has been passed and the user quota needs to be reset.

To fix this, I'm thinking that we will have the request fail if the usage period has been exceeded as well, so our conditions are going to look like:
```
ConditionExpression: usageQuota.model + :usage < limits.model AND quotaPeriod < quotaEndPeriod
UpdateExpression: ADD usageQuota.model :usage
```

If the condition fails then we read the API key, check if it was caused by the quota period, if it was then update the `quotaPeriod` and the `quotaEndPeriod` as well as resetting the quota. 

We have to read the API key because Dynamo doesn't provide an API for which condition failed, just that it has failed. Sadly this means that when a user has hit their quota limits we will be performing a failed write and a read each time on Dynamo, which isn't so great, but we can control that with rate limiting.

In most use cases this means that we'll only be adding an extra get and update when the quota period has been exceeded, which I think performance wise is just fine, we probably can't do much better. The only major negative of this approach is the use of a get on a failed update, however I think if we have rate-limiting implemented as well this really isn't an issue, no matter what we have to attempt a write per request so adding a get when it is failing isn't that bad.

**Comment by shogunpurple** [comment]
This solution seems like a good one to me. It's not too big a deal doing a read if someones quota fails. So the flow is something like the following:

- User hits the API
- Their quota isn't actually done, but the request fails because the renewal date has passed
- We get their renewal date from the db, and perform an update on it for a month from now, as well as setting all the quotas to the quota the current request is using
- request to client succeeds

A few things to note more generally - see the following:

![image](https://user-images.githubusercontent.com/11256663/95312174-81211180-0886-11eb-9b92-c4a755dcba63.png)

It looks like we consume a write unit regardless of whether the request fails or not. Just trying to understand the cheapest and most efficient way for us to manage this middleware is. Here's a few back of a napkin calculations for what happens on any request:

### get before write
- Get the API quota on every request **(Subtotal: 0.5 RRU)**
- Check the renewal date hasn't passed
- If the renewal date hasn't passed and the quota is blown just fail 
- Update the quota in the DB with the current request and If the date has passed, reset the renewal date **(Subtotal: 1 WRU)**

**(TOTAL: 0.5 RRU, 1 WRU) per successful request. If quota is blown it's just 0.5 RRU**

### Conditional Writes
- Conditionally write the quota and and renewal date **(Subtotal: 1 WRU)**
- If it succeeds - just return successfully
- If it fails, read the usage to check why **(Subtotal: 1 WRU, 0.5 RRU)**
- If it's past the renewal date, just reset the quota and renewal date **(Subtotal: 2 WRU, 0.5 RRU)**
- If the quota is just blown and the renewal date hasn't passed, fail the request

**(TOTAL: 1 WRU) per successful request. If quota is blown it's (1 WRU, 0.5 RRU), if renewal date has passed it's (2 WRU, 0.5 RRU)**



Either way, it's going to basically be free to run this. My vote is for doing the read then write. Thoughts?

**Comment by mike12345567** [comment]
Yes I think you're right, the circumstance under which the read then write is actually better is only when the quota has been blown, which should be an unusual case, if the majority of our users are blowing their quotas then we need to think about that anyway.

I think running the conditional write first is the correct choice as it optimises for the usual case, if the blown quotas are causing us problems then we can very easily in memory cache apps which have blown their caps recently and back off the conditional writes for a period, dropping the conditional write usage down to say every ten minutes or something, giving us very dependable performance under this condition. Building a write through cache for all this stuff would be a very easy optimisation in general so I think thats the best choice.

**Comment by mike12345567** [comment]
usageQuota structure will appear as:
```
{
        records: 0,
        storage: 0,
        views: 0,
        automationRuns: 0,
        users: 0
}
```

**Comment by shogunpurple** [comment]
Was just thinking there - we will also need to store their usage plan limits on that item too.

```
      usageLimits: {
        records: 100000,
        storage: 1312312312,
        views: 12,
        automationRuns: 100,
        users: 1999
      },
```

We could, of course, make the `usageQuota` become the source of truth, and decrement from it as the user blows through the quota - but I think the way above probably provides an easier way to bump people up, change plans when we need to and to reset them back to zero

**Comment by mike12345567** [comment]
Yeap thats what I was thinking, in my design I have it comparing against a structure which is nested in the same format as the usageQuota!
