### ISSUE TITLE
Create/Edit/View Record Screen

### ISSUE THREAD

**Issue by mjashanks** [Budibase/budibase#676]
## Problem

Currently, it is quite difficult so setup an "Edit Record" screen. We have to know how to use the `/my-record/:id` syntax - then creating a link with an :id parameter is also tricky for the non technical user.

Additionally, we want to give people a bit more of an advanced "Edit record" screen - currently they are quite restricted to the functionality of the form component. For example, it's not easy to hook up a single button for "Delete Record", or "Send Email" (triggers workflow)

### 1. Screen Templates

We will introduce the concept of screen templates.
![Screen Template](https://user-images.githubusercontent.com/3524181/95329498-f00a6480-089e-11eb-93c4-4aa7607bc73c.jpg)

In the mockup above, "Contact", "Deal" and "Order" are all tables in our backend. So, this is giving us the option of creating a new screen, that is all setup to point to a particular table.

This will allow us to setup more complex default screens for common use cases.

### 2. Urls Selector - use opinionated URLs

Currently, when we add a link, we are shown a dropdown of Screen uls to select. This is limited as is does not account for Id based urls `/contact/abcd1234def`

We will add additional URLs to this, such as "Edit Contact" and "New Contact". These will assume to convention `/<tablename>/<id>`  and `/<tablename>/new`

### 3. (time dependant) - Form to be used inside Record Detail

Currently, the form is standalone. 
- you put it on a screen, give it a model, and it fetches or creates records.
- ths submit button is uneditable - it can only Save a record
- We cannot add any more buttons
- We cannot add any other content inside the form.

a) We should edit the form component, so that it should be used inside a `Record detail`. The Record detail component will be responsible for fetching/creating the record, and the Form just reads for it's context
b) We should remove the submit button on the form (or make it hideable)
c) Our Edit record screen can now look something like the below. 
- The form is now just a set of fields. 
- Buttons are seperate, and hooked up via actions. 
- We can add other components inside the Record Details, which all have access to the underlying record

![Edit Record Template](https://user-images.githubusercontent.com/3524181/95330103-f3eab680-089f-11eb-8403-064a4ad64f2e.jpg)

**Comment by aptkingston** [comment]
Looks good! I'll try and get the linked record PR up ASAP because you'll definitely need to branch off that rather than master (both for linked record functionality and for the form updates I've done).

Only thing I'd say is for the URL's - to me `/<tablename>/<id>` looks like a URL for viewing a record rather than editing, so you might want `/<tablename>/edit/<id>` just to leave that first URL available for a view page.

For the buttons, personally I think we should have a submit button built in with a setting to change the text. The action for creating or saving is always the same, it's just the `save` API endpoint isn't it? The delete button could just be conditional on there being a record passed in (like by a record detail provider when editing).

**Comment by mjashanks** [comment]
@aptkingston

Yes, point taken about the urls 👍 

my point around the buttons was that there a few different buttons that people may want to add in there - and we can't determine them up front.  "Delete", "Cancel", "Send Email", ... or, a common use case - "Approve" / "Reject"

Also - the Form buttons cause us another issue. We are unable to put any other components between the end of the form, and the start of the buttons (see the way my screenshot has a table there, with the buttons at the end).

**Comment by shogunpurple** [comment]
The rails conventions might be a good place to look when it comes to our URL structure.

![Screenshot 2020-10-07 at 14 01 41](https://user-images.githubusercontent.com/11256663/95334125-a1ac9400-08a5-11eb-95c6-e4373ac2303a.png)

**Comment by aptkingston** [comment]
Sure, maybe I just can't think at the minute how we would wire up something like an appprove button to do something other than just submit the form. I was thinking this was just going to be a form for creating or editing a record, but if we can make it even more flexible and generic to use in other ways then that's great. As long as it's still simple to use then I'm on board, since most of the time I think users will probably just want a button to submit the form and either create or edit the record.

**Comment by mjashanks** [comment]
My only issue with those URLs is that it forces us to create at least 3 screens for every table (as currently, each screen has a single URL).

I had hoped (to save time now) we could have a single `Photo Screen`  that would handle New and Edit, and no seperate screen for View (`/photos/new` or `/photos/1234abcd` ... both handled by a url matcher of `/photos/:id` )

**Comment by mjashanks** [comment]
@aptkingston RE the buttons - I'm suggesting that they no longer belong to the form component at all. The are just added to the screen as seperate components. This means that we can wire them up using the existing `OnClick` handlers of a regular button component

**Comment by shogunpurple** [comment]
@mjashanks no that makes total sense - was just suggesting that URL structure as the "official" one at some point after launch

**Comment by joebudi** [comment]
I feel we should automatically create a List, Detail, and New screen for each table.
You could literally upload a CSV and automatically spit out an app. And, obviously, you still have the flexibility to make adjustments to your screens including removing the unnecessary ones.
