### ISSUE TITLE
Huge Memory Leak / Infinite Loop

### ISSUE THREAD

**Issue by Shadowfita** [Budibase/budibase#6797]
**Hosting**
- Self
  - Method: Docker
  - Budibase Version: 1.0.218

**Describe the bug**
Memory Leak / Loop issue causing infinite RAM usage until crash and app freeze

7 GB Memory used within 1.5 minutes.

**To Reproduce**
1. Create a data provider
2. Add a repeater
3. Add Container
4. Inside Container
  5. Card
  6. Table

![image](https://user-images.githubusercontent.com/11067520/179668596-d937240c-1ba3-4382-8847-50073a8a440d.png)

**Expected behavior**
Shouldn't occur

**Screenshots**
![image](https://user-images.githubusercontent.com/11067520/179668611-dd3072f7-536b-4e6c-a92f-98643342d857.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version 103.0.1264.62

**Comment by aptkingston** [comment]
Hey @Shadowfita. This isn't a bug or a memory leak - you're just designing something that your browser/data source can't handle. If your data provider is pulling 50 rows (the default) then you'll be doing 50 calls to fetch rows for your table nested inside the repeater, so it's just the load on your browser and data source that is causing the lag. If you have configured your data provider to fetch hundreds of rows (and therefore render hundreds of tables, all pulling data) then yes, this load will just crash your browser - but that isn't a bug.

For example, I just did this exact structure and while it was very slow (50 rows from data provider, so 50 tables), it did not cause any sort of bug or infinite loop. I would just never design this because it's completely wrecking the underlying data source, and I can't see a good use case for having 50 tables on a page.

If nesting a table inside a repeater is actually something you want to do, I'd recommend at least reducing the amount of rows your data provider is pulling back.

There is no limitation in Budibase here, so the upper limit is just your browser performance and the performance of the data source that you're hitting with all these requests.

If you experience an actual bug that's not just lag caused by pulling huge amounts of data, please open a new issue with reproduction steps and we can look into it. Thanks.
