### ISSUE TITLE
Table Block link table rows / link screen doesn't work

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#6866]
**Hosting**
- Cloud
  - App version - 1.1.21

**Describe the bug**
Table Block's "link table rows" / "link screen" doesn't work.

1. When linked to "/inner-page" it always redirects to home page instead, a.k.a. the "/" screen.
It's not a problem with access rights, as I'm trying to redirect an "Admin User" from a "Basic User Screen" to a "Public User Screen".

2. When linked to www.google.com, it redirects to https://tenantID.budibase.app/www.google.com/ro_ta_182baf8810ac47c4... So it inserts that third party link between the tenantID and some internal ID that starts with "ro_ta".

3. When linked to https://google.com, it redirects to https://google.com/ro_ta_182baf8810ac47c4... So it adds the internal ID to the google query or something.

**To Reproduce**
1. Create a Budibase Internal Table
2. Create some columns and add dummy data
4. Configure a Data Provider with Table Block
5. Check "link table rows" and select one of internal screens or type a third party URL.

**Expected behavior**
Redirect to an /inner-screen or https://website.com/

**Screenshots**
![link screen table block 1](https://user-images.githubusercontent.com/94982318/180491069-7e3a675e-e778-494b-897f-57a672848fde.png)
![link screen table block 5](https://user-images.githubusercontent.com/94982318/180491118-085c2f8c-78cf-43af-a4fc-f06ced1846a1.png)
![link screen table block 3](https://user-images.githubusercontent.com/94982318/180491125-beab4f44-8c85-44b2-90e6-2f108471a9ce.png)
![link screen table block 2](https://user-images.githubusercontent.com/94982318/180491164-23801a1f-fd78-42f2-9785-b90fbe5004f6.png)
![link screen table block 4](https://user-images.githubusercontent.com/94982318/180491173-59fa6e00-6f13-45c1-8814-d8f55c8e24a5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 103.0.5060.134 (Official Build) (64-bit)

**Additional context**
I didn't test beyond Admin role and public and basic screens for internal linking.

**Comment by Klience** [comment]
Edit: I tested the "Title Button" of Table Block that does the same thing. It works as expected. When linked to /job-portal it redirects correctly to both /inner-screens and https://website.com

**Comment by deanhannigan** [comment]
Hi @Klience,

> When linked to "/inner-page" it always redirects to home page instead, a.k.a. the "/" screen.
> It's not a problem with access rights, as I'm trying to redirect an "Admin User" from a "Basic User Screen" to a "Public User Screen".

Did you have a screen in your application with a path similar to `/inner-page/:id`? When the row is clicked, the configured link `/inner-page` is combined with the `_id` field for the row e.g `/inner-page/ro_ta_fad297....`
This is the default behaviour, if you wanted to append something other than `_id` you can specify that in the `ID column for linking` setting for the table.

Without the  `/inner-page/:id` screen existing, the app will redirect to the home screen. Which is the same behaviour that you are seeing here.

> When linked to [www.google.com](http://www.google.com/), it redirects to https://tenantid.budibase.app/www.google.com/ro_ta_182baf8810ac47c4... So it inserts that third party link between the tenantID and some internal ID that starts with "ro_ta".

The link value is treated like a string if not supplied with a protocol. It will be treated the same way as your `/inner-page` link unless prefixed with `http://` or `https://`. With a protocol supplied, the row `_id` variable will be appended to the supplied link e.g. "https://google.com/ro_ta_fad297...."

> When linked to https://google.com/, it redirects to https://google.com/ro_ta_182baf8810ac47c4... So it adds the internal ID to the google query or something.

As outlined above, this is the expected behaviour unless you reconfigure the value being appended.

Hopefully that all makes sense. If you have any further issues, please let me know.
