### ISSUE TITLE
The field value update by the action "Update Field Value" was not taken by the action "Save Row"

### ISSUE THREAD

**Issue by cyl1234567** [Budibase/budibase#6913]
**Hosting**

- Cloud
  - Tenant ID: <tenantId> 

**Describe the bug**
I want to implement a "history" field to track a row's change history.
To achieve this, I decide to update the "history" field automatically when user click "save" button in the edit page.
But the field value update by the action "Update Field Value" was not taken by the action "Save Row".

**To Reproduce**
1. in "Save" button's "On Click" action, update a field before save row 
    - ![image](https://user-images.githubusercontent.com/109498463/181196184-b4b1ffed-65bb-4923-b80f-c7ff78afa15f.png)
2. click save in the preview page, the history field update immediately as expect
    - ![image](https://user-images.githubusercontent.com/109498463/181196321-06be6e61-c309-46c1-86a7-0aff2ae6895e.png)
3. but after few second, when toast "Row Saved", the history field cleared
    - ![image](https://user-images.githubusercontent.com/109498463/181196341-fb2ae2c9-d478-4405-a35f-c1e96b96d02c.png)
  
**App Export**
[couchdb_test-export-1658911640372.txt](https://github.com/Budibase/budibase/files/9196640/couchdb_test-export-1658911640372.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 103.0.5060.134

**Comment by aptkingston** [comment]
Hey @cyl1234567. This is just because the actions are executing so quickly that there isn't enough time for a manual field change to be reflected in the save payload. A much better way to do this would just be manually specify the `history` field in the `Save row` action. You can do this by pressing "add column" in the save row action and specifying your value:
![image](https://user-images.githubusercontent.com/9075550/181216109-521e44d0-ca32-4030-be4c-8414e0fd9d5c.png)

**Comment by cyl1234567** [comment]
Hi @aptkingston,

Thanks. update history in "Save Row" works.

But I think the original issue is still a bug. 
No matter how quickly the "Update Field Value" execute, all action after it should take it's change, right?

**Comment by aptkingston** [comment]
Updating field values is designed to help users fill out forms - like "if you choose X, then this other field becomes Y". It's not designed to change values while executing button actions. I wouldn't consider this a bug because it's meant to work like that, but I understand what you mean. I can have a look, but I don't think it's really possible to do this.
