### ISSUE TITLE
Research Spike - BBUI/Client library versioning and regressions

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#6942]
Spec: https://budibase.atlassian.net/wiki/spaces/PROD/pages/46792705/Custom+Components

How can we manage updates to versions of BBUI when a custom component relies on it?

**COS**
- Documentation of findings - add to the spec above
- We can answer the question "Is there any way to pin versions of BBUI and tell the user that an upgrade to their app could break their custom component?"
- Should respect Semver 
- Should pin major versions of the client library

**Comment by aptkingston** [comment]
Just adding a reply here to address this specifically. The main way we're addressing this is by trying to bundle as little as possible inside the client library context - allowing custom plugins to install their own versions of whatever dependencies they require. BBUI is the main one relating to this ticket, so basically we will not be providing BBUI via the client library, and instead BBUI can be installed (at any version) as a normal dependency if it is required. 

The SDK for the public API will be published independently so will be treated similarly.

The only cases remaining would be breaking changes to the core utils provided by the client library, such as the styleable helper or the data provided by component context. To that effect we have much more control and ideally won't be making breaking changes there that are not backwards compatible.

There is nothing specifically in place to try to deal with breaking changes like that, but since reverting the client library is possible and broken plugins would be visible in the preview before publishing, I think we're ok here. If/when we publish our first breaking change in the client library we can simply warn that existing plugins may need updated, and we can provide migration information at that time depending on the scope of the change. The work done on custom components to support error states should hopefully help in this department too.
