### ISSUE TITLE
Change routes on screens and check they still work

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#705]
This failed on two accounts:

* When I updated a screens URL/route, I wanted to update my link to point to the new URL. The URL within the link was still the old url.
* When I changed the URL in the browser to the new URL, it failed.

https://www.loom.com/share/587211eefc1e4dab92fbd9fcc5f967b7

**Comment by aptkingston** [comment]
Because of the way the preview apps are served it's not possible to refresh them. The SPA routing doesn't seem to hydrate properly on a fresh load, so you just need to close it and press the preview button again to see the changes. It would be nice if it was possible to refresh or manually enter a URL though, but I've never looked in to how it currently works. The test case will pass though, like just changing the target screen of a link and previewing again works.

**Comment by aptkingston** [comment]
Taking the above comment back because refreshing my apps does appear to work now... Magic! Maybe someone addressed the issue.

**Comment by aptkingston** [comment]
Just an update to say I discovered the actual issue behind my comment of not being able to ever refresh the page - client apps only route with the app ID as a prefix when running on `localhost` or `127.0.0.1`. My screen updates PR includes a fix to allow serving from LAN IP addressess too (as I have the builder inside a VM and use the browser inside my host). Maybe not applicable to the initial issue here but just to explain why I was having issues written above.

**Comment by mjashanks** [comment]
I looked into this for a bit, and stopped because it was messy, and a bit risky for now. Issues...

1. When a route has a parameter... `/contact/:id` we have to do some regexing to parse out things like `/contact/{{ List.Contact._id }}`
2. We need to know which props are URLs. We would really need to make a new "URL" type in component's JSON, then walk the component tree looking for these

I think for now, its
a) Not very likely that people will change a route
b) Not a stretch to ask them to manually update their links
