### ISSUE TITLE
Conditional UI of a Form to allow setting the Active Step.

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7063]
Allow for dynamic selection of the Active / Selected Step of a Form.

**Comment by melohagan** [comment]
Related discussion: https://github.com/Budibase/budibase/discussions/4967

**Comment by melohagan** [comment]
Another related discussion: https://github.com/Budibase/budibase/discussions/7627

**Comment by melohagan** [comment]
Related issue: https://github.com/Budibase/budibase/issues/9323

**Comment by aptkingston** [comment]
If we had a setting for the "active" form step (which would then also allow setting it via conditional UI), then we would have to disable the ability to navigate forwards and backwards via button actions. Otherwise we would have 2 sources of truth, which is impossible. You would have to pick from:
- Explicitly set which step is active at all times via a binding
- Control active step via button actions only

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/9323
