### ISSUE TITLE
Non-clickable records in many-to-many relationship

### ISSUE THREAD

**Issue by vibecy** [Budibase/budibase#7111]
Hi all,

I am trying to create a School Management System. My data has students (who have one or more Guardians) and Guardians (who have one or more Students). I tried creating the student page in designer, the records are retrieved properly, but the Guardians are non-clickable. Expected behaviour would be to take me to the Guardian specific record.  Is this achievable somehome?

See below screenshot:

![image](https://user-images.githubusercontent.com/25839616/183074639-7518278a-07ae-4431-b3ce-fdfd36a7ca40.png)

Thank you!

**Comment by vicam001** [comment]
Hi @vibecy , what is the data source of your data (e.g. internal Budibase DB, external PostgreSQL DB, Airtable, REST source...) ?

I ask this because I believe I've seen on the editor a hint indicating that the connection from one row on a table component to another screen works only when the source is Budibase DB or external SQL db.

Hope this helps/points towards the right direction.

**Comment by vibecy** [comment]
I don't know if my query is related to the below:

https://github.com/Budibase/budibase/discussions/5089
