### ISSUE TITLE
Ability to have 2 types of export, (App + Config tables), (Transactional Tables)

### ISSUE THREAD

**Issue by aderici** [Budibase/budibase#7181]
It would be nice that if one could mark some of their budibase internal db tables as "Transactional" and some as "Config Table".

The data within config tables are required for the app to function (like users, dropdown options that list your factories, branches etc)

Transactional tables contain all the other business data.

When exporting an app, it's important to have an option to just export app itself and the tables definitions as well as data for config tables. The size will be relatively low.

Now since there's no such distinction, transactional tables datas are exported as well so app export size grows and grows. To the extent that export will start timing out.

Add the couchdb inability to completely remove deleted rows from itself. Contributes to the size increase

**Comment by melohagan** [comment]
I'm going to close this one, as you can now choose to export without data rows: https://docs.budibase.com/docs/export-and-import-apps#export-an-app

As for the issue of increasing app size. This is largely due to data revisions, which we want to keep for the revision history and version control feature that's currently being worked on!
