### ISSUE TITLE
Table and Table Block have non-matching features

### ISSUE THREAD

**Issue by GabrieleLabanca** [Budibase/budibase#7195]
**Describe the feature request**
It is not clear why there are two different components for tables; moreover, each of them has features that miss from the other.

Table:
- doesn't allow searching
- can't be directly connected to a data source

Table Block:
- doesn't allow scrolling (it just extends the table)

**Comment by aptkingston** [comment]
Hi @GabrieleLabanca. A `Table` is a component. The `Table Block` is a block. "Blocks" are more feature rich and are made up of multiple underlying components. The table block uses a table, a form and some search inputs to allow filtering and searching. They are not the same thing.

Documentation on blocks can be found here: https://docs.budibase.com/docs/blocks
Documentation for the table component be found here: https://docs.budibase.com/docs/table

**Comment by GabrieleLabanca** [comment]
Hi @aptkingston, this makes sense to me, but I don't get why the table block doesn't have all the functionalities of a table, e.g. the scrolling.

**Comment by aptkingston** [comment]
The table block handles pagination for you, so there's no need for scrolling (as long as your data source supports pagination). The table block will display an entire page of results at one time, because behind the scenes it's using the same value for the "table scroll limit" and for "data provider limit".

If you're using a datasource that doesn't support pagination, I can see that the table won't scroll even though there is more data to display. Perhaps we should update the table block so that if you disable pagination, it will not set a limit on the data provider and therefore show a scrolling table. Is that would you would like?

**Comment by GabrieleLabanca** [comment]
@aptkingston thanks for the explanation. Yes, exactly: I'm working with a SQL query that, as far as I understand, does not support pagination.
