### ISSUE TITLE
Allow row selection does nothing for Table with DynamoDB data source

### ISSUE THREAD

**Issue by zoell** [Budibase/budibase#7198]
**Hosting**
- Self
  - Method: docker
  - Budibase Version: 1.2.9

**Describe the bug**
When adding a Table with a DynamoDB or REST data source the Allow row selection checkbox does nothing.
This prevents the possibility to add an export button to export data which should be essential.

**To Reproduce**
1. Add DynamoDB data source
2. Add a simple scan without any filters or fileds, just a scan.
3. Insert Data Provider
4. Insert Table
5. Select Allow row selection

**Expected behavior**
Allow row selection checkbox enables selection checkboxes on each row of the Table with DynamoDB datasource.

**Comment by aptkingston** [comment]
Hi @zoell. Just below the checkbox to enable row selection, you'll notice that it says that row selection is only supported for internal tables or SQL tables:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/9075550/184497330-2327a735-6a3f-4808-a9f9-518ef1f87c2b.png">

We don't currently support row selection for other external datasources as we can't support exporting data for external datasources, meaning selecting the rows would be pointless. I'm guessing the main reason you'd like row selection to work is because you'd also like to be able to export data from Dynamo?

We could support exporting data from any datasource (including Dynamo) but with the restriction that you can only export data you can currently see in the table, and it would only export the exact format of data that the table is currently showing.

**Comment by zoell** [comment]
Wow I have not noticed that text at all.
I believe exporting data from any "supported" datasource is essential for any CRUD/business application. Exporting what we can see in the table (including the other pages, not just the page that is currently on screen) looks OK to me.
