### ISSUE TITLE
Casing of column name is important - should it be

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#720]
In the image below you can see I've been able to create two columns in a table with what seems to be the same name:

![image](https://user-images.githubusercontent.com/4407001/96021888-f755e300-0e47-11eb-8224-5761c9b7e096.png)

You are not currently allowed to create columns with the same name in the same table, which makes sense for reducing confusion in a table but if I create a column `a` and then a column `A` these will both appear.

Might be worth considering two things, whether we should uppercase the first letter of the column name and whether or not we should simply lowercase all column names before adding them to the table.

**Comment by shogunpurple** [comment]
IMO we should remove the `text-transform: capitalize;` from the table headers - casing matters in this scenario, so if you have lower cased it the table headers are actually incorrect - seems like a potential source for bugs

**Comment by mjashanks** [comment]
I think we should
1. Stop the creation of columns where `column1.toLowerCase() === column2.toLowerCase()`
2. Do as @shogunpurple says - remove the capitalize

I say this because
- We should stop people creating same named columns 
- But casing still matters - to the API - people need to know the proper casing of the column if they ever make API requests

**Comment by mike12345567** [comment]
I agree, I think the capitalization is confusing for those that plan to use the system as an API, if casing is important we shouldn't fiddle with it when displaying it.

I can take this and sort it out, make it work as @mjashanks suggest!
