### ISSUE TITLE
Date saves 1 hour earlier than selected

### ISSUE THREAD

**Issue by PaulMcF1987** [Budibase/budibase#7202]
I have a Friend who is a driving instructor and thought I would make him an app to keep tabs on pupil progression etc. I also added in a "diary" where he can add his next lesson dates/times etc...

You will see from the following [video](https://www.awesomescreenshot.com/video/10437896)

The time seems to save, 1 hour earlier than the time selected.

I am using the most recent version of Budibase - 1.2.26
Budibase is self hosted via docker on an Ubuntu 20.04 server.

any help would be much appreciated.

**Comment by aptkingston** [comment]
Hey @PaulMcF1987. I can't access your video, but could I check where the data is stored for that app? If it's internal tables or a SQL database then I would recommend turning on the option "ignore time zones" if you're having time zone problems, since this sounds like the sort of app where you don't need to worry about that.

This will ensure that the time you pick in a date picker is always going to be the time stored and displayed.

![image](https://user-images.githubusercontent.com/9075550/183952118-af3f87d7-9512-418a-99ed-fd24d40df9d9.png)

**Comment by PaulMcF1987** [comment]
@aptkingston 
I am using an external MariaDB databaseThat option has already been selected

However, within the app design area it was not turned on, I have turned it on now which seems to have sorted the problem. thanks

**Comment by aptkingston** [comment]
Glad to hear so! The problem was probably caused by one side having it enabled, but not the other. Having both sides enabled or both sides disabled would probably work just fine :+1:
