### ISSUE TITLE
bbproxy - Backend Services Hardcoded

### ISSUE THREAD

**Issue by Daniel-CS-Team** [Budibase/budibase#7274]
I tried to setup Budibase in AWS ECS and FARGATE using the docker-compose.yaml as base.
But I ran into a major issue: the budibase-proxy service expects ist backend services to be reachabel via their service names as defined in the docker-compose.yaml. For the other services, this can be configured using Environment Variables, but not for the proxy-service.

This becomes an issue, when using FARGATE, because there is no internal Docker-Network. All Containers must communicate via the Loopback interface. Furthermore, there is no way to modify the hosts-file on the FARGATE host. So the only way to resolve this, ist to add Environament-Variables for the proxy-service.

**Comment by aptkingston** [comment]
Hey @Daniel-CS-Team. The image for our proxy-service is just a nginx image bundled with our config file, so if you wanted to get around this at the moment then you could simply update the proxy-service in the compose file to use the base nginx image and mount a modified config.

If you clone the repo locally, you can generate a slightly modified nginx config very easily. In `scripts/proxy/generateProxyConfig.js` you'll see at the bottom that we have a `Configs` object. This is what defines the hostnames to use in our generated nginx config. Since you're using compose, you could update `Configs.compose` to use whatever IP/hostname you want for each of the services. Once you've done that, just run `node scripts/proxy/generateProxyConfig compose` and it will generate `hosting/proxy/.generated-nginx.prod.conf`. If you mount that nginx config inside a basic nginx container then everything should work.

We do this ourselves for our dev config - check out `hosting/docker-compose.dev.yaml`.

**Comment by Daniel-CS-Team** [comment]
Hi @aptkingston, thank you for the quick answer. I will try it out, when I get the time for it. For now, I will check AWS EKS as a more sound alternative.

**Comment by Rory-Powell** [comment]
We have a PR open currently that will address this, allowing the URLs to be configured via environment variables
see: https://github.com/Budibase/budibase/pull/7065

**Comment by Daniel-CS-Team** [comment]
Allrigth. I got it running with AWS FARGATE. 

For anyone searching this in the Future: 
1. Use the offical couchdb image from Dockerhub, not the one in the docker-compose file as it will not work with persistent Storage aka. AWS EFS.
2. You have to modify the budibase/proxy image, because service-URLs are hardcoded and in FARGATE, there is no such thing as a docker-DNS:
````
FROM budibase/proxy
RUN sed -i '/127.0.0.11/d' /etc/nginx/nginx.conf
RUN sed -i '/set $apps app-service;/d' /etc/nginx/nginx.conf
RUN sed -i '/set $worker worker-service;/d' /etc/nginx/nginx.conf
RUN sed -i '/set $minio minio-service;/d' /etc/nginx/nginx.conf
RUN sed -i '/set $couchdb couchdb-service;/d' /etc/nginx/nginx.conf
RUN sed -i '/set $watchtower watchtower-service;/d' /etc/nginx/nginx.conf
RUN sed -i 's/$apps/localhost/g' /etc/nginx/nginx.conf
RUN sed -i 's/$worker/localhost/g' /etc/nginx/nginx.conf
RUN sed -i 's/$minio/localhost/g' /etc/nginx/nginx.conf
RUN sed -i 's/$couchdb/localhost/g' /etc/nginx/nginx.conf
RUN sed -i 's/$watchtower/localhost/g' /etc/nginx/nginx.conf

**Comment by mike12345567** [comment]
Hi @Daniel-CS-Team - just to note - using the official CouchDB image will cause some fairly serious problems - the IBM image we currently use has a Lucene search index (called Clouseau) built into it - without this large parts of Budibase will not function as expected.

**Comment by Daniel-CS-Team** [comment]
Hi @mike12345567,

thanks for the warning. Issue with the IBM-image and AWS EFS is, that it cannot wirte any file, despite the correct permissions. I found the workaround of using the offical image. 
I noticed some problems trying to use the Budibase-DB, but this is not required for our usecase (users-table works fine). 
But I keep in mind, that other issues might be caused by this.
