### ISSUE TITLE
Actions in OnChange in Options Picker should be sequential / synchronous

### ISSUE THREAD

**Issue by evtnl** [Budibase/budibase#7359]
**Hosting**

- Self
  - Method: docker compose 
  - Budibase Version: 1.2.9 

**Describe the bug**
When you add actions to the onChange event, you can order them around. This implies the actions will be run in the specified order.
Action are however executed asynchronous, should be synchronous.
Is you have multiple actions they could be dependent on the result of the previous one. Becaus the actions are executed, or at least finish, in random order, the reults might be stale or not availanble in de next action.
E.g. if you execute a query and set the result in a form element, the result is not available when setting the form element and the form element wil be set empty or to the old value.

**Comment by aptkingston** [comment]
Hey @evtnl. Could you provide more detail about your setup? Button actions are indeed executed sequentially, and you can indeed reference the result of previous actions. I believe the only action executed asynschronously is the "trigger automation" action, as that simply kicks off a background job. Everything else should wait for a result and provide this to further actions.

**Comment by evtnl** [comment]
in a new row screen:

Form:
- options picker populated from dataset (100 items) "select1"
- text field "text"

add actions to Select1 :
1. set state variable "selectedvalue" to {{ Form.Fields.select1 }}
2. update field value "text" to {{ State.selectedvalue }}

If you test this,  field "text" will be empty after choosing a value in the options picker.
The second time, it will get the previous valu of the options picker and so on.

I wanted to use this to update a second dataset query to populate a second Options Picker. It got updated with the wrong id from the first options picker or an empty value.
Also the second options picker often would not update, because the query was not fast enough to provide results. Resulting in an empty second options picker.

**Comment by aptkingston** [comment]
Thanks for the detail! 

All you need to do to fix this is use the binding for `{{ Field Value }}` in your "on change" action, rather than the form field binding. It's the top one in the binding list when inside an "on change" action,
![image](https://user-images.githubusercontent.com/9075550/185640867-5d2fdf24-e6fe-4fd8-bb94-bf5b494e5ee1.png)

It's mentioned very briefly in the docs: 
![image](https://user-images.githubusercontent.com/9075550/185641167-c8c99743-8cc0-41f7-a065-3974da9d9e20.png)
, but I admin it's a bit unusual. The special `{{ Field Value }}` binding is the new value that's triggering the actions, and the `{{ Form.Fields.select1 }}` binding is the previous value, before the change even occurred.

We might update this in future because quite a few people have been tripped up by that.

**Comment by evtnl** [comment]
thanks @aptkingston for the explanation.

Great to have the new and the previous value available! Might come in handy somtime.

For those that come here searching for the same setup:
I've managed to make this work in a way inspired by the "Video tutorial: filter with two option pickers" on [https://docs.budibase.com/docs/searchfilter-data](https://docs.budibase.com/docs/searchfilter-data)
Instead of putting a form whithin two nested dataproviders, you can put the two dataproviders inside the form! 

The first dataprovider then delivers the possible options for the first options picker.
The second dataprovider has a binding for the query parameter. Use {{ Form.Fields.<optionspicker1> }} as the value for this binding.
It works automagically without using actions.
