### ISSUE TITLE
Options picker should show all options when used with Data Provider as options source

### ISSUE THREAD

**Issue by Klience** [Budibase/budibase#7370]
**Describe the feature request**
We should be able to see all options when selecting options using "Options Picker" with Data Provider as Option Source.

See the video here in [Budibase docs](https://docs.budibase.com/docs/option-picker). At 02:00 you see a lot of options. Then we click on "cereal" and it gets selected. Then when we click on "cereal" again you can see only "Filter by item type" and "cereal" are shown. So you have to click on "Filter by item type" placeholder to be able to see the options again.

This is unintuitive and leads to bad UX. It took me a while to see if it's a bug or intended. Then I found the video above.

This video is old I believe, but it has the same behaviour at the moment.

**Comment by aptkingston** [comment]
Ah I see what's going on. The problem here (and in that video) is that you're using an options field with a data provider source, to filter that exact same data provider. Therefore once you pick a value it updates the data provider results, which in turn restricts the available options to only a certain type. I would struggle to call this a bug because everything is working as intended.

You basically never want to filter a datasource that you're using as an options picker source, unless you specifically want to reduce the option set down.

The solution is just to use 2 data providers (pointing at the same table) - and don't filter on the one you want to use as the options source.

**Comment by Klience** [comment]
@aptkingston Thanks! It works!

One thing I noticed though is if you set the "limit" to 1 on the data provider that's used as a options picker source, it doesn't see all the options after the 1 row. So with a table with 2 rows, 1st row being "apples" and 2nd row being "bananas", options picker will see only "apples" as a filter option.

You need to increase the limit to 2 to be able to cover both rows. I guess if the table has 10 options, you need to set the "limit" to 10 and so on. Or set the "limit" to e.g. 50 in advance.

Which is okay, when you know that there's not going to be dozens of options. But if someone uses that as dynamic filter (like Budibase docs suggest) with no reasonably expected limit, they can get confused as to why some options aren't available (like when the newly created row with a not-seen-before option exceeds the set "limit" on data provider).
