### ISSUE TITLE
New occurrence of auto log out

### ISSUE THREAD

**Issue by kasgithub8** [Budibase/budibase#7430]
**Hosting**
- Self
  - Method: <docker>
  - Budibase Version: <1.2.47> 
  - App Version: <1.2.47> 

**Describe the bug**
Our users are logged out again. 

**Additional context**
This happened 1 or 2 updates before this aswell.

**Comment by shogunpurple** [comment]
@kasgithub8 - you have to give us more information. "Our users are logged out again" is not sufficient. Is it all users? Some users? Is there a pattern? 

Since this is a self hosted instance, there's also a chance other things are at play here.

Please use the provided issue template and fill it out **with as much detail as you can** for us to debug this.

I'm going to close this one pending a better issue report - and continue to close issues that provide very little context or actionable debugging steps for the team.

Thank you

**Comment by kasgithub8** [comment]
Hi @shogunpurple, 

sorry, false warning. 
Basically, we have a public page for users who don't have access to this app.
Every time a new row is created, emails are being sent out with a link to that row.
Problem is that our users are being redirected to the public page because they're not logged in.
I think our normal "App users" are being logged out every time they restart their pc. 
I don't know how to solve this. Is it possible to make another "login" page in this app?
