### ISSUE TITLE
Relationships and Attachments don't work with Card / Stacked List

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#745]
Relationships and Attachments data types do not work with the card and stacked list.

**Comment by aptkingston** [comment]
Attachments will now work as an image source (once the PR is merged). What did you mean by relationships don't work? Binding to relationships should always give you the count of the related records.

**Comment by joebudi** [comment]
I wanted to display the relationships, like in a grid, but in a card.

**Comment by aptkingston** [comment]
Ah gotcha. We won't be able to do that until we do some sort of overhaul of the binding stuff. Currently you can do it using nested lists like I demo'd recently, but it'll need to be built manually rather than using a card. Either that or allow children to be nested inside a card, so you could add a list and display relationships inside.
