### ISSUE TITLE
Budibase DB relationship Filtering

### ISSUE THREAD

**Issue by siegbertus420** [Budibase/budibase#7464]
Why does this feature: [SQL relationship filtering
](https://github.com/Budibase/budibase/pull/4073) not work when using Budibase DB?

**Comment by mike12345567** [comment]
Hi @siegbertus420 - this has been discussed previously in issues:
1. https://github.com/Budibase/budibase/issues/4887
2. https://github.com/Budibase/budibase/issues/2316
3. https://github.com/Budibase/budibase/issues/6039

This is sadly a common issue with Budibase DB that we can't solve particularly easily due to the NoSQL nature of the underlying CouchDB. The use of static formulas is a workaround that we recommend.

Closing this issue has it has been discussed at length before now.
