### ISSUE TITLE
Remove "Like" from internal table filtering as it does not behave the same as other Datasources

### ISSUE THREAD

**Issue by gzh1960** [Budibase/budibase#7467]
**Hosting**
- Self
  - Method: Docker on Linux
  - Budibase Version: 1.2.47
 
**Describe the bug**
Have added a Dynamic filter to a Members screen and when I set a filter constraint as follows Budibase is not displaying data:
Last Name LIKE Bour

**To Reproduce**
1. Load Members Directory Template
2. Click on 'Members' and filters and add a constraint Last Name Like Bour
3. No error just not displaying the expected data.

**Expected behavior**
Display the filtered record.

**Screenshots**
  
![image](https://user-images.githubusercontent.com/6695874/186818142-710818b6-ef81-4b93-9f4c-a5aff1f5f926.png)

![image](https://user-images.githubusercontent.com/6695874/186818824-c82cc14b-dbc4-4be9-8236-4bf99d408129.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [103.0.2]

**Comment by aptkingston** [comment]
Hey @gzh1960. The "like" operator is actually just a "starts with" operator when used with internal tables. It will only perform a real "like" match if used against a SQL table. We know this is a limitation (due to lucene, our search index, not supporting a fuzzy match) and it would probably be better just to hide the option altogether depending on what datasource you're using.

**Comment by gzh1960** [comment]
Thanks for the heads up. I think you should update the doco. I used starts with and it was fine but noticed the like would not work and wondered why!

Like is important for other DBs e.g. MySql etc so don't know that you should remove it totally.

**Comment by shogunpurple** [comment]
Closing in favour of https://github.com/Budibase/budibase/issues/3386
