### ISSUE TITLE
Binding Text is not passed into drawer

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#7532]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 1.2.56
  - App Version: 1.2.56

**Describe the bug**
Whenever a value is typed into a binding field in the components setting panel, the text is not passed into the binding drawer when the flash icon is pressed.
It's a small thing but I keep making the mistake. Sometimes you start typing text before you realise you need access to the bindings drawer.

**To Reproduce**
1. Save some text to a paragraph component
2. Change the text
3. Click the lightning bolt icon
4. See that the previous text is showing, not the newly typed text

**Expected behavior**
If I enter new text into a binding field, I should see this new text whenever I press the flash icon and enter the bindings drawer.

**Screenshots**
*Enter new text*
![Screenshot 2022-08-31 at 10 25 17](https://user-images.githubusercontent.com/101575380/187645910-b875f268-7c93-479c-ab26-4af9a9afdeca.png)

*Click flash icon. Binding drawer not updated.*
![Screenshot 2022-08-31 at 10 26 15](https://user-images.githubusercontent.com/101575380/187646109-ae075f6e-52f2-42ce-af93-6a67b405cff8.png)

**Comment by aptkingston** [comment]
This is actually just a race condition, and it happens in cloud due to it being slower than a self hosted installation.

We save changes to settings when the components get blurred (we don't do it on every key press because that would spam the server with save requests). When you change the text in a field and then press the lightning bolt icon, the field is blurred at the same time that the drawer begins to open.

The text that is displayed depends on how quickly the save request was processed - if it's quick then the new text will appear, if not then the old text will appear. In my self hosted installation I always see the new text, but in cloud I see the old text.

The hacky fix would be delaying opening the drawer by 500ms when you click the icon, to ensure pending save requests are hopefully finished. We could maybe make it less hacky by explicitly waiting for any pending save requests before opening the drawer but that's not particularly nice either.

A better fix would be reflecting live changes in the drawer if the underlying screen definition changes, but this is also a bad idea because the value should not be able to change when the drawer is already open, and adding this reset functionality could very easily annoy people by accidentically wiping changes to complicated settings (like the filters on a data provider for example) because some field changed in the background.

**Comment by melohagan** [comment]
Closing in favour of: https://github.com/Budibase/budibase/issues/9060
