### ISSUE TITLE
Unable to clear date in Date/Time column in PostgreSQL

### ISSUE THREAD

**Issue by bdelcamp** [Budibase/budibase#7537]
**Hosting**

- Self
  - Method: docker
  - Budibase Version: 1.2.52

**Describe the bug**
Unable to remove date from column.

**To Reproduce**
1. Create column with Date
2. Set date
3. Edit, and highlight date, press Delete.
4. Date clears in dialog, but not in actual database row. This breaks formulas to check if the date is set.

**Expected behavior**
Deleting date in picker dialog should clear date.

 - OS: MacOS
 - Browser Edge, Safari

**Comment by shogunpurple** [comment]
@bdelcamp could you please send an app export with a reproduction?

**Comment by radtkedev** [comment]
@shogunpurple It seems like this bug only happens when using PostgreSQL, I could not recreate this issue when using the internal Budibase database. Using selfhosted single-container docker variant on version 2.1.28.

Steps to recreate this bug:
- Connect PostgreSQL
- Create a new table with the following columns:
  - SomeText (required, Type: Text)
  - SomeDate (optional, Type: Date/Time)
- Create a row with any text or date
- Publish an autogenerated screen
- Edit, highlight the date and press the delete key
- After saving, the date field does not get deleted, no errors are shown
