### ISSUE TITLE
Deployed app - logout does not return you to login screen

### ISSUE THREAD

**Issue by mike12345567** [Budibase/budibase#754]
It seems the routing of the logout button when app is deployed does not return you to anywhere, looks like it will route to:
`https://<APP_ID>.app.budi.live/` instead of `https:/<APP_ID>.app.budi.live/<APP_ID>` which is where the login screens is routed.

We likely should route the first one through to the login screen as well if un-authenticated.

**Comment by aptkingston** [comment]
The logout button in the nav currently just deletes the cookie then reloads the current URL, assuming the client router will then serve the unauthenticated page. It's probably better to address this in the client router than force a navigation to a certain URL since routues will be different in preview and production

**Comment by shogunpurple** [comment]
Seems to be resolved. Closing
