### ISSUE TITLE
Problem with default value Multi-select-picker

### ISSUE THREAD

**Issue by Maxiwork** [Budibase/budibase#7581]
https://www.loom.com/share/7cf7378a99654825a30b765937ac06bc

Impossible to unselect default value. I can unselect default value on my first multi select-picker but not the second.

**Comment by Maxiwork** [comment]
https://www.loom.com/share/af05b2a2d10a4b03b7acd1b4255c38d4

**Comment by Maxiwork** [comment]
Even tried to separate the multi-select-picker, each one inside a view

https://www.loom.com/share/0816dc24692a46cd838855771b4543a7

**Comment by aptkingston** [comment]
Hey @Maxiwork. Are there any errors in the browser console when this happens? Since it works with your first picker (and I am unable to reproduce this myself), I wonder if there is an error in your second one. I also noticed in your video that the second picker includes "Error executing JS" which makes me think that some of your options might be null, making something break with the picker.

Could I also check why you're designing the page this way? If you put your form inside the top level repeater then the fields will automatically default to using the values stored in your row, without the need to manually fill out default value expressions. I noticed that you seem to have arrays of objects stored inside your row though so perhaps you'll need to fill them out manually like this, since it looks like your data was created outside Budibase (as Budibase would only store IDs inside arrays rather than full objects if created via the multi-select picker).

**Comment by Maxiwork** [comment]
Hi @aptkingston, thank you for your answer.

So I put the form inside the top level repeater but I still need to insert something on default value.

My problem is, the default value doesn't appear after the loading of the page.

https://loom.com/share/768accbdac654d7ea71afc1983599e20

I can have my default value on the first but not on my second.

Another problem I have is, when I have 2 selected and remove one, when I click on save, that save the 2 elements and not only 1.

**Comment by melohagan** [comment]
404 on videos. No reproduction steps. Closing!
