### ISSUE TITLE
Object.keys not working in REST Transformer

### ISSUE THREAD

**Issue by tsukhu** [Budibase/budibase#7672]
**Hosting**

- Cloud
  - Tenant ID: tsukhu.budibase.app

**Describe the bug**
Tried to create a transform for the dogs ceo breed list and extracting the keys using Object.keys. This seems to be returning only the first result instead of the array of results

**To Reproduce**
- Create an app
- Define a REST Data source
- API GET call to https://dog.ceo/api/breeds/list/all
- Add the following transformer
```
let myItems = data.message;
return Object.keys(myItems);
``` 
**Expected behavior**
Should get the complete list of breeds but this only returns the first entry

**Screenshots**
![image](https://user-images.githubusercontent.com/846306/188848945-df21f656-af0e-4f7b-9906-27662ccc46b1.png)
  
**App Export**
If possible - please attach an export of your budibase application for debugging/reproduction purposes.
[export.txt](https://github.com/Budibase/budibase/files/9504963/export.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser - Chrome
 - Version 104.0.5112.102

**Comment by mike12345567** [comment]
Hi @tsukhu - this is intentional, if you return an array from a REST transformer then that will be used as the response of the query.

For example if we use your query in a data provider with a table:
![image](https://user-images.githubusercontent.com/4407001/188862494-315b944c-eb9e-4bbb-8693-84f383af5030.png)

You can see the response has been broken into individual rows, queries must always return an array of objects as this is how Budibase works with data, so if you return an array of strings, it will automatically convert the strings into objects in the format of:
```
[
  { "value": "affenpinscher" },
  { "value": "african" },
...
]
```

If you wish to have a single response with all of the dog breeds in it, then you can use a transformer like:
```
let myItems = data.message
return { breeds: Object.keys(myItems) }
```

![image](https://user-images.githubusercontent.com/4407001/188863039-7b30fcbe-eec9-4939-9f1d-662871d365a3.png)
This will still be converted to an array so that you can use it with a data provider/repeater (there is no concept of singular data within Budibase right now).

**Comment by tsukhu** [comment]
Brilliant. Thank you for such a quick response

**Comment by tsukhu** [comment]
@mike12345567 - How can I dynamically create a REST API like this 
https://dog.ceo/api/breed/{{Bindings.breed}}/images/random

- I guess this is not valid
What I want to do is to call the API on clicking the breed in the list generated with the earlier API

**Comment by mike12345567** [comment]
Hi @tsukhu - this is possible, you just need to use `https://dog.ceo/api/breed/{{breed}}/images/random` instead of the dot syntax. Bindings are simply top level attributes based on the name you've set.
![image](https://user-images.githubusercontent.com/4407001/188887966-daf31088-dcbc-48b0-9fc1-66d5e6412677.png)

**Comment by mike12345567** [comment]
Hi @tsukhu - thought it might be easier to explain with an app export, here is an app with what you were describing within.

[dog-export.txt](https://github.com/Budibase/budibase/files/9506607/dog-export.txt)

**Comment by tsukhu** [comment]
@mike12345567  - Thank you for this. It works as expected .
The power of exporting the entire project as json meta data is really a winner !
