### ISSUE TITLE
CSS Cascade Issues - Make components respect CSS hierarchy

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#771]
When you apply styles at the top level in budibase, there are quite a few issues with them not being reflected. For example, `h2` elements have their color hardcoded, so any changes to text color in the parent is not reflected.

All budibase components should respect CSS classes and hierarchy. This prevents people having to tinker with individual components as much which can be frustrating.

* Update all budibase standard-components to respect CSS hierarchy

**Comment by aptkingston** [comment]
I think ideally we would specify as few CSS properties as possible in the components themselves, since they can't be overridden. The problem then is making things look acceptable by default. It would be cool if we updated `temporaryPanelStructure.js` to allow definingh default styles for components. That way we could make them look good by default but also be changed.

**Comment by shogunpurple** [comment]
yep - that's the problem we are facing. I guess there are certain things we shouldn't default, like text colours. I like the idea of default styles - a base of styles for all components of that type
