### ISSUE TITLE
app creation error on fresh docker install

### ISSUE THREAD

**Issue by gkibria** [Budibase/budibase#7714]
**Hosting**

- Self
  - Method: docker single image
  - Budibase Version: 1.3.11

**Describe the bug**
App creation failed on a freshly installed single docker image.  for errors, see the screenshot

**Screenshots**
![Screenshot 2022-09-09 at 22 47 28](https://user-images.githubusercontent.com/7963363/189440924-93fb1592-2976-4310-9ea8-541bc17b15b4.png)

OS : Ubuntu arm with aapanel

what is wrong? Thanks

**Comment by MarcusSorealheis** [comment]
@gkibria Is this a regression from previously observed behavior? I think a little bit more information is needed because this error occurs when the system is checking to ensure an S3 bucket exists from my reading [here](https://github.com/Budibase/budibase/blob/f7b76f625d29d598f8627353de3c6cc5d1d4bd67/packages/backend-core/src/objectStore/index.ts#L96). Can you paste the command you are using to start the container? Any customizations?

**Comment by gkibria** [comment]
Hi @MarcusSorealheis I have created the container according to the instruction https://hub.docker.com/r/budibase/budibase No customization
