### ISSUE TITLE
Error creating app

### ISSUE THREAD

**Issue by mralesssss** [Budibase/budibase#7744]
- Self-hosted
-  Method: docker single image (updated to the newest)
- Budibase Version: 1.3.15

Hello. Every time i want to create an app, i get the: "Error creating app"
Thank you! 

Best regards

**Comment by aptkingston** [comment]
Hi @mralesssss. We need more information in order to help you. Can you please provide some other form of logs?

Useful information would include:
- Browser console errors
- Network response when app creation fails
- Docker container logs
- Does this happen with templates, create from scratch, or both

App creation works perfectly fine in 1.3.15 (I have just tested this), so this must be something to do with your environment.

**Comment by mralesssss** [comment]
Hi @aptkingston. It happens with templates and from scratch. The Browser console shows this error:
![image](https://user-images.githubusercontent.com/113243505/189962596-d9bd9fc5-1468-4138-bb20-0b517aef2278.png)
Thanks for the support!
