### ISSUE TITLE
Automations - Query Rows - Enable SQL queries as sources

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#7751]
Currently you can only select a table as the Data Source of a Query Row action in Automations
The user should be able to also use Queries as Data Sources

**Comment by mike12345567** [comment]
Hi @poirazis - this is by design, the query rows feature is for tables which have much more extensive filtering capabilities vs queries. If you wish to run a query then you can use the `External Data Connector` action which allows the more limited queries to be performed.

It is possible to filter over queries in the frontend which may cause some confusion - but automations run on the backend which does not have this capability.

**Comment by poirazis** [comment]
Thank you @mike12345567 !
