### ISSUE TITLE
Custom component not listed in "Add component" sidebar

### ISSUE THREAD

**Issue by andreasbhansen** [Budibase/budibase#7885]
**Hosting**
- Self
  - Method: docker compose
  - Node: v16.13.2 
  - Budibase Version: CLI v1.4.7 (globally installed)
  - App Version: Installed v1.4.7

**Describe the bug**
Can't see my custom component in the "Add Component" section of the UI builder. See below for additional details. Am I missing something obvious here?

**To Reproduce**
1. Followed the instructions for [Hot reloading (developers only)](https://docs.budibase.com/docs/custom-plugin#hot-reloading-developers-only) although I didn't clone the repo but instead used the [Docker (compose) setup](https://docs.budibase.com/docs/docker-compose). Does this perhaps not work?
2. Within the plugins folder I created on my machine, I init'ed a new component (`budi plugins --init component`), called it `budi-datatable` and gave it a `"friendlyName": "BudiDataTable"`.
3. I updated the `PLUGINS_DIR` environment variable, and I can verify with Docker Desktop in `bbapps`' inspect tab that the variable is set correctly (`/Users/andreas/Documents/projects/budibase-related/budi_plugins`). 
4. Whether I use `yarn watch` or `budi plugins --watch` within my plugin's folder makes no difference as to the component not being visible in the builder.
5. I start Budibase through Docker compose, and it is running on `http://127.0.0.1:10000/builder` and it is working fine.
6. I try to find the component, but alas (it's also not present on the Portal's "Plugins" page):
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1404793/191589460-192280e1-9154-4f96-a61d-559456e11833.png">
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1404793/191590131-6e858088-0726-4d02-9f68-111945a6679b.png">

**Expected behavior**
Having the custom component readily available in the Budibase builder UI, and that it would live-reload when changed.

**Screenshots**
Nothing else to show than the error stack above. 

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser: Chrome
 - Version: 105.0.5195.102 (Official Build) (x86_64)

**Comment by aptkingston** [comment]
Hey @andreasbhansen. The only extra thing you'll need to do since you're running the compose stack, rather than cloning the repo, is actually mount your plugins directory as a volume to the `app-service` container. You aren't seeing any plugins because docker containers have no visibility of your file system unless you make them available!

Assuming you're running the full compose stack rather than the single image, the steps you need to do are:
- Mount your plugins directory inside the app-service container
```yaml
volumes:
  - /Users/andreas/Documents/projects/budibase-related/budi_plugins:/plugins
```
- Just use `/plugins` as the `PLUGINS_DIR` environment variable, because that's the path the container sees your mounted directory under
```yaml
environment:
  PLUGINS_DIR: /plugins
```

Once you start up that stack everything should work and it should automatically import your existing plugins. Hot reloading should then work fine once you run a watch command in one of your plugin directories.

**Comment by andreasbhansen** [comment]
Thanks, @aptkingston! The changes worked, and I can now use the component in the builder and it live reloads as intended 👍
