### ISSUE TITLE
Budibase with Helm Installation - No redirect to Login Page

### ISSUE THREAD

**Issue by nirajdesai29** [Budibase/budibase#7926]
I have installed budibase with HELM with the latest chart.

As of now , when creating organization and admin , it all runs gracefully, but then the page does not move from admin to login.

I even recieve the message that admin has been created. I checked the same behaviour on different browsers and it is the same.
Upon checking the logs , it says when clicking add the admin , it surely imports the data to the DB but then there is no rediret to login page

https://user-images.githubusercontent.com/93580333/191942637-a55b9037-37c1-4a22-a7cd-133a6e99eff1.mov

Can you look into it .

I will add a video for better understanding.

**Comment by nirajdesai29** [comment]
@shogunpurple  can you take a look into this one?

**Comment by eltomato89** [comment]
Got the same problem!

**Comment by alonronin** [comment]
same here

**Comment by moloti** [comment]
Same problem

**Comment by eltomato89** [comment]
bump

**Comment by eltomato89** [comment]
unstale

**Comment by Rory-Powell** [comment]
Hi all, this one should have been resolved in these fixes: 
https://github.com/Budibase/budibase/pull/9074
https://github.com/Budibase/budibase/pull/8814

The root of the issue was how budibase interprets `process.env` values, the logic required to turn e.g. `"0"` into a flasy flag: `0`, was not running correctly. This only affected the helm deployments where args are always submitted as strings.

The issue you are seeing above is with the `MULTI_TENANCY` flag being incorrectly set to true, which should be disabled by default in any self hosted install. This isn't officially supported in self hosting yet. 

Pulling the latest helm chart should fix things
