### ISSUE TITLE
Partially migrated app navigation settings are not migrated again upon import

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#7966]
A screen slot appears instead of components within the design section.
https://vimeo.com/753160929/68a2429a54

With the new release, I think screens with a custom layout or created at a certain time will be broken until the detach action is completed.

BB Cloud
Tenant: BB
App: recruit

**Comment by aptkingston** [comment]
Is this just when importing an old app? So you have an old app export from before July, you import it, and then you have to manually detach every screen?

This was the way old app imports worked before some recent changes which were supposed to do all that detaching automatically, so just looks like that new logic isn't working.

This isn't breaking though right? It's just you need to do the manual detachment of each screen for old apps again.

**Comment by aptkingston** [comment]
I've checked with that specific app, and the reason the migration didn't work is because that app already had navigation settings. That means you must have already imported this app (before we had automatic migration), manually migrated a few screens, then exported it again. Because it already has existing navigation settings, the server correctly did not overwrite those settings again.

I'll add a change so that if existing navigation settings exist it still won't update those, but it will at least still do the screen detaching, if required.

**Comment by aptkingston** [comment]
And I've confirmed that normal old apps (e.g. templates) still function properly and are fully migrated, so I'm bumping down the severity here as everything is working and this is a rare edge case.
