### ISSUE TITLE
permissions on rows on internal tables

### ISSUE THREAD

**Issue by yeoldegrove** [Budibase/budibase#8013]
**Describe the feature request**
It would be great if one could assign read/write access permissions (to roles) on a per row basis for internal tables.

**Comment by mike12345567** [comment]
Hi @yeoldegrove - this is something that is covered by two issues currently:
1. #3421 - more advanced controls to allow configuring a table so that users can only update their own rows.
2. #5320 - A larger re-work of the RBAC system to allow per-row controls, this is quite a bit project and so has been split out.

I'm going to close this issue as it will be tagged on the advanced RBAC issue - it is something we are already aware of and is in the pipeline.
