### ISSUE TITLE
Poor mathematical calculations

### ISSUE THREAD

**Issue by schiz0phr3ne** [Budibase/budibase#8140]
**Hosting**

- Self
  - Method: docker compose
  - Budibase Version: 1.4.7
  - App Version: 1.4.7

**Describe the bug**

With basic formulas (substract and multiply), expected results are not those obtained.

Given example (see screenshot) : 
- 45 - 49.2 = -4.200000000000003
- (45 - 49.2) * 12 = -50.400000000000034

Formulas : 
- {{ subtract pv_mensuel pa_mensuel }}
- {{ multiply (subtract pv_mensuel pa_mensuel) 12 }}

**To Reproduce**

Not sure if this bug can be reproduced elsewhere, and how.

**Expected behavior**

- 45 - 49.2 = -4.2
- (45 - 49.2) * 12 = -50.4

**Screenshots**

![image](https://user-images.githubusercontent.com/22858496/194080912-df80112d-0c25-4e09-b5e9-ae386f78d540.png)
![image](https://user-images.githubusercontent.com/22858496/194083694-8d696d1c-1d7e-4c31-9bd7-a9b0e2a1ff21.png)
![image](https://user-images.githubusercontent.com/22858496/194083794-e219c0de-1557-442c-ac1f-53095bdd457e.png)
  
**App Export**

Not possible as customers data are in.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox
 - Version: 105.0.1

**Comment by FlaminWrap** [comment]
Sounds like floating point math issues e.g. 0.1 + 0.2 = 0.30000000000000004

**Comment by shogunpurple** [comment]
Hi @schiz0phr3ne - this is not a bug with budibase - it's a [floating point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic) problem. When you run the following in JavaScript:

`45 - 49.2` 

You will get the same answer. ` -4.200000000000003` - this is because of the way a computer represents numbers in base 2. For example in "real life" - we cannot represent 1/3 (base 10) as a decimal - you get the recurring `0.333333333333333333333` etc. This problem is basically the same thing with computers, except with certain values that cannot be represented in binary (base 2).

You can of course round the numbers (using JS etc), but if you need exact figures you will not be able to use JavaScript to represent that, as it cannot represent these numbers (0.1, 0.2 etc) exactly.
