### ISSUE TITLE
Duplicate users in budibase which can not be deleted.

### ISSUE THREAD

**Issue by Cityjohn** [Budibase/budibase#8179]
I am self hosting budibase 1.4.7.

I tried the Budibase API with Python to create a user and first deleted one with a spare Email I have laying around but now I have two of those users with the same email and I can't delete them anywhere. They do not show up in my CouchDB either.

How can I delete the users permanently?

![image](https://user-images.githubusercontent.com/34970833/194742335-9093ab20-d426-49fa-a11a-44fe51722851.png)

![image](https://user-images.githubusercontent.com/34970833/194742133-462895f3-c1c2-4e01-bae0-c28b44cbe998.png)

![image](https://user-images.githubusercontent.com/34970833/194742157-1fceabde-4881-405a-ab64-2e5a6d714f5a.png)

**Comment by Cityjohn** [comment]
Trying the API Delete user did not work.

![image](https://user-images.githubusercontent.com/34970833/194742741-2ec9e637-ff74-4e5b-8912-7d846b465a06.png)

**Comment by Cityjohn** [comment]
Nvm, had to delete them from all applications in CouchDB.

**Comment by Rory-Powell** [comment]
Hi @Cityjohn, this is by design in order to preserve data that has been linked to historical user information. This is similar functionality to other apps where the removed user appears as inactive but their details and metadata are still available, e.g. message author in messaging apps, assignee in ticketing apps. In Budibase's case the `status` field on the in-app user will become `inactive`, the user will no longer have access to the platform or be able to log in to view any of your apps.
