### ISSUE TITLE
Step form disappearing from screen

### ISSUE THREAD

**Issue by edrisi6** [Budibase/budibase#8275]
### Discussed in https://github.com/Budibase/budibase/discussions/8272

<div type='discussions-op-text'>

<sup>Originally posted by **edrisi6** October 16, 2022</sup>
and shows again once the component edit is opened and the step is selected

https://user-images.githubusercontent.com/4608742/196026233-3bcc8bcf-756f-4028-8c36-c0f7e4a3affc.mov

</div>

**Comment by aptkingston** [comment]
Hi @edrisi6. This is normal behaviour. Only the form step that is selected is displayed when you're inside the builder. This is because you might have lots of form steps and showing them all would be both confusing and hard to work with.

There seems to be an edge case that if you are on the screens tab and toggle between design and data, the selected form step is not reselected until you go back to the components tab. If you stay on the components tab then this works properly, and you can toggle between design and data.

I would encourage you to stay on the components tab before toggling between design and data if you are working on form steps.
