### ISSUE TITLE
New Account can't create app - Access Denied

### ISSUE THREAD

**Issue by LuD1161** [Budibase/budibase#8351]
**Hosting**
- Cloud
  - Tenant ID: securemyorg2.budibase.app

**Description**
I've been trying the same thing and it's showing `access denied`. I am using my company gmail to signup. I also verified my account. Still the same error 🤔 
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/17861054/197194825-86de01bc-f690-47ca-9af6-0512b7345491.png">

I logged out of my account and tried relogging in . No issues there. But when I create an app or *Edit an app* , it shows *Locked by you* and in the error box it shows *Error initialising app: Not Found*

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/17861054/197195250-41f69fea-9b67-4fbf-947f-83b14057b28a.png">

**Desktop (please complete the following information):**
 - OS: iOS 12.3.1 
 - Browser - Firefox 105.0.3 (64-bit)

I checked this issue as well #5738 , same issue I guess.

**Comment by shogunpurple** [comment]
Hi @LuD1161 - this one should now be resolved, thanks for reporting!

**Comment by LuD1161** [comment]
Hey @shogunpurple 👋 
What was the issue 🤔 

Will I face the same issue on self-hosted version ?

**Comment by shogunpurple** [comment]
Hi @LuD1161 - we had a small issue in our cloud earlier that we have since resolved - it will not happen in either environment now.

**Comment by ShowMeIT** [comment]
Hi,

I have just sign up for an account, when I try and create an App from scratch I get 'Error initialising app:'
![image](https://user-images.githubusercontent.com/51915383/197307031-42629b40-645f-4c11-b64c-1a2880643350.png)

Hosting: Cloud
Desktop:
Windows 11, Have tried Edge & Chrome, Have logged out and back in on both.

**Comment by tbankstemp** [comment]
I'm having the same issues. 

When clicking on my app, or after importing an app and then clicking on it. I get what's in the screen shot. I'm testing locally, self-hosted, using docker with the single (all-in-one) image "budibase/budibase:latest"   
The update section shows I'm using [2.1.14], had the same issues yesterday with 2.1.13, and 2.1.11. 

![Screenshot at 2022-11-04 11-41-58](https://user-images.githubusercontent.com/9778528/200022754-59e463f9-2716-406e-992b-faf5562f1aba.png)

Tried creating new apps, adding templates, and get the same results. Also, went back to the version I knew worked, when I exported/backedup my apps, and that is also not working(v2.0.30 and v2.0.37).

I also noticed that after I create an app, budibase logs me out. This also happens when creating a new app after the first one and will not create a new app after...if that makes sense.

I've read through some of the other issues with "Error initialising app: Not Found", also tried multiple browser, as well as setting up a docker environment on a different computer, but nothing has worked.

Any insight would be appreciated. 
Thanks
