### ISSUE TITLE
Filtering by current date doesn't return data on internal DB

### ISSUE THREAD

**Issue by nunopoco** [Budibase/budibase#8385]
**Hosting**
- Self
  - Method: digital ocean
  - Budibase Version: 2.0.33

**Describe the bug**
Filtering by date is not working for internal DB if the Table is not the Current User's data.

**To Reproduce**
1. Create a table with a date field;
2. Add two screens, one for basic role and another for power role;
3. Add a data provider on both and a table beneath them;
4. Set the basic role data provider as coming from current user's table entries;
5. Set the power role table data provider as coming from the whole table;
6. Filter both by date below the current date, using JS: "return new Date().toISOString()";

**Expected behavior**
The power role table should return as many or more results than the basic role user's table.

**Video walkthrough**
https://nuno.dubb.com/v/3pcM8l
  
**App Export**
[Processos-export-1666658575059.txt](https://github.com/Budibase/budibase/files/9856212/Processos-export-1666658575059.txt)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 106.0.5249.119

**Comment by melohagan** [comment]
@nunopoco Thanks for the detailed repro steps and video!

As a note, I don't think this has anything to do with roles, it seems to simply be a difference in how date filtering is handled between data retrieved via current user, and data retrieved via the regular table search endpoint.

**Table search**
![Screenshot 2022-10-26 at 10 30 01](https://user-images.githubusercontent.com/101575380/197990489-9b7d413e-0d2a-4a36-8f1e-4c07e747655b.png)

**User search**
![Screenshot 2022-10-26 at 10 32 04](https://user-images.githubusercontent.com/101575380/197990932-503b1676-5f86-4330-add0-b2ae2f986422.png)

**Comment by melohagan** [comment]
Hey @nunopoco 

I found out what is wrong. The date filter is trying to filter against `Pronto_para_o_dia` when the field name is actually `Pronto para o dia`

When I renamed that field to simply `pronto` the date filtering started to work for me.

**Comment by melohagan** [comment]
@nunopoco I'm going to close this issue because it's not actually to do with date filtering. It seems that your couchdb index got out of date. This can happen when upgrading from a very old version of Budibase.

Please follow the guide I outlined to you previously: https://github.com/Budibase/budibase/discussions/7777#discussioncomment-3732390

But this time, expand the *Search Indexes* section and click *Edit* under the spanner icon: 

![Screenshot 2022-10-26 at 15 00 14](https://user-images.githubusercontent.com/101575380/198046490-1e30cca3-d718-4e2f-bb24-72b7c6a97767.png)

On the highlighted line that has the replace function, add the letter **g** after the `/ /`.
**Save document and build index**
And then the filtering in your app should work. 

**Filtering working in your app:**
![Screenshot 2022-10-26 at 15 06 50](https://user-images.githubusercontent.com/101575380/198048172-3f25b538-9045-4995-a056-01acd2f44dbf.png)
