### ISSUE TITLE
Allow disabling of specific dates in Date Picker

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8415]
**Describe the feature request**
As a user, I want to specify a list of dates that should be disabled in the date picker.
Related discussion: https://github.com/Budibase/budibase/discussions/8402

https://flatpickr.js.org/examples/#disabling-specific-dates

**Comment by melohagan** [comment]
Hey @daanvdberg12 at some stage we are going to replace the current date picker component, but there is no timeline on this for now.

Closing in favour of: https://github.com/Budibase/budibase/issues/11894

**Comment by Gtchik** [comment]
Hey,

I really needed this feature in my project, and since it isn't currently supported natively, I came up with a workaround inspired by the discussion mentioned here #6839 

Admittedly, the solution is not the cleanest, but it gets the job done for my use case. Here's the code I integrated into an `embed` block:  

```
<img style="display: none;" src onerror="
  if (document.readyState === 'complete' || document.readyState === 'interactive') {
    initializeObserver();
  } else {
    document.addEventListener('DOMContentLoaded', initializeObserver);
  }

  function initializeObserver() {
    const targetDates = ['Friday, December 13, 2024', 'Tuesday, December 17, 2024']; 

    const observer = new MutationObserver(() => {
      targetDates.forEach((targetTitle) => {
        const cells = document.querySelectorAll(`td[title='${targetTitle}']`);
        
        cells.forEach((cell) => {
          if (!cell.dataset.disabled) {
            // Remove existing events by replacing the element with a clone
            const clone = cell.cloneNode(true);
            clone.addEventListener('click', (event) => {
              event.stopPropagation();
              event.preventDefault();
            });

            // Apply a style to indicate it is disabled
            clone.setAttribute('aria-disabled', 'true');
            clone.dataset.disabled = 'true';
            clone.style.opacity = '0.5';  // Make the element visually dimmed
            clone.style.pointerEvents = 'none';  // Disable user interactions

            // Strike through the textual content
            const dateSpan = clone.querySelector('.spectrum-Calendar-date');
            if (dateSpan) {
              dateSpan.style.textDecoration = 'line-through';
            }

            // Replace the old element with the clone
            cell.parentNode.replaceChild(clone, cell);
          }
        });
      });
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true, // Also observe child elements
    });
  }
">
```

This script listens for DOM changes, locates cells with specific date titles, and applies a "disabled" effect to those cells. The key steps are:  
- Cloning the cell to remove existing event listeners.  
- Disabling user interactions and visually dimming the cell.  
- Adding a strikethrough effect to indicate the cell's state.  

I hope this helps anyone else facing a similar issue. Feedback is welcome if there's a better way to achieve this!
