### ISSUE TITLE
Relationship data in record view is not responsive

### ISSUE THREAD

**Issue by joebudi** [Budibase/budibase#846]
**Describe the bug**
If you create long-form content for a relationship - such as notes - it is not displayed accordingly in the app.

**To Reproduce**

1. Create two tables. 1 table must be notes/long-form content.
1. Relate both tables
1. Add long-form content to the notes table
1. Check the detail screen for that table in the frontend

**Expected behavior**
Tricky one, I feel we need a long-form data type to begin with.

**Screenshots**
![Screenshot 2020-11-09 at 20 30 05](https://user-images.githubusercontent.com/49767913/98593277-d491df80-22ca-11eb-856a-d33dfe58d300.png)

**Desktop (please complete the following information):**

* Mac

**Comment by aptkingston** [comment]
The actual relationship text there is clipped and is responsive, so I think that's maybe just needing some better styling on the form to stop the inputs overflowing. I'll throw something in to stop that.

You're right though about a long form data type. Something that uses a textarea by default rather than an input. We could just do "Long text" as well as "Text".

**Comment by kevmodrome** [comment]
@shogunpurple and I discussed types for the Rich Text Component last week and we landed in adding a longText type, the quill component I built for the hackday is pretty much ready to go as well, so not too much work to get it added

**Comment by shogunpurple** [comment]
@aptkingston did you add the form fix in your current branch? @kevmodrome I think the long form work is dependent on this one https://github.com/Budibase/budibase/issues/807. Is it possible to get the `LongText` component merged into standard-components without having this type available? Then we can wire it up afterwards, seems like a viable option

**Comment by kevmodrome** [comment]
Yes, I'll get on it right away

**Comment by aptkingston** [comment]
I didn't actually but that's not a bad thing because my branch is completely mangled and broken and will likely stay that way for a few more days haha. Could throw that change in with the PR for the LongText component whenever that comes around. I think this fix is as simple as adding an extra `overflow: hidden` or two.

**Comment by shogunpurple** [comment]
All good, sounds like a plan. Cheers folks!
