### ISSUE TITLE
Using Like in dynamic filter not working properly

### ISSUE THREAD

**Issue by muksidin** [Budibase/budibase#8477]
**Hosting**

- Self
  - Method: Docker single image
  - Budibase Version: 2.0.37
**Describe the bug**
I use LIKE in dynamic filter but it seems not working properly. it doesn't show something in field.
![Screenshot_20221102_025431](https://user-images.githubusercontent.com/5665115/199328677-a6c54ddb-112d-4ae6-aa51-2c2b4296e8e1.png)

**Comment by mike12345567** [comment]
Hi @muksidin - just to confirm, is the underlying table an internal table? If this is the case, then it is like this issue you are experiencing - https://github.com/Budibase/budibase/issues/7467

**Comment by muksidin** [comment]
yes internal table, i think before using `LIKE` is such as in MySQL query. But in this case (budibase) there is no result.

**Comment by mike12345567** [comment]
Hi @muksidin - yes sadly the Budibase internal table does not provide a `LIKE` operator, similar to what you get with a SQL database - I'm going to close this issue as the underlying issue is that we need to hide the `LIKE` option for internal tables - as discussed in https://github.com/Budibase/budibase/issues/7467.
