### ISSUE TITLE
Unable to edit Data Providers and fields on some pages

### ISSUE THREAD

**Issue by adamjdavies** [Budibase/budibase#8483]
**Hosting**
  - Tenant ID: tern 
 
**Describe the bug**
I've been unable to edit/update Data Providers and some fields on specific pages within my BB app. On some pages I can edit static text fields and update the Data Providers as expected, however on others I'm getting the error **Error updating component prop** when trying to edit either static text fields or Data providers. 

There doesn't seem to be any consistency to this issue as on the pages where I can update fields and Data Providers are a similar structure and use similar data sources to the pages where I can't. 

**To Reproduce**
1. Navigate to a page containing a Data provider
2. Try to edit the data provider

**Expected behavior**
I expect to be able to update data providers and text fields at all times without any issues. 

**Screenshots**
  
![Screen Recording 2022-11-02 at 10 07 04](https://user-images.githubusercontent.com/64409787/199464268-063ad7b8-71c9-4901-b0b0-aa44c8b35430.gif)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6 
 - Browser: Chrome Version 
 - Version: 107.0.5304.62 (Official Build) (arm64)

**Additional context**
I updated to BB v2.1.4 and saw this issue. I then reverted back to v2.1.1 but that didn't seem to fix anything.

**Comment by FlaminWrap** [comment]
I get this error in the browser console when trying to select a date from the date picker, do you also get that? 
![image](https://user-images.githubusercontent.com/97764630/199475791-02d84967-faf2-42aa-8a25-a65bc374d6f8.png)

**Comment by adamjdavies** [comment]
Tested again today after the newest release but still having the same issue. This is one error I'm seeing in the inspector:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/64409787/199683998-ae4b5199-2ea5-4c8e-9014-2da5e5743a3a.png">

Any ideas?

**Comment by adamjdavies** [comment]
Others are having this issue to as reported on #8495

**Comment by stellarfinn** [comment]
All the errors below are happening on some, but not all, screens.

Getting the following error when attempting up change component settings such as Name, Text, Size, etc. 

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/99847728/199742766-479d7809-d328-47cd-a3d2-62c7787f9a72.png">

Getting the following error when attempting to add a new component to the screen
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/99847728/199743070-302a31e9-e40a-4436-80b7-3c9ee2d77143.png">

Attempts to duplicate the screen and see if a new copy will work result in the following error:
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/99847728/199743341-beeafb24-1152-454b-903f-c1a101a91c7c.png">

The issue seems isolated to screens at random and I cannot identify anything in particular that stands out on those screens. Other screens appear to be fine.

**Comment by adamjdavies** [comment]
Appears to be fixed now.
