### ISSUE TITLE
Normalise Pages and Screens

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#849]
Pages **contain** screens in the database. This means you have to update 2 places when saving a screen.

We should move all screen related data out of the pages document, and link it back via ID if required.

**Comment by aptkingston** [comment]
I think ideally we'd remove pages altogether and move to a single flat structure of just screens wouldn't we? And let user role / logged in status be a configuration setting for each screen. Maybe that's further down the line but reducing duplication in the mean time is a good call definitely 👍

**Comment by mike12345567** [comment]
@aptkingston the problem with removing pages altogether is that they are used as the master screen currently, replacing them in that way could be difficult but I agree removing them should be our goal.

As part of this we will also want to have a look at the static `clientFrontendDefinition.js` which the previewed/deployed apps load to get the context of the pages and screens they are working from. The work towards new routing has suggested loading this file all at once will make things difficult moving forward, so in the process of this re-factor we should look at having the server provide the screen definitions out instead.

Access doesn't need to be attached to a page anymore as this is only really a binary access system of logged in or not logged in, instead our new access system is determined based on routing and therefore we should remove the attachment of pages to whether or not the user can view a screen, it should simply come down to their logged in (or not logged in) access level and what screens they can route to, making public screens viable.

Pages as they are today could be converted into a master screen feature instead, renaming this everywhere they are still used and the screens could link to their parent master screen instead of the pages containing all the screens.

**Comment by mike12345567** [comment]
## The design
The goal we have for this issue is to make the purpose of pages and screens very clear, with an overarching goal of simplifying the system. Today pages and screens are fairly inter-tangled and it isn't clear what purpose each one serves, for example the login page has no screens, it simply specifies a login component, while every other page in the system must be populated with a screen.
We believe the best approach is to try and remove pages and instead replaced them with a single entity, a `layout screen`. The naming of this is still to be decided but all the layout screen offers is a rough layout, like a header bar and then a `slot` component in which the screen will be inserted (currently this is the `screenslot` in the page). This will provide the following:
1. Screens will manage access levels, as part of a screens settings there will be three options:
   * The access level, this by default will be logged in
   * The screen layout which this screen inherits from
   * The route the screen appears on
2. The routing structure on the left hand side panel will appear as such:
![image](https://user-images.githubusercontent.com/4407001/99410526-7b3d3800-28ea-11eb-9ac2-a81423e293ae.png)
but with the addition that at the top of an option to pick between *Screens* and *Screen layouts* or whatever the name is decided to be. The screen layouts will simply be what we consider to be the current master screen, offering a layout that surrounds the main slot.
3. Finally the initialization process is greatly simplified as today creating a new screen requires calling to the API to create the screen, then calling again to update the page with the reference of the screens. This is pointless and creates race conditions, originally we had thought we would make this part of the process internal to the server so that saving the screen carries out all necessary work and the builder can move on once the screen is fully saved; this is however pointless given that pages don't really do anything now other than offer a redundant form of access control and the screen layout functionality. Instead if we get rid of them then saving the screen with its CSS and the screen layout it is linked to all the work can be performed in a single call easily.

Pages will become the screen layouts, removing their access control element and re-naming them as well as removing their references to the screen itself. The idea here is that the screen layouts can exist without any screens existing around them and then the screens can be brought up with a link to the correct screen layout.

## Work required
There are a few bits of work required to make this happen:
1. Remove all use of the access control provided by pages, this is mostly client side currently and with the client and SDK re-work it makes sense that we could try and remove this.
2. Make the access control provided by screens the main functionality of the system, ensuring that public screens can be used for logins etc.
3. Replace what is left of pages with the screen layout system, fixing up how this looks in the builder UI and removing their links to the screens.
4. Update the screen API so that saving a screen performs all necessary actions for a screen to be usable.
5. Create a login screen as currently the unauthenticated page handles all of the login functionality.
6. Update the client and builder to use a new cutdown `appPackage` call which controls the screens a user has access to (in the case of the client).
