### ISSUE TITLE
When there are no rows, the 'Create' type form block has no fields

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8577]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.15
  - App Version: 2.1.15

**Describe the bug**
When creating autogenerated screens, the Create `/new/row` screen will have no rows if the table has no rows. 

**To Reproduce**
1. Add a Budibase DB table without any rows
2. Auto generate screens
3. Got to `/new/row` screen
4. See that there are no form fields to fill out
5. Add a row manually to your table
6. The `/new/row` screen will now show form fields

**Expected behavior**
When my table has no rows, I should see the fields in a form block when it is in 'Create' mode.

**Screenshots**
![Screenshot 2022-11-08 at 09 41 55](https://user-images.githubusercontent.com/101575380/200530323-ab07ab7d-c85a-47f9-8b62-4c89839491b9.png)

![Screenshot 2022-11-08 at 09 42 23](https://user-images.githubusercontent.com/101575380/200530423-c88f1d8c-6696-40f3-82d4-84562ae4bd0f.png)

---

**Now manually add a row to the table**
![Screenshot 2022-11-08 at 09 43 13](https://user-images.githubusercontent.com/101575380/200530681-6a5a3359-8a84-4515-afcd-1ea090a22575.png)

![Screenshot 2022-11-08 at 09 42 58](https://user-images.githubusercontent.com/101575380/200530585-35cea97c-2907-4198-bf9a-6ffa86c961da.png)

**Comment by chrismb23** [comment]
@melohagan I’m experiencing this issue also on the hosted (cloud) version of Budibase.

**Comment by avivkri** [comment]
@chrismb23,

As a temporary workaround for New row screen, you may eject the Form block, keep only the Form intact and remove the Data provider and the Repeater components.

**Comment by aptkingston** [comment]
I'm pretty sure this is because of the hot fix that was released recently - I commented on that issue that I expected that it would prevent create forms from working at all as it passes a reference to the real data provider, which contains 0 rows when using a create form.

Original issue: https://github.com/Budibase/budibase/issues/8493
Hotfix: https://github.com/Budibase/budibase/pull/8489
My input on the fix: https://github.com/Budibase/budibase/pull/8489#issuecomment-1305547508

Rather than revert the hot fix, I'll push a fix to fix both the original issue and this new regression.
