### ISSUE TITLE
Exported tables doesn't have auto columns.

### ISSUE THREAD

**Issue by pakin1** [Budibase/budibase#8630]
**Hosting**

- Self
  - Method: Digital Ocean and then I exported my app to Budibase.com 
**Describe the bug**

Can't export auto columns. File export.csv doesn't have auto columns.

**To Reproduce**
1. Go to export.
2. Open csv file.
3. There's no User ID data. (Created by, Updated by)

I'm using BudibaseDB.
I have 2 tables - Clients and Users
When I'm trying to edit Created By or Edited By auto columns I'm getting this text in red. 

`Column name already in use in table Users`

**Expected behavior**
Export JSON or CSV file with Auto Columns.

**Comment by melohagan** [comment]
Hey @pakin1 

That particular error message is no longer shown in the latest version of Budibase.

As for the relationship columns, they are purposefully excluded from the table exports. This is because the relationship ids are only relevant to a particular app instance. 
If you exported a table with relationships and imported them into another app, the relationships would be invalid.
