### ISSUE TITLE
App disappeared after Budibase update

### ISSUE THREAD

**Issue by arladmin** [Budibase/budibase#864]
Hi, i opened my Budibase Builder on my Windows 10 system, today.

I have one app, and it was visible there.

Then i saw the notification to restart the builder to update, which i did. After the restart, my app is no longer visible!

**Comment by shogunpurple** [comment]
@arladmin Im sorry to hear you have had an issue after the update.

Unfortunately, your app has been lost because we have made a fairly large breaking change to the way Budibase applications work under the hood.

As mentioned in our docs and README, we recommend not to use Budibase for production applications at this time as it's still under heavy development during beta. These breaking changes are necessary to help us deliver an awesome product for launch.

Getting Budibase production ready and ensuring total backwards compatibility for apps is our number one priority as a team, and should be completed very soon.

Thanks so much for the feedback and for using Budibase!

**Comment by joebudi** [comment]
@all-contributors please add @shogunpurple for code

**Comment by shogunpurple** [comment]
@all-contributors please add @shogunpurple for code

**Comment by shogunpurple** [comment]
Should be resolved in latest release.
