### ISSUE TITLE
Ejecting a form block without any fields selected results in error

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#8643]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.1.23
  - App Version: 2.1.23

**Describe the bug**
The eject button should not be available if ejection is invalid.

**To Reproduce**
1. Add a form block
2. Do NOT select any fields
3. Click Eject block
4. Confirm
5. Nothing happens - see error in console.

**Expected behavior**
If no fields are selected, the eject block option should not be available / be disabled.

**Screenshots**
![Screenshot 2022-11-11 at 09 41 24](https://user-images.githubusercontent.com/101575380/201312410-64da2211-1ae9-4af8-941d-a43cb60de71c.png)

![Screenshot 2022-11-11 at 09 41 06](https://user-images.githubusercontent.com/101575380/201312345-4a305e82-ee3c-4231-8636-bb5c1a8d9f1b.png)

**Comment by aptkingston** [comment]
My open PR https://github.com/Budibase/budibase/pull/8608 for addressing other form block issues already fixes this as well :+1:

**Comment by melohagan** [comment]
Hey @aptkingston just FYI I found another moderate bug:

1. Create autogenerated screens for a Postgres table. Navigate to `/:id` screen.
<img width="647" alt="Screenshot 2022-11-15 at 11 48 38" src="https://user-images.githubusercontent.com/101575380/201912367-cf7fc6d9-8e1d-4507-91c6-92655938cce0.png">

2. Untick three of the columns:
<img width="647" alt="Screenshot 2022-11-15 at 11 50 06" src="https://user-images.githubusercontent.com/101575380/201912645-7d659891-9b75-415d-a310-920fa87c89f0.png">

3. Eject the block:
<img width="647" alt="Screenshot 2022-11-15 at 11 50 54" src="https://user-images.githubusercontent.com/101575380/201912796-22b41a03-d105-46aa-bfaa-26634ad4b1eb.png">

*There are still 7 columns, but it appears to duplicate the last column*

**Comment by aptkingston** [comment]
> 

What has the form block ever done to deserve this vendetta against it :sweat_smile: 

Yep this is just an edge case where you change which fields are selected and then immediately eject - because those fields were present and mounted at one stage, it's just not clearing them again. Ejection is very complicated and it relies on checking which components get mounted at runtime.

 If you had refreshed the page in between then it would be fine, as would adding fields.

It's specifically removing fields and then ejecting before leaving the page.
