### ISSUE TITLE
Problem deleting an application

### ISSUE THREAD

**Issue by KevinHamonApp** [Budibase/budibase#8837]
**Hosting**

- Cloud
  - Tenant ID: `hamon `

**Describe the bug**
I deleted my app from the API, from the interface here: https://docs.budibase.com/reference/delete_applications-appid 
The request went well. But then, I still have my app in the apps list on my account. I can't edit / manage it anymore (404 not found).
But I can't add a new app as I reached the 4 limit from free cloud. 

**To Reproduce**
1. Create an app
2. Go to this url https://docs.budibase.com/reference/delete_applications-appid 
3. Specify the app id and api-key
4. Launch the request
5. Come back to your account
6. See error

**Expected behavior**
I would have expected to have deleted my app from the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/74555017/204258668-aba8f5b4-d30e-4593-ba47-bf86485a3b05.png)
![image](https://user-images.githubusercontent.com/74555017/204258867-593796b1-c8c9-4f8b-a3f5-cd6195176451.png)

**Comment by shogunpurple** [comment]
Hi @KevinHamonApp 

I've just looked into this and I'm able to reproduce. You can fix your issue in the meantime by deleting the **dev app**, in your case the appID is:
`app_dev_hamon_6a89ca6a030e47c0b65f0f5f62eaa709`

The problem here is that the minIO bucket is shared between the dev and production apps, and was deleted when you deleted the published app. I'll add some code to prevent this when the app is published, so that the dev app is still accessible.
