### ISSUE TITLE
[ Builder ] - Provide "Reset" and "Info" on Component Properties

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#9013]
![Screenshot 2022-12-12 at 1 17 02 PM](https://user-images.githubusercontent.com/80512170/207040733-5317420b-1808-474d-b073-02e17e60577b.jpg)

Given my graphics aren't the finest, the idea is to give the user an easy way to "Reset" the property to its default / empty value with the icon on the left of the Property name, and the icon on the right, when hovered, will be showing a popup with explanatory information about the property ( that would be coming from the Components schema )

**Comment by JayP718** [comment]
+1 This would be nice. Especially the "info"

**Comment by aptkingston** [comment]
There already is `info` - it's even in the bottom of your screenshot there ("Pagination is only available for data stored..."). The only different is that it will show the info text below the setting rather than in a hover tooltip.

As of todays release, you can also add `info` to the top level component definition itself, which will show up like this:
![image](https://user-images.githubusercontent.com/9075550/207049324-46816ee6-dde9-4f30-9d1d-476f4535fe29.png)

**Comment by poirazis** [comment]
Hey @aptkingston 
Nice looking one for the Component Definition! 
The idea for the per property pop-up was to allow for more instructions on usage without taking unnecessary space in the Settings Panel. Like a little help dialog. Maybe it will just add unnecessary weight, i dunno ...

**Comment by poirazis** [comment]
Hey @aptkingston 
Looks awesome ! 
Maybe it should show ( or include ) the components Friendly Name too ?
<img width="392" alt="Screenshot 2022-12-12 at 9 28 48 PM" src="https://user-images.githubusercontent.com/80512170/207136827-5aa83fdb-c81b-476d-8ca8-912d52870f59.png">
