### ISSUE TITLE
Is in filter no longer directly supports relationship pickers

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9015]
**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.1
  - App Version: 2.2.1

**Describe the bug**
A common use-case that was somewhat simple has now become impossible without confusing code. 
This is the tutorial here: https://docs.budibase.com/docs/filter-by-relationships

Originally you could use the **Is in** filter as shown in the docs screenshot, i.e.
![image](https://user-images.githubusercontent.com/101575380/207101536-f0084453-acd5-45c4-b734-4a2c34f3da2e.png)

Now the following JavaScript binding is required:
```js
return $("Details Form.Fields.Pets").map(pet => parseInt(decodeURI(pet)?.replace(/[\[\]]/g, "")));
``` 
It's difficult to put that in a tutorial 😓 

**To Reproduce**
1. Follow the steps in the docs tutorial. See that it doesn't work.
2. Replace the **Is in** filter with the JavaScript binding above. It will now work.

**Expected behavior**
The **Is in** filter should be somewhat flexible and not require exact typings and decoding. Maybe the filter needs more context as to whether the field is a relationship and if it is external/internal. 

**SQL Scripts**

**Owners SQL**
```sql
CREATE TABLE IF NOT EXISTS public."Owners"
(
    id integer NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Address" json,
    CONSTRAINT "Owners_pkey" PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Owners"
    OWNER to postgres;
```

**Pets SQL**
```sql
CREATE TABLE IF NOT EXISTS public."Pets"
(
    id integer NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Animal" text COLLATE pg_catalog."default",
    "Breed_test" text COLLATE pg_catalog."default",
    "Date of birth" timestamp with time zone,
    fk_owner integer,
    "Age" integer,
    CONSTRAINT "Pets_pkey" PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Pets"
    OWNER to postgres;
```

**Appointments SQL**
```sql
CREATE TABLE IF NOT EXISTS public."Appointments"
(
    id integer NOT NULL,
    "Reason" text COLLATE pg_catalog."default",
    "Date" timestamp with time zone,
    fk_pet integer,
    newcol integer,
    CONSTRAINT "Appointments_pkey" PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Appointments"
    OWNER to postgres;
```

**Comment by aptkingston** [comment]
The issue here is that the value of a relationship field uses our internal `_id` field, but it's not currently possible to filter on `_id` for external DB's any more. I believe you removed this yourself actually a few weeks ago in https://github.com/Budibase/budibase/commit/9b6bd124995ce110807004897f89c473865e207a.

That change has actually broken data providers inside detail screens too because it's now impossible to even do `_id equals URL.id` even though that is completely valid and actually is still used inside form blocks. It's just not possible to create via the UI any more and if you eject a form block you will see the field is shown as `null` even though it's actually filtering by `_id` and working fine.

Ejected "update" form block which works totally fine using `_id` but now shows as `null`:
![image](https://user-images.githubusercontent.com/9075550/207280185-c08e7ecd-eae5-48b1-8074-36d66f0514fc.png)

Being able to filter on `_id` is a requirement of being a datasource plus and has always been used - otherwise detail screens for SQL DBs would never have worked.

I think we need to revert that change and allow filtering on `_id` again.

I believe the case that doesn't work is doing `is in` with the `_id` field, but doing an `equals` has always worked and continues to be used inside everyones apps today, even though it's not possible to manually construct it any more.

**Comment by melohagan** [comment]
This was the original commit: https://github.com/Budibase/budibase/pull/8804/commits/b2e8522b7b3ca6ac7bd66e01d3a37dc4531b1f2e

But there was concerns about that affecting internal table filtering because technically you could have a filter like:
`_id Equals ro... OR _id Equals ro... OR id Equals ro... etc`

I believe reverting this change will re-introduce the bug that was fixed. Filtering on **_id** was broken for external DBs: https://github.com/Budibase/budibase/issues/8334#issuecomment-1310614216

**Comment by aptkingston** [comment]
Could that just have been a MySQL thing? Filtering on `_id` for PostgreSQL for example has always worked, and continues to work now. The `_id` is just split into a primary key lookup as it contains the underlying primary key, and the server handles it. The actual SQL passed to the DB should never contain the `_id` field. I can't explain what was happening that guys issue but he was an edge case - the feature was still working though.

**Comment by melohagan** [comment]
> Could that just have been a MySQL thing? Filtering on `_id` for PostgreSQL for example has always worked, and continues to work now. The `_id` is just split into a primary key lookup as it contains the underlying primary key, and the server handles it. The actual SQL passed to the DB should never contain the `_id` field. I can't explain what was happening with that guys issue but he was an edge case - the feature was still working though.
> 
> Just to clarify I only mean with operations like equals/not equals - I don't think it's ever worked for other operators.

Let me spin up an older version (before the bug fix was merged in) and test MySQL, PostgreSQL and SQL Server and I'll get back to you

**Comment by melohagan** [comment]
Someone stating that they came across it in Postgres: https://github.com/Budibase/budibase/issues/8334#issuecomment-1323761580

But I'll confirm

**Comment by aptkingston** [comment]
Working on a fix for that core issue now :+1:
