### ISSUE TITLE
Duplicated queries

### ISSUE THREAD

**Issue by Valdri** [Budibase/budibase#9143]
**Hosting**

- Self
  - Method: docker  
  - Budibase Version: 2.2.9 

After updating budibase from 2.1.28, I noticed that the application runs noticeably slower than before the update.
I checked that with chrome dev tools I noticed that budibase is sending way too many queries.

![1](https://user-images.githubusercontent.com/13934649/208946394-9e3cb009-3872-4eb1-9e89-fcd92b3de67c.png)

this is the same page on 2.1.28

![2](https://user-images.githubusercontent.com/13934649/208946908-86a74915-4f80-4d7d-a20f-2cd34c06e9cf.png)

It is sending queries with default bindings values for child data provider.

Components:
- New Data Provider1 - sending query for customer order
-  - New Data Provider2 - sending correct query and multiple duplicated queries with default binding value

**Comment by melohagan** [comment]
This may be related too: https://github.com/Budibase/budibase/issues/9106

**Comment by pinwaven** [comment]
I exprience the similiar data query slowdown issue with version 2.2.x. To replicate the issue, i created a blank project with a small bb table with 3 rows, then a data provider with a paragraph component, then set the text of the paragraph to a javascript function. the javascript function was called 4 times instead of once. please see the attached pics.
<img width="1579" alt="bug01" src="https://user-images.githubusercontent.com/12550765/210190908-6b40d7a0-6a37-4e83-b92b-a6533db33311.png">
<img width="1067" alt="bug02" src="https://user-images.githubusercontent.com/12550765/210190910-566128c2-a367-47c1-8b6a-7ae37e28ed03.png">

**Comment by aptkingston** [comment]
This should already be resolved as of https://github.com/Budibase/budibase/pull/9256. We're also fully reverting skeleton loaders this iteration as well.
