### ISSUE TITLE
[Custom Components] - Allow self assembly 

### ISSUE THREAD

**Issue by poirazis** [Budibase/budibase#9193]
Scenario : I have a custom component, Super Table which requires another two components to work ( Super Column and Super Cell ).

Feature : I would like to be able to self assemble the Super Table component ( programmatically add to it the required Super Columns and Super Cells ) to a default state, depending on the Data Provider chosen. This feature, would need to allow the Custom Component to programmatically add or delete Child Components to its own component tree and set their properties.

Should this option be available, Custom Components would be able to offer different presets to the user ( like templates ) for the no-code users to get faster up and running.

Have a great year everyone !

**Comment by Rory-Powell** [comment]
@poirazis you can have a look into the block implementation to try to address the requirements of controlling child components. Best to raise a discussion to troubleshoot any issues you may have with this.

**Comment by aptkingston** [comment]
> Hey @Rory-Powell is it possible for the Block Component implementation be exposed via the SDK context so we dont have to maintain a local copy that will be out of sync with the core ?

Hey @poirazis! We can easily expose them, but I'm fairly certain that you still won't be able to build custom blocks until we make further code changes. Custom blocks isn't something we officially support (yet), so until we do support them, I'm afraid that maintaining a local copy of `Block.svelte` and `BlockComponent.svelte` which is patched (it has hardcoded things that won't work with blocks) is probably the only way to do it.

There could be other things that don't work with custom blocks, but I don't know what they are because I haven't tried yet 👍

**Comment by poirazis** [comment]
Thank you @aptkingston !
No issue in waiting for things to be finalized and officially supported !
I am playing around with local copies for the moment to learn the ropes a bit !
