### ISSUE TITLE
Ejecting a cards block adds undefined CSS

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9376]
## Checklist
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: docker compose
  - Budibase Version: 2.2.16
  - App Version: 2.2.16

**Describe the bug**
Ejecting a Cards Block leads to `undefined` in the Form component.

**To Reproduce**
1. Add a cards block for a table and eject
2. `Edit custom CSS` for the Form component, see **undefined**.

**Expected behavior**
Undefined CSS should not appear in the Form component.

**Screenshots**
![Screenshot 2023-01-18 at 15 24 24](https://user-images.githubusercontent.com/101575380/213212079-b615d14d-6859-4c75-bc95-c23fb0d9cbce.png)
*Form*

**Comment by aptkingston** [comment]
The `undefined` seems to just be a very minor issue with ejection in general, in that anything you eject gets `undefined` added to custom CSS, but it doesn't affect functionality. Should be an easy fix.

For the second point, I'm not really sure what the issue is here... Ejecting preserves things like custom CSS and those styles are what the cards block uses, so it's expected that they would be there after ejection, or else it would immediately break when you eject. There aren't really any layout otions on the cards block - what is it that you're changing and isn't working after ejection?

**Comment by melohagan** [comment]
I was having issues with the styling, but I think I must have been making a very basic mistake somewhere because I can't reproduce the styling problem I was seeing earlier. 

I'll update the issue to just be about the minor `undefined` form css.

**Comment by aptkingston** [comment]
No problem, sounds good!
