### ISSUE TITLE
SQL Constraints: Could the auto-generated screen Delete button also delete the relationship rows if needed? 

### ISSUE THREAD

**Issue by melohagan** [Budibase/budibase#9411]
**Describe the feature request**
I have a relationship defined as:
 - One Employee -> Many Orders

The following foreign key constraint exists on the Employee table:
**FK_Orders_Employees** -> EmployeeID column

I add an auto-generated screen for the Employee table. When I click the delete button, I get the constraint violation.

Is there anyway to handle these foreign key constraints without the error? 
Maybe there's a way to check if the foreign key constraints exist and simply do not include the delete button in those scenarios.

**Screenshots**
<img width="632" alt="Screenshot 2023-01-23 at 10 23 45" src="https://user-images.githubusercontent.com/101575380/214016625-c62bb0f8-e878-4855-ac1f-5b503d1e4c09.png">

![Screenshot 2023-01-23 at 10 30 52](https://user-images.githubusercontent.com/101575380/214018044-ddb2ef27-57c8-43ec-81af-d5d7fdddabd6.png)

**Comment by mike12345567** [comment]
This is mostly down to the table design, whether or not the foreign key/table constraints have been configured in a way in which `CASCADE` has been enabled. E.g.
```sql 
CONSTRAINT fkName FOREIGN KEY(column)
REFERENCES table (column)
ON DELETE CASCADE
```

Personally I think it is better that this is baked into the SQL schema for the table rather than implemented in application code (as this is one of the big benefits of SQL relational design).

There is maybe an issue here that when a table is being added to a database/we're creating a relationship column (not defining an existing one) that we configure the constraints with cascade, but I think the issue needs re-defined in that case.

**Comment by melohagan** [comment]
Ah nice, that makes sense.

In that case then, is it possible to check if there are foreign key constraints without cascade, and hide the delete button in that scenario? 

It's a very small thing tbf.

**Comment by mike12345567** [comment]
Sadly screen updates in this way are basically impossible - the design section is very very disconnected from the data schema/isn't even aware the screen is based on SQL data (not internal table, a query etc).

Think we might need to close this issue if thats OK as I don't think there is anything we can feasible do about this - other than document the warning and explain to users that they may need cascade enabled - otherwise the error returned is expected/useful, basically stating that there are still relationships so you can't/shouldn't delete the row.
