### ISSUE TITLE
Button Query Action not being performed

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#9535]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method:docker compose
  - Budibase Version: 2.2.22
  - App Version: 2.2.22

**Describe the bug**
When assigning an action to a button, the action is not carried out. It is not hitting the backend webhook. It does however work when on the data tab. 

**To Reproduce**
1. Assign the action to a button
2. click the button
3. No action is performed 

**Expected behavior**
The binding is passed the given values and the query is executed.

**Screenshots**
![Recording 2023-02-03 at 15 18 34](https://user-images.githubusercontent.com/96125948/216702697-3b50347a-9cc1-44f2-b93e-3a1761fa1512.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Chrome

**Comment by kerbersystems** [comment]
If I manually type in the value into the Default value for the binding it passed correctly. If I try to pass any value through a form, it sends NULL
![image](https://user-images.githubusercontent.com/96125948/216711935-500a7ff0-2ef7-471d-9b5f-1a4c5430b3ca.png)

**Comment by avivkri** [comment]
Hi @kerbersystems,

This might be related to the issue here - [readable to runtimeBinding wrong in rest api #9045](https://github.com/Budibase/budibase/issues/9045).

The binding name appears to be different based on whether a default value is set or not. So, you could try replacing the binding name `{{ Binding.partnumber }}` with just `{{ partnumber }}` in the RequestBody.
![budibase default binding problem](https://user-images.githubusercontent.com/13772138/216753023-4c54f161-5dc9-4ffa-8b50-b72deb3f6202.png)

**Comment by kerbersystems** [comment]
I tried that with no luck. Rundeck (which is what's handling the execution after the webhook) doesn't even receive a job to run. This could be that it's so malformed that it doesn't want to even try. I was experimenting with different ways of passing the binding and the furthest I got was passing the whole JSON: `{"partnumber": "part123"}` This did get through to Rundeck but came with a value of NULL (this can be seen in my second post). That is not the case however if I paste that JSON as the default value. Is there any way for me to trace the call in BB?

**Comment by avivkri** [comment]
Since the API call works in Data section, I don't see how it could be different when invoked from Design section.
To understand better, can you share screenshots of both of these
1) Data section -> Query -> Body tab
2) Design section -> Actions -> Binding values along with RequestBody

Regarding tracing in BB: You could try some options like
- Put the bindings in Paragraph element and see them in screen
- Budibase DevTools in Preview mode
- Browser network and console tabs
- For REST APIs, it is better to test the API calls in external tools like Postman and then try in Budibase to narrow down the problem.

**Comment by kerbersystems** [comment]
1.
![image](https://user-images.githubusercontent.com/96125948/216770910-39890ae9-6fec-4d7b-8b11-73268c1e1dfc.png)

2.
![image](https://user-images.githubusercontent.com/96125948/216770936-d899e99c-6a10-4410-8f09-90de040257a4.png)

I will try and see if I can intercept the call. It works in Postman, NodeJS, and Python scripts. It also works when I input the value into the default binding so BB can do it.

**Comment by avivkri** [comment]
Great, that helps to narrow down the problem. The binding names indeed look good in both Data and Design sections.

Next, Are you sure the `{{ State.barcode }}` is not empty. With the binding name still as `{{ partnumber }}` everywhere (without Binding. prefix), can you also pass these 2 values instead of `{{ State.barcode }}` in Action and see if there is a difference.

1. direct value like `test` 
2. field binding like `{{ Form.Fields.FieldName }}` (if the partnumber value can be accessed from the Form itself instead of State)

**Comment by kerbersystems** [comment]
So, making sure that the binding in the Data pane does not have the Bindings. before the name and passing the value to that seems to work! The photo in my last post is what worked.
