### ISSUE TITLE
Url/Query Parameters in Context

### ISSUE THREAD

**Issue by shogunpurple** [Budibase/budibase#954]
- Bind values in define actions to URL params
- Make URL params a bindable value that can be bound anywhere in the platform

**Comment by aptkingston** [comment]
I've been looking at this for a while now and most of it is easily possible and implemented on my branch. URL params are available as bindable properties, and the client app provides the URL params through context.

The part that isn't possible at the moment is using a free-type text field with bindable properties to enter URL - just because of the grid. Every other instance of us needing to enter a URL to navigate to can be swapped to a text field and bindings can be made available. This means links, cards and even the button action navigate could work perfectly.

Grids are unique because they expect to be given a specific form of URL with an `:id` param in it, which it uses to create the correct URLs. Grids don't provide context per row, so we can't use bindable properties in the URL field. They also actually can't provide context if they wanted to, because AG grid dynamically attaches them to the DOM manually, which means they can't share context with the rest of the app. We can leave the grid setting as a unique type of setting, but that still means it won't work with external datasources. I think our best option is to leave grids as they are for now, and implement the new URL settings everywhere else. Especially since we're eventually probably going to end up making our own spectrum based table which would solve this.

**Comment by shogunpurple** [comment]
Thanks for the detail @aptkingston - happy to close this one out once your PR is merged!

**Comment by aptkingston** [comment]
The second half of this has been completed. Since URL settings are now a text component and can be set to bound values, I'm not sure if we still need an explicit action to set a URL param (or how that would work). Do you reckon we can call this completed or is there anything else we should add?

The AG grid edge case will be taken care of whenever we do a datasource refactor and replace the grid with something like our own spectrum based table.
