### ISSUE TITLE
Can not import app

### ISSUE THREAD

**Issue by kerbersystems** [Budibase/budibase#9763]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Self
  - Method: Docker Hub
  - Budibase Version: 2.3.15
  - App Version: 2.3.15

**Describe the bug**
I am unable to import an app from an on-prem environment to Azure App Services.

**To Reproduce**
![Recording 2023-02-21 at 05 25 30](https://user-images.githubusercontent.com/96125948/220319450-213bbee2-2223-4ce0-9318-4ac1cd3fa602.gif)

**Expected behavior**
To be able to import an app.

**App Export**
[NIMO-export-1676974901289.tar.gz](https://github.com/Budibase/budibase/files/10792490/NIMO-export-1676974901289.tar.gz)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by andz-bb** [comment]
hey @kerbersystems, I had a quick look at your app export and I think you're missing the [Stripe checkout datasource plugin](https://github.com/melohagan/budibase-datasource-stripe-checkout). Can you try importing the plugin into your new environment and then retry the app import? Apologies for this, the error you got could be more clear about what's causing the problem here.

**Comment by mike12345567** [comment]
Closing issue as resolved on Discord.
