### ISSUE TITLE
[BUDI-6638] 403 Forbidden (Invalid CSRF token) thrown on Requests to the Public API

### ISSUE THREAD

**Issue by annafohlmeister** [Budibase/budibase#9778]
**Checklist**
- [x] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**
- Cloud
  - Tenant ID: smatch (smatch.budibase.app)

**Describe the bug**
When attempting to access data from Budibase's internal data storage via the Public API a 403 Forbidden (Invalid CSRF token) is thrown whenever query parameters are set. The issues does not occur with URL parameters (I have not attempted, but would assume, that it would also occur for requests with bodies, ie POST / PUT). 

**Example #1: Searching for Table Rows**
GET https://budibase.app/api/public/v1/tables/$tableId/rows/search?param=xxx
403 Status with `{ message: 'Invalid CSRF token', status: 403 }` in the response body. 

**Example #2: Fetching a Table by ID**
GET https://budibase.app/api/public/v1/tables/$tableId
200 Status with `{ data: <tableData> }` in the response body.

I would not expect a CSRF token to be required on a stateless API. As Example #2 is working, and I can find no reference to CSRF tokens in the API documentation, I am confident that this is a bug and not a feature. 

**To Reproduce**
I'm working in nodeJS, therefore specific steps to replicate, but I believe this issue would arise anywhere:
 
1. Create a new NodeJS project and add the Axios Open API Client NPM Package (https://github.com/anttiviljami/openapi-client-axios/blob/master/packages/openapi-client-axios/README.md). 
2. Create an index.js file with:
```
const { OpenAPIClientAxios } = require('openapi-client-axios');

const openApiUrl = 'https://raw.githubusercontent.com/annafohlmeister/budibase/develop/packages/server/specs/openapi.json';

const config = {
    headers: {
        'x-budibase-api-key': 'xxx',
        'x-budibase-app-id': 'xxx'
    }
};

const tableId = 'xxx';

const api = new OpenAPIClientAxios({ definition: openApiUrl });

var test = async function () {

    const client = await api.getClient();

    /*
    // Working example 
    const table = await client.getTableById({tableId: tableId}, null, config);
    console.log(table);
    */

    // Failing example - feel free to add search parameters: { tableId: tableId, search: 'param' }
    const rows = await client.searchTableRows({ tableId: tableId }, null, config);
    console.log(rows);
}

var init = function () {
    api.init();
    test();
}

init();
```
4. Run the script. 
5. See error in console. 

**Expected behavior**
I would expect to be able to send a request to the Public API without providing a CSRF token for request with query parameters. 

**Additional context**
The Budibase OpenAPI file is invalid, as it does not set unique operationIds. While operationIds are optional, if they are used, they must be unique across the whole openapi document (see https://swagger.io/docs/specification/paths-and-operations). This leads to issues with third party tooling.

<sub>[BUDI-6638](https://linear.app/budibase/issue/BUDI-6638/403-forbidden-invalid-csrf-token-thrown-on-requests-to-the-public-api)</sub>

**Comment by shogunpurple** [comment]
Hi - a few issues here:

* The first request to search rows should be a `POST` not a `GET` 
* it appears you are using a custom, forked openAPI spec in your own repo, rather than our built in SDK or openAPI definition. You can generate the budibase SDK directly from your own fork, or install the NPM package `@budibase/sdk` that you can use in your Node script.

I'm not familiar with the axios open API package you have linked. We are happy to accept a PR or any other input around this but it's a bit of an unsupported configuration so closing this issue for now.

**Comment by annafohlmeister** [comment]
Hey there @shogunpurple @mike12345567, 

thanks for getting back to me! Before I dive into the internals, to figure out what's going on - three questions:

1. Can you confirm that the Budi API requires a CSRF token for server-to-server requests? 
2. Assuming that (1.) is true, why did you chose this approach (it feels quite counter-intuitive to me, and I would like to understand the reaonsing)? 
3. Assuming that (1.) is true, do you have any type of documentation on where to get the CSRF token from? 

Thank you! (And I particularly appreciate the update for the openAPI specs. I had it on my list to push a PR in your direction, but this issue got in the way first).

**Comment by mike12345567** [comment]
Hi @annafohlmeister - the public API (documented here: https://docs.budibase.com/reference/post_applications) does not require CSRF tokens - what you were experiencing was a CSRF token being required for the internal API - the `GET` request you were performing was falling back to an endpoint in our internal API which captures all `GET` requests - this is something we want to address in the near future as it is confusing, it would preferable if a `GET` request like say `GET https://budibase.app/api/public/v1/tables/$tableId/rows/search?param=xxx` 404'd as it really should - rather than falling back to an unrelated internal API.

**Comment by annafohlmeister** [comment]
Hey @mike12345567 - thanks for the background. I've found the issue (it was me). Taking a step back, and not having tunnel vision on the CSRF issue helped a lot :).

**Comment by mike12345567** [comment]
Hi @annafohlmeister - glad could help!
