### ISSUE TITLE
[BUDI-6702] budi CLI doesn't work, and doesn't produce the logs it says it does

### ISSUE THREAD

**Issue by dnk8n** [Budibase/budibase#9887]
**Checklist**
- [yes] I have searched budibase discussions and github issues to check if my issue already exists

**Hosting**

- Self
  - Method: <method> CLI (docker-compose)
  - Budibase Version: <version> 2.3.21 (budi --version)

**Describe the bug**
`budi hosting --start` fails, and so does `budi hosting --update`)

**To Reproduce**
1. Follow docs to install, then finally: `npm install -g @budibase/cli`
1. `budi --version` works (see below)
1. `budi hosting --init` works
1. `budi hosting --start` fails
1. Logs are *not* written to file: `docker-error.log`

**Expected behavior**
I expected a similar behavior to `docker-compose up -d`

**Screenshots**
[Screencast from 06-03-2023 14:35:28.webm](https://user-images.githubusercontent.com/3307753/223112232-ac0fcd24-99ef-4800-aa67-15db18cd3958.webm)

<sub>[BUDI-6702](https://linear.app/budibase/issue/BUDI-6702/budi-cli-doesnt-work-and-doesnt-produce-the-logs-it-says-it-does)</sub>

**Comment by dnk8n** [comment]
Some context / extra info, probably unrelated to this bug but interesting to know...

I can simply proceed using `docker compose up -d` (with either `docker-compose` or even with plugin version of compose, which the CLI doesn't support, my machine has both installed)

What is the value of the CLI if it all works with docker-compose under the hood? And btw, it never fully worked until I did a `docker compose restart`.

**Comment by mike12345567** [comment]
Hi @dnk8n - I was not able to replicate this - I expect the issue is to do with the mixture of `docker-compose` and the newer `docker compose` functionality which we are waiting for support for (brought up in other issue: https://github.com/Budibase/budibase/issues/9871).

I'm currently using Docker version `20.10.14` with Docker-compose version `1.27.4` - with a clean Budi CLI install this is able to init and start the services fine.

Not sure what more can be done on this issue while we await support for the new `docker compose` sub-command which is documented in the other issue.

In terms of value of these commands in the CLI, the init and update commands are more use than anything else, the start and stop can be ran directly through docker compose with no issue, we just thought it would be helpful to provide a system for getting the docker-compose file and filling out the environment file with unique secrets, and updating it incase any changes have occurred to the docker-compose script (new service or environment variable).
